// Copyright 2026 Antfly, Inc.
//
// Licensed under the Elastic License 2.0 (ELv2); you may not use this file
// except in compliance with the Elastic License 2.0. You may obtain a copy of
// the Elastic License 2.0 at
//
//     https://www.antfly.io/licensing/ELv2-license
//
// Unless required by applicable law or agreed to in writing, software distributed
// under the Elastic License 2.0 is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// Elastic License 2.0 for the specific language governing permissions and
// limitations.

//! Shared mapping for in-process reads and the compiled local-query provider.

const db_query_search = @import("../storage/db/query/control_contract.zig");
const query_api = @import("query_contract.zig");

pub fn fromStorage(profile: db_query_search.DenseSearchProfile) query_api.QueryResponseMeta.DenseSearchProfile {
    return .{
        .total_ns = profile.total_ns,
        .index_lookup_ns = profile.index_lookup_ns,
        .hbc_search_ns = profile.hbc_search_ns,
        .hbc_runtime_txn_ns = profile.hbc_runtime_txn_ns,
        .hbc_admission_wait_ns = profile.hbc_admission_wait_ns,
        .hbc_scan_admission_wait_ns = profile.hbc_scan_admission_wait_ns,
        .hbc_rerank_admission_wait_ns = profile.hbc_rerank_admission_wait_ns,
        .hbc_admission_estimated_scan_bytes = profile.hbc_admission_estimated_scan_bytes,
        .hbc_admission_selected_scan_bytes = profile.hbc_admission_selected_scan_bytes,
        .hbc_admission_peak_reserved_bytes = profile.hbc_admission_peak_reserved_bytes,
        .hbc_admission_reservations = profile.hbc_admission_reservations,
        .hbc_admission_fallback_leaves = profile.hbc_admission_fallback_leaves,
        .hbc_leaf_scan_bytes = profile.hbc_leaf_scan_bytes,
        .hbc_native_leaf_lookup_ns = profile.hbc_native_leaf_lookup_ns,
        .hbc_projection_completion_ns = profile.hbc_projection_completion_ns,
        .hbc_scratch_acquire_ns = profile.hbc_scratch_acquire_ns,
        .hbc_node_cache_lookup_ns = profile.hbc_node_cache_lookup_ns,
        .hbc_quantized_cache_lookup_ns = profile.hbc_quantized_cache_lookup_ns,
        .hbc_child_expand_ns = profile.hbc_child_expand_ns,
        .hbc_leaf_score_ns = profile.hbc_leaf_score_ns,
        .hbc_filter_candidates = profile.hbc_filter_candidates,
        .hbc_filter_rejected = profile.hbc_filter_rejected,
        .hbc_filter_metadata_batches = profile.hbc_filter_metadata_batches,
        .hbc_filter_metadata_batch_ns = profile.hbc_filter_metadata_batch_ns,
        .hbc_traversal_waves = profile.hbc_traversal_waves,
        .hbc_traversal_initial_wave_leaves = profile.hbc_traversal_initial_wave_leaves,
        .hbc_traversal_max_wave_leaves = profile.hbc_traversal_max_wave_leaves,
        .hbc_traversal_bound_resolutions = profile.hbc_traversal_bound_resolutions,
        .hbc_traversal_bound_fallbacks = profile.hbc_traversal_bound_fallbacks,
        .hbc_traversal_bound_stops = profile.hbc_traversal_bound_stops,
        .hbc_traversal_bound_unresolved_frontier = profile.hbc_traversal_bound_unresolved_frontier,
        .hbc_traversal_bound_incomplete_topk = profile.hbc_traversal_bound_incomplete_topk,
        .hbc_traversal_bound_overlap = profile.hbc_traversal_bound_overlap,
        .hbc_traversal_unresolved_posting_bounds = profile.hbc_traversal_unresolved_posting_bounds,
        .hbc_traversal_incomplete_routing_directory = profile.hbc_traversal_incomplete_routing_directory,
        .hbc_traversal_frontier_remaining = profile.hbc_traversal_frontier_remaining,
        .hbc_traversal_eligible_vectors = profile.hbc_traversal_eligible_vectors,
        .hbc_traversal_stop_lower_bound = profile.hbc_traversal_stop_lower_bound,
        .hbc_traversal_stop_result_upper_bound = profile.hbc_traversal_stop_result_upper_bound,
        .resolved_search_width = profile.resolved_search_width,
        .resolved_epsilon = profile.resolved_epsilon,
        .native_filter_candidate_count = profile.native_filter_candidate_count,
        .search_route = profile.search_route,
        .route_reason = profile.route_reason,
        .route_estimated_exact_storage_bytes = profile.route_estimated_exact_storage_bytes,
        .route_estimated_hbc_storage_bytes = profile.route_estimated_hbc_storage_bytes,
        .route_estimated_exact_work_ns = profile.route_estimated_exact_work_ns,
        .route_estimated_hbc_work_ns = profile.route_estimated_hbc_work_ns,
        .exact_candidate_count = profile.exact_candidate_count,
        .exact_batch_count = profile.exact_batch_count,
        .exact_max_batch_size = profile.exact_max_batch_size,
        .exact_workspace_bytes = profile.exact_workspace_bytes,
        .exact_request_vector_cache_entries = profile.exact_request_vector_cache_entries,
        .exact_raw_batch_reads = profile.exact_raw_batch_reads,
        .exact_raw_scalar_reads = profile.exact_raw_scalar_reads,
        .exact_missing_vectors = profile.exact_missing_vectors,
        .exact_candidate_prepare_ns = profile.exact_candidate_prepare_ns,
        .exact_metadata_lookup_ns = profile.exact_metadata_lookup_ns,
        .exact_artifact_key_ns = profile.exact_artifact_key_ns,
        .exact_artifact_read_ns = profile.exact_artifact_read_ns,
        .exact_artifact_decode_ns = profile.exact_artifact_decode_ns,
        .exact_distance_ns = profile.exact_distance_ns,
        .exact_lsm_cache_hits = profile.exact_lsm_cache_hits,
        .exact_lsm_cache_misses = profile.exact_lsm_cache_misses,
        .exact_artifact_cache_hits = profile.exact_artifact_cache_hits,
        .exact_artifact_vectors_loaded = profile.exact_artifact_vectors_loaded,
        .hbc_nodes_visited = profile.hbc_nodes_visited,
        .hbc_leaves_explored = profile.hbc_leaves_explored,
        .hbc_approx_vectors_scored = profile.hbc_approx_vectors_scored,
        .hbc_exact_vectors_scored = profile.hbc_exact_vectors_scored,
        .hbc_leaf_payload_stale = profile.hbc_leaf_payload_stale,
        .hbc_leaf_payload_missing = profile.hbc_leaf_payload_missing,
        .hbc_native_leaf_scan_hits = profile.hbc_native_leaf_scan_hits,
        .hbc_subgroup_leaves_scored = profile.hbc_subgroup_leaves_scored,
        .hbc_subgroup_vectors_skipped = profile.hbc_subgroup_vectors_skipped,
        .hbc_subgroup_compact_groups_scored = profile.hbc_subgroup_compact_groups_scored,
        .hbc_subgroup_routing_ns = profile.hbc_subgroup_routing_ns,
        .hbc_native_leaf_scan_fallbacks = profile.hbc_native_leaf_scan_fallbacks,
        .hbc_reranked_vectors = profile.hbc_reranked_vectors,
        .hbc_approx_candidate_count = profile.hbc_approx_candidate_count,
        .hbc_rerank_candidate_count = profile.hbc_rerank_candidate_count,
        .hbc_rerank_batches = profile.hbc_rerank_batches,
        .hbc_rerank_max_batch_size = profile.hbc_rerank_max_batch_size,
        .hbc_rerank_candidates_skipped_by_bound = profile.hbc_rerank_candidates_skipped_by_bound,
        .hbc_ambiguous_top_k_pairs = profile.hbc_ambiguous_top_k_pairs,
        .hbc_ambiguous_boundary_pairs = profile.hbc_ambiguous_boundary_pairs,
        .hbc_ambiguous_distance_over_hits = profile.hbc_ambiguous_distance_over_hits,
        .hbc_ambiguous_distance_under_hits = profile.hbc_ambiguous_distance_under_hits,
        .hbc_full_rerank_due_to_threshold = profile.hbc_full_rerank_due_to_threshold,
        .hbc_top_k_count = profile.hbc_top_k_count,
        .hbc_min_distance_gap_top_k = profile.hbc_min_distance_gap_top_k,
        .hbc_min_interval_gap_top_k = profile.hbc_min_interval_gap_top_k,
        .hbc_closest_pair_top_k = if (profile.hbc_closest_pair_top_k) |pair| mapDenseDebugPair(pair) else null,
        .hbc_boundary_pair = if (profile.hbc_boundary_pair) |pair| mapDenseDebugPair(pair) else null,
        .hbc_boundary_tail_error_avg = profile.hbc_boundary_tail_error_avg,
        .hbc_boundary_tail_error_max = profile.hbc_boundary_tail_error_max,
        .hbc_boundary_tail_distance_gap_avg = profile.hbc_boundary_tail_distance_gap_avg,
        .hbc_boundary_tail_distance_gap_min = profile.hbc_boundary_tail_distance_gap_min,
        .hbc_boundary_tail_distance_gap_max = profile.hbc_boundary_tail_distance_gap_max,
        .hbc_boundary_tail_interval_gap_avg = profile.hbc_boundary_tail_interval_gap_avg,
        .hbc_boundary_tail_interval_gap_min = profile.hbc_boundary_tail_interval_gap_min,
        .hbc_boundary_tail_interval_gap_max = profile.hbc_boundary_tail_interval_gap_max,
        .hbc_approx_top_count = profile.hbc_approx_top_count,
        .hbc_approx_top = blk: {
            var out: [5]query_api.QueryResponseMeta.DenseSearchProfile.DebugHit = .{ .{}, .{}, .{}, .{}, .{} };
            for (profile.hbc_approx_top, 0..) |hit, i| out[i] = mapDenseDebugHit(hit);
            break :blk out;
        },
        .hbc_rerank_external_score_ns = profile.hbc_rerank_external_score_ns,
        .hbc_rerank_vector_load_ns = profile.hbc_rerank_vector_load_ns,
        .hbc_rerank_metadata_lookup_ns = profile.hbc_rerank_metadata_lookup_ns,
        .hbc_rerank_metadata_vectors_loaded = profile.hbc_rerank_metadata_vectors_loaded,
        .hbc_rerank_artifact_key_ns = profile.hbc_rerank_artifact_key_ns,
        .hbc_rerank_artifact_read_ns = profile.hbc_rerank_artifact_read_ns,
        .hbc_rerank_artifact_decode_ns = profile.hbc_rerank_artifact_decode_ns,
        .hbc_rerank_artifact_distance_ns = profile.hbc_rerank_artifact_distance_ns,
        .hbc_rerank_lsm_cache_hits = profile.hbc_rerank_lsm_cache_hits,
        .hbc_rerank_lsm_cache_misses = profile.hbc_rerank_lsm_cache_misses,
        .hbc_rerank_vector_block_hits = profile.hbc_rerank_vector_block_hits,
        .hbc_rerank_vector_projection_reads = profile.hbc_rerank_vector_projection_reads,
        .hbc_rerank_vector_projection_borrows = profile.hbc_rerank_vector_projection_borrows,
        .hbc_rerank_vector_projection_bytes = profile.hbc_rerank_vector_projection_bytes,
        .hbc_rerank_vector_residual_reads = profile.hbc_rerank_vector_residual_reads,
        .hbc_rerank_vector_residual_bytes = profile.hbc_rerank_vector_residual_bytes,
        .hbc_rerank_vector_physical_reads = profile.hbc_rerank_vector_physical_reads,
        .hbc_rerank_vector_physical_bytes = profile.hbc_rerank_vector_physical_bytes,
        .hbc_rerank_vector_location_reuses = profile.hbc_rerank_vector_location_reuses,
        .hbc_rerank_member_binding_hits = profile.hbc_rerank_member_binding_hits,
        .hbc_rerank_member_binding_batches = profile.hbc_rerank_member_binding_batches,
        .hbc_rerank_member_binding_mixed_batches = profile.hbc_rerank_member_binding_mixed_batches,
        .hbc_rerank_member_binding_bytes = profile.hbc_rerank_member_binding_bytes,
        .hbc_rerank_read_batches = profile.hbc_rerank_read_batches,
        .hbc_rerank_read_requests = profile.hbc_rerank_read_requests,
        .hbc_rerank_read_helpers = profile.hbc_rerank_read_helpers,
        .hbc_rerank_read_denied = profile.hbc_rerank_read_denied,
        .hbc_rerank_read_dispatch_ns = profile.hbc_rerank_read_dispatch_ns,
        .hbc_rerank_read_caller_ns = profile.hbc_rerank_read_caller_ns,
        .hbc_rerank_read_join_ns = profile.hbc_rerank_read_join_ns,
        .hbc_rerank_read_worker_wall_ns = profile.hbc_rerank_read_worker_wall_ns,
        .hbc_rerank_read_adaptive_inline_batches = profile.hbc_rerank_read_adaptive_inline_batches,
        .hbc_rerank_read_adaptive_wide_batches = profile.hbc_rerank_read_adaptive_wide_batches,
        .hbc_rerank_read_adaptive_probe_ns = profile.hbc_rerank_read_adaptive_probe_ns,
        .hbc_rerank_read_worker_start_delay_ns = profile.hbc_rerank_read_worker_start_delay_ns,
        .hbc_rerank_read_mapped_requests = profile.hbc_rerank_read_mapped_requests,
        .hbc_rerank_read_mapped_bytes = profile.hbc_rerank_read_mapped_bytes,
        .hbc_rerank_member_binding_misses = profile.hbc_rerank_member_binding_misses,
        .hbc_rerank_vector_block_misses = profile.hbc_rerank_vector_block_misses,
        .hbc_rerank_vector_block_fallbacks = profile.hbc_rerank_vector_block_fallbacks,
        .hbc_rerank_artifact_cache_hits = profile.hbc_rerank_artifact_cache_hits,
        .hbc_rerank_artifact_vectors_loaded = profile.hbc_rerank_artifact_vectors_loaded,
        .hbc_rerank_distance_ns = profile.hbc_rerank_distance_ns,
        .doc_key_resolve_ns = profile.doc_key_resolve_ns,
        .doc_ordinal_lookup_ns = profile.doc_ordinal_lookup_ns,
        .load_projected_document_ns = profile.load_projected_document_ns,
        .postprocess_ns = profile.postprocess_ns,
        .raw_hit_count = profile.raw_hit_count,
        .returned_hit_count = profile.returned_hit_count,
        .inline_metadata_hits = profile.inline_metadata_hits,
        .fetched_metadata_hits = profile.fetched_metadata_hits,
        .lookup_doc_key_hits = profile.lookup_doc_key_hits,
    };
}

fn mapDenseDebugHit(hit: db_query_search.DenseSearchProfile.DebugHit) query_api.QueryResponseMeta.DenseSearchProfile.DebugHit {
    return .{
        .id = hit.id,
        .distance = hit.distance,
        .error_bound = hit.error_bound,
        .lower_bound = hit.lower_bound,
        .upper_bound = hit.upper_bound,
    };
}

fn mapDenseDebugPair(pair: db_query_search.DenseSearchProfile.DebugPair) query_api.QueryResponseMeta.DenseSearchProfile.DebugPair {
    return .{
        .left = mapDenseDebugHit(pair.left),
        .right = mapDenseDebugHit(pair.right),
        .distance_gap = pair.distance_gap,
        .interval_gap = pair.interval_gap,
        .overlaps = pair.overlaps,
    };
}
