// Copyright 2026 Antfly, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0

// Code generated by scripts/generate_graph_identifier_policy.py from
// specs/graph_identifier_policy.json; DO NOT EDIT.

export const GRAPH_IDENTIFIER_POLICY_VERSION = 1;
export const GRAPH_IDENTIFIER_UNICODE_VERSION = "15.0.0";
export const MAX_GRAPH_IDENTIFIER_CODE_POINTS = 128;
export const MAX_GRAPH_IDENTIFIER_UTF8_BYTES = 512;

const DISALLOWED_RANGES: readonly (readonly [number, number])[] = [
  [0x0, 0x1f],
  [0x7f, 0xa0],
  [0xad, 0xad],
  [0x600, 0x605],
  [0x61c, 0x61c],
  [0x6dd, 0x6dd],
  [0x70f, 0x70f],
  [0x890, 0x891],
  [0x8e2, 0x8e2],
  [0x1680, 0x1680],
  [0x180e, 0x180e],
  [0x2000, 0x200f],
  [0x2028, 0x202f],
  [0x205f, 0x2064],
  [0x2066, 0x206f],
  [0x3000, 0x3000],
  [0xd800, 0xdfff],
  [0xfeff, 0xfeff],
  [0xfff9, 0xfffb],
  [0x110bd, 0x110bd],
  [0x110cd, 0x110cd],
  [0x13430, 0x1343f],
  [0x1bca0, 0x1bca3],
  [0x1d173, 0x1d17a],
  [0xe0001, 0xe0001],
  [0xe0020, 0xe007f],
];
const RESERVED_EXACT = new Set(["*"]);
const RESERVED_PREFIXES = ["$"] as const;

function codePointDisallowed(codePoint: number): boolean {
  let lo = 0;
  let hi = DISALLOWED_RANGES.length;
  while (lo < hi) {
    const mid = lo + Math.floor((hi - lo) / 2);
    const codePointRange = DISALLOWED_RANGES[mid];
    if (!codePointRange) return false;
    const [rangeLo, rangeHi] = codePointRange;
    if (codePoint < rangeLo) {
      hi = mid;
    } else if (codePoint > rangeHi) {
      lo = mid + 1;
    } else {
      return true;
    }
  }
  return false;
}

/** Return whether value satisfies the versioned Antfly wire policy. */
export function isValidGraphIdentifier(value: string): boolean {
  if (
    !value ||
    RESERVED_EXACT.has(value) ||
    RESERVED_PREFIXES.some((prefix) => value.startsWith(prefix))
  ) {
    return false;
  }

  let codePoints = 0;
  let utf8Bytes = 0;
  let firstCodePoint: number | undefined;
  let lastCodePoint: number | undefined;
  for (const char of value) {
    const codePoint = char.codePointAt(0);
    if (codePoint === undefined || codePointDisallowed(codePoint)) return false;
    firstCodePoint ??= codePoint;
    lastCodePoint = codePoint;
    codePoints += 1;
    utf8Bytes += codePoint <= 0x7f ? 1 : codePoint <= 0x7ff ? 2 : codePoint <= 0xffff ? 3 : 4;
    if (
      codePoints > MAX_GRAPH_IDENTIFIER_CODE_POINTS ||
      utf8Bytes > MAX_GRAPH_IDENTIFIER_UTF8_BYTES
    )
      return false;
  }
  return firstCodePoint !== 0x20 && lastCodePoint !== 0x20;
}

export const GRAPH_IDENTIFIER_CONFORMANCE_CASES = [
  { name: "ascii", value: "author", valid: true },
  { name: "internal_ascii_space", value: "post author", valid: true },
  { name: "visible_unicode", value: "\u6587\u7ae0", valid: true },
  { name: "decomposed_unicode", value: "e\u0301", valid: true },
  { name: "empty", value: "", valid: false },
  { name: "count_sentinel", value: "*", valid: false },
  { name: "reserved_prefix", value: "$result", valid: false },
  { name: "leading_space", value: " author", valid: false },
  { name: "trailing_space", value: "author ", valid: false },
  { name: "newline", value: "post\nauthor", valid: false },
  { name: "null_control", value: "post\u0000author", valid: false },
  { name: "non_breaking_space", value: "post\u00a0author", valid: false },
  { name: "zero_width_space", value: "post\u200bauthor", valid: false },
  { name: "line_separator", value: "post\u2028author", valid: false },
  { name: "bidi_override", value: "post\u202eauthor", valid: false },
] as const;
