// Copyright 2026 Antfly, Inc.
//
// Licensed under the Elastic License 2.0 (ELv2); you may not use this file
// except in compliance with the Elastic License 2.0. You may obtain a copy of
// the Elastic License 2.0 at
//
//     https://www.antfly.io/licensing/ELv2-license
//
// Unless required by applicable law or agreed to in writing, software distributed
// under the Elastic License 2.0 is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// Elastic License 2.0 for the specific language governing permissions and
// limitations.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: ops.proto

package db

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op_OpType int32

const (
	Op_OpBatch             Op_OpType = 0
	Op_OpSplit             Op_OpType = 1
	Op_OpSetRange          Op_OpType = 2
	Op_OpUpdateSchema      Op_OpType = 3
	Op_OpAddIndex          Op_OpType = 4
	Op_OpDeleteIndex       Op_OpType = 5
	Op_OpBackup            Op_OpType = 6
	Op_OpInitTransaction   Op_OpType = 7
	Op_OpCommitTransaction Op_OpType = 8
	Op_OpAbortTransaction  Op_OpType = 9
	Op_OpWriteIntent       Op_OpType = 10
	Op_OpResolveIntents    Op_OpType = 11
	Op_OpFinalizeSplit     Op_OpType = 12 // Complete a split by deleting split-off data
	Op_OpSetSplitState     Op_OpType = 13 // Update split state (replaces local pendingSplitKey)
	Op_OpFinalizeMerge     Op_OpType = 14 // Complete a merge by widening the receiver range
	Op_OpSetMergeState     Op_OpType = 15 // Update merge state on donor/receiver shards
)

// Enum value maps for Op_OpType.
var (
	Op_OpType_name = map[int32]string{
		0:  "OpBatch",
		1:  "OpSplit",
		2:  "OpSetRange",
		3:  "OpUpdateSchema",
		4:  "OpAddIndex",
		5:  "OpDeleteIndex",
		6:  "OpBackup",
		7:  "OpInitTransaction",
		8:  "OpCommitTransaction",
		9:  "OpAbortTransaction",
		10: "OpWriteIntent",
		11: "OpResolveIntents",
		12: "OpFinalizeSplit",
		13: "OpSetSplitState",
		14: "OpFinalizeMerge",
		15: "OpSetMergeState",
	}
	Op_OpType_value = map[string]int32{
		"OpBatch":             0,
		"OpSplit":             1,
		"OpSetRange":          2,
		"OpUpdateSchema":      3,
		"OpAddIndex":          4,
		"OpDeleteIndex":       5,
		"OpBackup":            6,
		"OpInitTransaction":   7,
		"OpCommitTransaction": 8,
		"OpAbortTransaction":  9,
		"OpWriteIntent":       10,
		"OpResolveIntents":    11,
		"OpFinalizeSplit":     12,
		"OpSetSplitState":     13,
		"OpFinalizeMerge":     14,
		"OpSetMergeState":     15,
	}
)

func (x Op_OpType) Enum() *Op_OpType {
	p := new(Op_OpType)
	*p = x
	return p
}

func (x Op_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_ops_proto_enumTypes[0].Descriptor()
}

func (Op_OpType) Type() protoreflect.EnumType {
	return &file_ops_proto_enumTypes[0]
}

func (x Op_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Op_SyncLevel int32

const (
	Op_SyncLevelPropose     Op_SyncLevel = 0 // Wait for Raft proposal acceptance (default)
	Op_SyncLevelWrite       Op_SyncLevel = 1 // Wait for Pebble KV write
	Op_SyncLevelFullText    Op_SyncLevel = 2 // Wait for full-text index WAL write
	Op_SyncLevelEnrichments Op_SyncLevel = 3 // Pre-compute enrichments before Raft proposal
	Op_SyncLevelEmbeddings  Op_SyncLevel = 4 // Wait for embeddings index write (dense + sparse + full-text)
)

// Enum value maps for Op_SyncLevel.
var (
	Op_SyncLevel_name = map[int32]string{
		0: "SyncLevelPropose",
		1: "SyncLevelWrite",
		2: "SyncLevelFullText",
		3: "SyncLevelEnrichments",
		4: "SyncLevelEmbeddings",
	}
	Op_SyncLevel_value = map[string]int32{
		"SyncLevelPropose":     0,
		"SyncLevelWrite":       1,
		"SyncLevelFullText":    2,
		"SyncLevelEnrichments": 3,
		"SyncLevelEmbeddings":  4,
	}
)

func (x Op_SyncLevel) Enum() *Op_SyncLevel {
	p := new(Op_SyncLevel)
	*p = x
	return p
}

func (x Op_SyncLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op_SyncLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_ops_proto_enumTypes[1].Descriptor()
}

func (Op_SyncLevel) Type() protoreflect.EnumType {
	return &file_ops_proto_enumTypes[1]
}

func (x Op_SyncLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type TransformOp_OpType int32

const (
	TransformOp_SET          TransformOp_OpType = 0  // $set - Set value at path
	TransformOp_UNSET        TransformOp_OpType = 1  // $unset - Remove field
	TransformOp_INC          TransformOp_OpType = 2  // $inc - Increment/decrement numeric value
	TransformOp_PUSH         TransformOp_OpType = 3  // $push - Append to array
	TransformOp_PULL         TransformOp_OpType = 4  // $pull - Remove array elements matching value
	TransformOp_ADD_TO_SET   TransformOp_OpType = 5  // $addToSet - Add to array if not exists
	TransformOp_POP          TransformOp_OpType = 6  // $pop - Remove first (-1) or last (1) array element
	TransformOp_MUL          TransformOp_OpType = 7  // $mul - Multiply numeric value
	TransformOp_MIN          TransformOp_OpType = 8  // $min - Set to minimum of current and value
	TransformOp_MAX          TransformOp_OpType = 9  // $max - Set to maximum of current and value
	TransformOp_CURRENT_DATE TransformOp_OpType = 10 // $currentDate - Set to current timestamp
	TransformOp_RENAME       TransformOp_OpType = 11 // $rename - Rename field
)

// Enum value maps for TransformOp_OpType.
var (
	TransformOp_OpType_name = map[int32]string{
		0:  "SET",
		1:  "UNSET",
		2:  "INC",
		3:  "PUSH",
		4:  "PULL",
		5:  "ADD_TO_SET",
		6:  "POP",
		7:  "MUL",
		8:  "MIN",
		9:  "MAX",
		10: "CURRENT_DATE",
		11: "RENAME",
	}
	TransformOp_OpType_value = map[string]int32{
		"SET":          0,
		"UNSET":        1,
		"INC":          2,
		"PUSH":         3,
		"PULL":         4,
		"ADD_TO_SET":   5,
		"POP":          6,
		"MUL":          7,
		"MIN":          8,
		"MAX":          9,
		"CURRENT_DATE": 10,
		"RENAME":       11,
	}
)

func (x TransformOp_OpType) Enum() *TransformOp_OpType {
	p := new(TransformOp_OpType)
	*p = x
	return p
}

func (x TransformOp_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransformOp_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_ops_proto_enumTypes[2].Descriptor()
}

func (TransformOp_OpType) Type() protoreflect.EnumType {
	return &file_ops_proto_enumTypes[2]
}

func (x TransformOp_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Phase represents the current stage of the split operation.
type SplitState_Phase int32

const (
	SplitState_PHASE_NONE         SplitState_Phase = 0 // No split in progress
	SplitState_PHASE_PREPARE      SplitState_Phase = 1 // Shadow index created, dual-write active
	SplitState_PHASE_SPLITTING    SplitState_Phase = 2 // Archive created, new shard starting
	SplitState_PHASE_FINALIZING   SplitState_Phase = 3 // New shard ready, cleaning up parent
	SplitState_PHASE_ROLLING_BACK SplitState_Phase = 4 // Timeout reached, reverting to pre-split
)

// Enum value maps for SplitState_Phase.
var (
	SplitState_Phase_name = map[int32]string{
		0: "PHASE_NONE",
		1: "PHASE_PREPARE",
		2: "PHASE_SPLITTING",
		3: "PHASE_FINALIZING",
		4: "PHASE_ROLLING_BACK",
	}
	SplitState_Phase_value = map[string]int32{
		"PHASE_NONE":         0,
		"PHASE_PREPARE":      1,
		"PHASE_SPLITTING":    2,
		"PHASE_FINALIZING":   3,
		"PHASE_ROLLING_BACK": 4,
	}
)

func (x SplitState_Phase) Enum() *SplitState_Phase {
	p := new(SplitState_Phase)
	*p = x
	return p
}

func (x SplitState_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitState_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_ops_proto_enumTypes[3].Descriptor()
}

func (SplitState_Phase) Type() protoreflect.EnumType {
	return &file_ops_proto_enumTypes[3]
}

func (x SplitState_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MergeState_Phase int32

const (
	MergeState_PHASE_NONE         MergeState_Phase = 0
	MergeState_PHASE_PREPARE      MergeState_Phase = 1
	MergeState_PHASE_COPYING      MergeState_Phase = 2
	MergeState_PHASE_CATCHUP      MergeState_Phase = 3
	MergeState_PHASE_FINALIZING   MergeState_Phase = 4
	MergeState_PHASE_ROLLING_BACK MergeState_Phase = 5
)

// Enum value maps for MergeState_Phase.
var (
	MergeState_Phase_name = map[int32]string{
		0: "PHASE_NONE",
		1: "PHASE_PREPARE",
		2: "PHASE_COPYING",
		3: "PHASE_CATCHUP",
		4: "PHASE_FINALIZING",
		5: "PHASE_ROLLING_BACK",
	}
	MergeState_Phase_value = map[string]int32{
		"PHASE_NONE":         0,
		"PHASE_PREPARE":      1,
		"PHASE_COPYING":      2,
		"PHASE_CATCHUP":      3,
		"PHASE_FINALIZING":   4,
		"PHASE_ROLLING_BACK": 5,
	}
)

func (x MergeState_Phase) Enum() *MergeState_Phase {
	p := new(MergeState_Phase)
	*p = x
	return p
}

func (x MergeState_Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MergeState_Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_ops_proto_enumTypes[4].Descriptor()
}

func (MergeState_Phase) Type() protoreflect.EnumType {
	return &file_ops_proto_enumTypes[4]
}

func (x MergeState_Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Op struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Op        Op_OpType              `protobuf:"varint,1,opt,name=op,enum=db.Op_OpType"`
	xxx_hidden_Uuid      *string                `protobuf:"bytes,2,opt,name=uuid"`
	xxx_hidden_Operation isOp_Operation         `protobuf_oneof:"operation"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_ops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Op) GetOp() Op_OpType {
	if x != nil {
		return x.xxx_hidden_Op
	}
	return Op_OpBatch
}

func (x *Op) GetUuid() string {
	if x != nil {
		if x.xxx_hidden_Uuid != nil {
			return *x.xxx_hidden_Uuid
		}
		return ""
	}
	return ""
}

func (x *Op) GetBatch() *BatchOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

func (x *Op) GetSplit() *SplitOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_Split); ok {
			return x.Split
		}
	}
	return nil
}

func (x *Op) GetSetRange() *SetRangeOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_SetRange); ok {
			return x.SetRange
		}
	}
	return nil
}

func (x *Op) GetUpdateSchema() *UpdateSchemaOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_UpdateSchema); ok {
			return x.UpdateSchema
		}
	}
	return nil
}

func (x *Op) GetAddIndex() *AddIndexOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_AddIndex); ok {
			return x.AddIndex
		}
	}
	return nil
}

func (x *Op) GetDeleteIndex() *DeleteIndexOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_DeleteIndex); ok {
			return x.DeleteIndex
		}
	}
	return nil
}

func (x *Op) GetBackup() *BackupOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_Backup); ok {
			return x.Backup
		}
	}
	return nil
}

func (x *Op) GetInitTransaction() *InitTransactionOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_InitTransaction); ok {
			return x.InitTransaction
		}
	}
	return nil
}

func (x *Op) GetCommitTransaction() *CommitTransactionOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_CommitTransaction); ok {
			return x.CommitTransaction
		}
	}
	return nil
}

func (x *Op) GetAbortTransaction() *AbortTransactionOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_AbortTransaction); ok {
			return x.AbortTransaction
		}
	}
	return nil
}

func (x *Op) GetWriteIntent() *WriteIntentOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_WriteIntent); ok {
			return x.WriteIntent
		}
	}
	return nil
}

func (x *Op) GetResolveIntents() *ResolveIntentsOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_ResolveIntents); ok {
			return x.ResolveIntents
		}
	}
	return nil
}

func (x *Op) GetFinalizeSplit() *FinalizeSplitOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_FinalizeSplit); ok {
			return x.FinalizeSplit
		}
	}
	return nil
}

func (x *Op) GetSetSplitState() *SetSplitStateOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_SetSplitState); ok {
			return x.SetSplitState
		}
	}
	return nil
}

func (x *Op) GetFinalizeMerge() *FinalizeMergeOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_FinalizeMerge); ok {
			return x.FinalizeMerge
		}
	}
	return nil
}

func (x *Op) GetSetMergeState() *SetMergeStateOp {
	if x != nil {
		if x, ok := x.xxx_hidden_Operation.(*op_SetMergeState); ok {
			return x.SetMergeState
		}
	}
	return nil
}

func (x *Op) SetOp(v Op_OpType) {
	x.xxx_hidden_Op = v
}

func (x *Op) SetUuid(v string) {
	x.xxx_hidden_Uuid = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *Op) SetBatch(v *BatchOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_Batch{v}
}

func (x *Op) SetSplit(v *SplitOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_Split{v}
}

func (x *Op) SetSetRange(v *SetRangeOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_SetRange{v}
}

func (x *Op) SetUpdateSchema(v *UpdateSchemaOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_UpdateSchema{v}
}

func (x *Op) SetAddIndex(v *AddIndexOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_AddIndex{v}
}

func (x *Op) SetDeleteIndex(v *DeleteIndexOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_DeleteIndex{v}
}

func (x *Op) SetBackup(v *BackupOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_Backup{v}
}

func (x *Op) SetInitTransaction(v *InitTransactionOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_InitTransaction{v}
}

func (x *Op) SetCommitTransaction(v *CommitTransactionOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_CommitTransaction{v}
}

func (x *Op) SetAbortTransaction(v *AbortTransactionOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_AbortTransaction{v}
}

func (x *Op) SetWriteIntent(v *WriteIntentOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_WriteIntent{v}
}

func (x *Op) SetResolveIntents(v *ResolveIntentsOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_ResolveIntents{v}
}

func (x *Op) SetFinalizeSplit(v *FinalizeSplitOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_FinalizeSplit{v}
}

func (x *Op) SetSetSplitState(v *SetSplitStateOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_SetSplitState{v}
}

func (x *Op) SetFinalizeMerge(v *FinalizeMergeOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_FinalizeMerge{v}
}

func (x *Op) SetSetMergeState(v *SetMergeStateOp) {
	if v == nil {
		x.xxx_hidden_Operation = nil
		return
	}
	x.xxx_hidden_Operation = &op_SetMergeState{v}
}

func (x *Op) HasUuid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Op) HasOperation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Operation != nil
}

func (x *Op) HasBatch() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_Batch)
	return ok
}

func (x *Op) HasSplit() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_Split)
	return ok
}

func (x *Op) HasSetRange() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_SetRange)
	return ok
}

func (x *Op) HasUpdateSchema() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_UpdateSchema)
	return ok
}

func (x *Op) HasAddIndex() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_AddIndex)
	return ok
}

func (x *Op) HasDeleteIndex() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_DeleteIndex)
	return ok
}

func (x *Op) HasBackup() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_Backup)
	return ok
}

func (x *Op) HasInitTransaction() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_InitTransaction)
	return ok
}

func (x *Op) HasCommitTransaction() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_CommitTransaction)
	return ok
}

func (x *Op) HasAbortTransaction() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_AbortTransaction)
	return ok
}

func (x *Op) HasWriteIntent() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_WriteIntent)
	return ok
}

func (x *Op) HasResolveIntents() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_ResolveIntents)
	return ok
}

func (x *Op) HasFinalizeSplit() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_FinalizeSplit)
	return ok
}

func (x *Op) HasSetSplitState() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_SetSplitState)
	return ok
}

func (x *Op) HasFinalizeMerge() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_FinalizeMerge)
	return ok
}

func (x *Op) HasSetMergeState() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Operation.(*op_SetMergeState)
	return ok
}

func (x *Op) ClearUuid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Uuid = nil
}

func (x *Op) ClearOperation() {
	x.xxx_hidden_Operation = nil
}

func (x *Op) ClearBatch() {
	if _, ok := x.xxx_hidden_Operation.(*op_Batch); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearSplit() {
	if _, ok := x.xxx_hidden_Operation.(*op_Split); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearSetRange() {
	if _, ok := x.xxx_hidden_Operation.(*op_SetRange); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearUpdateSchema() {
	if _, ok := x.xxx_hidden_Operation.(*op_UpdateSchema); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearAddIndex() {
	if _, ok := x.xxx_hidden_Operation.(*op_AddIndex); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearDeleteIndex() {
	if _, ok := x.xxx_hidden_Operation.(*op_DeleteIndex); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearBackup() {
	if _, ok := x.xxx_hidden_Operation.(*op_Backup); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearInitTransaction() {
	if _, ok := x.xxx_hidden_Operation.(*op_InitTransaction); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearCommitTransaction() {
	if _, ok := x.xxx_hidden_Operation.(*op_CommitTransaction); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearAbortTransaction() {
	if _, ok := x.xxx_hidden_Operation.(*op_AbortTransaction); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearWriteIntent() {
	if _, ok := x.xxx_hidden_Operation.(*op_WriteIntent); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearResolveIntents() {
	if _, ok := x.xxx_hidden_Operation.(*op_ResolveIntents); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearFinalizeSplit() {
	if _, ok := x.xxx_hidden_Operation.(*op_FinalizeSplit); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearSetSplitState() {
	if _, ok := x.xxx_hidden_Operation.(*op_SetSplitState); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearFinalizeMerge() {
	if _, ok := x.xxx_hidden_Operation.(*op_FinalizeMerge); ok {
		x.xxx_hidden_Operation = nil
	}
}

func (x *Op) ClearSetMergeState() {
	if _, ok := x.xxx_hidden_Operation.(*op_SetMergeState); ok {
		x.xxx_hidden_Operation = nil
	}
}

const Op_Operation_not_set_case case_Op_Operation = 0
const Op_Batch_case case_Op_Operation = 3
const Op_Split_case case_Op_Operation = 4
const Op_SetRange_case case_Op_Operation = 5
const Op_UpdateSchema_case case_Op_Operation = 6
const Op_AddIndex_case case_Op_Operation = 7
const Op_DeleteIndex_case case_Op_Operation = 8
const Op_Backup_case case_Op_Operation = 9
const Op_InitTransaction_case case_Op_Operation = 10
const Op_CommitTransaction_case case_Op_Operation = 11
const Op_AbortTransaction_case case_Op_Operation = 12
const Op_WriteIntent_case case_Op_Operation = 13
const Op_ResolveIntents_case case_Op_Operation = 14
const Op_FinalizeSplit_case case_Op_Operation = 15
const Op_SetSplitState_case case_Op_Operation = 16
const Op_FinalizeMerge_case case_Op_Operation = 17
const Op_SetMergeState_case case_Op_Operation = 18

func (x *Op) WhichOperation() case_Op_Operation {
	if x == nil {
		return Op_Operation_not_set_case
	}
	switch x.xxx_hidden_Operation.(type) {
	case *op_Batch:
		return Op_Batch_case
	case *op_Split:
		return Op_Split_case
	case *op_SetRange:
		return Op_SetRange_case
	case *op_UpdateSchema:
		return Op_UpdateSchema_case
	case *op_AddIndex:
		return Op_AddIndex_case
	case *op_DeleteIndex:
		return Op_DeleteIndex_case
	case *op_Backup:
		return Op_Backup_case
	case *op_InitTransaction:
		return Op_InitTransaction_case
	case *op_CommitTransaction:
		return Op_CommitTransaction_case
	case *op_AbortTransaction:
		return Op_AbortTransaction_case
	case *op_WriteIntent:
		return Op_WriteIntent_case
	case *op_ResolveIntents:
		return Op_ResolveIntents_case
	case *op_FinalizeSplit:
		return Op_FinalizeSplit_case
	case *op_SetSplitState:
		return Op_SetSplitState_case
	case *op_FinalizeMerge:
		return Op_FinalizeMerge_case
	case *op_SetMergeState:
		return Op_SetMergeState_case
	default:
		return Op_Operation_not_set_case
	}
}

type Op_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Op   Op_OpType
	Uuid *string
	// Operation-specific data

	// Fields of oneof xxx_hidden_Operation:
	Batch             *BatchOp
	Split             *SplitOp
	SetRange          *SetRangeOp
	UpdateSchema      *UpdateSchemaOp
	AddIndex          *AddIndexOp
	DeleteIndex       *DeleteIndexOp
	Backup            *BackupOp
	InitTransaction   *InitTransactionOp
	CommitTransaction *CommitTransactionOp
	AbortTransaction  *AbortTransactionOp
	WriteIntent       *WriteIntentOp
	ResolveIntents    *ResolveIntentsOp
	FinalizeSplit     *FinalizeSplitOp
	SetSplitState     *SetSplitStateOp
	FinalizeMerge     *FinalizeMergeOp
	SetMergeState     *SetMergeStateOp
	// -- end of xxx_hidden_Operation
}

func (b0 Op_builder) Build() *Op {
	m0 := &Op{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Op = b.Op
	if b.Uuid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Uuid = b.Uuid
	}
	if b.Batch != nil {
		x.xxx_hidden_Operation = &op_Batch{b.Batch}
	}
	if b.Split != nil {
		x.xxx_hidden_Operation = &op_Split{b.Split}
	}
	if b.SetRange != nil {
		x.xxx_hidden_Operation = &op_SetRange{b.SetRange}
	}
	if b.UpdateSchema != nil {
		x.xxx_hidden_Operation = &op_UpdateSchema{b.UpdateSchema}
	}
	if b.AddIndex != nil {
		x.xxx_hidden_Operation = &op_AddIndex{b.AddIndex}
	}
	if b.DeleteIndex != nil {
		x.xxx_hidden_Operation = &op_DeleteIndex{b.DeleteIndex}
	}
	if b.Backup != nil {
		x.xxx_hidden_Operation = &op_Backup{b.Backup}
	}
	if b.InitTransaction != nil {
		x.xxx_hidden_Operation = &op_InitTransaction{b.InitTransaction}
	}
	if b.CommitTransaction != nil {
		x.xxx_hidden_Operation = &op_CommitTransaction{b.CommitTransaction}
	}
	if b.AbortTransaction != nil {
		x.xxx_hidden_Operation = &op_AbortTransaction{b.AbortTransaction}
	}
	if b.WriteIntent != nil {
		x.xxx_hidden_Operation = &op_WriteIntent{b.WriteIntent}
	}
	if b.ResolveIntents != nil {
		x.xxx_hidden_Operation = &op_ResolveIntents{b.ResolveIntents}
	}
	if b.FinalizeSplit != nil {
		x.xxx_hidden_Operation = &op_FinalizeSplit{b.FinalizeSplit}
	}
	if b.SetSplitState != nil {
		x.xxx_hidden_Operation = &op_SetSplitState{b.SetSplitState}
	}
	if b.FinalizeMerge != nil {
		x.xxx_hidden_Operation = &op_FinalizeMerge{b.FinalizeMerge}
	}
	if b.SetMergeState != nil {
		x.xxx_hidden_Operation = &op_SetMergeState{b.SetMergeState}
	}
	return m0
}

type case_Op_Operation protoreflect.FieldNumber

func (x case_Op_Operation) String() string {
	md := file_ops_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isOp_Operation interface {
	isOp_Operation()
}

type op_Batch struct {
	Batch *BatchOp `protobuf:"bytes,3,opt,name=batch,oneof"`
}

type op_Split struct {
	Split *SplitOp `protobuf:"bytes,4,opt,name=split,oneof"`
}

type op_SetRange struct {
	SetRange *SetRangeOp `protobuf:"bytes,5,opt,name=set_range,json=setRange,oneof"`
}

type op_UpdateSchema struct {
	UpdateSchema *UpdateSchemaOp `protobuf:"bytes,6,opt,name=update_schema,json=updateSchema,oneof"`
}

type op_AddIndex struct {
	AddIndex *AddIndexOp `protobuf:"bytes,7,opt,name=add_index,json=addIndex,oneof"`
}

type op_DeleteIndex struct {
	DeleteIndex *DeleteIndexOp `protobuf:"bytes,8,opt,name=delete_index,json=deleteIndex,oneof"`
}

type op_Backup struct {
	Backup *BackupOp `protobuf:"bytes,9,opt,name=backup,oneof"`
}

type op_InitTransaction struct {
	InitTransaction *InitTransactionOp `protobuf:"bytes,10,opt,name=init_transaction,json=initTransaction,oneof"`
}

type op_CommitTransaction struct {
	CommitTransaction *CommitTransactionOp `protobuf:"bytes,11,opt,name=commit_transaction,json=commitTransaction,oneof"`
}

type op_AbortTransaction struct {
	AbortTransaction *AbortTransactionOp `protobuf:"bytes,12,opt,name=abort_transaction,json=abortTransaction,oneof"`
}

type op_WriteIntent struct {
	WriteIntent *WriteIntentOp `protobuf:"bytes,13,opt,name=write_intent,json=writeIntent,oneof"`
}

type op_ResolveIntents struct {
	ResolveIntents *ResolveIntentsOp `protobuf:"bytes,14,opt,name=resolve_intents,json=resolveIntents,oneof"`
}

type op_FinalizeSplit struct {
	FinalizeSplit *FinalizeSplitOp `protobuf:"bytes,15,opt,name=finalize_split,json=finalizeSplit,oneof"`
}

type op_SetSplitState struct {
	SetSplitState *SetSplitStateOp `protobuf:"bytes,16,opt,name=set_split_state,json=setSplitState,oneof"`
}

type op_FinalizeMerge struct {
	FinalizeMerge *FinalizeMergeOp `protobuf:"bytes,17,opt,name=finalize_merge,json=finalizeMerge,oneof"`
}

type op_SetMergeState struct {
	SetMergeState *SetMergeStateOp `protobuf:"bytes,18,opt,name=set_merge_state,json=setMergeState,oneof"`
}

func (*op_Batch) isOp_Operation() {}

func (*op_Split) isOp_Operation() {}

func (*op_SetRange) isOp_Operation() {}

func (*op_UpdateSchema) isOp_Operation() {}

func (*op_AddIndex) isOp_Operation() {}

func (*op_DeleteIndex) isOp_Operation() {}

func (*op_Backup) isOp_Operation() {}

func (*op_InitTransaction) isOp_Operation() {}

func (*op_CommitTransaction) isOp_Operation() {}

func (*op_AbortTransaction) isOp_Operation() {}

func (*op_WriteIntent) isOp_Operation() {}

func (*op_ResolveIntents) isOp_Operation() {}

func (*op_FinalizeSplit) isOp_Operation() {}

func (*op_SetSplitState) isOp_Operation() {}

func (*op_FinalizeMerge) isOp_Operation() {}

func (*op_SetMergeState) isOp_Operation() {}

type Write struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   []byte                 `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Value []byte                 `protobuf:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Write) Reset() {
	*x = Write{}
	mi := &file_ops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Write) GetKey() []byte {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *Write) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *Write) SetKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = v
}

func (x *Write) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
}

type Write_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   []byte
	Value []byte
}

func (b0 Write_builder) Build() *Write {
	m0 := &Write{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

type TransformOp struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Path        string                 `protobuf:"bytes,1,opt,name=path"`
	xxx_hidden_Op          TransformOp_OpType     `protobuf:"varint,2,opt,name=op,enum=db.TransformOp_OpType"`
	xxx_hidden_Value       []byte                 `protobuf:"bytes,3,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TransformOp) Reset() {
	*x = TransformOp{}
	mi := &file_ops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformOp) ProtoMessage() {}

func (x *TransformOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TransformOp) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *TransformOp) GetOp() TransformOp_OpType {
	if x != nil {
		return x.xxx_hidden_Op
	}
	return TransformOp_SET
}

func (x *TransformOp) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *TransformOp) SetPath(v string) {
	x.xxx_hidden_Path = v
}

func (x *TransformOp) SetOp(v TransformOp_OpType) {
	x.xxx_hidden_Op = v
}

func (x *TransformOp) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *TransformOp) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *TransformOp) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Value = nil
}

type TransformOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Path  string
	Op    TransformOp_OpType
	Value []byte
}

func (b0 TransformOp_builder) Build() *TransformOp {
	m0 := &TransformOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Path = b.Path
	x.xxx_hidden_Op = b.Op
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Value = b.Value
	}
	return m0
}

type Transform struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key         []byte                 `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_Operations  *[]*TransformOp        `protobuf:"bytes,2,rep,name=operations"`
	xxx_hidden_Upsert      bool                   `protobuf:"varint,3,opt,name=upsert"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Transform) Reset() {
	*x = Transform{}
	mi := &file_ops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Transform) GetKey() []byte {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *Transform) GetOperations() []*TransformOp {
	if x != nil {
		if x.xxx_hidden_Operations != nil {
			return *x.xxx_hidden_Operations
		}
	}
	return nil
}

func (x *Transform) GetUpsert() bool {
	if x != nil {
		return x.xxx_hidden_Upsert
	}
	return false
}

func (x *Transform) SetKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = v
}

func (x *Transform) SetOperations(v []*TransformOp) {
	x.xxx_hidden_Operations = &v
}

func (x *Transform) SetUpsert(v bool) {
	x.xxx_hidden_Upsert = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *Transform) HasUpsert() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Transform) ClearUpsert() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Upsert = false
}

type Transform_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key        []byte
	Operations []*TransformOp
	Upsert     *bool
}

func (b0 Transform_builder) Build() *Transform {
	m0 := &Transform{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Operations = &b.Operations
	if b.Upsert != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Upsert = *b.Upsert
	}
	return m0
}

type BatchOp struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Writes      *[]*Write              `protobuf:"bytes,1,rep,name=writes"`
	xxx_hidden_Deletes     [][]byte               `protobuf:"bytes,2,rep,name=deletes"`
	xxx_hidden_Transforms  *[]*Transform          `protobuf:"bytes,3,rep,name=transforms"`
	xxx_hidden_SyncLevel   Op_SyncLevel           `protobuf:"varint,4,opt,name=sync_level,json=syncLevel,enum=db.Op_SyncLevel"`
	xxx_hidden_Timestamp   uint64                 `protobuf:"varint,5,opt,name=timestamp"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BatchOp) Reset() {
	*x = BatchOp{}
	mi := &file_ops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOp) ProtoMessage() {}

func (x *BatchOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BatchOp) GetWrites() []*Write {
	if x != nil {
		if x.xxx_hidden_Writes != nil {
			return *x.xxx_hidden_Writes
		}
	}
	return nil
}

func (x *BatchOp) GetDeletes() [][]byte {
	if x != nil {
		return x.xxx_hidden_Deletes
	}
	return nil
}

func (x *BatchOp) GetTransforms() []*Transform {
	if x != nil {
		if x.xxx_hidden_Transforms != nil {
			return *x.xxx_hidden_Transforms
		}
	}
	return nil
}

func (x *BatchOp) GetSyncLevel() Op_SyncLevel {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_SyncLevel
		}
	}
	return Op_SyncLevelPropose
}

func (x *BatchOp) GetTimestamp() uint64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *BatchOp) SetWrites(v []*Write) {
	x.xxx_hidden_Writes = &v
}

func (x *BatchOp) SetDeletes(v [][]byte) {
	x.xxx_hidden_Deletes = v
}

func (x *BatchOp) SetTransforms(v []*Transform) {
	x.xxx_hidden_Transforms = &v
}

func (x *BatchOp) SetSyncLevel(v Op_SyncLevel) {
	x.xxx_hidden_SyncLevel = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *BatchOp) SetTimestamp(v uint64) {
	x.xxx_hidden_Timestamp = v
}

func (x *BatchOp) HasSyncLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BatchOp) ClearSyncLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_SyncLevel = Op_SyncLevelPropose
}

type BatchOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Writes     []*Write
	Deletes    [][]byte
	Transforms []*Transform
	SyncLevel  *Op_SyncLevel
	Timestamp  uint64
}

func (b0 BatchOp_builder) Build() *BatchOp {
	m0 := &BatchOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Writes = &b.Writes
	x.xxx_hidden_Deletes = b.Deletes
	x.xxx_hidden_Transforms = &b.Transforms
	if b.SyncLevel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_SyncLevel = *b.SyncLevel
	}
	x.xxx_hidden_Timestamp = b.Timestamp
	return m0
}

type SplitDeltaEntry struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sequence  uint64                 `protobuf:"varint,1,opt,name=sequence"`
	xxx_hidden_Timestamp uint64                 `protobuf:"varint,2,opt,name=timestamp"`
	xxx_hidden_Writes    *[]*Write              `protobuf:"bytes,3,rep,name=writes"`
	xxx_hidden_Deletes   [][]byte               `protobuf:"bytes,4,rep,name=deletes"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SplitDeltaEntry) Reset() {
	*x = SplitDeltaEntry{}
	mi := &file_ops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitDeltaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitDeltaEntry) ProtoMessage() {}

func (x *SplitDeltaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SplitDeltaEntry) GetSequence() uint64 {
	if x != nil {
		return x.xxx_hidden_Sequence
	}
	return 0
}

func (x *SplitDeltaEntry) GetTimestamp() uint64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *SplitDeltaEntry) GetWrites() []*Write {
	if x != nil {
		if x.xxx_hidden_Writes != nil {
			return *x.xxx_hidden_Writes
		}
	}
	return nil
}

func (x *SplitDeltaEntry) GetDeletes() [][]byte {
	if x != nil {
		return x.xxx_hidden_Deletes
	}
	return nil
}

func (x *SplitDeltaEntry) SetSequence(v uint64) {
	x.xxx_hidden_Sequence = v
}

func (x *SplitDeltaEntry) SetTimestamp(v uint64) {
	x.xxx_hidden_Timestamp = v
}

func (x *SplitDeltaEntry) SetWrites(v []*Write) {
	x.xxx_hidden_Writes = &v
}

func (x *SplitDeltaEntry) SetDeletes(v [][]byte) {
	x.xxx_hidden_Deletes = v
}

type SplitDeltaEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sequence  uint64
	Timestamp uint64
	Writes    []*Write
	Deletes   [][]byte
}

func (b0 SplitDeltaEntry_builder) Build() *SplitDeltaEntry {
	m0 := &SplitDeltaEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sequence = b.Sequence
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Writes = &b.Writes
	x.xxx_hidden_Deletes = b.Deletes
	return m0
}

type MergeDeltaEntry struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Sequence  uint64                 `protobuf:"varint,1,opt,name=sequence"`
	xxx_hidden_Timestamp uint64                 `protobuf:"varint,2,opt,name=timestamp"`
	xxx_hidden_Writes    *[]*Write              `protobuf:"bytes,3,rep,name=writes"`
	xxx_hidden_Deletes   [][]byte               `protobuf:"bytes,4,rep,name=deletes"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MergeDeltaEntry) Reset() {
	*x = MergeDeltaEntry{}
	mi := &file_ops_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeDeltaEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeDeltaEntry) ProtoMessage() {}

func (x *MergeDeltaEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MergeDeltaEntry) GetSequence() uint64 {
	if x != nil {
		return x.xxx_hidden_Sequence
	}
	return 0
}

func (x *MergeDeltaEntry) GetTimestamp() uint64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *MergeDeltaEntry) GetWrites() []*Write {
	if x != nil {
		if x.xxx_hidden_Writes != nil {
			return *x.xxx_hidden_Writes
		}
	}
	return nil
}

func (x *MergeDeltaEntry) GetDeletes() [][]byte {
	if x != nil {
		return x.xxx_hidden_Deletes
	}
	return nil
}

func (x *MergeDeltaEntry) SetSequence(v uint64) {
	x.xxx_hidden_Sequence = v
}

func (x *MergeDeltaEntry) SetTimestamp(v uint64) {
	x.xxx_hidden_Timestamp = v
}

func (x *MergeDeltaEntry) SetWrites(v []*Write) {
	x.xxx_hidden_Writes = &v
}

func (x *MergeDeltaEntry) SetDeletes(v [][]byte) {
	x.xxx_hidden_Deletes = v
}

type MergeDeltaEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Sequence  uint64
	Timestamp uint64
	Writes    []*Write
	Deletes   [][]byte
}

func (b0 MergeDeltaEntry_builder) Build() *MergeDeltaEntry {
	m0 := &MergeDeltaEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Sequence = b.Sequence
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Writes = &b.Writes
	x.xxx_hidden_Deletes = b.Deletes
	return m0
}

type SplitOp struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NewShardId uint64                 `protobuf:"varint,1,opt,name=new_shard_id,json=newShardId"`
	xxx_hidden_SplitKey   []byte                 `protobuf:"bytes,2,opt,name=split_key,json=splitKey"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SplitOp) Reset() {
	*x = SplitOp{}
	mi := &file_ops_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitOp) ProtoMessage() {}

func (x *SplitOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SplitOp) GetNewShardId() uint64 {
	if x != nil {
		return x.xxx_hidden_NewShardId
	}
	return 0
}

func (x *SplitOp) GetSplitKey() []byte {
	if x != nil {
		return x.xxx_hidden_SplitKey
	}
	return nil
}

func (x *SplitOp) SetNewShardId(v uint64) {
	x.xxx_hidden_NewShardId = v
}

func (x *SplitOp) SetSplitKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SplitKey = v
}

type SplitOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NewShardId uint64
	SplitKey   []byte
}

func (b0 SplitOp_builder) Build() *SplitOp {
	m0 := &SplitOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NewShardId = b.NewShardId
	x.xxx_hidden_SplitKey = b.SplitKey
	return m0
}

// FinalizeSplitOp completes a split by deleting split-off data and updating the byte range.
// This is the second phase of a two-phase split that ensures continuous data availability.
// The first phase (SplitOp) creates the archive but preserves data on the parent shard.
// FinalizeSplit is triggered when the new shard is ready (has HasSnapshot=true).
type FinalizeSplitOp struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NewRangeEnd []byte                 `protobuf:"bytes,1,opt,name=new_range_end,json=newRangeEnd"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FinalizeSplitOp) Reset() {
	*x = FinalizeSplitOp{}
	mi := &file_ops_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSplitOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSplitOp) ProtoMessage() {}

func (x *FinalizeSplitOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FinalizeSplitOp) GetNewRangeEnd() []byte {
	if x != nil {
		return x.xxx_hidden_NewRangeEnd
	}
	return nil
}

func (x *FinalizeSplitOp) SetNewRangeEnd(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_NewRangeEnd = v
}

type FinalizeSplitOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The new end of the byte range after the split (the split key)
	NewRangeEnd []byte
}

func (b0 FinalizeSplitOp_builder) Build() *FinalizeSplitOp {
	m0 := &FinalizeSplitOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NewRangeEnd = b.NewRangeEnd
	return m0
}

type FinalizeMergeOp struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NewRangeStart []byte                 `protobuf:"bytes,1,opt,name=new_range_start,json=newRangeStart"`
	xxx_hidden_NewRangeEnd   []byte                 `protobuf:"bytes,2,opt,name=new_range_end,json=newRangeEnd"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *FinalizeMergeOp) Reset() {
	*x = FinalizeMergeOp{}
	mi := &file_ops_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeMergeOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeMergeOp) ProtoMessage() {}

func (x *FinalizeMergeOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FinalizeMergeOp) GetNewRangeStart() []byte {
	if x != nil {
		return x.xxx_hidden_NewRangeStart
	}
	return nil
}

func (x *FinalizeMergeOp) GetNewRangeEnd() []byte {
	if x != nil {
		return x.xxx_hidden_NewRangeEnd
	}
	return nil
}

func (x *FinalizeMergeOp) SetNewRangeStart(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_NewRangeStart = v
}

func (x *FinalizeMergeOp) SetNewRangeEnd(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_NewRangeEnd = v
}

type FinalizeMergeOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NewRangeStart []byte
	NewRangeEnd   []byte
}

func (b0 FinalizeMergeOp_builder) Build() *FinalizeMergeOp {
	m0 := &FinalizeMergeOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NewRangeStart = b.NewRangeStart
	x.xxx_hidden_NewRangeEnd = b.NewRangeEnd
	return m0
}

type SetRangeOp struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StartKey []byte                 `protobuf:"bytes,1,opt,name=start_key,json=startKey"`
	xxx_hidden_EndKey   []byte                 `protobuf:"bytes,2,opt,name=end_key,json=endKey"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetRangeOp) Reset() {
	*x = SetRangeOp{}
	mi := &file_ops_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRangeOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRangeOp) ProtoMessage() {}

func (x *SetRangeOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetRangeOp) GetStartKey() []byte {
	if x != nil {
		return x.xxx_hidden_StartKey
	}
	return nil
}

func (x *SetRangeOp) GetEndKey() []byte {
	if x != nil {
		return x.xxx_hidden_EndKey
	}
	return nil
}

func (x *SetRangeOp) SetStartKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_StartKey = v
}

func (x *SetRangeOp) SetEndKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_EndKey = v
}

type SetRangeOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	StartKey []byte
	EndKey   []byte
}

func (b0 SetRangeOp_builder) Build() *SetRangeOp {
	m0 := &SetRangeOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_StartKey = b.StartKey
	x.xxx_hidden_EndKey = b.EndKey
	return m0
}

type UpdateSchemaOp struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Schema []byte                 `protobuf:"bytes,1,opt,name=schema"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateSchemaOp) Reset() {
	*x = UpdateSchemaOp{}
	mi := &file_ops_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSchemaOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSchemaOp) ProtoMessage() {}

func (x *UpdateSchemaOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateSchemaOp) GetSchema() []byte {
	if x != nil {
		return x.xxx_hidden_Schema
	}
	return nil
}

func (x *UpdateSchemaOp) SetSchema(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Schema = v
}

type UpdateSchemaOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Schema []byte
}

func (b0 UpdateSchemaOp_builder) Build() *UpdateSchemaOp {
	m0 := &UpdateSchemaOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Schema = b.Schema
	return m0
}

type AddIndexOp struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name   string                 `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Type   string                 `protobuf:"bytes,2,opt,name=type"`
	xxx_hidden_Config []byte                 `protobuf:"bytes,3,opt,name=config"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddIndexOp) Reset() {
	*x = AddIndexOp{}
	mi := &file_ops_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIndexOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIndexOp) ProtoMessage() {}

func (x *AddIndexOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AddIndexOp) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *AddIndexOp) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *AddIndexOp) GetConfig() []byte {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *AddIndexOp) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *AddIndexOp) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *AddIndexOp) SetConfig(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Config = v
}

type AddIndexOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name   string
	Type   string
	Config []byte
}

func (b0 AddIndexOp_builder) Build() *AddIndexOp {
	m0 := &AddIndexOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Config = b.Config
	return m0
}

type DeleteIndexOp struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteIndexOp) Reset() {
	*x = DeleteIndexOp{}
	mi := &file_ops_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIndexOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIndexOp) ProtoMessage() {}

func (x *DeleteIndexOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteIndexOp) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *DeleteIndexOp) SetName(v string) {
	x.xxx_hidden_Name = v
}

type DeleteIndexOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 DeleteIndexOp_builder) Build() *DeleteIndexOp {
	m0 := &DeleteIndexOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

type BackupOp struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BackupId string                 `protobuf:"bytes,1,opt,name=backup_id,json=backupId"`
	xxx_hidden_Location string                 `protobuf:"bytes,2,opt,name=location"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BackupOp) Reset() {
	*x = BackupOp{}
	mi := &file_ops_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupOp) ProtoMessage() {}

func (x *BackupOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BackupOp) GetBackupId() string {
	if x != nil {
		return x.xxx_hidden_BackupId
	}
	return ""
}

func (x *BackupOp) GetLocation() string {
	if x != nil {
		return x.xxx_hidden_Location
	}
	return ""
}

func (x *BackupOp) SetBackupId(v string) {
	x.xxx_hidden_BackupId = v
}

func (x *BackupOp) SetLocation(v string) {
	x.xxx_hidden_Location = v
}

type BackupOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BackupId string
	Location string
}

func (b0 BackupOp_builder) Build() *BackupOp {
	m0 := &BackupOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BackupId = b.BackupId
	x.xxx_hidden_Location = b.Location
	return m0
}

type InitTransactionOp struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TxnId        []byte                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId"`
	xxx_hidden_Timestamp    uint64                 `protobuf:"varint,2,opt,name=timestamp"`
	xxx_hidden_Participants [][]byte               `protobuf:"bytes,3,rep,name=participants"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *InitTransactionOp) Reset() {
	*x = InitTransactionOp{}
	mi := &file_ops_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitTransactionOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTransactionOp) ProtoMessage() {}

func (x *InitTransactionOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *InitTransactionOp) GetTxnId() []byte {
	if x != nil {
		return x.xxx_hidden_TxnId
	}
	return nil
}

func (x *InitTransactionOp) GetTimestamp() uint64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *InitTransactionOp) GetParticipants() [][]byte {
	if x != nil {
		return x.xxx_hidden_Participants
	}
	return nil
}

func (x *InitTransactionOp) SetTxnId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TxnId = v
}

func (x *InitTransactionOp) SetTimestamp(v uint64) {
	x.xxx_hidden_Timestamp = v
}

func (x *InitTransactionOp) SetParticipants(v [][]byte) {
	x.xxx_hidden_Participants = v
}

type InitTransactionOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TxnId        []byte
	Timestamp    uint64
	Participants [][]byte
}

func (b0 InitTransactionOp_builder) Build() *InitTransactionOp {
	m0 := &InitTransactionOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TxnId = b.TxnId
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Participants = b.Participants
	return m0
}

type CommitTransactionOp struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TxnId []byte                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommitTransactionOp) Reset() {
	*x = CommitTransactionOp{}
	mi := &file_ops_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTransactionOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTransactionOp) ProtoMessage() {}

func (x *CommitTransactionOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CommitTransactionOp) GetTxnId() []byte {
	if x != nil {
		return x.xxx_hidden_TxnId
	}
	return nil
}

func (x *CommitTransactionOp) SetTxnId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TxnId = v
}

type CommitTransactionOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TxnId []byte
}

func (b0 CommitTransactionOp_builder) Build() *CommitTransactionOp {
	m0 := &CommitTransactionOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TxnId = b.TxnId
	return m0
}

type AbortTransactionOp struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TxnId []byte                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AbortTransactionOp) Reset() {
	*x = AbortTransactionOp{}
	mi := &file_ops_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortTransactionOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortTransactionOp) ProtoMessage() {}

func (x *AbortTransactionOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AbortTransactionOp) GetTxnId() []byte {
	if x != nil {
		return x.xxx_hidden_TxnId
	}
	return nil
}

func (x *AbortTransactionOp) SetTxnId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TxnId = v
}

type AbortTransactionOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TxnId []byte
}

func (b0 AbortTransactionOp_builder) Build() *AbortTransactionOp {
	m0 := &AbortTransactionOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TxnId = b.TxnId
	return m0
}

type VersionPredicate struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key             []byte                 `protobuf:"bytes,1,opt,name=key"`
	xxx_hidden_ExpectedVersion uint64                 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *VersionPredicate) Reset() {
	*x = VersionPredicate{}
	mi := &file_ops_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionPredicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionPredicate) ProtoMessage() {}

func (x *VersionPredicate) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VersionPredicate) GetKey() []byte {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return nil
}

func (x *VersionPredicate) GetExpectedVersion() uint64 {
	if x != nil {
		return x.xxx_hidden_ExpectedVersion
	}
	return 0
}

func (x *VersionPredicate) SetKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Key = v
}

func (x *VersionPredicate) SetExpectedVersion(v uint64) {
	x.xxx_hidden_ExpectedVersion = v
}

type VersionPredicate_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key             []byte
	ExpectedVersion uint64
}

func (b0 VersionPredicate_builder) Build() *VersionPredicate {
	m0 := &VersionPredicate{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_ExpectedVersion = b.ExpectedVersion
	return m0
}

type WriteIntentOp struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TxnId            []byte                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId"`
	xxx_hidden_Timestamp        uint64                 `protobuf:"varint,2,opt,name=timestamp"`
	xxx_hidden_CoordinatorShard []byte                 `protobuf:"bytes,3,opt,name=coordinator_shard,json=coordinatorShard"`
	xxx_hidden_Batch            *BatchOp               `protobuf:"bytes,4,opt,name=batch"`
	xxx_hidden_Predicates       *[]*VersionPredicate   `protobuf:"bytes,5,rep,name=predicates"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *WriteIntentOp) Reset() {
	*x = WriteIntentOp{}
	mi := &file_ops_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteIntentOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteIntentOp) ProtoMessage() {}

func (x *WriteIntentOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WriteIntentOp) GetTxnId() []byte {
	if x != nil {
		return x.xxx_hidden_TxnId
	}
	return nil
}

func (x *WriteIntentOp) GetTimestamp() uint64 {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return 0
}

func (x *WriteIntentOp) GetCoordinatorShard() []byte {
	if x != nil {
		return x.xxx_hidden_CoordinatorShard
	}
	return nil
}

func (x *WriteIntentOp) GetBatch() *BatchOp {
	if x != nil {
		return x.xxx_hidden_Batch
	}
	return nil
}

func (x *WriteIntentOp) GetPredicates() []*VersionPredicate {
	if x != nil {
		if x.xxx_hidden_Predicates != nil {
			return *x.xxx_hidden_Predicates
		}
	}
	return nil
}

func (x *WriteIntentOp) SetTxnId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TxnId = v
}

func (x *WriteIntentOp) SetTimestamp(v uint64) {
	x.xxx_hidden_Timestamp = v
}

func (x *WriteIntentOp) SetCoordinatorShard(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_CoordinatorShard = v
}

func (x *WriteIntentOp) SetBatch(v *BatchOp) {
	x.xxx_hidden_Batch = v
}

func (x *WriteIntentOp) SetPredicates(v []*VersionPredicate) {
	x.xxx_hidden_Predicates = &v
}

func (x *WriteIntentOp) HasBatch() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Batch != nil
}

func (x *WriteIntentOp) ClearBatch() {
	x.xxx_hidden_Batch = nil
}

type WriteIntentOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TxnId            []byte
	Timestamp        uint64
	CoordinatorShard []byte
	Batch            *BatchOp
	Predicates       []*VersionPredicate
}

func (b0 WriteIntentOp_builder) Build() *WriteIntentOp {
	m0 := &WriteIntentOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TxnId = b.TxnId
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_CoordinatorShard = b.CoordinatorShard
	x.xxx_hidden_Batch = b.Batch
	x.xxx_hidden_Predicates = &b.Predicates
	return m0
}

type ResolveIntentsOp struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TxnId         []byte                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId"`
	xxx_hidden_Status        int32                  `protobuf:"varint,2,opt,name=status"`
	xxx_hidden_CommitVersion uint64                 `protobuf:"varint,3,opt,name=commit_version,json=commitVersion"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ResolveIntentsOp) Reset() {
	*x = ResolveIntentsOp{}
	mi := &file_ops_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIntentsOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIntentsOp) ProtoMessage() {}

func (x *ResolveIntentsOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResolveIntentsOp) GetTxnId() []byte {
	if x != nil {
		return x.xxx_hidden_TxnId
	}
	return nil
}

func (x *ResolveIntentsOp) GetStatus() int32 {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return 0
}

func (x *ResolveIntentsOp) GetCommitVersion() uint64 {
	if x != nil {
		return x.xxx_hidden_CommitVersion
	}
	return 0
}

func (x *ResolveIntentsOp) SetTxnId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TxnId = v
}

func (x *ResolveIntentsOp) SetStatus(v int32) {
	x.xxx_hidden_Status = v
}

func (x *ResolveIntentsOp) SetCommitVersion(v uint64) {
	x.xxx_hidden_CommitVersion = v
}

type ResolveIntentsOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TxnId         []byte
	Status        int32
	CommitVersion uint64
}

func (b0 ResolveIntentsOp_builder) Build() *ResolveIntentsOp {
	m0 := &ResolveIntentsOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TxnId = b.TxnId
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_CommitVersion = b.CommitVersion
	return m0
}

// SplitState represents the current phase of a shard split operation.
// This state is persisted in Pebble and replicated via Raft to ensure
// consistency across leadership changes. Unlike the old pendingSplitKey
// which was local-only, SplitState survives leadership transitions.
type SplitState struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Phase              SplitState_Phase       `protobuf:"varint,1,opt,name=phase,enum=db.SplitState_Phase"`
	xxx_hidden_SplitKey           []byte                 `protobuf:"bytes,2,opt,name=split_key,json=splitKey"`
	xxx_hidden_NewShardId         uint64                 `protobuf:"varint,3,opt,name=new_shard_id,json=newShardId"`
	xxx_hidden_StartedAtUnixNanos int64                  `protobuf:"varint,4,opt,name=started_at_unix_nanos,json=startedAtUnixNanos"`
	xxx_hidden_OriginalRangeEnd   []byte                 `protobuf:"bytes,5,opt,name=original_range_end,json=originalRangeEnd"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SplitState) Reset() {
	*x = SplitState{}
	mi := &file_ops_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitState) ProtoMessage() {}

func (x *SplitState) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SplitState) GetPhase() SplitState_Phase {
	if x != nil {
		return x.xxx_hidden_Phase
	}
	return SplitState_PHASE_NONE
}

func (x *SplitState) GetSplitKey() []byte {
	if x != nil {
		return x.xxx_hidden_SplitKey
	}
	return nil
}

func (x *SplitState) GetNewShardId() uint64 {
	if x != nil {
		return x.xxx_hidden_NewShardId
	}
	return 0
}

func (x *SplitState) GetStartedAtUnixNanos() int64 {
	if x != nil {
		return x.xxx_hidden_StartedAtUnixNanos
	}
	return 0
}

func (x *SplitState) GetOriginalRangeEnd() []byte {
	if x != nil {
		return x.xxx_hidden_OriginalRangeEnd
	}
	return nil
}

func (x *SplitState) SetPhase(v SplitState_Phase) {
	x.xxx_hidden_Phase = v
}

func (x *SplitState) SetSplitKey(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SplitKey = v
}

func (x *SplitState) SetNewShardId(v uint64) {
	x.xxx_hidden_NewShardId = v
}

func (x *SplitState) SetStartedAtUnixNanos(v int64) {
	x.xxx_hidden_StartedAtUnixNanos = v
}

func (x *SplitState) SetOriginalRangeEnd(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OriginalRangeEnd = v
}

type SplitState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Phase              SplitState_Phase
	SplitKey           []byte
	NewShardId         uint64
	StartedAtUnixNanos int64
	OriginalRangeEnd   []byte
}

func (b0 SplitState_builder) Build() *SplitState {
	m0 := &SplitState{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Phase = b.Phase
	x.xxx_hidden_SplitKey = b.SplitKey
	x.xxx_hidden_NewShardId = b.NewShardId
	x.xxx_hidden_StartedAtUnixNanos = b.StartedAtUnixNanos
	x.xxx_hidden_OriginalRangeEnd = b.OriginalRangeEnd
	return m0
}

// SetSplitStateOp is used to atomically update the split state during a split operation.
// This replaces the old local-only pendingSplitKey with a Raft-replicated state machine.
type SetSplitStateOp struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State *SplitState            `protobuf:"bytes,1,opt,name=state"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetSplitStateOp) Reset() {
	*x = SetSplitStateOp{}
	mi := &file_ops_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSplitStateOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSplitStateOp) ProtoMessage() {}

func (x *SetSplitStateOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetSplitStateOp) GetState() *SplitState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return nil
}

func (x *SetSplitStateOp) SetState(v *SplitState) {
	x.xxx_hidden_State = v
}

func (x *SetSplitStateOp) HasState() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_State != nil
}

func (x *SetSplitStateOp) ClearState() {
	x.xxx_hidden_State = nil
}

type SetSplitStateOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The new split state, or nil to clear the state (after finalize/rollback).
	State *SplitState
}

func (b0 SetSplitStateOp_builder) Build() *SetSplitStateOp {
	m0 := &SetSplitStateOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	return m0
}

// MergeState represents the current phase of an online shard merge operation.
// Unlike MergeRange, this tracks donor/receiver coordination for non-empty merges.
type MergeState struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Phase              MergeState_Phase       `protobuf:"varint,1,opt,name=phase,enum=db.MergeState_Phase"`
	xxx_hidden_DonorShardId       uint64                 `protobuf:"varint,2,opt,name=donor_shard_id,json=donorShardId"`
	xxx_hidden_ReceiverShardId    uint64                 `protobuf:"varint,3,opt,name=receiver_shard_id,json=receiverShardId"`
	xxx_hidden_DonorRangeStart    []byte                 `protobuf:"bytes,4,opt,name=donor_range_start,json=donorRangeStart"`
	xxx_hidden_DonorRangeEnd      []byte                 `protobuf:"bytes,5,opt,name=donor_range_end,json=donorRangeEnd"`
	xxx_hidden_ReceiverRangeStart []byte                 `protobuf:"bytes,6,opt,name=receiver_range_start,json=receiverRangeStart"`
	xxx_hidden_ReceiverRangeEnd   []byte                 `protobuf:"bytes,7,opt,name=receiver_range_end,json=receiverRangeEnd"`
	xxx_hidden_StartedAtUnixNanos int64                  `protobuf:"varint,8,opt,name=started_at_unix_nanos,json=startedAtUnixNanos"`
	xxx_hidden_ReplaySeq          uint64                 `protobuf:"varint,9,opt,name=replay_seq,json=replaySeq"`
	xxx_hidden_FinalSeq           uint64                 `protobuf:"varint,10,opt,name=final_seq,json=finalSeq"`
	xxx_hidden_CopyCompleted      bool                   `protobuf:"varint,11,opt,name=copy_completed,json=copyCompleted"`
	xxx_hidden_CaptureDeltas      bool                   `protobuf:"varint,12,opt,name=capture_deltas,json=captureDeltas"`
	xxx_hidden_AcceptDonorRange   bool                   `protobuf:"varint,13,opt,name=accept_donor_range,json=acceptDonorRange"`
	xxx_hidden_DenyDonorWrites    bool                   `protobuf:"varint,14,opt,name=deny_donor_writes,json=denyDonorWrites"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *MergeState) Reset() {
	*x = MergeState{}
	mi := &file_ops_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeState) ProtoMessage() {}

func (x *MergeState) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MergeState) GetPhase() MergeState_Phase {
	if x != nil {
		return x.xxx_hidden_Phase
	}
	return MergeState_PHASE_NONE
}

func (x *MergeState) GetDonorShardId() uint64 {
	if x != nil {
		return x.xxx_hidden_DonorShardId
	}
	return 0
}

func (x *MergeState) GetReceiverShardId() uint64 {
	if x != nil {
		return x.xxx_hidden_ReceiverShardId
	}
	return 0
}

func (x *MergeState) GetDonorRangeStart() []byte {
	if x != nil {
		return x.xxx_hidden_DonorRangeStart
	}
	return nil
}

func (x *MergeState) GetDonorRangeEnd() []byte {
	if x != nil {
		return x.xxx_hidden_DonorRangeEnd
	}
	return nil
}

func (x *MergeState) GetReceiverRangeStart() []byte {
	if x != nil {
		return x.xxx_hidden_ReceiverRangeStart
	}
	return nil
}

func (x *MergeState) GetReceiverRangeEnd() []byte {
	if x != nil {
		return x.xxx_hidden_ReceiverRangeEnd
	}
	return nil
}

func (x *MergeState) GetStartedAtUnixNanos() int64 {
	if x != nil {
		return x.xxx_hidden_StartedAtUnixNanos
	}
	return 0
}

func (x *MergeState) GetReplaySeq() uint64 {
	if x != nil {
		return x.xxx_hidden_ReplaySeq
	}
	return 0
}

func (x *MergeState) GetFinalSeq() uint64 {
	if x != nil {
		return x.xxx_hidden_FinalSeq
	}
	return 0
}

func (x *MergeState) GetCopyCompleted() bool {
	if x != nil {
		return x.xxx_hidden_CopyCompleted
	}
	return false
}

func (x *MergeState) GetCaptureDeltas() bool {
	if x != nil {
		return x.xxx_hidden_CaptureDeltas
	}
	return false
}

func (x *MergeState) GetAcceptDonorRange() bool {
	if x != nil {
		return x.xxx_hidden_AcceptDonorRange
	}
	return false
}

func (x *MergeState) GetDenyDonorWrites() bool {
	if x != nil {
		return x.xxx_hidden_DenyDonorWrites
	}
	return false
}

func (x *MergeState) SetPhase(v MergeState_Phase) {
	x.xxx_hidden_Phase = v
}

func (x *MergeState) SetDonorShardId(v uint64) {
	x.xxx_hidden_DonorShardId = v
}

func (x *MergeState) SetReceiverShardId(v uint64) {
	x.xxx_hidden_ReceiverShardId = v
}

func (x *MergeState) SetDonorRangeStart(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DonorRangeStart = v
}

func (x *MergeState) SetDonorRangeEnd(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_DonorRangeEnd = v
}

func (x *MergeState) SetReceiverRangeStart(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ReceiverRangeStart = v
}

func (x *MergeState) SetReceiverRangeEnd(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ReceiverRangeEnd = v
}

func (x *MergeState) SetStartedAtUnixNanos(v int64) {
	x.xxx_hidden_StartedAtUnixNanos = v
}

func (x *MergeState) SetReplaySeq(v uint64) {
	x.xxx_hidden_ReplaySeq = v
}

func (x *MergeState) SetFinalSeq(v uint64) {
	x.xxx_hidden_FinalSeq = v
}

func (x *MergeState) SetCopyCompleted(v bool) {
	x.xxx_hidden_CopyCompleted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 14)
}

func (x *MergeState) SetCaptureDeltas(v bool) {
	x.xxx_hidden_CaptureDeltas = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 11, 14)
}

func (x *MergeState) SetAcceptDonorRange(v bool) {
	x.xxx_hidden_AcceptDonorRange = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 12, 14)
}

func (x *MergeState) SetDenyDonorWrites(v bool) {
	x.xxx_hidden_DenyDonorWrites = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 14)
}

func (x *MergeState) HasCopyCompleted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *MergeState) HasCaptureDeltas() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 11)
}

func (x *MergeState) HasAcceptDonorRange() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 12)
}

func (x *MergeState) HasDenyDonorWrites() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *MergeState) ClearCopyCompleted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_CopyCompleted = false
}

func (x *MergeState) ClearCaptureDeltas() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 11)
	x.xxx_hidden_CaptureDeltas = false
}

func (x *MergeState) ClearAcceptDonorRange() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 12)
	x.xxx_hidden_AcceptDonorRange = false
}

func (x *MergeState) ClearDenyDonorWrites() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_DenyDonorWrites = false
}

type MergeState_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Phase              MergeState_Phase
	DonorShardId       uint64
	ReceiverShardId    uint64
	DonorRangeStart    []byte
	DonorRangeEnd      []byte
	ReceiverRangeStart []byte
	ReceiverRangeEnd   []byte
	StartedAtUnixNanos int64
	ReplaySeq          uint64
	FinalSeq           uint64
	CopyCompleted      *bool
	CaptureDeltas      *bool
	AcceptDonorRange   *bool
	DenyDonorWrites    *bool
}

func (b0 MergeState_builder) Build() *MergeState {
	m0 := &MergeState{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Phase = b.Phase
	x.xxx_hidden_DonorShardId = b.DonorShardId
	x.xxx_hidden_ReceiverShardId = b.ReceiverShardId
	x.xxx_hidden_DonorRangeStart = b.DonorRangeStart
	x.xxx_hidden_DonorRangeEnd = b.DonorRangeEnd
	x.xxx_hidden_ReceiverRangeStart = b.ReceiverRangeStart
	x.xxx_hidden_ReceiverRangeEnd = b.ReceiverRangeEnd
	x.xxx_hidden_StartedAtUnixNanos = b.StartedAtUnixNanos
	x.xxx_hidden_ReplaySeq = b.ReplaySeq
	x.xxx_hidden_FinalSeq = b.FinalSeq
	if b.CopyCompleted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 14)
		x.xxx_hidden_CopyCompleted = *b.CopyCompleted
	}
	if b.CaptureDeltas != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 11, 14)
		x.xxx_hidden_CaptureDeltas = *b.CaptureDeltas
	}
	if b.AcceptDonorRange != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 12, 14)
		x.xxx_hidden_AcceptDonorRange = *b.AcceptDonorRange
	}
	if b.DenyDonorWrites != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 14)
		x.xxx_hidden_DenyDonorWrites = *b.DenyDonorWrites
	}
	return m0
}

type SetMergeStateOp struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State *MergeState            `protobuf:"bytes,1,opt,name=state"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SetMergeStateOp) Reset() {
	*x = SetMergeStateOp{}
	mi := &file_ops_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMergeStateOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMergeStateOp) ProtoMessage() {}

func (x *SetMergeStateOp) ProtoReflect() protoreflect.Message {
	mi := &file_ops_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetMergeStateOp) GetState() *MergeState {
	if x != nil {
		return x.xxx_hidden_State
	}
	return nil
}

func (x *SetMergeStateOp) SetState(v *MergeState) {
	x.xxx_hidden_State = v
}

func (x *SetMergeStateOp) HasState() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_State != nil
}

func (x *SetMergeStateOp) ClearState() {
	x.xxx_hidden_State = nil
}

type SetMergeStateOp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The new merge state, or nil to clear the state (after finalize/rollback).
	State *MergeState
}

func (b0 SetMergeStateOp_builder) Build() *SetMergeStateOp {
	m0 := &SetMergeStateOp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	return m0
}

var File_ops_proto protoreflect.FileDescriptor

const file_ops_proto_rawDesc = "" +
	"\n" +
	"\tops.proto\x12\x02db\x1a!google/protobuf/go_features.proto\"\xd6\v\n" +
	"\x02Op\x12$\n" +
	"\x02op\x18\x01 \x01(\x0e2\r.db.Op.OpTypeB\x05\xaa\x01\x02\b\x02R\x02op\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12'\n" +
	"\x05batch\x18\x03 \x01(\v2\v.db.BatchOpB\x02(\x01H\x00R\x05batch\x12'\n" +
	"\x05split\x18\x04 \x01(\v2\v.db.SplitOpB\x02(\x01H\x00R\x05split\x121\n" +
	"\tset_range\x18\x05 \x01(\v2\x0e.db.SetRangeOpB\x02(\x01H\x00R\bsetRange\x12=\n" +
	"\rupdate_schema\x18\x06 \x01(\v2\x12.db.UpdateSchemaOpB\x02(\x01H\x00R\fupdateSchema\x121\n" +
	"\tadd_index\x18\a \x01(\v2\x0e.db.AddIndexOpB\x02(\x01H\x00R\baddIndex\x12:\n" +
	"\fdelete_index\x18\b \x01(\v2\x11.db.DeleteIndexOpB\x02(\x01H\x00R\vdeleteIndex\x12*\n" +
	"\x06backup\x18\t \x01(\v2\f.db.BackupOpB\x02(\x01H\x00R\x06backup\x12F\n" +
	"\x10init_transaction\x18\n" +
	" \x01(\v2\x15.db.InitTransactionOpB\x02(\x01H\x00R\x0finitTransaction\x12L\n" +
	"\x12commit_transaction\x18\v \x01(\v2\x17.db.CommitTransactionOpB\x02(\x01H\x00R\x11commitTransaction\x12I\n" +
	"\x11abort_transaction\x18\f \x01(\v2\x16.db.AbortTransactionOpB\x02(\x01H\x00R\x10abortTransaction\x12:\n" +
	"\fwrite_intent\x18\r \x01(\v2\x11.db.WriteIntentOpB\x02(\x01H\x00R\vwriteIntent\x12C\n" +
	"\x0fresolve_intents\x18\x0e \x01(\v2\x14.db.ResolveIntentsOpB\x02(\x01H\x00R\x0eresolveIntents\x12@\n" +
	"\x0efinalize_split\x18\x0f \x01(\v2\x13.db.FinalizeSplitOpB\x02(\x01H\x00R\rfinalizeSplit\x12A\n" +
	"\x0fset_split_state\x18\x10 \x01(\v2\x13.db.SetSplitStateOpB\x02(\x01H\x00R\rsetSplitState\x12@\n" +
	"\x0efinalize_merge\x18\x11 \x01(\v2\x13.db.FinalizeMergeOpB\x02(\x01H\x00R\rfinalizeMerge\x12A\n" +
	"\x0fset_merge_state\x18\x12 \x01(\v2\x13.db.SetMergeStateOpB\x02(\x01H\x00R\rsetMergeState\"\xbc\x02\n" +
	"\x06OpType\x12\v\n" +
	"\aOpBatch\x10\x00\x12\v\n" +
	"\aOpSplit\x10\x01\x12\x0e\n" +
	"\n" +
	"OpSetRange\x10\x02\x12\x12\n" +
	"\x0eOpUpdateSchema\x10\x03\x12\x0e\n" +
	"\n" +
	"OpAddIndex\x10\x04\x12\x11\n" +
	"\rOpDeleteIndex\x10\x05\x12\f\n" +
	"\bOpBackup\x10\x06\x12\x15\n" +
	"\x11OpInitTransaction\x10\a\x12\x17\n" +
	"\x13OpCommitTransaction\x10\b\x12\x16\n" +
	"\x12OpAbortTransaction\x10\t\x12\x11\n" +
	"\rOpWriteIntent\x10\n" +
	"\x12\x14\n" +
	"\x10OpResolveIntents\x10\v\x12\x13\n" +
	"\x0fOpFinalizeSplit\x10\f\x12\x13\n" +
	"\x0fOpSetSplitState\x10\r\x12\x13\n" +
	"\x0fOpFinalizeMerge\x10\x0e\x12\x13\n" +
	"\x0fOpSetMergeState\x10\x0f\"\x7f\n" +
	"\tSyncLevel\x12\x14\n" +
	"\x10SyncLevelPropose\x10\x00\x12\x12\n" +
	"\x0eSyncLevelWrite\x10\x01\x12\x15\n" +
	"\x11SyncLevelFullText\x10\x02\x12\x18\n" +
	"\x14SyncLevelEnrichments\x10\x03\x12\x17\n" +
	"\x13SyncLevelEmbeddings\x10\x04B\v\n" +
	"\toperation\"=\n" +
	"\x05Write\x12\x17\n" +
	"\x03key\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x03key\x12\x1b\n" +
	"\x05value\x18\x02 \x01(\fB\x05\xaa\x01\x02\b\x02R\x05value\"\xfb\x01\n" +
	"\vTransformOp\x12\x19\n" +
	"\x04path\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04path\x12-\n" +
	"\x02op\x18\x02 \x01(\x0e2\x16.db.TransformOp.OpTypeB\x05\xaa\x01\x02\b\x02R\x02op\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\x8b\x01\n" +
	"\x06OpType\x12\a\n" +
	"\x03SET\x10\x00\x12\t\n" +
	"\x05UNSET\x10\x01\x12\a\n" +
	"\x03INC\x10\x02\x12\b\n" +
	"\x04PUSH\x10\x03\x12\b\n" +
	"\x04PULL\x10\x04\x12\x0e\n" +
	"\n" +
	"ADD_TO_SET\x10\x05\x12\a\n" +
	"\x03POP\x10\x06\x12\a\n" +
	"\x03MUL\x10\a\x12\a\n" +
	"\x03MIN\x10\b\x12\a\n" +
	"\x03MAX\x10\t\x12\x10\n" +
	"\fCURRENT_DATE\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06RENAME\x10\v\"m\n" +
	"\tTransform\x12\x17\n" +
	"\x03key\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x03key\x12/\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x0f.db.TransformOpR\n" +
	"operations\x12\x16\n" +
	"\x06upsert\x18\x03 \x01(\bR\x06upsert\"\xcb\x01\n" +
	"\aBatchOp\x12!\n" +
	"\x06writes\x18\x01 \x03(\v2\t.db.WriteR\x06writes\x12\x18\n" +
	"\adeletes\x18\x02 \x03(\fR\adeletes\x12-\n" +
	"\n" +
	"transforms\x18\x03 \x03(\v2\r.db.TransformR\n" +
	"transforms\x12/\n" +
	"\n" +
	"sync_level\x18\x04 \x01(\x0e2\x10.db.Op.SyncLevelR\tsyncLevel\x12#\n" +
	"\ttimestamp\x18\x05 \x01(\x04B\x05\xaa\x01\x02\b\x02R\ttimestamp\"\x96\x01\n" +
	"\x0fSplitDeltaEntry\x12!\n" +
	"\bsequence\x18\x01 \x01(\x04B\x05\xaa\x01\x02\b\x02R\bsequence\x12#\n" +
	"\ttimestamp\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\ttimestamp\x12!\n" +
	"\x06writes\x18\x03 \x03(\v2\t.db.WriteR\x06writes\x12\x18\n" +
	"\adeletes\x18\x04 \x03(\fR\adeletes\"\x96\x01\n" +
	"\x0fMergeDeltaEntry\x12!\n" +
	"\bsequence\x18\x01 \x01(\x04B\x05\xaa\x01\x02\b\x02R\bsequence\x12#\n" +
	"\ttimestamp\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\ttimestamp\x12!\n" +
	"\x06writes\x18\x03 \x03(\v2\t.db.WriteR\x06writes\x12\x18\n" +
	"\adeletes\x18\x04 \x03(\fR\adeletes\"V\n" +
	"\aSplitOp\x12'\n" +
	"\fnew_shard_id\x18\x01 \x01(\x04B\x05\xaa\x01\x02\b\x02R\n" +
	"newShardId\x12\"\n" +
	"\tsplit_key\x18\x02 \x01(\fB\x05\xaa\x01\x02\b\x02R\bsplitKey\"<\n" +
	"\x0fFinalizeSplitOp\x12)\n" +
	"\rnew_range_end\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\vnewRangeEnd\"k\n" +
	"\x0fFinalizeMergeOp\x12-\n" +
	"\x0fnew_range_start\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\rnewRangeStart\x12)\n" +
	"\rnew_range_end\x18\x02 \x01(\fB\x05\xaa\x01\x02\b\x02R\vnewRangeEnd\"P\n" +
	"\n" +
	"SetRangeOp\x12\"\n" +
	"\tstart_key\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\bstartKey\x12\x1e\n" +
	"\aend_key\x18\x02 \x01(\fB\x05\xaa\x01\x02\b\x02R\x06endKey\"/\n" +
	"\x0eUpdateSchemaOp\x12\x1d\n" +
	"\x06schema\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x06schema\"a\n" +
	"\n" +
	"AddIndexOp\x12\x19\n" +
	"\x04name\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\x12\x19\n" +
	"\x04type\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04type\x12\x1d\n" +
	"\x06config\x18\x03 \x01(\fB\x05\xaa\x01\x02\b\x02R\x06config\"*\n" +
	"\rDeleteIndexOp\x12\x19\n" +
	"\x04name\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x04name\"Q\n" +
	"\bBackupOp\x12\"\n" +
	"\tbackup_id\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\bbackupId\x12!\n" +
	"\blocation\x18\x02 \x01(\tB\x05\xaa\x01\x02\b\x02R\blocation\"z\n" +
	"\x11InitTransactionOp\x12\x1c\n" +
	"\x06txn_id\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x05txnId\x12#\n" +
	"\ttimestamp\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\ttimestamp\x12\"\n" +
	"\fparticipants\x18\x03 \x03(\fR\fparticipants\"3\n" +
	"\x13CommitTransactionOp\x12\x1c\n" +
	"\x06txn_id\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x05txnId\"2\n" +
	"\x12AbortTransactionOp\x12\x1c\n" +
	"\x06txn_id\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x05txnId\"]\n" +
	"\x10VersionPredicate\x12\x17\n" +
	"\x03key\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x03key\x120\n" +
	"\x10expected_version\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\x0fexpectedVersion\"\xdf\x01\n" +
	"\rWriteIntentOp\x12\x1c\n" +
	"\x06txn_id\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x05txnId\x12#\n" +
	"\ttimestamp\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\ttimestamp\x122\n" +
	"\x11coordinator_shard\x18\x03 \x01(\fB\x05\xaa\x01\x02\b\x02R\x10coordinatorShard\x12!\n" +
	"\x05batch\x18\x04 \x01(\v2\v.db.BatchOpR\x05batch\x124\n" +
	"\n" +
	"predicates\x18\x05 \x03(\v2\x14.db.VersionPredicateR\n" +
	"predicates\"}\n" +
	"\x10ResolveIntentsOp\x12\x1c\n" +
	"\x06txn_id\x18\x01 \x01(\fB\x05\xaa\x01\x02\b\x02R\x05txnId\x12\x1d\n" +
	"\x06status\x18\x02 \x01(\x05B\x05\xaa\x01\x02\b\x02R\x06status\x12,\n" +
	"\x0ecommit_version\x18\x03 \x01(\x04B\x05\xaa\x01\x02\b\x02R\rcommitVersion\"\xea\x02\n" +
	"\n" +
	"SplitState\x121\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x14.db.SplitState.PhaseB\x05\xaa\x01\x02\b\x02R\x05phase\x12\"\n" +
	"\tsplit_key\x18\x02 \x01(\fB\x05\xaa\x01\x02\b\x02R\bsplitKey\x12'\n" +
	"\fnew_shard_id\x18\x03 \x01(\x04B\x05\xaa\x01\x02\b\x02R\n" +
	"newShardId\x128\n" +
	"\x15started_at_unix_nanos\x18\x04 \x01(\x03B\x05\xaa\x01\x02\b\x02R\x12startedAtUnixNanos\x123\n" +
	"\x12original_range_end\x18\x05 \x01(\fB\x05\xaa\x01\x02\b\x02R\x10originalRangeEnd\"m\n" +
	"\x05Phase\x12\x0e\n" +
	"\n" +
	"PHASE_NONE\x10\x00\x12\x11\n" +
	"\rPHASE_PREPARE\x10\x01\x12\x13\n" +
	"\x0fPHASE_SPLITTING\x10\x02\x12\x14\n" +
	"\x10PHASE_FINALIZING\x10\x03\x12\x16\n" +
	"\x12PHASE_ROLLING_BACK\x10\x04\"7\n" +
	"\x0fSetSplitStateOp\x12$\n" +
	"\x05state\x18\x01 \x01(\v2\x0e.db.SplitStateR\x05state\"\x9b\x06\n" +
	"\n" +
	"MergeState\x121\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x14.db.MergeState.PhaseB\x05\xaa\x01\x02\b\x02R\x05phase\x12+\n" +
	"\x0edonor_shard_id\x18\x02 \x01(\x04B\x05\xaa\x01\x02\b\x02R\fdonorShardId\x121\n" +
	"\x11receiver_shard_id\x18\x03 \x01(\x04B\x05\xaa\x01\x02\b\x02R\x0freceiverShardId\x121\n" +
	"\x11donor_range_start\x18\x04 \x01(\fB\x05\xaa\x01\x02\b\x02R\x0fdonorRangeStart\x12-\n" +
	"\x0fdonor_range_end\x18\x05 \x01(\fB\x05\xaa\x01\x02\b\x02R\rdonorRangeEnd\x127\n" +
	"\x14receiver_range_start\x18\x06 \x01(\fB\x05\xaa\x01\x02\b\x02R\x12receiverRangeStart\x123\n" +
	"\x12receiver_range_end\x18\a \x01(\fB\x05\xaa\x01\x02\b\x02R\x10receiverRangeEnd\x128\n" +
	"\x15started_at_unix_nanos\x18\b \x01(\x03B\x05\xaa\x01\x02\b\x02R\x12startedAtUnixNanos\x12$\n" +
	"\n" +
	"replay_seq\x18\t \x01(\x04B\x05\xaa\x01\x02\b\x02R\treplaySeq\x12\"\n" +
	"\tfinal_seq\x18\n" +
	" \x01(\x04B\x05\xaa\x01\x02\b\x02R\bfinalSeq\x12%\n" +
	"\x0ecopy_completed\x18\v \x01(\bR\rcopyCompleted\x12%\n" +
	"\x0ecapture_deltas\x18\f \x01(\bR\rcaptureDeltas\x12,\n" +
	"\x12accept_donor_range\x18\r \x01(\bR\x10acceptDonorRange\x12*\n" +
	"\x11deny_donor_writes\x18\x0e \x01(\bR\x0fdenyDonorWrites\"~\n" +
	"\x05Phase\x12\x0e\n" +
	"\n" +
	"PHASE_NONE\x10\x00\x12\x11\n" +
	"\rPHASE_PREPARE\x10\x01\x12\x11\n" +
	"\rPHASE_COPYING\x10\x02\x12\x11\n" +
	"\rPHASE_CATCHUP\x10\x03\x12\x14\n" +
	"\x10PHASE_FINALIZING\x10\x04\x12\x16\n" +
	"\x12PHASE_ROLLING_BACK\x10\x05\"7\n" +
	"\x0fSetMergeStateOp\x12$\n" +
	"\x05state\x18\x01 \x01(\v2\x0e.db.MergeStateR\x05stateB?Z5github.com/antflydb/antfly/go/pkg/antfly/src/store/db\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_ops_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_ops_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_ops_proto_goTypes = []any{
	(Op_OpType)(0),              // 0: db.Op.OpType
	(Op_SyncLevel)(0),           // 1: db.Op.SyncLevel
	(TransformOp_OpType)(0),     // 2: db.TransformOp.OpType
	(SplitState_Phase)(0),       // 3: db.SplitState.Phase
	(MergeState_Phase)(0),       // 4: db.MergeState.Phase
	(*Op)(nil),                  // 5: db.Op
	(*Write)(nil),               // 6: db.Write
	(*TransformOp)(nil),         // 7: db.TransformOp
	(*Transform)(nil),           // 8: db.Transform
	(*BatchOp)(nil),             // 9: db.BatchOp
	(*SplitDeltaEntry)(nil),     // 10: db.SplitDeltaEntry
	(*MergeDeltaEntry)(nil),     // 11: db.MergeDeltaEntry
	(*SplitOp)(nil),             // 12: db.SplitOp
	(*FinalizeSplitOp)(nil),     // 13: db.FinalizeSplitOp
	(*FinalizeMergeOp)(nil),     // 14: db.FinalizeMergeOp
	(*SetRangeOp)(nil),          // 15: db.SetRangeOp
	(*UpdateSchemaOp)(nil),      // 16: db.UpdateSchemaOp
	(*AddIndexOp)(nil),          // 17: db.AddIndexOp
	(*DeleteIndexOp)(nil),       // 18: db.DeleteIndexOp
	(*BackupOp)(nil),            // 19: db.BackupOp
	(*InitTransactionOp)(nil),   // 20: db.InitTransactionOp
	(*CommitTransactionOp)(nil), // 21: db.CommitTransactionOp
	(*AbortTransactionOp)(nil),  // 22: db.AbortTransactionOp
	(*VersionPredicate)(nil),    // 23: db.VersionPredicate
	(*WriteIntentOp)(nil),       // 24: db.WriteIntentOp
	(*ResolveIntentsOp)(nil),    // 25: db.ResolveIntentsOp
	(*SplitState)(nil),          // 26: db.SplitState
	(*SetSplitStateOp)(nil),     // 27: db.SetSplitStateOp
	(*MergeState)(nil),          // 28: db.MergeState
	(*SetMergeStateOp)(nil),     // 29: db.SetMergeStateOp
}
var file_ops_proto_depIdxs = []int32{
	0,  // 0: db.Op.op:type_name -> db.Op.OpType
	9,  // 1: db.Op.batch:type_name -> db.BatchOp
	12, // 2: db.Op.split:type_name -> db.SplitOp
	15, // 3: db.Op.set_range:type_name -> db.SetRangeOp
	16, // 4: db.Op.update_schema:type_name -> db.UpdateSchemaOp
	17, // 5: db.Op.add_index:type_name -> db.AddIndexOp
	18, // 6: db.Op.delete_index:type_name -> db.DeleteIndexOp
	19, // 7: db.Op.backup:type_name -> db.BackupOp
	20, // 8: db.Op.init_transaction:type_name -> db.InitTransactionOp
	21, // 9: db.Op.commit_transaction:type_name -> db.CommitTransactionOp
	22, // 10: db.Op.abort_transaction:type_name -> db.AbortTransactionOp
	24, // 11: db.Op.write_intent:type_name -> db.WriteIntentOp
	25, // 12: db.Op.resolve_intents:type_name -> db.ResolveIntentsOp
	13, // 13: db.Op.finalize_split:type_name -> db.FinalizeSplitOp
	27, // 14: db.Op.set_split_state:type_name -> db.SetSplitStateOp
	14, // 15: db.Op.finalize_merge:type_name -> db.FinalizeMergeOp
	29, // 16: db.Op.set_merge_state:type_name -> db.SetMergeStateOp
	2,  // 17: db.TransformOp.op:type_name -> db.TransformOp.OpType
	7,  // 18: db.Transform.operations:type_name -> db.TransformOp
	6,  // 19: db.BatchOp.writes:type_name -> db.Write
	8,  // 20: db.BatchOp.transforms:type_name -> db.Transform
	1,  // 21: db.BatchOp.sync_level:type_name -> db.Op.SyncLevel
	6,  // 22: db.SplitDeltaEntry.writes:type_name -> db.Write
	6,  // 23: db.MergeDeltaEntry.writes:type_name -> db.Write
	9,  // 24: db.WriteIntentOp.batch:type_name -> db.BatchOp
	23, // 25: db.WriteIntentOp.predicates:type_name -> db.VersionPredicate
	3,  // 26: db.SplitState.phase:type_name -> db.SplitState.Phase
	26, // 27: db.SetSplitStateOp.state:type_name -> db.SplitState
	4,  // 28: db.MergeState.phase:type_name -> db.MergeState.Phase
	28, // 29: db.SetMergeStateOp.state:type_name -> db.MergeState
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_ops_proto_init() }
func file_ops_proto_init() {
	if File_ops_proto != nil {
		return
	}
	file_ops_proto_msgTypes[0].OneofWrappers = []any{
		(*op_Batch)(nil),
		(*op_Split)(nil),
		(*op_SetRange)(nil),
		(*op_UpdateSchema)(nil),
		(*op_AddIndex)(nil),
		(*op_DeleteIndex)(nil),
		(*op_Backup)(nil),
		(*op_InitTransaction)(nil),
		(*op_CommitTransaction)(nil),
		(*op_AbortTransaction)(nil),
		(*op_WriteIntent)(nil),
		(*op_ResolveIntents)(nil),
		(*op_FinalizeSplit)(nil),
		(*op_SetSplitState)(nil),
		(*op_FinalizeMerge)(nil),
		(*op_SetMergeState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ops_proto_rawDesc), len(file_ops_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ops_proto_goTypes,
		DependencyIndexes: file_ops_proto_depIdxs,
		EnumInfos:         file_ops_proto_enumTypes,
		MessageInfos:      file_ops_proto_msgTypes,
	}.Build()
	File_ops_proto = out.File
	file_ops_proto_goTypes = nil
	file_ops_proto_depIdxs = nil
}
