apiVersion: v1
kind: Service
metadata:
  name: antfly-operator-webhook-service
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    app.kubernetes.io/name: antfly-operator
    app.kubernetes.io/component: controller
