// Copyright 2026 Antfly, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tiled matrix multiplication with B transposed and IQ4_XS dequantization.
// C[M,N] = A[M,K] @ dequant(B_iq4_xs)^T
//
// B is quantized in IQ4_XS format: blocks of 256 values.
// Each block = 2 bytes f16 d + 2 bytes high scale bits
// + 4 bytes low scale nibbles + 128 bytes q4 table indices.

struct Params {
    M: u32,
    N: u32,
    K: u32,
    _pad: u32,
};

@group(0) @binding(0) var<storage, read> A: array<f32>;
@group(0) @binding(1) var<storage, read> B_raw: array<u32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;
@group(0) @binding(3) var<uniform> params: Params;

fn read_byte(byte_offset: u32) -> u32 {
    let word_idx = byte_offset / 4u;
    let byte_in_word = byte_offset % 4u;
    return (B_raw[word_idx] >> (byte_in_word * 8u)) & 0xFFu;
}

fn read_u16(byte_offset: u32) -> u32 {
    return read_byte(byte_offset) | (read_byte(byte_offset + 1u) << 8u);
}

fn read_f16(byte_offset: u32) -> f32 {
    return unpack2x16float(read_u16(byte_offset)).x;
}

fn iq4_nl_value(nibble: u32) -> f32 {
    var value: f32;
    switch (nibble) {
        case 0u: { value = -127.0; }
        case 1u: { value = -104.0; }
        case 2u: { value = -83.0; }
        case 3u: { value = -65.0; }
        case 4u: { value = -49.0; }
        case 5u: { value = -35.0; }
        case 6u: { value = -22.0; }
        case 7u: { value = -10.0; }
        case 8u: { value = 1.0; }
        case 9u: { value = 13.0; }
        case 10u: { value = 25.0; }
        case 11u: { value = 38.0; }
        case 12u: { value = 53.0; }
        case 13u: { value = 69.0; }
        case 14u: { value = 89.0; }
        default: { value = 113.0; }
    }
    return value;
}

fn dequant_iq4_xs(b_row: u32, k_abs: u32) -> f32 {
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 136u;
    let sub = in_block / 32u;
    let elem = in_block % 32u;

    let d = read_f16(block_byte);
    let scales_h = read_u16(block_byte + 2u);
    let scales_l = read_byte(block_byte + 4u + sub / 2u);
    let low = (scales_l >> (4u * (sub % 2u))) & 0x0Fu;
    let high = (scales_h >> (2u * sub)) & 0x03u;
    let dl = d * (f32(low | (high << 4u)) - 32.0);

    let packed = read_byte(block_byte + 8u + sub * 16u + (elem % 16u));
    let nibble = select((packed >> 4u) & 0x0Fu, packed & 0x0Fu, elem < 16u);
    return dl * iq4_nl_value(nibble);
}

// === MMV (matrix-vector) variant — auto-generated by scripts/gen_mmv_shaders.py.
// One workgroup per output column. Threads cooperatively reduce over K
// using a workgroup-shared partial-sum array and a tree reduction.
const MMV_WORKGROUP_SIZE: u32 = 128u;
var<workgroup> mmv_partial: array<f32, 128>;

@compute @workgroup_size(MMV_WORKGROUP_SIZE, 1, 1)
fn matmul_transb_iq4_xs_mmv(
    @builtin(workgroup_id) wid: vec3<u32>,
    @builtin(local_invocation_id) lid: vec3<u32>,
) {
    let col = wid.x;
    let tid = lid.x;
    if (col >= params.N) { return; }

    var acc: f32 = 0.0;
    var k: u32 = tid;
    loop {
        if (k >= params.K) { break; }
        acc = acc + A[k] * dequant_iq4_xs(col, k);
        k = k + MMV_WORKGROUP_SIZE;
    }

    mmv_partial[tid] = acc;
    workgroupBarrier();

    var stride: u32 = MMV_WORKGROUP_SIZE / 2u;
    loop {
        if (stride == 0u) { break; }
        if (tid < stride) {
            mmv_partial[tid] = mmv_partial[tid] + mmv_partial[tid + stride];
        }
        workgroupBarrier();
        stride = stride / 2u;
    }

    if (tid == 0u) {
        C[col] = mmv_partial[0];
    }
}
