// Copyright 2026 Antfly, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tiled matrix multiplication with B transposed and Q3_K dequantization.
// C[M,N] = A[M,K] @ dequant(B_q3_k)^T

struct Params {
    M: u32,
    N: u32,
    K: u32,
    _pad: u32,
};

@group(0) @binding(0) var<storage, read> A: array<f32>;
@group(0) @binding(1) var<storage, read> B_raw: array<u32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;
@group(0) @binding(3) var<uniform> params: Params;

fn read_byte(byte_offset: u32) -> u32 {
    let word_idx = byte_offset / 4u;
    let byte_in_word = byte_offset % 4u;
    return (B_raw[word_idx] >> (byte_in_word * 8u)) & 0xFFu;
}

fn read_f16(byte_offset: u32) -> f32 {
    let word_idx = byte_offset / 4u;
    let byte_off = byte_offset % 4u;
    let w0 = B_raw[word_idx];
    var bits: u32;
    if (byte_off == 0u) {
        bits = w0 & 0xFFFFu;
    } else if (byte_off == 2u) {
        bits = (w0 >> 16u) & 0xFFFFu;
    } else {
        let w1 = B_raw[word_idx + 1u];
        bits = ((w0 >> (byte_off * 8u)) | (w1 << ((4u - byte_off) * 8u))) & 0xFFFFu;
    }
    return unpack2x16float(bits).x;
}

fn q3_scale_raw(block_byte: u32, sub: u32) -> u32 {
    let base = block_byte + 96u;
    if (sub < 4u) {
        let i = sub;
        return (read_byte(base + i) & 0x0Fu) | ((read_byte(base + 8u + i) & 0x03u) << 4u);
    }
    if (sub < 8u) {
        let i = sub - 4u;
        return (read_byte(base + 4u + i) & 0x0Fu) | (((read_byte(base + 8u + i) >> 2u) & 0x03u) << 4u);
    }
    if (sub < 12u) {
        let i = sub - 8u;
        return ((read_byte(base + i) >> 4u) & 0x0Fu) | (((read_byte(base + 8u + i) >> 4u) & 0x03u) << 4u);
    }
    let i = sub - 12u;
    return ((read_byte(base + 4u + i) >> 4u) & 0x0Fu) | (((read_byte(base + 8u + i) >> 6u) & 0x03u) << 4u);
}

fn dequant_q3_k(b_row: u32, k_abs: u32) -> f32 {
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 110u;

    let sub = in_block / 16u;
    let elem = in_block % 16u;
    let d = read_f16(block_byte + 108u);
    let scale = d * (f32(q3_scale_raw(block_byte, sub)) - 32.0);

    let chunk = sub / 8u;
    let group = (sub % 8u) / 2u;
    let l_base = (sub % 2u) * 16u;
    let q_base = chunk * 32u;
    let l = l_base + elem;
    let low2 = (read_byte(block_byte + 32u + q_base + l) >> (group * 2u)) & 0x03u;
    let high1 = (read_byte(block_byte + l) >> (chunk * 4u + group)) & 0x01u;
    let q = f32(low2 + high1 * 4u) - 4.0;
    return scale * q;
}

// === MMV (matrix-vector) variant — auto-generated by scripts/gen_mmv_shaders.py.
// One workgroup per output column. Threads cooperatively reduce over K
// using a workgroup-shared partial-sum array and a tree reduction.
const MMV_WORKGROUP_SIZE: u32 = 128u;
var<workgroup> mmv_partial: array<f32, 128>;

@compute @workgroup_size(MMV_WORKGROUP_SIZE, 1, 1)
fn matmul_transb_q3_k_mmv(
    @builtin(workgroup_id) wid: vec3<u32>,
    @builtin(local_invocation_id) lid: vec3<u32>,
) {
    let col = wid.x;
    let tid = lid.x;
    if (col >= params.N) { return; }

    var acc: f32 = 0.0;
    var k: u32 = tid;
    loop {
        if (k >= params.K) { break; }
        acc = acc + A[k] * dequant_q3_k(col, k);
        k = k + MMV_WORKGROUP_SIZE;
    }

    mmv_partial[tid] = acc;
    workgroupBarrier();

    var stride: u32 = MMV_WORKGROUP_SIZE / 2u;
    loop {
        if (stride == 0u) { break; }
        if (tid < stride) {
            mmv_partial[tid] = mmv_partial[tid] + mmv_partial[tid + stride];
        }
        workgroupBarrier();
        stride = stride / 2u;
    }

    if (tid == 0u) {
        C[col] = mmv_partial[0];
    }
}
