// Copyright 2026 Antfly, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tiled matrix multiplication with B transposed and NVFP4 dequantization.
// C[M,N] = A[M,K] @ dequant(B_nvfp4)^T
//
// NVFP4 layout: blocks of 64 values, 36 bytes per block:
//   [0:4]    4 ue4m3 scales (one per 16-element sub-block)
//   [4:36]   32 bytes; 4 sub-blocks of 8 packed bytes (16 nibbles each)
// Within sub-block: low nibbles = elements 0..7, high nibbles = elements 8..15.

struct Params {
    M: u32,
    N: u32,
    K: u32,
    _pad: u32,
};

@group(0) @binding(0) var<storage, read> A: array<f32>;
@group(0) @binding(1) var<storage, read> B_raw: array<u32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;
@group(0) @binding(3) var<uniform> params: Params;

fn read_byte(byte_offset: u32) -> u32 {
    let word_idx = byte_offset / 4u;
    let byte_in_word = byte_offset % 4u;
    return (B_raw[word_idx] >> (byte_in_word * 8u)) & 0xFFu;
}

fn mxfp4_value(nibble: u32) -> f32 {
    var value: f32;
    switch (nibble) {
        case 0u: { value = 0.0; }
        case 1u: { value = 1.0; }
        case 2u: { value = 2.0; }
        case 3u: { value = 3.0; }
        case 4u: { value = 4.0; }
        case 5u: { value = 6.0; }
        case 6u: { value = 8.0; }
        case 7u: { value = 12.0; }
        case 8u: { value = 0.0; }
        case 9u: { value = -1.0; }
        case 10u: { value = -2.0; }
        case 11u: { value = -3.0; }
        case 12u: { value = -4.0; }
        case 13u: { value = -6.0; }
        case 14u: { value = -8.0; }
        default: { value = -12.0; }
    }
    return value;
}

fn decode_ue4m3(value: u32) -> f32 {
    if (value == 0u || value == 0x7Fu) { return 0.0; }
    let exponent = (value >> 3u) & 0x0Fu;
    let mantissa = f32(value & 0x07u);
    var raw: f32;
    if (exponent == 0u) {
        raw = mantissa * exp2(-9.0);
    } else {
        raw = (1.0 + mantissa / 8.0) * exp2(f32(i32(exponent) - 7));
    }
    return raw * 0.5;
}

fn dequant_nvfp4(b_row: u32, k_abs: u32) -> f32 {
    let blocks_per_row = params.K / 64u;
    let block_idx = k_abs / 64u;
    let in_block = k_abs % 64u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 36u;

    let sub = in_block / 16u;       // 0..4
    let elem_in_sub = in_block % 16u;

    let d = decode_ue4m3(read_byte(block_byte + sub));
    let q_byte_offset = block_byte + 4u + sub * 8u + (elem_in_sub % 8u);
    let packed = read_byte(q_byte_offset);
    let nibble = select((packed >> 4u) & 0x0Fu, packed & 0x0Fu, elem_in_sub < 8u);
    return d * mxfp4_value(nibble);
}

// === MMV (matrix-vector) variant — auto-generated by scripts/gen_mmv_shaders.py.
// One workgroup per output column. Threads cooperatively reduce over K
// using a workgroup-shared partial-sum array and a tree reduction.
const MMV_WORKGROUP_SIZE: u32 = 128u;
var<workgroup> mmv_partial: array<f32, 128>;

@compute @workgroup_size(MMV_WORKGROUP_SIZE, 1, 1)
fn matmul_transb_nvfp4_mmv(
    @builtin(workgroup_id) wid: vec3<u32>,
    @builtin(local_invocation_id) lid: vec3<u32>,
) {
    let col = wid.x;
    let tid = lid.x;
    if (col >= params.N) { return; }

    var acc: f32 = 0.0;
    var k: u32 = tid;
    loop {
        if (k >= params.K) { break; }
        acc = acc + A[k] * dequant_nvfp4(col, k);
        k = k + MMV_WORKGROUP_SIZE;
    }

    mmv_partial[tid] = acc;
    workgroupBarrier();

    var stride: u32 = MMV_WORKGROUP_SIZE / 2u;
    loop {
        if (stride == 0u) { break; }
        if (tid < stride) {
            mmv_partial[tid] = mmv_partial[tid] + mmv_partial[tid + stride];
        }
        workgroupBarrier();
        stride = stride / 2u;
    }

    if (tid == 0u) {
        C[col] = mmv_partial[0];
    }
}
