// Copyright 2026 Antfly, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tiled matrix multiplication with B transposed and Q4_K dequantization.
// C[M,N] = A[M,K] @ dequant(B_q4k)^T
//
// B is quantized in Q4_K format: blocks of 256 values.
// Each block = 144 bytes:
//   [0:2]    d      - f16 scale
//   [2:4]    dmin   - f16 minimum scale
//   [4:16]   scales - 12 bytes, packed 6-bit scale+min per sub-block
//   [16:144] qs     - 128 bytes, low/high nibbles
//
// 8 sub-blocks of 32 values each.
// value = d * sc * q4 - dmin * mn

struct Params {
    M: u32,
    N: u32,
    K: u32,
    _pad: u32,
};

@group(0) @binding(0) var<storage, read> A: array<f32>;
@group(0) @binding(1) var<storage, read> B_raw: array<u32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;
@group(0) @binding(3) var<uniform> params: Params;

fn read_byte(byte_offset: u32) -> u32 {
    let word_idx = byte_offset / 4u;
    let byte_in_word = byte_offset % 4u;
    return (B_raw[word_idx] >> (byte_in_word * 8u)) & 0xFFu;
}

fn read_f16(byte_offset: u32) -> f32 {
    let word_idx = byte_offset / 4u;
    let byte_off = byte_offset % 4u;
    let w0 = B_raw[word_idx];
    var bits: u32;
    if (byte_off == 0u) {
        bits = w0 & 0xFFFFu;
    } else if (byte_off == 2u) {
        bits = (w0 >> 16u) & 0xFFFFu;
    } else {
        let w1 = B_raw[word_idx + 1u];
        bits = ((w0 >> (byte_off * 8u)) | (w1 << ((4u - byte_off) * 8u))) & 0xFFFFu;
    }
    return unpack2x16float(bits).x;
}

fn unpack_scale_min(block_byte: u32, sub: u32) -> vec2<f32> {
    let scales_off = block_byte + 4u;
    if (sub < 4u) {
        let sc = f32(read_byte(scales_off + sub) & 63u);
        let mn = f32(read_byte(scales_off + sub + 4u) & 63u);
        return vec2<f32>(sc, mn);
    } else {
        let sc_low = read_byte(scales_off + sub + 4u) & 0x0Fu;
        let sc_high = (read_byte(scales_off + sub - 4u) >> 6u) << 4u;
        let mn_low = read_byte(scales_off + sub + 4u) >> 4u;
        let mn_high = (read_byte(scales_off + sub) >> 6u) << 4u;
        return vec2<f32>(f32(sc_low | sc_high), f32(mn_low | mn_high));
    }
}

fn dequant_q4_k(b_row: u32, k_abs: u32) -> f32 {
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 144u;

    let sub = in_block / 32u;
    let elem = in_block % 32u;

    let d = read_f16(block_byte);
    let dmin = read_f16(block_byte + 2u);
    let sc_mn = unpack_scale_min(block_byte, sub);
    let dsc = d * sc_mn.x;
    let dmn = dmin * sc_mn.y;

    let q_byte = read_byte(block_byte + 16u + (sub / 2u) * 32u + elem);
    var q: u32;
    if ((sub % 2u) == 0u) {
        q = q_byte & 0x0Fu;
    } else {
        q = q_byte >> 4u;
    }

    return dsc * f32(q) - dmn;
}

// === MMV (matrix-vector) variant — auto-generated by scripts/gen_mmv_shaders.py.
// One workgroup per output column. Threads cooperatively reduce over K
// using a workgroup-shared partial-sum array and a tree reduction.
const MMV_WORKGROUP_SIZE: u32 = 128u;
var<workgroup> mmv_partial: array<f32, 128>;

@compute @workgroup_size(MMV_WORKGROUP_SIZE, 1, 1)
fn matmul_transb_q4_k_mmv(
    @builtin(workgroup_id) wid: vec3<u32>,
    @builtin(local_invocation_id) lid: vec3<u32>,
) {
    let col = wid.x;
    let tid = lid.x;
    if (col >= params.N) { return; }

    var acc: f32 = 0.0;
    var k: u32 = tid;
    loop {
        if (k >= params.K) { break; }
        acc = acc + A[k] * dequant_q4_k(col, k);
        k = k + MMV_WORKGROUP_SIZE;
    }

    mmv_partial[tid] = acc;
    workgroupBarrier();

    var stride: u32 = MMV_WORKGROUP_SIZE / 2u;
    loop {
        if (stride == 0u) { break; }
        if (tid < stride) {
            mmv_partial[tid] = mmv_partial[tid] + mmv_partial[tid + stride];
        }
        workgroupBarrier();
        stride = stride / 2u;
    }

    if (tid == 0u) {
        C[col] = mmv_partial[0];
    }
}
