// Copyright 2026 Antfly, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tiled matrix multiplication with B transposed and Q8_0 dequantization.
// C[M,N] = A[M,K] @ dequant(B_q8)^T
//
// B is quantized in Q8_0 format: blocks of 32 values.
// Each block = 2 bytes (f16 scale) + 32 bytes (32 x int8) = 34 bytes.
// B has shape [N, K] row-major (before transpose), so each of the N rows
// has K values packed into K/32 blocks.
//
// Uses 16x16x32 tiling: TILE_K=32 matches the Q8_0 block size exactly,
// so each K-tile step processes one complete quant block per B row.
// Dequantization happens cooperatively when loading tile_b into shared memory.

struct Params {
    M: u32,
    N: u32,
    K: u32,
    _pad: u32,
};

@group(0) @binding(0) var<storage, read> A: array<f32>;
@group(0) @binding(1) var<storage, read> B_raw: array<u32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;
@group(0) @binding(3) var<uniform> params: Params;

const TILE_K: u32 = 32;  // = Q8_0 block size

var<workgroup> tile_a: array<f32, 512>;  // [TILE_M][TILE_K]
var<workgroup> tile_b: array<f32, 512>;  // [TILE_K][TILE_N]

fn dequant_q8_0_block(b_row: u32, block_idx: u32, in_block: u32) -> f32 {
    let blocks_per_row = params.K / 32u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 34u;

    // Read scale (f16, 2 bytes)
    let scale_word_idx = block_byte / 4u;
    let scale_byte_off = block_byte % 4u;
    let w0 = B_raw[scale_word_idx];
    var scale_bits: u32;
    if (scale_byte_off == 0u) {
        scale_bits = w0 & 0xFFFFu;
    } else if (scale_byte_off == 2u) {
        scale_bits = (w0 >> 16u) & 0xFFFFu;
    } else {
        let w1 = B_raw[scale_word_idx + 1u];
        scale_bits = ((w0 >> (scale_byte_off * 8u)) | (w1 << ((4u - scale_byte_off) * 8u))) & 0xFFFFu;
    }
    let scale = unpack2x16float(scale_bits).x;

    // Read int8 value
    let val_byte_offset = block_byte + 2u + in_block;
    let val_word_idx = val_byte_offset / 4u;
    let val_byte_in_word = val_byte_offset % 4u;
    let val_word = B_raw[val_word_idx];
    let byte_val = (val_word >> (val_byte_in_word * 8u)) & 0xFFu;

    // Sign-extend from 8-bit
    var signed_val: f32;
    if (byte_val >= 128u) {
        signed_val = f32(byte_val) - 256.0;
    } else {
        signed_val = f32(byte_val);
    }

    return scale * signed_val;
}

// === MMV (matrix-vector) variant — auto-generated by scripts/gen_mmv_shaders.py.
// One workgroup per output column. Threads cooperatively reduce over K
// using a workgroup-shared partial-sum array and a tree reduction.
const MMV_WORKGROUP_SIZE: u32 = 128u;
var<workgroup> mmv_partial: array<f32, 128>;

@compute @workgroup_size(MMV_WORKGROUP_SIZE, 1, 1)
fn matmul_transb_q8_0_mmv(
    @builtin(workgroup_id) wid: vec3<u32>,
    @builtin(local_invocation_id) lid: vec3<u32>,
) {
    let col = wid.x;
    let tid = lid.x;
    if (col >= params.N) { return; }

    var acc: f32 = 0.0;
    var k: u32 = tid;
    loop {
        if (k >= params.K) { break; }
        acc = acc + A[k] * dequant_q8_0_block(col, k / 32u, k % 32u);
        k = k + MMV_WORKGROUP_SIZE;
    }

    mmv_partial[tid] = acc;
    workgroupBarrier();

    var stride: u32 = MMV_WORKGROUP_SIZE / 2u;
    loop {
        if (stride == 0u) { break; }
        if (tid < stride) {
            mmv_partial[tid] = mmv_partial[tid] + mmv_partial[tid + stride];
        }
        workgroupBarrier();
        stride = stride / 2u;
    }

    if (tid == 0u) {
        C[col] = mmv_partial[0];
    }
}
