// Copyright 2026 Antfly, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tiled matrix multiplication with B transposed and TQ2_0 dequantization.
// C[M,N] = A[M,K] @ dequant(B_tq2_0)^T
//
// TQ2_0 layout: blocks of 256 values, 66 bytes per block:
//   [0:64]   qs - 64 bytes; 2 groups of 32 bytes; each byte holds 4 ternary
//             trits via 2-bit packing across 4 shift levels (l = 0..3)
//   [64:66]  d  - f16 scale
// Output ordering: 2 j-groups x 4 l-shifts x 32 m-elements = 256 values.
// For an output index in_block (0..255):
//   j_byte_base = (in_block / 128) * 32      (0 or 32)
//   l           = (in_block % 128) / 32
//   m           = in_block % 32
//   q           = ((qs[j_byte_base + m] >> (l*2)) & 0x3) - 1   // -1, 0, or 1
//   value       = q * d

struct Params {
    M: u32,
    N: u32,
    K: u32,
    _pad: u32,
};

@group(0) @binding(0) var<storage, read> A: array<f32>;
@group(0) @binding(1) var<storage, read> B_raw: array<u32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;
@group(0) @binding(3) var<uniform> params: Params;

fn read_byte(byte_offset: u32) -> u32 {
    let word_idx = byte_offset / 4u;
    let byte_in_word = byte_offset % 4u;
    return (B_raw[word_idx] >> (byte_in_word * 8u)) & 0xFFu;
}

fn read_f16(byte_offset: u32) -> f32 {
    let word_idx = byte_offset / 4u;
    let byte_off = byte_offset % 4u;
    let w0 = B_raw[word_idx];
    var bits: u32;
    if (byte_off == 0u) {
        bits = w0 & 0xFFFFu;
    } else if (byte_off == 2u) {
        bits = (w0 >> 16u) & 0xFFFFu;
    } else {
        let w1 = B_raw[word_idx + 1u];
        bits = ((w0 >> (byte_off * 8u)) | (w1 << ((4u - byte_off) * 8u))) & 0xFFFFu;
    }
    return unpack2x16float(bits).x;
}

fn dequant_tq2_0(b_row: u32, k_abs: u32) -> f32 {
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 66u;

    let d = read_f16(block_byte + 64u);
    let j_byte_base = (in_block / 128u) * 32u;
    let l = (in_block % 128u) / 32u;
    let m = in_block % 32u;
    let shift = l * 2u;
    let raw = (read_byte(block_byte + j_byte_base + m) >> shift) & 0x03u;
    return (f32(i32(raw) - 1)) * d;
}

// === MMV (matrix-vector) variant — auto-generated by scripts/gen_mmv_shaders.py.
// One workgroup per output column. Threads cooperatively reduce over K
// using a workgroup-shared partial-sum array and a tree reduction.
const MMV_WORKGROUP_SIZE: u32 = 128u;
var<workgroup> mmv_partial: array<f32, 128>;

@compute @workgroup_size(MMV_WORKGROUP_SIZE, 1, 1)
fn matmul_transb_tq2_0_mmv(
    @builtin(workgroup_id) wid: vec3<u32>,
    @builtin(local_invocation_id) lid: vec3<u32>,
) {
    let col = wid.x;
    let tid = lid.x;
    if (col >= params.N) { return; }

    var acc: f32 = 0.0;
    var k: u32 = tid;
    loop {
        if (k >= params.K) { break; }
        acc = acc + A[k] * dequant_tq2_0(col, k);
        k = k + MMV_WORKGROUP_SIZE;
    }

    mmv_partial[tid] = acc;
    workgroupBarrier();

    var stride: u32 = MMV_WORKGROUP_SIZE / 2u;
    loop {
        if (stride == 0u) { break; }
        if (tid < stride) {
            mmv_partial[tid] = mmv_partial[tid] + mmv_partial[tid + stride];
        }
        workgroupBarrier();
        stride = stride / 2u;
    }

    if (tid == 0u) {
        C[col] = mmv_partial[0];
    }
}
