//go:build go1.22

// Package usermgr provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package usermgr

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BasicAuthScopes  = "BasicAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for AuthSubjectKind.
const (
	AuthSubjectKindGroup   AuthSubjectKind = "group"
	AuthSubjectKindRole    AuthSubjectKind = "role"
	AuthSubjectKindSubject AuthSubjectKind = "subject"
	AuthSubjectKindUser    AuthSubjectKind = "user"
)

// Defines values for PermissionType.
const (
	PermissionTypeAdmin PermissionType = "admin"
	PermissionTypeRead  PermissionType = "read"
	PermissionTypeWrite PermissionType = "write"
)

// Defines values for ResourceType.
const (
	ResourceTypeAsterisk ResourceType = "*"
	ResourceTypeTable    ResourceType = "table"
	ResourceTypeUser     ResourceType = "user"
)

// ApiKey Public metadata for an API key (secrets are never returned after creation).
type ApiKey struct {
	// CreatedAt When the API key was created.
	CreatedAt time.Time `json:"created_at"`

	// ExpiresAt When the API key expires. Null means never.
	ExpiresAt *time.Time `json:"expires_at"`

	// KeyId Unique identifier for the API key.
	KeyId string `json:"key_id"`

	// Name Human-readable name for the API key.
	Name string `json:"name"`

	// Permissions Optional permission scoping. If empty, inherits owner's full permissions.
	Permissions *[]Permission `json:"permissions"`

	// RowFilter Optional per-table row filter. Keys are table names (or '*' for all tables). Values are Antfly query JSON objects. API keys inherit the owner's effective row filters; key-local filters are applied as additional narrowing.
	RowFilter *map[string]interface{} `json:"row_filter"`

	// Username Owner of the API key.
	Username string `json:"username"`
}

// ApiKeyWithSecret defines model for ApiKeyWithSecret.
type ApiKeyWithSecret struct {
	// CreatedAt When the API key was created.
	CreatedAt time.Time `json:"created_at"`

	// Encoded Pre-encoded credential ready for the Authorization header: base64(key_id:key_secret).
	Encoded string `json:"encoded"`

	// ExpiresAt When the API key expires. Null means never.
	ExpiresAt *time.Time `json:"expires_at"`

	// KeyId Unique identifier for the API key.
	KeyId string `json:"key_id"`

	// KeySecret Cleartext secret for the API key. Store securely — it cannot be retrieved again.
	KeySecret string `json:"key_secret"`

	// Name Human-readable name for the API key.
	Name string `json:"name"`

	// Permissions Optional permission scoping. If empty, inherits owner's full permissions.
	Permissions *[]Permission `json:"permissions"`

	// RowFilter Optional per-table row filter. Keys are table names (or '*' for all tables). Values are Antfly query JSON objects. API keys inherit the owner's effective row filters; key-local filters are applied as additional narrowing.
	RowFilter *map[string]interface{} `json:"row_filter"`

	// Username Owner of the API key.
	Username string `json:"username"`
}

// AuthSubject defines model for AuthSubject.
type AuthSubject struct {
	// Kind Conservative subject classification inferred from user records and subject prefixes.
	Kind AuthSubjectKind `json:"kind"`

	// Subject Casbin subject name.
	Subject string `json:"subject"`
}

// AuthSubjectKind Conservative subject classification inferred from user records and subject prefixes.
type AuthSubjectKind string

// CreateApiKeyRequest Request to create a new API key.
type CreateApiKeyRequest struct {
	// ExpiresIn Duration until expiration (e.g., '720h' for 30 days). Empty means never.
	ExpiresIn *string `json:"expires_in,omitempty"`

	// Name Human-readable name for the API key.
	Name string `json:"name"`

	// Permissions Optional permission scoping. Each permission must be a subset of the creator's permissions.
	Permissions *[]Permission `json:"permissions"`

	// RowFilter Optional per-table row filter. Keys are table names (or '*' for all tables). Values are Antfly query JSON objects. API keys inherit the owner's effective row filters; key-local filters are applied as additional narrowing.
	RowFilter *map[string]interface{} `json:"row_filter"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// InitialPolicies Optional list of initial permissions for the user.
	InitialPolicies *[]Permission `json:"initial_policies"`

	// Metadata Auth metadata available to stored row-filter policies.
	Metadata *map[string]interface{} `json:"metadata"`
	Password string                  `json:"password"`

	// Username Username for the new user. If provided in the path, this field can be omitted or must match the path parameter.
	Username *string `json:"username,omitempty"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Permission defines model for Permission.
type Permission struct {
	// Resource Resource name (e.g., table name, target username, or '*' for global).
	Resource string `json:"resource"`

	// ResourceType Type of the resource, e.g., table, user, or global ('*').
	ResourceType ResourceType `json:"resource_type"`

	// Type Type of permission.
	Type PermissionType `json:"type"`
}

// PermissionType Type of permission.
type PermissionType string

// ResourceType Type of the resource, e.g., table, user, or global ('*').
type ResourceType string

// RoleAssignment defines model for RoleAssignment.
type RoleAssignment struct {
	// Role Role or group subject to assign, usually prefixed with role: or group:.
	Role string `json:"role"`
}

// RowFilterEntry A row filter policy for a user on a specific table.
type RowFilterEntry struct {
	// Filter Antfly query JSON that documents must match to be visible.
	Filter map[string]interface{} `json:"filter"`

	// Table Table name (or '*' for all tables).
	Table string `json:"table"`
}

// SuccessMessage defines model for SuccessMessage.
type SuccessMessage struct {
	Message *string `json:"message,omitempty"`
}

// UpdatePasswordRequest defines model for UpdatePasswordRequest.
type UpdatePasswordRequest struct {
	NewPassword string `json:"new_password"`
}

// User defines model for User.
type User struct {
	// Metadata Server-side auth metadata available to stored row-filter policies through $auth metadata paths.
	Metadata *map[string]interface{} `json:"metadata"`

	// PasswordHash Base64 encoded password hash. Exposing this is a security risk.
	PasswordHash []byte `json:"password_hash"`
	Username     string `json:"username"`
}

// KeyIdPathParameter defines model for KeyIdPathParameter.
type KeyIdPathParameter = string

// SubjectPathParameter defines model for SubjectPathParameter.
type SubjectPathParameter = string

// UserNamePathParameter defines model for UserNamePathParameter.
type UserNamePathParameter = string

// SetSubjectRowFilterJSONBody defines parameters for SetSubjectRowFilter.
type SetSubjectRowFilterJSONBody map[string]interface{}

// RemovePermissionFromUserParams defines parameters for RemovePermissionFromUser.
type RemovePermissionFromUserParams struct {
	// Resource The name of the resource for the permission to be removed.
	Resource string `form:"resource" json:"resource"`

	// ResourceType The type of the resource for the permission to be removed.
	ResourceType ResourceType `form:"resourceType" json:"resourceType"`
}

// RemoveRoleFromUserParams defines parameters for RemoveRoleFromUser.
type RemoveRoleFromUserParams struct {
	// Role Role or group subject to remove.
	Role string `form:"role" json:"role"`
}

// SetRowFilterJSONBody defines parameters for SetRowFilter.
type SetRowFilterJSONBody map[string]interface{}

// SetSubjectRowFilterJSONRequestBody defines body for SetSubjectRowFilter for application/json ContentType.
type SetSubjectRowFilterJSONRequestBody SetSubjectRowFilterJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// UpdateUserPasswordJSONRequestBody defines body for UpdateUserPassword for application/json ContentType.
type UpdateUserPasswordJSONRequestBody = UpdatePasswordRequest

// AddPermissionToUserJSONRequestBody defines body for AddPermissionToUser for application/json ContentType.
type AddPermissionToUserJSONRequestBody = Permission

// AddRoleToUserJSONRequestBody defines body for AddRoleToUser for application/json ContentType.
type AddRoleToUserJSONRequestBody = RoleAssignment

// SetRowFilterJSONRequestBody defines body for SetRowFilter for application/json ContentType.
type SetRowFilterJSONRequestBody SetRowFilterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get current authenticated user
	// (GET /auth/v1/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// List auth subjects
	// (GET /auth/v1/subjects)
	ListAuthSubjects(w http.ResponseWriter, r *http.Request)
	// List row filters for an auth subject
	// (GET /auth/v1/subjects/{subject}/row-filters)
	ListSubjectRowFilters(w http.ResponseWriter, r *http.Request, subject SubjectPathParameter)
	// Remove row filter for an auth subject on a table
	// (DELETE /auth/v1/subjects/{subject}/row-filters/{table})
	RemoveSubjectRowFilter(w http.ResponseWriter, r *http.Request, subject SubjectPathParameter, table string)
	// Get row filter for an auth subject on a table
	// (GET /auth/v1/subjects/{subject}/row-filters/{table})
	GetSubjectRowFilter(w http.ResponseWriter, r *http.Request, subject SubjectPathParameter, table string)
	// Set row filter for an auth subject on a table
	// (PUT /auth/v1/subjects/{subject}/row-filters/{table})
	SetSubjectRowFilter(w http.ResponseWriter, r *http.Request, subject SubjectPathParameter, table string)
	// List all users
	// (GET /auth/v1/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Delete a user
	// (DELETE /auth/v1/users/{userName})
	DeleteUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Get user details
	// (GET /auth/v1/users/{userName})
	GetUserByName(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Create a new user
	// (POST /auth/v1/users/{userName})
	CreateUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// List API keys for a user
	// (GET /auth/v1/users/{userName}/api-keys)
	ListApiKeys(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Create a new API key
	// (POST /auth/v1/users/{userName}/api-keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Delete an API key
	// (DELETE /auth/v1/users/{userName}/api-keys/{keyId})
	DeleteApiKey(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, keyId KeyIdPathParameter)
	// Update user password
	// (PUT /auth/v1/users/{userName}/password)
	UpdateUserPassword(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Remove permission from user
	// (DELETE /auth/v1/users/{userName}/permissions)
	RemovePermissionFromUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, params RemovePermissionFromUserParams)
	// Get user permissions
	// (GET /auth/v1/users/{userName}/permissions)
	GetUserPermissions(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Add permission to user
	// (POST /auth/v1/users/{userName}/permissions)
	AddPermissionToUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Remove role from user
	// (DELETE /auth/v1/users/{userName}/roles)
	RemoveRoleFromUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, params RemoveRoleFromUserParams)
	// List user roles
	// (GET /auth/v1/users/{userName}/roles)
	ListUserRoles(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Add role to user
	// (POST /auth/v1/users/{userName}/roles)
	AddRoleToUser(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// List row filters for a user
	// (GET /auth/v1/users/{userName}/row-filters)
	ListRowFilters(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter)
	// Remove row filter for a user on a table
	// (DELETE /auth/v1/users/{userName}/row-filters/{table})
	RemoveRowFilter(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, table string)
	// Get row filter for a user on a table
	// (GET /auth/v1/users/{userName}/row-filters/{table})
	GetRowFilter(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, table string)
	// Set row filter for a user on a table
	// (PUT /auth/v1/users/{userName}/row-filters/{table})
	SetRowFilter(w http.ResponseWriter, r *http.Request, userName UserNamePathParameter, table string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuthSubjects operation middleware
func (siw *ServerInterfaceWrapper) ListAuthSubjects(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuthSubjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSubjectRowFilters operation middleware
func (siw *ServerInterfaceWrapper) ListSubjectRowFilters(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subject" -------------
	var subject SubjectPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "subject", r.PathValue("subject"), &subject, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSubjectRowFilters(w, r, subject)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveSubjectRowFilter operation middleware
func (siw *ServerInterfaceWrapper) RemoveSubjectRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subject" -------------
	var subject SubjectPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "subject", r.PathValue("subject"), &subject, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveSubjectRowFilter(w, r, subject, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSubjectRowFilter operation middleware
func (siw *ServerInterfaceWrapper) GetSubjectRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subject" -------------
	var subject SubjectPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "subject", r.PathValue("subject"), &subject, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSubjectRowFilter(w, r, subject, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetSubjectRowFilter operation middleware
func (siw *ServerInterfaceWrapper) SetSubjectRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "subject" -------------
	var subject SubjectPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "subject", r.PathValue("subject"), &subject, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subject", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetSubjectRowFilter(w, r, subject, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserByName operation middleware
func (siw *ServerInterfaceWrapper) GetUserByName(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserByName(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApiKeys operation middleware
func (siw *ServerInterfaceWrapper) ListApiKeys(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiKeys(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiKey operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiKey(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	// ------------- Path parameter "keyId" -------------
	var keyId KeyIdPathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "keyId", r.PathValue("keyId"), &keyId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "keyId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiKey(w, r, userName, keyId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUserPassword operation middleware
func (siw *ServerInterfaceWrapper) UpdateUserPassword(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUserPassword(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemovePermissionFromUser operation middleware
func (siw *ServerInterfaceWrapper) RemovePermissionFromUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RemovePermissionFromUserParams

	// ------------- Required query parameter "resource" -------------

	if paramValue := r.URL.Query().Get("resource"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resource"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "resource", r.URL.Query(), &params.Resource)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resource", Err: err})
		return
	}

	// ------------- Required query parameter "resourceType" -------------

	if paramValue := r.URL.Query().Get("resourceType"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "resourceType"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "resourceType", r.URL.Query(), &params.ResourceType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "resourceType", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemovePermissionFromUser(w, r, userName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserPermissions operation middleware
func (siw *ServerInterfaceWrapper) GetUserPermissions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserPermissions(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddPermissionToUser operation middleware
func (siw *ServerInterfaceWrapper) AddPermissionToUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddPermissionToUser(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveRoleFromUser operation middleware
func (siw *ServerInterfaceWrapper) RemoveRoleFromUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params RemoveRoleFromUserParams

	// ------------- Required query parameter "role" -------------

	if paramValue := r.URL.Query().Get("role"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "role"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "role", r.URL.Query(), &params.Role)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "role", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveRoleFromUser(w, r, userName, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUserRoles operation middleware
func (siw *ServerInterfaceWrapper) ListUserRoles(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUserRoles(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddRoleToUser operation middleware
func (siw *ServerInterfaceWrapper) AddRoleToUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddRoleToUser(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRowFilters operation middleware
func (siw *ServerInterfaceWrapper) ListRowFilters(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRowFilters(w, r, userName)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveRowFilter operation middleware
func (siw *ServerInterfaceWrapper) RemoveRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveRowFilter(w, r, userName, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRowFilter operation middleware
func (siw *ServerInterfaceWrapper) GetRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRowFilter(w, r, userName, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetRowFilter operation middleware
func (siw *ServerInterfaceWrapper) SetRowFilter(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userName" -------------
	var userName UserNamePathParameter

	err = runtime.BindStyledParameterWithOptions("simple", "userName", r.PathValue("userName"), &userName, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userName", Err: err})
		return
	}

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", r.PathValue("table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BasicAuthScopes, []string{})

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetRowFilter(w, r, userName, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/me", wrapper.GetCurrentUser)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/subjects", wrapper.ListAuthSubjects)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/subjects/{subject}/row-filters", wrapper.ListSubjectRowFilters)
	m.HandleFunc("DELETE "+options.BaseURL+"/auth/v1/subjects/{subject}/row-filters/{table}", wrapper.RemoveSubjectRowFilter)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/subjects/{subject}/row-filters/{table}", wrapper.GetSubjectRowFilter)
	m.HandleFunc("PUT "+options.BaseURL+"/auth/v1/subjects/{subject}/row-filters/{table}", wrapper.SetSubjectRowFilter)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/users", wrapper.ListUsers)
	m.HandleFunc("DELETE "+options.BaseURL+"/auth/v1/users/{userName}", wrapper.DeleteUser)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/users/{userName}", wrapper.GetUserByName)
	m.HandleFunc("POST "+options.BaseURL+"/auth/v1/users/{userName}", wrapper.CreateUser)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/users/{userName}/api-keys", wrapper.ListApiKeys)
	m.HandleFunc("POST "+options.BaseURL+"/auth/v1/users/{userName}/api-keys", wrapper.CreateApiKey)
	m.HandleFunc("DELETE "+options.BaseURL+"/auth/v1/users/{userName}/api-keys/{keyId}", wrapper.DeleteApiKey)
	m.HandleFunc("PUT "+options.BaseURL+"/auth/v1/users/{userName}/password", wrapper.UpdateUserPassword)
	m.HandleFunc("DELETE "+options.BaseURL+"/auth/v1/users/{userName}/permissions", wrapper.RemovePermissionFromUser)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/users/{userName}/permissions", wrapper.GetUserPermissions)
	m.HandleFunc("POST "+options.BaseURL+"/auth/v1/users/{userName}/permissions", wrapper.AddPermissionToUser)
	m.HandleFunc("DELETE "+options.BaseURL+"/auth/v1/users/{userName}/roles", wrapper.RemoveRoleFromUser)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/users/{userName}/roles", wrapper.ListUserRoles)
	m.HandleFunc("POST "+options.BaseURL+"/auth/v1/users/{userName}/roles", wrapper.AddRoleToUser)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/users/{userName}/row-filters", wrapper.ListRowFilters)
	m.HandleFunc("DELETE "+options.BaseURL+"/auth/v1/users/{userName}/row-filters/{table}", wrapper.RemoveRowFilter)
	m.HandleFunc("GET "+options.BaseURL+"/auth/v1/users/{userName}/row-filters/{table}", wrapper.GetRowFilter)
	m.HandleFunc("PUT "+options.BaseURL+"/auth/v1/users/{userName}/row-filters/{table}", wrapper.SetRowFilter)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd/W4cN5J/FaJvAdvBaEb+yB5WiwVOdmxFTmIrHmsXm5wgcJo107S6yTbJ1mjWEHAP",
	"cU94T3Iokv0x3eyZkSzJo43+CKJMf7BI/qrqV8WqzpcollkuBQijo70vUU4VzcCAsv/1EywO2RE1yVH5",
	"M/7KQMeK54ZLEe1FHxMg+0eH5AwW5PCHYTSIOP6cU5NEg0jQDKK96AxfFA0iBZ8LroBFe0YVMIh0nEBG",
	"8aVwQbM8xXvpy/gHeDP7kb89+zl7J48+f9Afo0FkFjle1UZxMYsuLwfRuJh8gtiske8V1RMuiHY3ExRo",
	"QHQRJ4RqomQKewYEFeZUAWWgiFRkpmSR74GY9czGv2vD+XTHCM7mWIN6RzPYYLkLDQpF6RGv8G/aUL5P",
	"MhFMQkCoy/IBC4b9nP8Ei65ER8Uk5THJwFBGDSVTqQgVFSYea4gVGE2oAiLgHBRRYAolgBE6NaBIrIDi",
	"u57gfHIlc1CGgx3TXgJ2Sk133H8kIIhpoG9ONfEP4JumUmX4XMSogR3Ds8AUBxFc5FyB3mwEf/OQvCvS",
	"lGRAhXZT6h1PFGlKJ7jObgM645/B4pSz7tjHgn8ugHAGwvApB2XXtSEMDnlVpSkh0h7sxyKjYgfBibJa",
	"HVk93KtDkvMcUi4AL4ZGykFlXGsuhe4O+N7+QVNS30V0LHMuZkNyOCWQ5WYxIFwkoLjRRM4FqEeaTHHd",
	"G2+2GmAgs0P8ScE02ov+Y1SbtJHH7+ioesauQnhXqFJ0gdeVnJ9OeeoVkDLGnbhHTXBeDlZMasfYlVRy",
	"TtyLhuQnWDglMNUia/JYKvLou0dOadLUXdNPhuTvNC3A3b8vzDRdkM8FqAV5O37/jkhrf/Sw3BxdrpTd",
	"sXKxYDqF2PDzphj6r3j/TipjmpY/2UFonqccVVKTer5EUKXkHHflv0U/mp04uHClZQrsOApF5LQfU/12",
	"qGnHfi81xmO5MeagaS5OAtI5C/YPbpKxtUl2c9P0/TTa+301fLztuxx8aRkoELFkENDfIwU7/iIaJavG",
	"NCWoY4tatwqTSMX/Zc0fSaxz2CMTquHPLx67ee7hv5wJfbK8Xv88fvvpw8HfD37bTfJxZn6ZHH9/fvzj",
	"m3H89Nc///aayfjg3fe/ipef4PitHB8n7ydvzv41zi7Ofv31b3+LeiyRrtal5URToMrAhSHujo51IGMj",
	"FeDVQkG6IP/3P/9LuCExFUIaMgG0+YrDOSJsRrlYngo7SPJ48RL/SQ5/fJf+8/nblO1vhAQv8aDaie7G",
	"n7QVtTTnpeMhCnQuhQbCRZwWjIuZnVzcnvVjnci5IFLE8GRoEVWYxNMQy56WsHHGRQAYr3AgdU6tYpas",
	"JE6p1nzKYycPF1NQChiZKplZd08UxFIxTahg1VO5gim/AGsFQRQZrgnejI5fpqgQlslEg4qxnAxaxCQE",
	"BF1PaC2VWt7HDalOcw9rLmWXK6S2r6xWOxX8AJ8L0AHZ/AVipOcAhBIB86apaWmud/xIoNov+6FQbiMK",
	"YXjq3L774TEMZ8MBefSfz3YTZ7Wf7xJGF2iyX6PTarOCenHwkfvqkl/TOGleyApttZoiGDSY0rDbpZfo",
	"fB6c9JY66Zb+WfT1ax1GJQ2dW1YhLjg6tdNcpjz2v/Wsdsq1BYl/pAmPCtZoum4JK2VwchWkoG2voxp6",
	"TrkdAi2MRmfHcMd23PaQcgmWdPJL5G0hEvyIxhmskLVe+ZxqPZeKLYdp+nmsnpuj/9J6/l6xZrxR3R9Q",
	"+X5CduyvVMuP1tJuARLwXMlzjtyFuwgII8wBMQnXZMohZejZ0QDIjBsDDKNmaxMyauKkeoJU6YTrUb1q",
	"ZiGAvlZKqi4oofy5Hm5fEPsryUBrOls/rntHaNAG7DojK9CyUDGEnJO74sy49yG1hcG/1QxMFdgPSMPi",
	"zFI5oWmL/EnFQOlT+47QvpeynLorq3WpFO8j3ntZvm1T/XNPtVawWou2KP7tq9f2oxeglfpY5IA2pLYd",
	"TeKDrjIaRHPFDY5CWcZFi++4OzprtTT93lER0+VUBqSxhQO7bXbL3FaRx4++e/SkKVu5TZ6cfbcsV+8m",
	"fpAp7GvNZyIDEbC/lsB1wSZTqLJYFVkzklD7KhS3oGm6KOkjI3NuEpcKq7NfX03srHChbf4g52+s0Xwt",
	"jArkk/YbntDZVRcwUUeEpUDWkUOMdNntQJfcXZ0XdP23SaghTMYFLr5eMm8STd8519wPvmTxVebmlFNl",
	"3L5FIGZcAFTr1FkTB4Eu9mru18dBAlZh7daUgPOrFNqkcRHHoPUv3mB2oJfVF+rh3+fgaTIajBTQMWj3",
	"ommRpougYJ2hj3NGDRx5099LPgTMT8OeUsB8fA1n2SZGzfeHlggdaGhhrs40xqDOQe1ozoDQ67AOYhIl",
	"i1lC/rT8OPrgNiVpAxMX4mtYymlCddKF7kubxCBlCqS8m+DdQ/L6IpfahdlcE65RpSEuFDcLorg+W4b1",
	"24M3i9+e/aX4JRsOlzKtk4WBdazn6qyjkVBanuRJiEyXco/RMUIjU4780bHkaC9KSqPpc/RLmZ9aIlrm",
	"mXD9eFy+wjpdvD7BX+vbE2NyezNQBap7t/25fTsKzcVU2vy6FIa6UL8UzNpB9FUq9Y/ovdFoxk1STIax",
	"zEbU3sEm/o/oMpReQTOVUUFnuMm4oBrZI3BVIUEPbC6jFSemPAahoSlQTuMEyLPhbkeo+Xw+pPbyUKrZ",
	"yD+rRz8fvnr9bvx659lwd5iYLLUWlhsLAtRa8gtKBqgDGJxFg+gclON00flTmuYJfYrPyBwEzXm0Fz0f",
	"7g6fWzyYxG7xCBVtdP505EA2g2BKwqW8NGFgKE/rSCculAJh0oVVdxCGxxSNZRkBydKQHqJKHoB55R44",
	"9skdn66ykjzb3S130pMEGyW6TNLok3ZMtT74uY65Wm8MljML14jg2hHb1VW4rZpdM1u5IlItMA71Yvfp",
	"lVZw1aRcUBIY/FhQr/LAcNDvr7ht1xr0UBhcxZQ4D0PKGweRLrKMIvtCdJV4DKARV5rONJpFC74TfLgC",
	"vyeXepUKFEpoUrjTrPJ+wkDx82Z+0yU2fYKxRtOg4e2cvbDsFI1KM+Je1pefuTaNxKz+Wo3ZCM3NTHAH",
	"zptjcWtggYvoyIiul7GEwgfL7YNQGH3xf12O6q1bD5A25UdSw7iC2BpJY9DIMxvEkFYWujzKpzaCqQKY",
	"MCz8DlUhyN1goxXx/NvAo5GxLE/9m4hZAoxfgejEUse6yKTn4K2+ZRQs87g82Rx8oy824Ll06MOwJITD",
	"TKKnpoHgM4hDdOM+CoX6RAYtVBWSLsPPjdAGYBd/L0IRfSWSsm9phVXWh724fWA05BDSkKksxHb5MrfG",
	"zS0MwNJlEKqkSxChK22VzQTdEkoOwKyHyM2tdtsyXYU0PQDOkaevR9tN2MPB9XJHgfKxUtZNasd6E04n",
	"gygvAjo0BqPRRyvIUxr3GFyX7UN3PnDO3CZXpUlAtbx/V4HGPQpks0gvJVtcCTj9IdHaaKObUMRpuYki",
	"f60yi52lvvymCt/QOQ0m4GjuQPVeUkbKA31/WsLFOU05K0XDBX2yVaZgfAOmoMlpbFS0QW6BVmerqNou",
	"lvKHdnqhDWRDu5Rc4b0sWwqvwiT5WN8kMV7ON3x1WH997vxNwvwXu89vf9A3Uk04YyDIDlF9e72F0WWJ",
	"19VJBnvL6EtZ1bySxv9gf9fNE6JwTs3dGM6nvQgflhM3KNsak1jqEuG63Hb25M64mV2S7WRlbnP9gWEX",
	"XIOrpGvXIukArMF8uahK7m/JdVvpr2TvHmC5dcFC4QyJxVcImVcLBcI9I5Z8y1CRpKvp0r400spiz/6R",
	"LMz4OYh68+zZjD+qGZKqWAhdCsUn6BlokiuIgYGIA5FsXT/2Ffx71V50C9T64FDV+dYLv45xP711ta0l",
	"2yKXUrJsLvLC1Ko8qo5vM65tDYRX6L/cvpSvpJimPF4yL4SmrpAeLrg2ersCgVfN8uP1ZyhtejOiOd85",
	"g8X6nDnyp6q2VM4FMDJZtFJOrqBv3GnBcoXurlEqcHpij6Hv6OCkOvK+Z8T+j+3MLIOv0FfXZzXA7nf2",
	"rt1a2d1RHra3leFjqLPDchXflShFunAhtP3VKUCfg/OTvE0Xt9z5EEo1tftZvoWf6zRXrRN0W93ek28Q",
	"t3s5PIZgqSyGwEUMrous21vxQKzbHtdjLGSHNnK7oy+2WX1lmuEIVEaFq+BhPuWwbGrqvrhionFXhSl3",
	"V5OiLn2zfcs8TV2L3CeITcgnu4C2YWrW5StKRetPWdwBYkohtjtJIFYh5oY812Dtg4EvLSwfcXfw2qx9",
	"vTH3GjqycfW42jd1+Dhgo9SIexKHO6qrbm/DT4ZLhgPAeAfzeg6be8mbg2yrrjogYjkLUthJbY+TFM21",
	"8w36VbrgIdHTMC0Oji5SbdabXyEI7LRqritbqVSx0aWpihRciZ3vnZhQbflt1chCqlwPBl99RSt1peYb",
	"JTOf0mnZnO5XSuyrW40zFSlvSOm6KXxhS3Umbc9N60PppX6iTc+l+9qjAoflCdgVuHF5P7qep36ZN+/L",
	"QgO93vMfNba/t1bo2xgQK5eY+SPxGj81/26u2hYZFyIVsV1V9S8lLlzWtELnFhZDNZBbVds2jFGjCnuD",
	"kxGadlt3Nz0hOWqYtLtILK2qL384Rbn/pyj5Ep568Hy7iad9xsqs07KDWKsT+4w12l3lLR6TNNUgwDZr",
	"sctTTxSfsTvNHW3Aims5KWPbf2LyoLNNnd1nrKUgq7zQSmKsZAobUmJXkbvcFkAyyCagdMLzJjPuY77o",
	"9TflvL19146H9TJFuXG15UZd2CebVZSnsLX8EKd5x2ojlYPJlpe1l+FcS3t8O86asnX/9RnbQZxC3UxV",
	"d2XVpzj9hYEfrP7dFH/rdO5en6Y9HMf5D4X5DeqA406o0FqbuwJi+4yhsLfKhlqf1AjWP6/8fMaW8SIr",
	"7XYyom9gxreX/ViF6PKeQCNlgPFs3kaJ8XmolbLnLDxo5e9tc+SDDwj1ZHYhd/3Woz6nsCl+r9KJGe6y",
	"CwN5fd/l/Wy4rLnp/Wy8bHyx6cb7La+OhAN4aKq8T6AKNVdujKibOre/l02V19QYWxrnWTeZSLYg3L2r",
	"08sY7Lt8aLj8IzRc/tFZ1vj6Vqn5uTBrlRof+fr9BK1N88th7pfmp71+P0EToK1soQyk1wB3A1FSmr+6",
	"BlQlC+O/U2wvMlIIBoqUpK36stbIRvhe9u7HfL3Ca6IgtbUpPqLRtaHzsfvFDuM6T6nrivI/d+1p+JXL",
	"Jzv+xY0Ucff1S2d9mw1SVqdl1bfAGl9nKyvt2uPgQ+X/CGCTQZD7pnAOaf15u2kVW/nBmmazPR7aBn9x",
	"0yF9g3wrx1enYJoDW6R2x0wBOf3/BwAA//8476UlG2gAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
