resources:
  - certificate.yaml

replacements:
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: antfly-operator-serving-cert
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 0
          create: true
  - source:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: antfly-operator-serving-cert
      fieldPath: metadata.name
    targets:
      - select:
          kind: ValidatingWebhookConfiguration
        fieldPaths:
          - metadata.annotations.[cert-manager.io/inject-ca-from]
        options:
          delimiter: '/'
          index: 1
