from enum import Enum


class InferenceEmbedRequestTaskType(str, Enum):
    CLASSIFICATION = "CLASSIFICATION"
    CLUSTERING = "CLUSTERING"
    CODE_RETRIEVAL_QUERY = "CODE_RETRIEVAL_QUERY"
    FACT_VERIFICATION = "FACT_VERIFICATION"
    QUESTION_ANSWERING = "QUESTION_ANSWERING"
    RETRIEVAL_DOCUMENT = "RETRIEVAL_DOCUMENT"
    RETRIEVAL_QUERY = "RETRIEVAL_QUERY"
    SEMANTIC_SIMILARITY = "SEMANTIC_SIMILARITY"

    def __str__(self) -> str:
        return str(self.value)
