// Package chunking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package chunking

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// AudioChunkOptions Options specific to audio chunking.
type AudioChunkOptions struct {
	// OverlapDurationMs Overlap duration in milliseconds between audio chunks (default: 0).
	OverlapDurationMs int `json:"overlap_duration_ms,omitempty,omitzero"`

	// WindowDurationMs Window duration in milliseconds for fixed-window audio chunking (default: 30000).
	WindowDurationMs int `json:"window_duration_ms,omitempty,omitzero"`
}

// BinaryContent Binary media content with format-specific metadata.
type BinaryContent struct {
	// Data Base64-encoded binary data (valid WAV, PNG, etc.)
	Data []byte `json:"data,omitempty,omitzero"`

	// EndTimeMs Audio: window end time in milliseconds
	EndTimeMs float32 `json:"end_time_ms,omitempty,omitzero"`

	// FrameDelayMs Animation: display delay in milliseconds
	FrameDelayMs int `json:"frame_delay_ms,omitempty,omitzero"`

	// FrameIndex Animation: frame number
	FrameIndex int `json:"frame_index,omitempty,omitzero"`

	// StartTimeMs Audio: window start time in milliseconds
	StartTimeMs float32 `json:"start_time_ms,omitempty,omitzero"`
}

// Chunk defines model for Chunk.
type Chunk struct {
	// Id Sequence number of the chunk (0, 1, 2, ...)
	Id uint32 `json:"id"`

	// MimeType MIME type: text/plain, audio/wav, image/png, etc.
	MimeType string `json:"mime_type"`
	union    json.RawMessage
}

// ChunkOptions Per-request configuration for chunking. All fields are optional - zero/omitted values use chunker defaults.
type ChunkOptions struct {
	// Audio Options specific to audio chunking.
	Audio AudioChunkOptions `json:"audio,omitempty,omitzero"`

	// MaxChunks Maximum number of chunks to generate per document.
	MaxChunks int `json:"max_chunks,omitempty,omitzero"`

	// Text Options specific to text chunking.
	Text TextChunkOptions `json:"text,omitempty,omitzero"`

	// Threshold Confidence threshold for model-based chunking (0.0-1.0).
	Threshold float32 `json:"threshold,omitempty,omitzero"`
}

// TextChunkOptions Options specific to text chunking.
type TextChunkOptions struct {
	// OverlapTokens Number of tokens to overlap between consecutive chunks. Helps maintain context across chunk boundaries. Only used by fixed-size chunkers.
	OverlapTokens int `json:"overlap_tokens,omitempty,omitzero"`

	// Separator Separator string for splitting (e.g., '\n\n' for paragraphs). Only used by fixed-size chunkers.
	Separator string `json:"separator,omitempty,omitzero"`

	// TargetTokens Target number of tokens per chunk.
	TargetTokens int `json:"target_tokens,omitempty,omitzero"`
}

// TextContent Text content with character offsets.
type TextContent struct {
	// EndChar Character position in original text where chunk ends (exclusive)
	EndChar int `json:"end_char"`

	// StartChar Character position in original text where chunk starts
	StartChar int `json:"start_char"`

	// Text The chunk text content
	Text string `json:"text"`
}

// AsTextContent returns the union data inside the Chunk as a TextContent
func (t Chunk) AsTextContent() (TextContent, error) {
	var body TextContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextContent overwrites any union data inside the Chunk as the provided TextContent
func (t *Chunk) FromTextContent(v TextContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextContent performs a merge with any union data inside the Chunk, using the provided TextContent
func (t *Chunk) MergeTextContent(v TextContent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBinaryContent returns the union data inside the Chunk as a BinaryContent
func (t Chunk) AsBinaryContent() (BinaryContent, error) {
	var body BinaryContent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBinaryContent overwrites any union data inside the Chunk as the provided BinaryContent
func (t *Chunk) FromBinaryContent(v BinaryContent) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBinaryContent performs a merge with any union data inside the Chunk, using the provided BinaryContent
func (t *Chunk) MergeBinaryContent(v BinaryContent) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Chunk) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["id"], err = json.Marshal(t.Id)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'id': %w", err)
	}

	object["mime_type"], err = json.Marshal(t.MimeType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mime_type': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *Chunk) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &t.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
	}

	if raw, found := object["mime_type"]; found {
		err = json.Unmarshal(raw, &t.MimeType)
		if err != nil {
			return fmt.Errorf("error reading 'mime_type': %w", err)
		}
	}

	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xWXW/bNhf+Kwd8X6AJIMtuM+xCd1kwbLtoU2DBetEEAS0eSWelSJU88kcD//eBlGwr",
	"luJmxe5s8XzxOc95Dp9EbuvGGjTsRfYkfF5hLePP61aRvala8+W2YbImflToc0fxv8hEfwC+wZwKyoEt",
	"yOAGefAjU6YiEY2zDTomjBHsCp2WzaNqnQzej/VU4M4I9kZABmrSmjzm1igPS+Q1ohlm83ChsJCt5gwW",
	"lyExbxsUmSDDWKITu0SsySi7Pp/7U7R5OXVhHRS0QTXrop3ceFDF1WKxmK5kd/hkl39jzqG2X8hIt72x",
	"htHwuKzuGGpUJCHvrGBNXIWCasmzQxNqZKkkyzH24etEZOnx559maHKrUMGySxRs4WIlNSn4dP1XAh8/",
	"/JYAcp5eikR0OUUmllvG4wU9OzJluA0a9chU4yTEkVoZ9PihURBMT5Eepim0lXzMY9p62XW0cLLGR4Va",
	"bqdTGapjHzNQ5BsttxCNJ5KN6dIFJ6NwczZytIO+qKlAnqXj1+IRjX8UkSlmxSEOWaXWt4XIPj8Ja7D/",
	"9X+HhcjE/+ZHIZj3KjC/ww3vCblLzts+p+/uIdg/Zx+p8c3/xK8tmnwPHtgCuMJumOBikcDbBN4lkKaR",
	"dSfAJmIzK+2s/9qS4at34b51wLn7eprv/R/vf4VwlAHjhueNlmSSboTna7lKgGpZ4rwxZUf2Mbd3iXD4",
	"tSWHSmSfw62GGR9G+D8kp93ur2eL/RynEJDey1glVwiHiIM600MzX1Tkj+hmoTr0HIIXVO5lLMjWQZXh",
	"WmsoCLXyIB2Cjf5Swwy+obNzWxMzKlhJ3aKH1vctQQe9uvmxukQQw49zNBlvldAwuXnsLj/RMbmhuq0H",
	"BOlhYgslGnSSEZpQmM3bOoA5OYEBxe/VFul+UhpXDn1l9QR3bwK+KrL3YBVhrq1CPVtKj2qwFhbpYvY2",
	"7fbBj0zxqLpXrWM+EOvsNmb7BadCfjiOZbQIIXufww7OrfGYt0yrniU+hd9RNx5qSYYlmY7nGwaZO+t9",
	"z/+lbY2SjtCncGv0NtBMwXLbb1dP3w6s89NN9dhIJ9m6KWHpj6Cb29gY32hijt3AtEwTeHN/b+7vzZt4",
	"GhxKJ5vKX/6rgo5Lj6UrkV8E8y4eD6WuwzSwN8Z97VNhqMvjLLHjwwdCXkknc445C49TsxvWdTCbYPnB",
	"ubGe9i8i66ikIBixresK3V60MbyRLnCT69bTCi/P7MP/JmGM5c8O/QlAhwXDA6i+K/Qx2LPSkyNsY9kP",
	"7mQKO0HNSjpUcQt1r8luNIzaP+4G08rEGiMovYzcBS+RiBU634VbpIs0rj3boJENiUxcpYv0KvRYcuVF",
	"Zlqtd/8EAAD//xenz5bqCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
