#!/usr/bin/env python3
"""Generate the compact Unicode class table used by the GPT-2 scanner.

Usage:
  generate_unicode_classes.py VERSION UnicodeData.txt PropList.txt OUTPUT

The generated two-level table stores four 2-bit classes per byte and
deduplicates identical 256-codepoint pages. Unicode 16 occupies about 16 KiB
of data instead of a 272 KiB flat table.
"""

from __future__ import annotations

import pathlib
import sys


CODEPOINT_COUNT = 0x110000
PAGE_CODEPOINTS = 256
PACKED_PAGE_BYTES = PAGE_CODEPOINTS // 4

LETTER = 0
NUMBER = 1
WHITESPACE = 2
OTHER = 3


def parse_unicode_data(path: pathlib.Path) -> bytearray:
    classes = bytearray([OTHER]) * CODEPOINT_COUNT
    range_start: int | None = None
    range_class = OTHER

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        fields = raw_line.split(";")
        codepoint = int(fields[0], 16)
        name = fields[1]
        category = fields[2]
        char_class = LETTER if category.startswith("L") else NUMBER if category.startswith("N") else OTHER

        if name.endswith(", First>"):
            range_start = codepoint
            range_class = char_class
        elif name.endswith(", Last>"):
            if range_start is None:
                raise ValueError(f"range end without start at U+{codepoint:04X}")
            classes[range_start : codepoint + 1] = bytes([range_class]) * (codepoint + 1 - range_start)
            range_start = None
        else:
            classes[codepoint] = char_class

    if range_start is not None:
        raise ValueError("unterminated UnicodeData range")
    return classes


def apply_whitespace(classes: bytearray, path: pathlib.Path) -> None:
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        codepoints, prop = (part.strip() for part in line.split(";", 1))
        if prop != "White_Space":
            continue
        if ".." in codepoints:
            first, last = (int(part, 16) for part in codepoints.split("..", 1))
        else:
            first = last = int(codepoints, 16)
        classes[first : last + 1] = bytes([WHITESPACE]) * (last + 1 - first)


def packed_pages(classes: bytearray) -> tuple[list[int], list[bytes]]:
    indices: list[int] = []
    unique_pages: list[bytes] = []
    page_ids: dict[bytes, int] = {}

    for base in range(0, CODEPOINT_COUNT, PAGE_CODEPOINTS):
        packed = bytearray(PACKED_PAGE_BYTES)
        for offset, char_class in enumerate(classes[base : base + PAGE_CODEPOINTS]):
            packed[offset >> 2] |= char_class << ((offset & 3) * 2)
        page = bytes(packed)
        page_id = page_ids.get(page)
        if page_id is None:
            page_id = len(unique_pages)
            if page_id > 255:
                raise ValueError("deduplicated page count no longer fits u8")
            page_ids[page] = page_id
            unique_pages.append(page)
        indices.append(page_id)
    return indices, unique_pages


def format_values(values: list[int] | bytes, width: int, indent: str = "    ") -> str:
    rows = []
    for start in range(0, len(values), width):
        rows.append(indent + ", ".join(str(value) for value in values[start : start + width]) + ",")
    return "\n".join(rows)


def render(version: str, indices: list[int], pages: list[bytes]) -> str:
    rendered_pages = []
    for page in pages:
        rendered_pages.append("    .{\n" + format_values(page, 16, "        ") + "\n    },")
    return f"""// Generated by tools/generate_unicode_classes.py from Unicode {version}.
// Do not edit by hand.

pub const unicode_version = "{version}";

pub const Class = enum(u2) {{
    letter = 0,
    number = 1,
    whitespace = 2,
    other = 3,
}};

const page_index = [{len(indices)}]u8{{
{format_values(indices, 32)}
}};

const pages = [{len(pages)}][{PACKED_PAGE_BYTES}]u8{{
{chr(10).join(rendered_pages)}
}};

pub inline fn classify(codepoint: u21) Class {{
    const page = pages[page_index[codepoint >> 8]];
    const class_byte = page[(codepoint & 0xff) >> 2];
    return @enumFromInt((class_byte >> @intCast((codepoint & 3) * 2)) & 3);
}}
"""


def main() -> None:
    if len(sys.argv) != 5:
        raise SystemExit(__doc__)
    version, unicode_data_path, prop_list_path, output_path = sys.argv[1:]
    classes = parse_unicode_data(pathlib.Path(unicode_data_path))
    apply_whitespace(classes, pathlib.Path(prop_list_path))
    indices, pages = packed_pages(classes)
    pathlib.Path(output_path).write_text(render(version, indices, pages), encoding="utf-8")
    print(f"generated {len(indices)} page indices and {len(pages)} unique pages")


if __name__ == "__main__":
    main()
