#!/usr/bin/env python3
"""Generate a compact Unicode punctuation bitmap for the BERT pre-tokenizer.

Mirrors generate_unicode_nfc.py: reads codepoint properties straight from
CPython's pinned unicodedata module instead of raw UCD files.

Usage:
  generate_unicode_punctuation.py OUTPUT
"""

from __future__ import annotations
import pathlib
import sys
import unicodedata as ud

EXPECTED_UNICODE_VERSION = "15.0.0"
CODEPOINT_COUNT = 0x110000
PAGE_CODEPOINTS = 256
PAGE_BYTES = PAGE_CODEPOINTS // 8  # 1 bit per codepoint


def is_punctuation(cp: int) -> bool:
    # Matches HF tokenizers' normalizers::bert::_is_punctuation: the ASCII
    # ranges BERT's basic tokenizer special-cases, plus any codepoint whose
    # Unicode general category starts with "P".
    if (33 <= cp <= 47) or (58 <= cp <= 64) or (91 <= cp <= 96) or (123 <= cp <= 126):
        return True
    if 0xD800 <= cp <= 0xDFFF:  # surrogates: never a valid UTF-8 scalar value
        return False
    return ud.category(chr(cp)).startswith("P")


def packed_pages(bits: bytearray) -> tuple[list[int], list[bytes]]:
    indices: list[int] = []
    unique_pages: list[bytes] = []
    page_ids: dict[bytes, int] = {}
    for base in range(0, CODEPOINT_COUNT, PAGE_CODEPOINTS):
        packed = bytearray(PAGE_BYTES)
        for offset in range(PAGE_CODEPOINTS):
            if bits[base + offset]:
                packed[offset >> 3] |= 1 << (offset & 7)
        page = bytes(packed)
        page_id = page_ids.get(page)
        if page_id is None:
            page_id = len(unique_pages)
            if page_id > 255:
                raise ValueError("deduplicated page count no longer fits u8")
            page_ids[page] = page_id
            unique_pages.append(page)
        indices.append(page_id)
    return indices, unique_pages


def format_values(values, width, indent="    "):
    rows = []
    for start in range(0, len(values), width):
        rows.append(
            indent + ", ".join(str(v) for v in values[start : start + width]) + ","
        )
    return "\n".join(rows)


def render(indices, pages) -> str:
    rendered_pages = [
        "    .{\n" + format_values(p, 16, "        ") + "\n    }," for p in pages
    ]
    return f"""// Generated by tools/generate_unicode_punctuation.py from Unicode {EXPECTED_UNICODE_VERSION}.
// Do not edit by hand.

pub const unicode_version = "{EXPECTED_UNICODE_VERSION}";

const page_index = [{len(indices)}]u8{{
{format_values(indices, 32)}
}};

const pages = [{len(pages)}][{PAGE_BYTES}]u8{{
{chr(10).join(rendered_pages)}
}};

/// True when `codepoint`'s Unicode general category starts with "P", or it
/// falls in the ASCII ranges BERT's basic tokenizer treats as punctuation
/// (some of which, like '$', are Sc/Sm rather than P* in Unicode proper).
pub inline fn isPunctuation(codepoint: u21) bool {{
    const page = pages[page_index[codepoint >> 8]];
    const byte = page[(codepoint & 0xff) >> 3];
    return (byte >> @intCast(codepoint & 7)) & 1 == 1;
}}
"""


def main() -> None:
    if ud.unidata_version != EXPECTED_UNICODE_VERSION:
        raise SystemExit(
            f"expected Unicode {EXPECTED_UNICODE_VERSION}, got {ud.unidata_version}"
        )
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    bits = bytearray(CODEPOINT_COUNT)
    for cp in range(CODEPOINT_COUNT):
        bits[cp] = 1 if is_punctuation(cp) else 0
    indices, pages = packed_pages(bits)
    pathlib.Path(sys.argv[1]).write_text(render(indices, pages), encoding="utf-8")
    print(f"generated {len(indices)} page indices and {len(pages)} unique pages")


if __name__ == "__main__":
    main()
