#!/usr/bin/env python3
"""Packaging regression tests for Antfly C ABI artifacts."""

from __future__ import annotations

import base64
import hashlib
import importlib.util
import json
import os
import re
import stat
import subprocess
import sys
import tarfile
import tempfile
import unittest
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PACKAGING_DIR = Path(__file__).resolve().parent


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"failed to load module spec for {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def workflow_job(document: str, name: str) -> str:
    document = document[document.index("\njobs:\n") + 1 :]
    marker = f"  {name}:\n"
    start = document.index(marker)
    remainder = document[start + len(marker) :]
    next_job = re.search(r"(?m)^  [a-z][a-z0-9-]*:\n", remainder)
    end = start + len(marker) + (next_job.start() if next_job else len(remainder))
    return document[start:end]


package_cli_release = load_module(
    "package_cli_release_for_cabi_test",
    PACKAGING_DIR / "package_cli_release.py",
)


def write_release_archive(
    root: Path,
    version: str,
    os_name: str,
    arch: str,
    variant: str | None = None,
) -> Path:
    stage = root / f"{os_name}-{arch}"
    (stage / "include").mkdir(parents=True)
    (stage / "lib").mkdir()
    (stage / "share" / "antfly").mkdir(parents=True)
    (stage / "completions").mkdir()

    antfly = stage / "antfly"
    antfly.write_text("#!/bin/sh\n")
    antfly.chmod(antfly.stat().st_mode | stat.S_IXUSR)

    (stage / "include" / "antfly.h").write_text("/* antfly header */\n")
    lib_name = "libantfly.dylib" if os_name == "Darwin" else "libantfly.so"
    (stage / "lib" / lib_name).write_text("antfly library\n")
    (stage / "share" / "antfly" / "asset.txt").write_text("asset\n")
    for shell in ("bash", "zsh", "fish"):
        (stage / "completions" / f"antfly.{shell}").write_text(f"{shell} completion\n")

    suffix = f"_{variant}" if variant else ""
    archive = root / f"antfly_{version}_{os_name}_{arch}{suffix}.tar.gz"
    with tarfile.open(archive, "w:gz") as tar:
        for child in stage.iterdir():
            tar.add(child, arcname=child.name)
    return archive


class CompletionPackagingTests(unittest.TestCase):
    def test_generated_completions_include_nested_commands(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            output_dir = Path(raw) / "completions"
            subprocess.run(
                [str(REPO_ROOT / "scripts" / "completions.sh"), str(output_dir)],
                cwd=REPO_ROOT,
                check=True,
            )

            zsh = (output_dir / "antfly.zsh").read_text()
            bash = (output_dir / "antfly.bash").read_text()
            fish = (output_dir / "antfly.fish").read_text()
            self.assertIn("Generated by `antfly completion zsh`", zsh)
            self.assertIn('case "$words[2]" in', zsh)
            self.assertIn(
                "inference) subcommands=(run embed classify generate chat", zsh
            )
            self.assertIn("completion) subcommands=(bash zsh fish)", zsh)
            self.assertIn("_describe 'subcommand' subcommands", zsh)
            self.assertIn('compgen -W "bash zsh fish"', bash)
            self.assertIn("__fish_seen_subcommand_from completion", fish)


class CAbiPackagingTests(unittest.TestCase):
    def test_release_requires_native_homebrew_validation(self) -> None:
        workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-artifact-build.yml"
        ).read_text()
        job = workflow_job(workflow, "test-macos-homebrew")
        self.assertIn("runs-on: macos-15", job)
        self.assertIn("scripts/packaging/test_homebrew_install.sh", job)
        self.assertIn(
            "- test-macos-homebrew", workflow_job(workflow, "release-request")
        )

    def test_homebrew_job_provisions_packaging_toolchains(self) -> None:
        workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-release.yml"
        ).read_text()
        job = workflow_job(workflow, "prepare-zig-homebrew")
        bootstrap = job.split("      - name: Render formula", 1)[0]
        self.assertIn("uses: actions/setup-python@", bootstrap)
        self.assertIn("steps.toolchain.outputs.python_build", bootstrap)
        self.assertIn("uses: cachix/install-nix-action@", bootstrap)
        self.assertIn("steps.toolchain.outputs.zig_nixpkgs_revision", bootstrap)
        self.assertIn("steps.toolchain.outputs.zig_nix_attribute", bootstrap)
        self.assertIn("steps.toolchain.outputs.zig_version", bootstrap)
        self.assertIn("nix-build '<nixpkgs>' -A \"$ZIG_NIX_ATTRIBUTE\"", bootstrap)
        self.assertIn('echo "$zig_path/bin" >> "$GITHUB_PATH"', bootstrap)
        self.assertIn("grep -q 'dynamically linked'", bootstrap)

    def test_linux_abi_release_contract_stays_consistent(self) -> None:
        installer = (REPO_ROOT / "scripts" / "install.sh").read_text()
        minimum_match = re.search(
            r'^ANTFLY_MIN_GLIBC="([0-9]+\.[0-9]+)"$', installer, re.MULTILINE
        )
        self.assertIsNotNone(minimum_match)
        minimum_glibc = minimum_match.group(1)

        release_build_workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-release-build.yml"
        ).read_text()
        build_controller_workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-release-build-controller.yml"
        ).read_text()
        artifact_build_workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-artifact-build.yml"
        ).read_text()
        nightly_workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-nightly.yml"
        ).read_text()
        release_gc_workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-release-gc.yml"
        ).read_text()
        release_workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-release.yml"
        ).read_text()
        github_cli_action = (
            REPO_ROOT / ".github" / "actions" / "setup-github-cli" / "action.yml"
        ).read_text()
        container_workflow = (
            REPO_ROOT / ".github" / "workflows" / "antfly-container.yml"
        ).read_text()
        dev_publish = (REPO_ROOT / "scripts" / "publish-zig-runtime-dev.sh").read_text()
        platform_policy = json.loads(
            (REPO_ROOT / "scripts" / "release" / "platforms.json").read_text()
        )
        channel_policy = json.loads(
            (REPO_ROOT / "scripts" / "release" / "channels.json").read_text()
        )
        environment_policy = json.loads(
            (REPO_ROOT / "scripts" / "release" / "github-environments.json").read_text()
        )
        self.assertEqual(platform_policy["glibc_minimum"], minimum_glibc)
        gnu_floors = {
            match
            for platform in platform_policy["platforms"]
            for match in re.findall(
                r"(?:x86_64|aarch64)-linux-gnu\.([0-9]+\.[0-9]+)",
                platform["zig_target"],
            )
        }
        self.assertEqual(gnu_floors, {minimum_glibc})
        self.assertEqual(
            set(
                re.findall(
                    r"(?:x86_64|aarch64)-linux-gnu\.([0-9]+\.[0-9]+)", dev_publish
                )
            ),
            {minimum_glibc},
        )

        wheel_floor = minimum_glibc.replace(".", "_")
        gnu_platforms = [
            platform
            for platform in package_cli_release.PLATFORMS
            if platform.npm_libc == "glibc"
        ]
        self.assertEqual(len(gnu_platforms), 2)
        for platform in gnu_platforms:
            self.assertTrue(
                platform.wheel_platform.startswith(f"manylinux_{wheel_floor}_")
            )

        npm_cli = json.loads(
            (REPO_ROOT / "ts" / "packages" / "cli" / "package.json").read_text()
        )
        self.assertEqual(npm_cli["engines"]["node"], ">=24.0")

        package_workflow = (
            REPO_ROOT / ".github" / "workflows" / "cli-package.yml"
        ).read_text()
        self.assertNotIn("workflow_dispatch:", package_workflow)
        self.assertNotIn('tags:\n      - "cli/v*"', package_workflow)
        self.assertNotIn("cli-linux-arm64-gnu", package_workflow)
        self.assertNotIn("cli-linux-x64-gnu", package_workflow)
        self.assertNotIn("npm publish", package_workflow)
        self.assertNotIn("gh-action-pypi-publish", package_workflow)
        self.assertNotIn("releases.antfly.io", package_workflow)
        self.assertIn("source_commit:", package_workflow)
        self.assertIn("antfly-cli-snapshot", package_workflow)
        self.assertIn("publish_npm_package.sh", release_workflow)
        self.assertIn(
            "uses: ./.github/workflows/cli-package.yml", artifact_build_workflow
        )
        self.assertIn(
            "uses: ./.github/workflows/antfly-artifact-build.yml",
            build_controller_workflow,
        )
        self.assertNotIn(
            "uses: ./.github/workflows/antfly-artifact-build.yml",
            release_build_workflow,
        )
        self.assertNotIn(
            "uses: ./.github/workflows/antfly-artifact-build.yml", nightly_workflow
        )
        self.assertIn(
            'workflows: ["Release request", "Nightly request"]',
            build_controller_workflow,
        )
        self.assertIn(
            'test "$TRIGGER_HEAD_BRANCH" = "$DEFAULT_BRANCH"', build_controller_workflow
        )
        self.assertIn("build_controller_commit:", artifact_build_workflow)
        self.assertIn('tags:\n      - "v*"', release_build_workflow)
        self.assertIn("permissions:\n  contents: read", release_build_workflow)
        self.assertNotIn("contents: write", release_build_workflow)
        self.assertNotIn("id-token: write", release_build_workflow)
        self.assertNotIn("environment:", release_build_workflow)
        self.assertNotIn("publish_objectstorage.py", release_build_workflow)
        for field in ("release_line:", "source_ref:", "source_ref_head:"):
            self.assertIn(field, artifact_build_workflow)
            self.assertIn(field, build_controller_workflow)
        self.assertIn(
            "python scripts/release/release_lines.py resolve",
            build_controller_workflow,
        )
        self.assertIn(
            'git merge-base --is-ancestor "$source_commit" "$source_ref_head"',
            build_controller_workflow,
        )
        self.assertNotIn(
            'test "$source_commit" = "$source_ref_head"',
            build_controller_workflow,
        )
        self.assertIn(
            "release-line policy changed after this controller was queued",
            build_controller_workflow,
        )
        self.assertIn("permissions:\n  contents: read", artifact_build_workflow)
        self.assertNotIn("contents: write", artifact_build_workflow)
        self.assertNotIn("id-token: write", artifact_build_workflow)
        self.assertNotIn("environment:", artifact_build_workflow)
        self.assertNotIn("publish_objectstorage.py", artifact_build_workflow)
        self.assertNotIn("workflow_dispatch:", release_workflow)
        self.assertNotIn('tags:\n      - "v*"', release_workflow)
        self.assertIn("workflow_run:", release_workflow)
        self.assertIn('workflows: ["Release build"]', release_workflow)
        self.assertIn("repository_dispatch:", release_workflow)
        self.assertIn("promote-cli-release", release_workflow)
        self.assertIn("promote-release-channel", release_workflow)
        self.assertIn("release_channels.py resolve", artifact_build_workflow)
        self.assertIn("release_platforms.py github-matrix", artifact_build_workflow)
        self.assertIn("verify_release_ledger.py", release_workflow)
        self.assertIn("--scope cli", release_workflow)
        self.assertIn("--scope runtime", release_workflow)
        self.assertIn("gh attestation verify", release_workflow)
        self.assertIn("actions/attest-build-provenance@", release_workflow)
        self.assertIn("--immutable-assets", release_workflow)
        self.assertNotIn("environment: container-publish", container_workflow)
        self.assertNotIn("environment: container-publish", release_workflow)
        self.assertEqual(release_workflow.count("environment: release-promotion"), 1)
        self.assertIn("github_environment.py check", release_workflow)
        self.assertIn("--environment release-promotion", release_workflow)
        self.assertEqual(
            release_workflow.count("uses: ./.github/actions/setup-github-cli"), 3
        )
        self.assertEqual(
            release_gc_workflow.count("uses: ./.github/actions/setup-github-cli"),
            2,
        )
        for job_name in (
            "prepare-release-promotion",
            "preflight-release-channel",
            "publish-github-release",
        ):
            self.assertIn(
                "uses: ./.github/actions/setup-github-cli",
                workflow_job(release_workflow, job_name),
            )
        for job_name in ("plan", "apply"):
            self.assertIn(
                "uses: ./.github/actions/setup-github-cli",
                workflow_job(release_gc_workflow, job_name),
            )
        self.assertIn("GH_CLI_VERSION: 2.100.0", github_cli_action)
        self.assertIn("sha256sum --check --status", github_cli_action)
        self.assertIn('case "$RUNNER_ARCH" in', github_cli_action)
        self.assertIn("--content-addressed-prefix", release_workflow)
        self.assertEqual(release_workflow.count("--exact-prefix"), 2)
        self.assertIn("--signer-workflow", release_workflow)
        self.assertIn("prepare_pypi_promotion.py", release_workflow)
        self.assertNotIn("--replace-assets", release_workflow)
        self.assertNotIn("skip-existing:", release_workflow)
        self.assertIn(
            "--require-hashes -r scripts/release/requirements.lock", release_workflow
        )
        self.assertNotIn("workflow_dispatch:", container_workflow)
        self.assertNotIn("release:\n", container_workflow)
        self.assertIn("workflow_call:", container_workflow)
        self.assertIn("workflow_run|repository_dispatch", container_workflow)
        self.assertIn("antfly-release-runtime-archives", container_workflow)
        self.assertIn("consumer-matrix container", container_workflow)
        self.assertIn("registryctl.py container-digest", container_workflow)
        self.assertIn("registryctl.py container-lookup", container_workflow)
        self.assertIn("release_container_state.py bind", container_workflow)
        self.assertLess(
            container_workflow.index("release_container_state.py bind"),
            container_workflow.index("Retain the digest-addressed candidate"),
        )
        self.assertIn("release-ledger-${LEDGER_SHA256}", container_workflow)
        self.assertIn('mirror_image="ghcr.io/antflydb/antfly"', container_workflow)
        self.assertIn(
            "recorded container digest is missing from both retention registries",
            container_workflow,
        )
        self.assertIn("expected_digest:", container_workflow)
        self.assertNotIn("registryctl.py container-ensure", container_workflow)
        self.assertNotIn(
            'crane digest "$destination" 2>/dev/null || true', container_workflow
        )
        self.assertIn(
            "ref: ${{ inputs.promotion_controller_commit }}", container_workflow
        )
        self.assertNotIn("ref: ${{ inputs.source_commit }}", container_workflow)
        self.assertIn("release-build-${{ github.run_id }}", container_workflow)
        self.assertNotIn("Commit stable container aliases last", container_workflow)
        runtime_cloudbuild = (REPO_ROOT / "zig" / "cloudbuild.runtime.yaml").read_text()
        manifest_cloudbuild = (
            REPO_ROOT / "zig" / "cloudbuild.manifest.yaml"
        ).read_text()
        self.assertIn("moby/buildkit@sha256:", runtime_cloudbuild)
        self.assertIn("gcr.io/cloud-builders/gsutil@sha256:", runtime_cloudbuild)
        self.assertIn("gcr.io/cloud-builders/docker@sha256:", runtime_cloudbuild)
        self.assertIn("gcr.io/cloud-builders/docker@sha256:", manifest_cloudbuild)
        self.assertIn("needs: prepare-release-promotion", release_workflow)
        self.assertEqual(release_workflow.count("group: antfly-release-storage"), 2)
        workflow_header = release_workflow.split("\njobs:", 1)[0]
        self.assertNotIn("concurrency:", workflow_header)
        self.assertIn("release_channel_state.py begin", release_workflow)
        self.assertIn("release_channel_state.py preflight", release_workflow)
        self.assertIn("release_channel_state.py finish", release_workflow)
        self.assertIn("discover_channel_tag.py require", release_workflow)
        self.assertIn("release_container_state.py resolve", release_workflow)
        self.assertIn("preflight-release-channel:", release_workflow)
        self.assertIn("preflight-publication:", release_workflow)
        self.assertIn("prepare_npm_promotion.py", release_workflow)
        self.assertIn(
            "npm_version: ${{ steps.registry-identity.outputs.npm_version }}",
            release_workflow,
        )
        self.assertIn(
            "python_version: ${{ steps.registry-identity.outputs.python_version }}",
            release_workflow,
        )
        self.assertIn(
            "container_tag: ${{ steps.registry-identity.outputs.container_tag }}",
            release_workflow,
        )
        self.assertIn(
            "Bind authenticated registry versions to the sealed ledger",
            release_workflow,
        )
        self.assertEqual(release_workflow.count("--exact-assets"), 2)
        self.assertIn("recover_release_payload.py", release_workflow)
        self.assertIn('--expected-version "$PYTHON_PACKAGE_VERSION"', release_workflow)
        self.assertIn(
            "VERSION: ${{ needs.prepare-release-promotion.outputs.npm_version }}",
            release_workflow,
        )
        self.assertEqual(
            release_workflow.count("registryctl.py container-version-check"), 4
        )
        self.assertEqual(
            release_workflow.count("registryctl.py container-version \\"), 4
        )
        stage_job = release_workflow.split("  stage-container:", 1)[1].split(
            "\n  preflight-release-channel:", 1
        )[0]
        channel_preflight_job = release_workflow.split(
            "  preflight-release-channel:", 1
        )[1].split("\n  preflight-publication:", 1)[0]
        begin_job = release_workflow.split("  begin-release-channel:", 1)[1].split(
            "\n  promote-channel-aliases:", 1
        )[0]
        pypi_job = release_workflow.split("  publish-cli-pypi:", 1)[1].split(
            "\n  publish-cli-npm:", 1
        )[0]
        npm_job = release_workflow.split("  publish-cli-npm:", 1)[1].split(
            "\n  prepare-zig-homebrew:", 1
        )[0]
        promote_job = release_workflow.split("  promote-channel-aliases:", 1)[1].split(
            "\n  publish-github-release:", 1
        )[0]
        complete_job = release_workflow.split("  complete-release-channel:", 1)[1]
        self.assertIn("- preflight-release-channel", stage_job)
        self.assertIn("release_channel_state.py preflight", channel_preflight_job)
        self.assertNotIn(
            '--container-digest "$CONTAINER_DIGEST"', channel_preflight_job
        )
        self.assertIn("- preflight-publication", begin_job)
        self.assertIn("- begin-release-channel", pypi_job)
        self.assertIn("- begin-release-channel", npm_job)
        self.assertIn("group: antfly-release-storage", begin_job)
        self.assertNotIn("environment:", begin_job)
        self.assertIn('--container-digest "$CONTAINER_DIGEST"', begin_job)
        self.assertNotIn("environment:", promote_job)
        self.assertNotIn("environment:", complete_job)
        self.assertIn('--channel "$CHANNEL"', release_workflow)
        self.assertIn("Commit digest-pinned container version", release_workflow)
        self.assertIn('--container-digest "$CONTAINER_DIGEST"', release_workflow)
        self.assertIn("Commit the stable Homebrew formula", release_workflow)
        self.assertIn(
            "CHANNEL: ${{ needs.begin-release-channel.outputs.channel }}",
            release_workflow,
        )
        self.assertNotIn("npm dist-tag add", release_workflow)
        self.assertNotIn(
            "contains(needs.prepare-release-promotion.outputs.version", release_workflow
        )

        channels = channel_policy["channels"]
        self.assertEqual(set(channels), {"stable", "next", "nightly"})
        self.assertEqual(channels["stable"]["npm_tag"], "latest")
        self.assertTrue(channels["stable"]["publish_npm"])
        self.assertEqual(channels["next"]["container_alias"], "next")
        self.assertTrue(channels["next"]["publish_npm"])
        self.assertEqual(channels["nightly"]["object_alias"], "nightly")
        self.assertFalse(channels["nightly"]["publish_npm"])
        self.assertEqual(channels["nightly"]["bootstrap_sources"], ["object-storage"])
        self.assertEqual(channels["nightly"]["retention"]["minimum_count"], 10)
        self.assertFalse(channels["nightly"]["publish_pypi"])
        self.assertFalse(channels["nightly"]["publish_homebrew"])
        self.assertEqual(channels["nightly"]["github_release"], "none")
        self.assertEqual(
            channels["stable"]["object_static_files"],
            {"install.sh": "scripts/release/install_bootstrap.sh"},
        )
        self.assertFalse(channels["next"]["object_static_files"])
        self.assertFalse(channels["nightly"]["object_static_files"])
        self.assertIn("workflow_dispatch:", nightly_workflow)
        self.assertNotIn("schedule:", nightly_workflow)
        self.assertNotIn("push:", nightly_workflow)
        self.assertIn("v0.0.0-dev.${GITHUB_RUN_ID}", nightly_workflow)
        self.assertIn("name: antfly-build-request", nightly_workflow)
        self.assertIn('test "$channel" = nightly', build_controller_workflow)
        self.assertIn("schedule:", release_gc_workflow)
        self.assertEqual(release_gc_workflow.count("            --apply\n"), 1)
        self.assertEqual(release_gc_workflow.count("--apply-plan"), 1)
        self.assertEqual(release_gc_workflow.count("--approved-plan"), 1)
        self.assertIn("name: release-gc-plan", release_gc_workflow)
        self.assertNotIn("environment: container-publish", release_gc_workflow)
        self.assertEqual(release_gc_workflow.count("environment: release-promotion"), 1)
        self.assertIn("github_environment.py check", release_gc_workflow)
        self.assertIn(
            'test "$GITHUB_REF" = "refs/heads/$DEFAULT_BRANCH"',
            release_gc_workflow,
        )
        self.assertIn("group: antfly-release-storage", release_gc_workflow)
        self.assertIn("uses: google-github-actions/setup-gcloud@", release_gc_workflow)
        self.assertLess(
            release_gc_workflow.index("environment: release-promotion"),
            release_gc_workflow.index("group: antfly-release-storage"),
        )
        environments = environment_policy["environments"]
        self.assertEqual(set(environments), {"container-publish", "release-promotion"})
        container_refs = {
            (policy["name"], policy["type"])
            for policy in environments["container-publish"]["branch_policies"]
        }
        release_refs = {
            (policy["name"], policy["type"])
            for policy in environments["release-promotion"]["branch_policies"]
        }
        self.assertNotIn(("main", "branch"), container_refs)
        self.assertTrue(container_refs)
        self.assertTrue(all(policy_type == "tag" for _, policy_type in container_refs))
        self.assertEqual(release_refs, {("main", "branch")})
        sdk_npm_workflow = (
            REPO_ROOT / ".github" / "workflows" / "ts-npm-publish.yml"
        ).read_text()
        self.assertIn("steps.toolchain.outputs.npm_version", sdk_npm_workflow)
        self.assertIn('npm install -g "npm@$NPM_VERSION"', sdk_npm_workflow)
        sdks_ci_workflow = (
            REPO_ROOT / ".github" / "workflows" / "sdks-ci.yml"
        ).read_text()
        for workflow, expected_jobs in (
            (sdks_ci_workflow, 2),
            (sdk_npm_workflow, 1),
        ):
            lines = workflow.splitlines()
            node_steps = [
                index
                for index, line in enumerate(lines)
                if "uses: actions/setup-node@" in line
            ]
            pnpm_steps = [
                index
                for index, line in enumerate(lines)
                if "uses: pnpm/action-setup@" in line
            ]
            self.assertEqual(len(node_steps), expected_jobs)
            self.assertEqual(len(pnpm_steps), expected_jobs)
            self.assertTrue(
                all(
                    node_step < pnpm_step
                    for node_step, pnpm_step in zip(node_steps, pnpm_steps)
                ),
                "Node must be installed before pnpm so self-hosted runners "
                "avoid the native bootstrap",
            )
        platform_publish = [
            release_workflow.index(f'@antfly/cli-{name} "$VERSION"')
            for name in ("darwin-arm64", "linux-arm64", "linux-x64")
        ]
        selector_publish = release_workflow.index('@antfly/cli "$VERSION"')
        self.assertLess(max(platform_publish), selector_publish)

        cloud_build = (REPO_ROOT / "zig" / "cloudbuild.runtime.yaml").read_text()
        self.assertIn("_ARTIFACT_URI: __required__", cloud_build)
        self.assertIn(
            "_ARTIFACT_URI must be an explicit gs:// GNU runtime artifact", cloud_build
        )

        release_design = (REPO_ROOT / "RELEASE.md").read_text()
        self.assertIn(f"glibc {minimum_glibc}", release_design)
        for platform in package_cli_release.PLATFORMS:
            expected_archive = package_cli_release.archive_name("<version>", platform)
            self.assertIn(f"`{expected_archive}`", release_design)

    def test_release_scripting_target_discovers_the_complete_suite(self) -> None:
        makefile = (REPO_ROOT / "Makefile").read_text()
        test_script = (REPO_ROOT / "scripts" / "release" / "test.sh").read_text()
        workflow = (REPO_ROOT / ".github" / "workflows" / "sdks-ci.yml").read_text()
        check_script = (REPO_ROOT / "scripts" / "ci" / "check.sh").read_text()

        self.assertIn("run: scripts/ci/check.sh release", workflow)
        self.assertNotIn("run: make ", workflow)
        self.assertIn("uses: mlugg/setup-zig@", workflow)
        self.assertIn("steps.toolchain.outputs.zig_version", workflow)
        self.assertIn("xz-utils", workflow)
        self.assertIn('"$repo_root/scripts/release/test.sh"', check_script)
        self.assertIn("release-scripting-test:", makefile)
        self.assertIn("scripts/release/test.sh", makefile)
        self.assertIn(
            "python3 -m unittest discover -s scripts/packaging -p 'test_*.py'",
            test_script,
        )
        self.assertIn(
            "python3 -m unittest discover -s scripts/release -p 'test_*.py'",
            test_script,
        )
        self.assertIn("sh -n scripts/release/install_bootstrap.sh", test_script)

    def test_cli_platforms_select_libc_specific_linux_archives(self) -> None:
        names = {
            platform.key: package_cli_release.archive_name("1.2.3", platform)
            for platform in package_cli_release.PLATFORMS
        }
        self.assertEqual(names["darwin-arm64"], "antfly_1.2.3_Darwin_arm64.tar.gz")
        self.assertEqual(
            names["linux-arm64-gnu"], "antfly_1.2.3_Linux_arm64_gnu.tar.gz"
        )
        self.assertEqual(names["linux-x64-gnu"], "antfly_1.2.3_Linux_x86_64_gnu.tar.gz")
        self.assertEqual(names["linux-arm64-musl"], "antfly_1.2.3_Linux_arm64.tar.gz")
        self.assertEqual(names["linux-x64-musl"], "antfly_1.2.3_Linux_x86_64.tar.gz")

    def test_npm_platform_manifests_declare_the_expected_libc(self) -> None:
        expected_dependencies = set()
        for platform in package_cli_release.PACKAGE_PLATFORMS:
            package_cli_release.validate_npm_package(REPO_ROOT, platform)
            expected_dependencies.add(f"@antfly/{platform.npm_package_dir}")

        musl_platforms = [
            platform
            for platform in package_cli_release.PLATFORMS
            if platform.key.endswith("-musl")
        ]
        self.assertEqual(len(musl_platforms), 2)
        self.assertTrue(
            all(platform.npm_package_dir is None for platform in musl_platforms)
        )

        top_level = json.loads(
            (REPO_ROOT / "ts" / "packages" / "cli" / "package.json").read_text()
        )
        self.assertEqual(set(top_level["optionalDependencies"]), expected_dependencies)

    def test_npm_publish_is_retry_safe_and_rejects_content_drift(self) -> None:
        helper = REPO_ROOT / "scripts" / "packaging" / "publish_npm_package.sh"
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            fake_bin = root / "bin"
            fake_bin.mkdir()
            npm = fake_bin / "npm"
            npm.write_text('#!/bin/sh\nprintf \'%s\\n\' "$*" >> "$FAKE_NPM_LOG"\n')
            npm.chmod(0o755)
            python = fake_bin / "python3"
            python.write_text(
                "#!/bin/sh\n"
                'case "$*" in\n'
                "  *npm-integrity*) printf '%s\\n' \"${FAKE_NPM_INTEGRITY:-}\" ;;\n"
                "  *npm-tag*)\n"
                '    if [ -n "${FAKE_NPM_TAG_FILE:-}" ]; then\n'
                '      cat "$FAKE_NPM_TAG_FILE"\n'
                "    else printf '%s\\n' \"${FAKE_NPM_TAG:-}\"; fi ;;\n"
                "  *) exit 2 ;;\n"
                "esac\n"
            )
            python.chmod(0o755)
            tarball = root / "package.tgz"
            tarball.write_bytes(b"npm package")
            digest = base64.b64encode(
                hashlib.sha512(tarball.read_bytes()).digest()
            ).decode()
            integrity = f"sha512-{digest}"
            log = root / "npm.log"
            env = {
                **os.environ,
                "PATH": f"{fake_bin}:{os.environ['PATH']}",
                "FAKE_NPM_LOG": str(log),
                "FAKE_NPM_INTEGRITY": integrity,
                "FAKE_NPM_TAG": "1.2.3",
            }
            command = [
                "sh",
                str(helper),
                "@antfly/cli",
                "1.2.3",
                "latest",
                str(tarball),
            ]

            subprocess.run(command, check=True, env=env, capture_output=True, text=True)
            self.assertFalse(log.exists())

            env["FAKE_NPM_INTEGRITY"] = "sha512-different"
            mismatch = subprocess.run(
                command, env=env, capture_output=True, text=True, check=False
            )
            self.assertNotEqual(mismatch.returncode, 0)
            self.assertIn("exists with different contents", mismatch.stderr)

            env["FAKE_NPM_INTEGRITY"] = integrity
            env["FAKE_NPM_TAG"] = "1.2.2"
            alias_drift = subprocess.run(
                command, env=env, capture_output=True, text=True, check=False
            )
            self.assertNotEqual(alias_drift.returncode, 0)
            self.assertIn("dist-tag latest points", alias_drift.stderr)

            env["FAKE_NPM_INTEGRITY"] = ""
            env["FAKE_NPM_TAG"] = "1.2.3"
            subprocess.run(command, check=True, env=env, capture_output=True, text=True)
            self.assertIn("publish", log.read_text())

            # Model a successful publish whose tag is initially stale, then
            # becomes visible on the next read. No real waits or registry writes.
            tag_file = root / "tag"
            tag_file.write_text("1.2.2\n")
            env["FAKE_NPM_TAG_FILE"] = str(tag_file)
            sleep = fake_bin / "sleep"
            sleep.write_text('#!/bin/sh\nprintf "1.2.3\\n" > "$FAKE_NPM_TAG_FILE"\n')
            sleep.chmod(0o755)
            log.write_text("")
            propagated = subprocess.run(
                command, check=True, env=env, capture_output=True, text=True
            )
            self.assertIn("waiting for npm dist-tag", propagated.stderr)
            self.assertEqual(len(log.read_text().splitlines()), 1)

            # A tag that never converges still fails after a bounded wait and
            # never triggers another publish or an unauthorized dist-tag repair.
            tag_file.write_text("1.2.2\n")
            sleep.write_text("#!/bin/sh\nexit 0\n")
            log.write_text("")
            stale = subprocess.run(
                command, env=env, capture_output=True, text=True, check=False
            )
            self.assertNotEqual(stale.returncode, 0)
            self.assertIn("after 30 checks", stale.stderr)
            self.assertEqual(stale.stderr.count("waiting for npm dist-tag"), 29)
            self.assertEqual(len(log.read_text().splitlines()), 1)

    def test_python_and_npm_packages_preserve_cabi_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            repo = root / "repo"
            extracted = root / "extracted"
            out = root / "out"
            archive_dir = root / "archives"
            archive_dir.mkdir()

            platform = package_cli_release.PLATFORMS[1]
            write_release_archive(
                archive_dir,
                "1.2.3",
                platform.release_os,
                platform.release_arch,
                platform.release_variant,
            )

            package_dir = repo / "ts" / "packages" / platform.npm_package_dir
            package_dir.mkdir(parents=True)
            (package_dir / "package.json").write_text(
                json.dumps(
                    {
                        "name": f"@antfly/{platform.npm_package_dir}",
                        "version": "0.0.0",
                        "files": ["bin", "include", "lib", "share", "README.md"],
                        "libc": [platform.npm_libc],
                    }
                )
                + "\n"
            )
            (repo / "zig" / "pkg" / "antfly" / "antfarm").mkdir(parents=True)
            (repo / "zig" / "pkg" / "antfly" / "antfarm" / "index.html").write_text(
                "antfarm\n"
            )
            (repo / "py" / "packages" / "cli" / "src" / "antfly_cli").mkdir(
                parents=True
            )
            (
                repo / "py" / "packages" / "cli" / "src" / "antfly_cli" / "__init__.py"
            ).write_text("def main(): return 0\n")
            (repo / "py" / "packages" / "cli" / "pyproject.toml").write_text(
                '[project]\nname = "antfly-cli"\nrequires-python = ">=3.11"\n'
            )

            package_cli_release.extract_archive(
                archive_dir, "1.2.3", platform, extracted
            )
            package_cli_release.copy_antfarm(repo, extracted)
            package_cli_release.populate_npm_package(repo, platform, extracted)

            npm_package = repo / "ts" / "packages" / platform.npm_package_dir
            self.assertEqual(
                (npm_package / "include" / "antfly.h").read_text(),
                "/* antfly header */\n",
            )
            self.assertEqual(
                (npm_package / "lib" / "libantfly.so").read_text(), "antfly library\n"
            )

            wheel = package_cli_release.package_python_wheel(
                repo, out, "1.2.3", platform, extracted
            )
            with zipfile.ZipFile(wheel) as zf:
                names = set(zf.namelist())
                metadata = zf.read("antfly_cli-1.2.3.dist-info/METADATA").decode()
            self.assertIn("antfly_cli/include/antfly.h", names)
            self.assertIn("antfly_cli/lib/libantfly.so", names)
            self.assertIn("antfly_cli/share/antfly/asset.txt", names)
            self.assertIn("Requires-Python: >=3.11", metadata)

    def test_homebrew_formula_installs_cabi_artifacts(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            archive_dir = root / "archives"
            archive_dir.mkdir()
            write_release_archive(archive_dir, "1.2.3", "Darwin", "arm64")
            write_release_archive(archive_dir, "1.2.3", "Linux", "arm64", "gnu")
            write_release_archive(archive_dir, "1.2.3", "Linux", "x86_64", "gnu")

            formula = root / "Formula" / "antfly.rb"
            subprocess.run(
                [
                    sys.executable,
                    str(PACKAGING_DIR / "render_homebrew_antfly_formula.py"),
                    "--version",
                    "1.2.3",
                    "--tag",
                    "v1.2.3",
                    "--archive-dir",
                    str(archive_dir),
                    "--out",
                    str(formula),
                ],
                cwd=REPO_ROOT,
                check=True,
            )

            rendered = formula.read_text()
            self.assertIn('version "1.2.3"', rendered)
            self.assertIn("version_scheme 1", rendered)
            self.assertIn('system "./smoke"', rendered)
            self.assertIn("antfly_1.2.3_Darwin_arm64.tar.gz", rendered)
            self.assertIn("antfly_1.2.3_Linux_arm64_gnu.tar.gz", rendered)
            self.assertIn("antfly_1.2.3_Linux_x86_64_gnu.tar.gz", rendered)
            self.assertIn(
                'include.install Dir["include/*"] if Dir.exist?("include")', rendered
            )
            self.assertIn('lib.install Dir["lib/*"] if Dir.exist?("lib")', rendered)
            self.assertIn(
                '(share/"antfly").install Dir["share/antfly/*"] if Dir.exist?("share/antfly")',
                rendered,
            )
            self.assertIn(
                'bash_completion.install "completions/antfly.bash" => "antfly"',
                rendered,
            )
            self.assertIn(
                'zsh_completion.install "completions/antfly.zsh" => "_antfly"', rendered
            )
            self.assertIn('fish_completion.install "completions/antfly.fish"', rendered)


if __name__ == "__main__":
    unittest.main()
