---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: antfly-operator-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - antfly.io
  resources:
  - antflybackups
  - antflyclusters
  - antflyrestores
  - termitepools
  - termiteroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - antfly.io
  resources:
  - antflybackups/finalizers
  - antflyclusters/finalizers
  - antflyrestores/finalizers
  - termitepools/finalizers
  - termiteroutes/finalizers
  verbs:
  - update
- apiGroups:
  - antfly.io
  resources:
  - antflybackups/status
  - antflyclusters/status
  - antflyrestores/status
  - termitepools/status
  - termiteroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - antfly.io
  resources:
  - externaltermitepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
