// Copyright 2026 Antfly, Inc.
// SPDX-License-Identifier: Elastic-2.0

//! Stable error transport for independently generated runtime archives.
//!
//! Zig error integers and error-union layouts are compilation-local.  Runtime
//! archives therefore exchange only these explicit C-layout values.  `Code`
//! carries the language-neutral behavior class; `Detail` preserves the small
//! set of domain outcomes that callers intentionally distinguish.

const std = @import("std");

pub const abi_version: u32 = 1;

pub const Code = enum(c_int) {
    ok = 0,
    out_of_memory,
    invalid_argument,
    not_found,
    already_exists,
    conflict,
    unauthorized,
    forbidden,
    unavailable,
    retryable,
    timeout,
    cancelled,
    unsupported,
    corrupt,
    internal,
};

pub const Detail = enum(c_int) {
    none = 0,
    out_of_memory,
    invalid_argument,
    invalid_arguments,
    invalid_request,
    invalid_query_request,
    invalid_filter_query_request,
    invalid_exclusion_query_request,
    invalid_batch_request,
    invalid_create_table_request,
    unsupported_create_table_request,
    invalid_schema_update_request,
    invalid_manifest,
    invalid_table_file,
    invalid_txn_record,
    not_found,
    file_not_found,
    table_not_found,
    table_already_exists,
    index_not_found,
    model_not_found,
    secret_not_found,
    user_not_found,
    unknown_group,
    txn_not_found,
    conflict,
    decision_conflict,
    table_transition_active,
    extension_owned_object,
    restore_intent_conflict,
    unauthorized,
    forbidden,
    unavailable,
    write_unavailable,
    read_unavailable,
    read_requires_primary,
    storage_read_temporarily_unavailable,
    resource_request_too_large,
    resource_temporarily_unavailable,
    restore_job_persistence_unavailable,
    backpressured,
    dense_repair_backpressure,
    outcome_unknown,
    commit_propagation_incomplete,
    commit_decision_unknown,
    committed_pending,
    write_outcome_unknown,
    doc_identity_unavailable,
    ha_read_only_standby,
    ha_promoted_standby_requires_primary_open,
    ha_fenced_primary,
    internal_failure,
    not_leader,
    topology_changed,
    identity_read_generation_changed,
    doc_identity_namespace_mismatch,
    table_generation_changed,
    generation_durability_uncertain,
    index_rebuilding,
    table_visibility_timeout,
    writer_locked,
    lsm_root_writer_already_open,
    unexpected_http_status,
    method_not_allowed,
    unsupported,
    unsupported_operation,
    unsupported_query_request,
    unsupported_filter_query_request,
    unsupported_exclusion_query_request,
    unsupported_sync_level,
    unsupported_exact_sort,
    unsupported_version,
    timeout,
    connection_timeout,
    connection_timed_out,
    cancelled,
    canceled,
    connection_refused,
    connection_reset_by_peer,
    network_unreachable,
    host_unreachable,
    temporary_name_server_failure,
    name_server_failure,
    query_candidate_budget_exceeded,
    query_embedding_input_too_large,
    query_embedding_overloaded,
    embed_rate_limited,
    embed_transient_failure,
    embed_upstream_failure,
    embedding_probe_unavailable,
    invalid_embedding_response,
    invalid_embedding_dimensions,
    backup_already_exists,
    backup_manifest_too_large,
    backup_integrity_failure,
    backup_artifact_integrity_mismatch,
    backup_repository_busy,
    invalid_backup_request,
    restore_durability_pending,
    restore_durability_confirmed,
    corrupt_input,
    corrupted,
    corrupt_restore_job_store,
    table_block_checksum_mismatch,
    value_too_long,
    unsupported_platform,
    // Append-only: numeric Detail values are part of the stable C ABI.
    unsupported_transform_operation,
    ha_read_requires_primary,
    ha_read_wait_for_apply,
    ha_read_wait_for_metadata,
    persistent_descriptor_admission_exhausted,
    invalid_graph_edges,
    invalid_table_index_metadata,
    transaction_begin_failed,
    abort_decision_not_durable,
    commit_visibility_not_satisfied,
    leader_unavailable,
    raft_batch_write_outcome_unknown,
    raft_batch_write_partial_outcome,
    enrichment_retry_in_progress,
    resource_budget_exceeded,
    text_merge_backpressure_timeout,
    text_merge_backpressure_unavailable,
    text_merge_runtime_shutdown,
    background_owner_closing,
    invalid_enrichment_config,
    restore_identity_mismatch,
    table_read_churn,
    unsupported_multi_range_table,
    proposal_dropped,
    leader_transfer_in_progress,
    metadata_linearizable_read_timeout,
    reconcile_lease_not_held,
    enrichment_not_found,
    invalid_extension_enrichment,
    conflicting_enrichment_config,
    invalid_create_index_request,
    unsupported_backup_migration_state,
    unsupported_backup_format,
    extension_already_installed,
    extension_not_installed,
    extension_disabled,
    extension_lifecycle_busy,
    extension_visibility_timeout,
    dependent_extension_exists,
    required_extension_not_installed,
    missing_extension_package,
    package_not_found,
    package_version_mismatch,
    unsupported_package_kind,
    invalid_extension_shape,
    unsupported_extension_scope,
    invalid_extension_lifecycle_request,
    restore_job_fenced,
    restore_job_capacity_exceeded,
    restore_job_record_too_large,
    too_many_restore_tables,
    duplicate_restore_table_name,
    idempotency_conflict,
    invalid_idempotency_key,
    async_restore_unavailable,
    background_runtime_unavailable,
    backup_staging_unavailable,
    backup_artifact_missing,
    backup_integrity_missing,
    backup_attempt_lease_lost,
    background_owner_closed,
    restore_scheduling_capacity,
    restore_wait_interrupted,
    api_key_expired,
    api_key_invalid,
    api_key_not_found,
    auth_row_filter_no_match,
    backup_maintenance_queue_full,
    backup_maintenance_unavailable,
    connection_not_found,
    embed_request_failed,
    empty_embedding_response,
    empty_name,
    end_of_stream,
    foreign_query_failed,
    invalid_api_key_request,
    invalid_api_server_config,
    invalid_ard_agents_request,
    invalid_ard_search_request,
    invalid_backup_id,
    invalid_backup_list_limit,
    invalid_character,
    invalid_create_user_request,
    invalid_detail,
    invalid_duration,
    invalid_enrichment_request,
    invalid_eval_request,
    invalid_identifier,
    invalid_index_request,
    invalid_job_id,
    invalid_json_object,
    invalid_linear_merge_request,
    invalid_metadata,
    invalid_password,
    invalid_password_update_request,
    invalid_path_parameter,
    invalid_permission_type,
    invalid_query_builder_request,
    invalid_read_consistency,
    invalid_resource_type,
    invalid_restore_job_list_cursor,
    invalid_restore_job_list_limit,
    invalid_restore_job_list_phase,
    invalid_restore_job_list_scope,
    invalid_retrieval_agent_request,
    invalid_role,
    invalid_secret_key,
    invalid_transaction_commit_request,
    invalid_transaction_session_record,
    maintenance_busy,
    maintenance_history_full,
    maintenance_job_id_exhausted,
    member_table_outside_scope,
    missing_field,
    missing_location,
    missing_resource,
    missing_resource_type,
    missing_role,
    no_tables,
    path_already_exists,
    privilege_escalation,
    probe_unavailable,
    role_not_found,
    row_filter_not_found,
    savepoint_limit_exceeded,
    session_lease_lost,
    session_limit_exceeded,
    session_record_too_large,
    stale_index_repair_control,
    syntax_error,
    too_many_runtime_statuses,
    transaction_commit_request_mismatch,
    transaction_commit_sealed,
    tree_root_set_too_large,
    unrequested_capability_grant,
    unsupported_aggregate,
    unsupported_backup_location,
    unsupported_manifest_api_version,
    unsupported_object_kind_for_v1,
    unsupported_retrieval_agent_request,
    unsupported_source_kind,
    update_path_not_found,
    user_exists,
    // Generic admission outcomes used by runtime callbacks. Keep these
    // append-only so independently generated archives retain wire stability.
    queue_full,
    resource_limit_exceeded,
    body_too_large,
    body_capacity_exceeded,
    body_read_failed,
    // Stable provider-boundary outcomes. Inference internals may grow new
    // unit-private errors without making those failures look transient to
    // callers that cannot reconstruct their compilation-local identities.
    inference_provider_failure,
    kernel_jit_required_dynamic_load,
    unexpected_token,
    enrichment_wait_canceled,
    enrichment_wait_timeout,
    enrichment_worker_failed,
    // A locally committed RemoteApply write can cross the independently
    // generated storage/runtime boundary before its standby acknowledgement
    // is available. Preserve the exact reason so the public API can return
    // its explicit pending-durability contract instead of a generic 500.
    ha_sync_commit_would_block,
    ha_sync_commit_wait_limit_exceeded,
    ha_sync_commit_wait_missing_context,
    ha_sync_commit_wait_standby_not_in_policy,
    deadline_exceeded,
    pre_decision_deadline_exceeded,
    graph_distinct_budget_exceeded,
    graph_anchor_filter_requires_index,
    graph_match_operation_limit_exceeded,
    graph_cross_range_mode_unsupported,
    graph_work_budget_exceeded,
    graph_min_weight_domain_violation,
    graph_max_weight_domain_violation,
    graph_path_weight_overflow,
};

pub const Status = extern struct {
    // Keep the wire fields as integers so a newer peer's enum value can be
    // rejected without constructing an invalid exhaustive Zig enum.
    code: c_int = @intFromEnum(Code.ok),
    detail: c_int = @intFromEnum(Detail.none),

    pub const ok: Status = .{};

    pub fn isOk(self: Status) bool {
        return self.code == @intFromEnum(Code.ok);
    }
};

pub fn statusFromError(err: anyerror) Status {
    return switch (err) {
        error.OutOfMemory => status(.out_of_memory, .out_of_memory),
        error.InvalidArgument => status(.invalid_argument, .invalid_argument),
        error.InvalidArguments => status(.invalid_argument, .invalid_arguments),
        error.InvalidRequest => status(.invalid_argument, .invalid_request),
        error.InvalidQueryRequest => status(.invalid_argument, .invalid_query_request),
        error.InvalidFilterQueryRequest => status(.invalid_argument, .invalid_filter_query_request),
        error.InvalidExclusionQueryRequest => status(.invalid_argument, .invalid_exclusion_query_request),
        error.InvalidBatchRequest => status(.invalid_argument, .invalid_batch_request),
        error.InvalidCreateTableRequest => status(.invalid_argument, .invalid_create_table_request),
        error.UnsupportedCreateTableRequest => status(.unsupported, .unsupported_create_table_request),
        error.InvalidSchemaUpdateRequest => status(.invalid_argument, .invalid_schema_update_request),
        error.InvalidManifest => status(.invalid_argument, .invalid_manifest),
        error.InvalidTableFile => status(.invalid_argument, .invalid_table_file),
        error.InvalidTxnRecord => status(.invalid_argument, .invalid_txn_record),
        error.NotFound => status(.not_found, .not_found),
        error.FileNotFound => status(.not_found, .file_not_found),
        error.TableNotFound => status(.not_found, .table_not_found),
        error.TableAlreadyExists => status(.already_exists, .table_already_exists),
        error.IndexNotFound => status(.not_found, .index_not_found),
        error.ModelNotFound => status(.not_found, .model_not_found),
        error.SecretNotFound => status(.not_found, .secret_not_found),
        error.UserNotFound => status(.not_found, .user_not_found),
        error.UnknownGroup => status(.not_found, .unknown_group),
        error.TxnNotFound => status(.not_found, .txn_not_found),
        error.Conflict => status(.conflict, .conflict),
        error.DecisionConflict => status(.conflict, .decision_conflict),
        error.TableTransitionActive => status(.conflict, .table_transition_active),
        error.ExtensionOwnedObject => status(.conflict, .extension_owned_object),
        error.RestoreIntentConflict => status(.conflict, .restore_intent_conflict),
        error.Unauthorized => status(.unauthorized, .unauthorized),
        error.Forbidden => status(.forbidden, .forbidden),
        error.Unavailable => status(.unavailable, .unavailable),
        error.WriteUnavailable => status(.unavailable, .write_unavailable),
        error.ReadUnavailable => status(.unavailable, .read_unavailable),
        error.ReadRequiresPrimary => status(.unavailable, .read_requires_primary),
        error.HAReadRequiresPrimary => status(.unavailable, .ha_read_requires_primary),
        error.HAReadWaitForApply => status(.retryable, .ha_read_wait_for_apply),
        error.HAReadWaitForMetadata => status(.retryable, .ha_read_wait_for_metadata),
        error.StorageReadTemporarilyUnavailable => status(.retryable, .storage_read_temporarily_unavailable),
        error.PersistentDescriptorAdmissionExhausted => status(.retryable, .persistent_descriptor_admission_exhausted),
        error.ResourceRequestTooLarge => status(.invalid_argument, .resource_request_too_large),
        error.ResourceTemporarilyUnavailable => status(.retryable, .resource_temporarily_unavailable),
        error.RestoreJobPersistenceUnavailable => status(.unavailable, .restore_job_persistence_unavailable),
        error.Backpressured => status(.retryable, .backpressured),
        error.DenseRepairBackpressure => status(.retryable, .dense_repair_backpressure),
        error.OutcomeUnknown => status(.retryable, .outcome_unknown),
        error.CommitPropagationIncomplete => status(.retryable, .commit_propagation_incomplete),
        error.CommitDecisionUnknown => status(.retryable, .commit_decision_unknown),
        error.CommitVisibilityNotSatisfied => status(.retryable, .commit_visibility_not_satisfied),
        error.TransactionBeginFailed => status(.unavailable, .transaction_begin_failed),
        error.AbortDecisionNotDurable => status(.unavailable, .abort_decision_not_durable),
        error.CommittedPending => status(.retryable, .committed_pending),
        error.WriteOutcomeUnknown => status(.retryable, .write_outcome_unknown),
        error.RaftBatchWriteOutcomeUnknown => status(.retryable, .raft_batch_write_outcome_unknown),
        error.RaftBatchWritePartialOutcome => status(.retryable, .raft_batch_write_partial_outcome),
        error.DocIdentityUnavailable => status(.retryable, .doc_identity_unavailable),
        error.HAReadOnlyStandby => status(.unavailable, .ha_read_only_standby),
        error.HAPromotedStandbyRequiresPrimaryOpen => status(.unavailable, .ha_promoted_standby_requires_primary_open),
        error.HAFencedPrimary => status(.conflict, .ha_fenced_primary),
        error.HASyncCommitWouldBlock => status(.unavailable, .ha_sync_commit_would_block),
        error.HASyncCommitWaitLimitExceeded => status(.unavailable, .ha_sync_commit_wait_limit_exceeded),
        error.HASyncCommitWaitMissingContext => status(.unavailable, .ha_sync_commit_wait_missing_context),
        error.HASyncCommitWaitStandbyNotInPolicy => status(.unavailable, .ha_sync_commit_wait_standby_not_in_policy),
        error.InternalFailure => status(.internal, .internal_failure),
        error.NotLeader => status(.retryable, .not_leader),
        error.LeaderUnavailable => status(.unavailable, .leader_unavailable),
        error.TopologyChanged => status(.retryable, .topology_changed),
        error.IdentityReadGenerationChanged => status(.conflict, .identity_read_generation_changed),
        error.DocIdentityNamespaceMismatch => status(.conflict, .doc_identity_namespace_mismatch),
        error.TableGenerationChanged => status(.conflict, .table_generation_changed),
        error.GenerationDurabilityUncertain => status(.retryable, .generation_durability_uncertain),
        error.IndexRebuilding => status(.retryable, .index_rebuilding),
        error.TableVisibilityTimeout => status(.timeout, .table_visibility_timeout),
        error.WriterLocked => status(.retryable, .writer_locked),
        error.LsmRootWriterAlreadyOpen => status(.retryable, .lsm_root_writer_already_open),
        error.UnexpectedHttpStatus => status(.retryable, .unexpected_http_status),
        error.MethodNotAllowed => status(.unsupported, .method_not_allowed),
        error.Unsupported => status(.unsupported, .unsupported),
        error.UnsupportedOperation => status(.unsupported, .unsupported_operation),
        error.UnsupportedTransformOperation => status(.invalid_argument, .unsupported_transform_operation),
        error.InvalidGraphEdges => status(.invalid_argument, .invalid_graph_edges),
        error.InvalidTableIndexMetadata => status(.invalid_argument, .invalid_table_index_metadata),
        error.InvalidEnrichmentConfig => status(.invalid_argument, .invalid_enrichment_config),
        error.UnsupportedQueryRequest => status(.unsupported, .unsupported_query_request),
        error.UnsupportedHierarchyGrouping => status(.unsupported, .unsupported_query_request),
        error.UnsupportedFilterQueryRequest => status(.unsupported, .unsupported_filter_query_request),
        error.UnsupportedExclusionQueryRequest => status(.unsupported, .unsupported_exclusion_query_request),
        error.UnsupportedSyncLevel => status(.unsupported, .unsupported_sync_level),
        error.UnsupportedExactSort => status(.unsupported, .unsupported_exact_sort),
        error.UnsupportedVersion => status(.unsupported, .unsupported_version),
        error.UnsupportedPlatform => status(.unsupported, .unsupported_platform),
        error.Timeout => status(.timeout, .timeout),
        error.DeadlineExceeded => status(.timeout, .deadline_exceeded),
        error.PreDecisionDeadlineExceeded => status(.timeout, .pre_decision_deadline_exceeded),
        error.ConnectionTimeout => status(.timeout, .connection_timeout),
        error.ConnectionTimedOut => status(.timeout, .connection_timed_out),
        error.Cancelled => status(.cancelled, .cancelled),
        error.Canceled => status(.cancelled, .canceled),
        error.ConnectionRefused => status(.unavailable, .connection_refused),
        error.ConnectionResetByPeer => status(.unavailable, .connection_reset_by_peer),
        error.NetworkUnreachable => status(.unavailable, .network_unreachable),
        error.HostUnreachable => status(.unavailable, .host_unreachable),
        error.TemporaryNameServerFailure => status(.retryable, .temporary_name_server_failure),
        error.NameServerFailure => status(.unavailable, .name_server_failure),
        error.QueryCandidateBudgetExceeded => status(.unavailable, .query_candidate_budget_exceeded),
        error.GraphWorkBudgetExceeded => status(.invalid_argument, .graph_work_budget_exceeded),
        error.GraphMinWeightDomainViolation => status(.invalid_argument, .graph_min_weight_domain_violation),
        error.GraphMaxWeightDomainViolation => status(.invalid_argument, .graph_max_weight_domain_violation),
        error.GraphPathWeightOverflow => status(.invalid_argument, .graph_path_weight_overflow),
        error.GraphDistinctBudgetExceeded => status(.invalid_argument, .graph_distinct_budget_exceeded),
        error.GraphAnchorFilterRequiresIndex => status(.unsupported, .graph_anchor_filter_requires_index),
        error.GraphMatchOperationLimitExceeded => status(.invalid_argument, .graph_match_operation_limit_exceeded),
        // Preserve the append-only runtime detail code while the public error
        // name reflects that unsupported exact modes are not topology-specific.
        error.GraphQueryModeUnsupported => status(.unsupported, .graph_cross_range_mode_unsupported),
        error.QueryEmbeddingInputTooLarge => status(.invalid_argument, .query_embedding_input_too_large),
        error.QueryEmbeddingOverloaded => status(.unavailable, .query_embedding_overloaded),
        error.EmbedRateLimited => status(.retryable, .embed_rate_limited),
        error.EmbedTransientFailure => status(.retryable, .embed_transient_failure),
        error.EmbedUpstreamFailure => status(.unavailable, .embed_upstream_failure),
        error.EmbeddingProbeUnavailable => status(.unavailable, .embedding_probe_unavailable),
        error.InvalidEmbeddingResponse => status(.invalid_argument, .invalid_embedding_response),
        error.InvalidEmbeddingDimensions => status(.invalid_argument, .invalid_embedding_dimensions),
        error.BackupAlreadyExists => status(.already_exists, .backup_already_exists),
        error.BackupManifestTooLarge => status(.invalid_argument, .backup_manifest_too_large),
        error.BackupIntegrityFailure => status(.corrupt, .backup_integrity_failure),
        error.BackupArtifactIntegrityMismatch => status(.corrupt, .backup_artifact_integrity_mismatch),
        error.BackupRepositoryBusy => status(.retryable, .backup_repository_busy),
        error.InvalidBackupRequest => status(.invalid_argument, .invalid_backup_request),
        error.RestoreDurabilityPending => status(.retryable, .restore_durability_pending),
        // This is still transported as an error-union failure by existing
        // callers.  Never encode it as `ok`: doing so would discard the
        // detail before the receiving unit can reconstruct the local error.
        error.RestoreDurabilityConfirmed => status(.retryable, .restore_durability_confirmed),
        error.CorruptInput => status(.corrupt, .corrupt_input),
        error.Corrupted => status(.corrupt, .corrupted),
        error.CorruptRestoreJobStore => status(.corrupt, .corrupt_restore_job_store),
        error.TableBlockChecksumMismatch => status(.corrupt, .table_block_checksum_mismatch),
        error.ValueTooLong => status(.invalid_argument, .value_too_long),
        error.EnrichmentRetryInProgress => status(.retryable, .enrichment_retry_in_progress),
        error.ResourceBudgetExceeded => status(.retryable, .resource_budget_exceeded),
        error.TextMergeBackpressureTimeout => status(.retryable, .text_merge_backpressure_timeout),
        error.TextMergeBackpressureUnavailable => status(.retryable, .text_merge_backpressure_unavailable),
        error.TextMergeRuntimeShutdown => status(.unavailable, .text_merge_runtime_shutdown),
        error.BackgroundOwnerClosing => status(.unavailable, .background_owner_closing),
        error.RestoreIdentityMismatch => status(.conflict, .restore_identity_mismatch),
        error.TableReadChurn => status(.retryable, .table_read_churn),
        error.UnsupportedMultiRangeTable => status(.unsupported, .unsupported_multi_range_table),
        error.ProposalDropped => status(.retryable, .proposal_dropped),
        error.LeaderTransferInProgress => status(.retryable, .leader_transfer_in_progress),
        error.MetadataLinearizableReadTimeout => status(.timeout, .metadata_linearizable_read_timeout),
        error.ReconcileLeaseNotHeld => status(.retryable, .reconcile_lease_not_held),
        error.EnrichmentNotFound => status(.not_found, .enrichment_not_found),
        error.InvalidExtensionEnrichment => status(.invalid_argument, .invalid_extension_enrichment),
        error.ConflictingEnrichmentConfig => status(.invalid_argument, .conflicting_enrichment_config),
        error.InvalidCreateIndexRequest => status(.invalid_argument, .invalid_create_index_request),
        error.UnsupportedBackupMigrationState => status(.invalid_argument, .unsupported_backup_migration_state),
        error.UnsupportedBackupFormat => status(.unsupported, .unsupported_backup_format),
        error.ExtensionAlreadyInstalled => status(.already_exists, .extension_already_installed),
        error.ExtensionNotInstalled => status(.not_found, .extension_not_installed),
        error.ExtensionDisabled => status(.conflict, .extension_disabled),
        error.ExtensionLifecycleBusy => status(.retryable, .extension_lifecycle_busy),
        error.ExtensionVisibilityTimeout => status(.timeout, .extension_visibility_timeout),
        error.DependentExtensionExists => status(.conflict, .dependent_extension_exists),
        error.RequiredExtensionNotInstalled => status(.conflict, .required_extension_not_installed),
        error.MissingExtensionPackage => status(.not_found, .missing_extension_package),
        error.PackageNotFound => status(.not_found, .package_not_found),
        error.PackageVersionMismatch => status(.conflict, .package_version_mismatch),
        error.UnsupportedPackageKind => status(.unsupported, .unsupported_package_kind),
        error.InvalidExtensionShape => status(.invalid_argument, .invalid_extension_shape),
        error.UnsupportedExtensionScope => status(.unsupported, .unsupported_extension_scope),
        error.InvalidExtensionLifecycleRequest => status(.invalid_argument, .invalid_extension_lifecycle_request),
        error.RestoreJobFenced => status(.conflict, .restore_job_fenced),
        error.RestoreJobCapacityExceeded => status(.unavailable, .restore_job_capacity_exceeded),
        error.RestoreJobRecordTooLarge => status(.invalid_argument, .restore_job_record_too_large),
        error.TooManyRestoreTables => status(.invalid_argument, .too_many_restore_tables),
        error.DuplicateRestoreTableName => status(.invalid_argument, .duplicate_restore_table_name),
        error.IdempotencyConflict => status(.conflict, .idempotency_conflict),
        error.InvalidIdempotencyKey => status(.invalid_argument, .invalid_idempotency_key),
        error.AsyncRestoreUnavailable => status(.unavailable, .async_restore_unavailable),
        error.BackgroundRuntimeUnavailable => status(.unavailable, .background_runtime_unavailable),
        error.BackupStagingUnavailable => status(.unavailable, .backup_staging_unavailable),
        error.BackupArtifactMissing => status(.not_found, .backup_artifact_missing),
        error.BackupIntegrityMissing => status(.corrupt, .backup_integrity_missing),
        error.BackupAttemptLeaseLost => status(.conflict, .backup_attempt_lease_lost),
        error.BackgroundOwnerClosed => status(.unavailable, .background_owner_closed),
        error.RestoreSchedulingCapacity => status(.retryable, .restore_scheduling_capacity),
        error.RestoreWaitInterrupted => status(.cancelled, .restore_wait_interrupted),
        error.ApiKeyExpired => status(.unauthorized, .api_key_expired),
        error.ApiKeyInvalid => status(.unauthorized, .api_key_invalid),
        error.ApiKeyNotFound => status(.not_found, .api_key_not_found),
        error.AuthRowFilterNoMatch => status(.forbidden, .auth_row_filter_no_match),
        error.BackupMaintenanceQueueFull => status(.retryable, .backup_maintenance_queue_full),
        error.QueueFull => status(.retryable, .queue_full),
        error.ResourceLimitExceeded => status(.unavailable, .resource_limit_exceeded),
        error.BodyTooLarge => status(.invalid_argument, .body_too_large),
        error.BodyCapacityExceeded => status(.retryable, .body_capacity_exceeded),
        error.BodyReadFailed => status(.unavailable, .body_read_failed),
        error.InferenceProviderFailure => status(.internal, .inference_provider_failure),
        error.KernelJitRequiredDynamicLoad => status(.unsupported, .kernel_jit_required_dynamic_load),
        error.UnexpectedToken => status(.internal, .unexpected_token),
        error.EnrichmentWaitCanceled => status(.cancelled, .enrichment_wait_canceled),
        error.EnrichmentWaitTimeout => status(.timeout, .enrichment_wait_timeout),
        // This can be reported only after a write's primary mutation is
        // durable. Preserve it across the API/storage partition so ingress
        // can return committed_repair_required instead of an unsafe 500.
        error.EnrichmentWorkerFailed => status(.internal, .enrichment_worker_failed),
        error.BackupMaintenanceUnavailable => status(.unavailable, .backup_maintenance_unavailable),
        error.ConnectionNotFound => status(.not_found, .connection_not_found),
        error.EmbedRequestFailed => status(.unavailable, .embed_request_failed),
        error.EmptyEmbeddingResponse => status(.unavailable, .empty_embedding_response),
        error.EmptyName => status(.invalid_argument, .empty_name),
        error.EndOfStream => status(.retryable, .end_of_stream),
        error.ForeignQueryFailed => status(.unavailable, .foreign_query_failed),
        error.InvalidApiKeyRequest => status(.invalid_argument, .invalid_api_key_request),
        error.InvalidApiServerConfig => status(.invalid_argument, .invalid_api_server_config),
        error.InvalidArdAgentsRequest => status(.invalid_argument, .invalid_ard_agents_request),
        error.InvalidArdSearchRequest => status(.invalid_argument, .invalid_ard_search_request),
        error.InvalidBackupId => status(.invalid_argument, .invalid_backup_id),
        error.InvalidBackupListLimit => status(.invalid_argument, .invalid_backup_list_limit),
        error.InvalidCharacter => status(.invalid_argument, .invalid_character),
        error.InvalidCreateUserRequest => status(.invalid_argument, .invalid_create_user_request),
        error.InvalidDetail => status(.invalid_argument, .invalid_detail),
        error.InvalidDuration => status(.invalid_argument, .invalid_duration),
        error.InvalidEnrichmentRequest => status(.invalid_argument, .invalid_enrichment_request),
        error.InvalidEvalRequest => status(.invalid_argument, .invalid_eval_request),
        error.InvalidIdentifier => status(.invalid_argument, .invalid_identifier),
        error.InvalidIndexRequest => status(.invalid_argument, .invalid_index_request),
        error.InvalidJobId => status(.invalid_argument, .invalid_job_id),
        error.InvalidJsonObject => status(.invalid_argument, .invalid_json_object),
        error.InvalidLinearMergeRequest => status(.invalid_argument, .invalid_linear_merge_request),
        error.InvalidMetadata => status(.invalid_argument, .invalid_metadata),
        error.InvalidPassword => status(.invalid_argument, .invalid_password),
        error.InvalidPasswordUpdateRequest => status(.invalid_argument, .invalid_password_update_request),
        error.InvalidPathParameter => status(.invalid_argument, .invalid_path_parameter),
        error.InvalidPermissionType => status(.invalid_argument, .invalid_permission_type),
        error.InvalidQueryBuilderRequest => status(.invalid_argument, .invalid_query_builder_request),
        error.InvalidReadConsistency => status(.invalid_argument, .invalid_read_consistency),
        error.InvalidResourceType => status(.invalid_argument, .invalid_resource_type),
        error.InvalidRestoreJobListCursor => status(.invalid_argument, .invalid_restore_job_list_cursor),
        error.InvalidRestoreJobListLimit => status(.invalid_argument, .invalid_restore_job_list_limit),
        error.InvalidRestoreJobListPhase => status(.invalid_argument, .invalid_restore_job_list_phase),
        error.InvalidRestoreJobListScope => status(.invalid_argument, .invalid_restore_job_list_scope),
        error.InvalidRetrievalAgentRequest => status(.invalid_argument, .invalid_retrieval_agent_request),
        error.InvalidRole => status(.invalid_argument, .invalid_role),
        error.InvalidSecretKey => status(.invalid_argument, .invalid_secret_key),
        error.InvalidTransactionCommitRequest => status(.invalid_argument, .invalid_transaction_commit_request),
        error.InvalidTransactionSessionRecord => status(.invalid_argument, .invalid_transaction_session_record),
        error.MaintenanceBusy => status(.retryable, .maintenance_busy),
        error.MaintenanceHistoryFull => status(.unavailable, .maintenance_history_full),
        error.MaintenanceJobIdExhausted => status(.unavailable, .maintenance_job_id_exhausted),
        error.MemberTableOutsideScope => status(.invalid_argument, .member_table_outside_scope),
        error.MissingField => status(.invalid_argument, .missing_field),
        error.MissingLocation => status(.invalid_argument, .missing_location),
        error.MissingResource => status(.not_found, .missing_resource),
        error.MissingResourceType => status(.invalid_argument, .missing_resource_type),
        error.MissingRole => status(.invalid_argument, .missing_role),
        error.NoTables => status(.invalid_argument, .no_tables),
        error.PathAlreadyExists => status(.already_exists, .path_already_exists),
        error.PrivilegeEscalation => status(.forbidden, .privilege_escalation),
        error.ProbeUnavailable => status(.unavailable, .probe_unavailable),
        error.RoleNotFound => status(.not_found, .role_not_found),
        error.RowFilterNotFound => status(.not_found, .row_filter_not_found),
        error.SavepointLimitExceeded => status(.unavailable, .savepoint_limit_exceeded),
        error.SessionLeaseLost => status(.conflict, .session_lease_lost),
        error.SessionLimitExceeded => status(.unavailable, .session_limit_exceeded),
        error.SessionRecordTooLarge => status(.invalid_argument, .session_record_too_large),
        error.StaleIndexRepairControl => status(.conflict, .stale_index_repair_control),
        error.SyntaxError => status(.invalid_argument, .syntax_error),
        error.TooManyRuntimeStatuses => status(.unavailable, .too_many_runtime_statuses),
        error.TransactionCommitRequestMismatch => status(.conflict, .transaction_commit_request_mismatch),
        error.TransactionCommitSealed => status(.conflict, .transaction_commit_sealed),
        error.TreeRootSetTooLarge => status(.invalid_argument, .tree_root_set_too_large),
        error.UnrequestedCapabilityGrant => status(.forbidden, .unrequested_capability_grant),
        error.UnsupportedAggregate => status(.unsupported, .unsupported_aggregate),
        error.UnsupportedBackupLocation => status(.unsupported, .unsupported_backup_location),
        error.UnsupportedManifestApiVersion => status(.unsupported, .unsupported_manifest_api_version),
        error.UnsupportedObjectKindForV1 => status(.unsupported, .unsupported_object_kind_for_v1),
        error.UnsupportedRetrievalAgentRequest => status(.unsupported, .unsupported_retrieval_agent_request),
        error.UnsupportedSourceKind => status(.unsupported, .unsupported_source_kind),
        error.UpdatePathNotFound => status(.not_found, .update_path_not_found),
        error.UserExists => status(.already_exists, .user_exists),
        else => status(.internal, .none),
    };
}

/// Preserve an explicitly classified error and replace an untransportable,
/// compilation-local error with a stable boundary-specific outcome.
///
/// Callers should log `err` on the owning side before using this helper: the
/// fallback intentionally carries behavior and a diagnosable boundary name,
/// not an arbitrary error string across the stable ABI.
pub fn statusFromErrorWithFallback(err: anyerror, fallback: anyerror) Status {
    const value = statusFromError(err);
    if (value.detail != @intFromEnum(Detail.none)) return value;
    const fallback_value = statusFromError(fallback);
    std.debug.assert(fallback_value.detail != @intFromEnum(Detail.none));
    return fallback_value;
}

pub fn errorHasStableDetail(err: anyerror) bool {
    return statusFromError(err).detail != @intFromEnum(Detail.none);
}

fn status(code: Code, detail: Detail) Status {
    return .{ .code = @intFromEnum(code), .detail = @intFromEnum(detail) };
}

pub fn errorFromStatus(value: Status) anyerror {
    const code = std.enums.fromInt(Code, value.code) orelse return error.RuntimeBoundaryFailure;
    if (code == .ok) return error.RuntimeBoundaryFailure;
    const detail = std.enums.fromInt(Detail, value.detail) orelse return error.RuntimeBoundaryFailure;
    const err: anyerror = switch (detail) {
        .none => error.RuntimeBoundaryFailure,
        inline else => |known_detail| @field(anyerror, detailErrorName(known_detail)),
    };
    if (err == error.RuntimeBoundaryFailure) return err;
    const canonical = statusFromError(err);
    if (canonical.code != value.code or canonical.detail != value.detail)
        return error.RuntimeBoundaryFailure;
    return err;
}

fn detailErrorName(comptime detail: Detail) []const u8 {
    return switch (detail) {
        .none => "RuntimeBoundaryFailure",
        .out_of_memory => "OutOfMemory",
        .invalid_argument => "InvalidArgument",
        .invalid_arguments => "InvalidArguments",
        .invalid_request => "InvalidRequest",
        .invalid_query_request => "InvalidQueryRequest",
        .invalid_filter_query_request => "InvalidFilterQueryRequest",
        .invalid_exclusion_query_request => "InvalidExclusionQueryRequest",
        .invalid_batch_request => "InvalidBatchRequest",
        .invalid_create_table_request => "InvalidCreateTableRequest",
        .unsupported_create_table_request => "UnsupportedCreateTableRequest",
        .invalid_schema_update_request => "InvalidSchemaUpdateRequest",
        .invalid_manifest => "InvalidManifest",
        .invalid_table_file => "InvalidTableFile",
        .invalid_txn_record => "InvalidTxnRecord",
        .not_found => "NotFound",
        .file_not_found => "FileNotFound",
        .table_not_found => "TableNotFound",
        .table_already_exists => "TableAlreadyExists",
        .index_not_found => "IndexNotFound",
        .model_not_found => "ModelNotFound",
        .secret_not_found => "SecretNotFound",
        .user_not_found => "UserNotFound",
        .unknown_group => "UnknownGroup",
        .txn_not_found => "TxnNotFound",
        .conflict => "Conflict",
        .decision_conflict => "DecisionConflict",
        .table_transition_active => "TableTransitionActive",
        .extension_owned_object => "ExtensionOwnedObject",
        .restore_intent_conflict => "RestoreIntentConflict",
        .unauthorized => "Unauthorized",
        .forbidden => "Forbidden",
        .unavailable => "Unavailable",
        .write_unavailable => "WriteUnavailable",
        .read_unavailable => "ReadUnavailable",
        .read_requires_primary => "ReadRequiresPrimary",
        .storage_read_temporarily_unavailable => "StorageReadTemporarilyUnavailable",
        .resource_request_too_large => "ResourceRequestTooLarge",
        .resource_temporarily_unavailable => "ResourceTemporarilyUnavailable",
        .restore_job_persistence_unavailable => "RestoreJobPersistenceUnavailable",
        .backpressured => "Backpressured",
        .dense_repair_backpressure => "DenseRepairBackpressure",
        .outcome_unknown => "OutcomeUnknown",
        .commit_propagation_incomplete => "CommitPropagationIncomplete",
        .commit_decision_unknown => "CommitDecisionUnknown",
        .committed_pending => "CommittedPending",
        .write_outcome_unknown => "WriteOutcomeUnknown",
        .doc_identity_unavailable => "DocIdentityUnavailable",
        .ha_read_only_standby => "HAReadOnlyStandby",
        .ha_promoted_standby_requires_primary_open => "HAPromotedStandbyRequiresPrimaryOpen",
        .ha_fenced_primary => "HAFencedPrimary",
        .internal_failure => "InternalFailure",
        .not_leader => "NotLeader",
        .topology_changed => "TopologyChanged",
        .identity_read_generation_changed => "IdentityReadGenerationChanged",
        .doc_identity_namespace_mismatch => "DocIdentityNamespaceMismatch",
        .table_generation_changed => "TableGenerationChanged",
        .generation_durability_uncertain => "GenerationDurabilityUncertain",
        .index_rebuilding => "IndexRebuilding",
        .table_visibility_timeout => "TableVisibilityTimeout",
        .writer_locked => "WriterLocked",
        .lsm_root_writer_already_open => "LsmRootWriterAlreadyOpen",
        .unexpected_http_status => "UnexpectedHttpStatus",
        .method_not_allowed => "MethodNotAllowed",
        .unsupported => "Unsupported",
        .unsupported_operation => "UnsupportedOperation",
        .unsupported_query_request => "UnsupportedQueryRequest",
        .unsupported_filter_query_request => "UnsupportedFilterQueryRequest",
        .unsupported_exclusion_query_request => "UnsupportedExclusionQueryRequest",
        .unsupported_sync_level => "UnsupportedSyncLevel",
        .unsupported_exact_sort => "UnsupportedExactSort",
        .unsupported_version => "UnsupportedVersion",
        .timeout => "Timeout",
        .connection_timeout => "ConnectionTimeout",
        .connection_timed_out => "ConnectionTimedOut",
        .cancelled => "Cancelled",
        .canceled => "Canceled",
        .connection_refused => "ConnectionRefused",
        .connection_reset_by_peer => "ConnectionResetByPeer",
        .network_unreachable => "NetworkUnreachable",
        .host_unreachable => "HostUnreachable",
        .temporary_name_server_failure => "TemporaryNameServerFailure",
        .name_server_failure => "NameServerFailure",
        .query_candidate_budget_exceeded => "QueryCandidateBudgetExceeded",
        .query_embedding_input_too_large => "QueryEmbeddingInputTooLarge",
        .query_embedding_overloaded => "QueryEmbeddingOverloaded",
        .embed_rate_limited => "EmbedRateLimited",
        .embed_transient_failure => "EmbedTransientFailure",
        .embed_upstream_failure => "EmbedUpstreamFailure",
        .embedding_probe_unavailable => "EmbeddingProbeUnavailable",
        .invalid_embedding_response => "InvalidEmbeddingResponse",
        .invalid_embedding_dimensions => "InvalidEmbeddingDimensions",
        .backup_already_exists => "BackupAlreadyExists",
        .backup_manifest_too_large => "BackupManifestTooLarge",
        .backup_integrity_failure => "BackupIntegrityFailure",
        .backup_artifact_integrity_mismatch => "BackupArtifactIntegrityMismatch",
        .backup_repository_busy => "BackupRepositoryBusy",
        .invalid_backup_request => "InvalidBackupRequest",
        .restore_durability_pending => "RestoreDurabilityPending",
        .restore_durability_confirmed => "RestoreDurabilityConfirmed",
        .corrupt_input => "CorruptInput",
        .corrupted => "Corrupted",
        .corrupt_restore_job_store => "CorruptRestoreJobStore",
        .table_block_checksum_mismatch => "TableBlockChecksumMismatch",
        .value_too_long => "ValueTooLong",
        .unsupported_platform => "UnsupportedPlatform",
        .unsupported_transform_operation => "UnsupportedTransformOperation",
        .ha_read_requires_primary => "HAReadRequiresPrimary",
        .ha_read_wait_for_apply => "HAReadWaitForApply",
        .ha_read_wait_for_metadata => "HAReadWaitForMetadata",
        .persistent_descriptor_admission_exhausted => "PersistentDescriptorAdmissionExhausted",
        .invalid_graph_edges => "InvalidGraphEdges",
        .invalid_table_index_metadata => "InvalidTableIndexMetadata",
        .transaction_begin_failed => "TransactionBeginFailed",
        .abort_decision_not_durable => "AbortDecisionNotDurable",
        .commit_visibility_not_satisfied => "CommitVisibilityNotSatisfied",
        .leader_unavailable => "LeaderUnavailable",
        .raft_batch_write_outcome_unknown => "RaftBatchWriteOutcomeUnknown",
        .raft_batch_write_partial_outcome => "RaftBatchWritePartialOutcome",
        .enrichment_retry_in_progress => "EnrichmentRetryInProgress",
        .resource_budget_exceeded => "ResourceBudgetExceeded",
        .text_merge_backpressure_timeout => "TextMergeBackpressureTimeout",
        .text_merge_backpressure_unavailable => "TextMergeBackpressureUnavailable",
        .text_merge_runtime_shutdown => "TextMergeRuntimeShutdown",
        .background_owner_closing => "BackgroundOwnerClosing",
        .invalid_enrichment_config => "InvalidEnrichmentConfig",
        .restore_identity_mismatch => "RestoreIdentityMismatch",
        .table_read_churn => "TableReadChurn",
        .unsupported_multi_range_table => "UnsupportedMultiRangeTable",
        .proposal_dropped => "ProposalDropped",
        .leader_transfer_in_progress => "LeaderTransferInProgress",
        .metadata_linearizable_read_timeout => "MetadataLinearizableReadTimeout",
        .reconcile_lease_not_held => "ReconcileLeaseNotHeld",
        .enrichment_not_found => "EnrichmentNotFound",
        .invalid_extension_enrichment => "InvalidExtensionEnrichment",
        .conflicting_enrichment_config => "ConflictingEnrichmentConfig",
        .invalid_create_index_request => "InvalidCreateIndexRequest",
        .unsupported_backup_migration_state => "UnsupportedBackupMigrationState",
        .unsupported_backup_format => "UnsupportedBackupFormat",
        .extension_already_installed => "ExtensionAlreadyInstalled",
        .extension_not_installed => "ExtensionNotInstalled",
        .extension_disabled => "ExtensionDisabled",
        .extension_lifecycle_busy => "ExtensionLifecycleBusy",
        .extension_visibility_timeout => "ExtensionVisibilityTimeout",
        .dependent_extension_exists => "DependentExtensionExists",
        .required_extension_not_installed => "RequiredExtensionNotInstalled",
        .missing_extension_package => "MissingExtensionPackage",
        .package_not_found => "PackageNotFound",
        .package_version_mismatch => "PackageVersionMismatch",
        .unsupported_package_kind => "UnsupportedPackageKind",
        .invalid_extension_shape => "InvalidExtensionShape",
        .unsupported_extension_scope => "UnsupportedExtensionScope",
        .invalid_extension_lifecycle_request => "InvalidExtensionLifecycleRequest",
        .restore_job_fenced => "RestoreJobFenced",
        .restore_job_capacity_exceeded => "RestoreJobCapacityExceeded",
        .restore_job_record_too_large => "RestoreJobRecordTooLarge",
        .too_many_restore_tables => "TooManyRestoreTables",
        .duplicate_restore_table_name => "DuplicateRestoreTableName",
        .idempotency_conflict => "IdempotencyConflict",
        .invalid_idempotency_key => "InvalidIdempotencyKey",
        .async_restore_unavailable => "AsyncRestoreUnavailable",
        .background_runtime_unavailable => "BackgroundRuntimeUnavailable",
        .backup_staging_unavailable => "BackupStagingUnavailable",
        .backup_artifact_missing => "BackupArtifactMissing",
        .backup_integrity_missing => "BackupIntegrityMissing",
        .backup_attempt_lease_lost => "BackupAttemptLeaseLost",
        .background_owner_closed => "BackgroundOwnerClosed",
        .restore_scheduling_capacity => "RestoreSchedulingCapacity",
        .restore_wait_interrupted => "RestoreWaitInterrupted",
        .api_key_expired => "ApiKeyExpired",
        .api_key_invalid => "ApiKeyInvalid",
        .api_key_not_found => "ApiKeyNotFound",
        .auth_row_filter_no_match => "AuthRowFilterNoMatch",
        .backup_maintenance_queue_full => "BackupMaintenanceQueueFull",
        .backup_maintenance_unavailable => "BackupMaintenanceUnavailable",
        .connection_not_found => "ConnectionNotFound",
        .embed_request_failed => "EmbedRequestFailed",
        .empty_embedding_response => "EmptyEmbeddingResponse",
        .empty_name => "EmptyName",
        .end_of_stream => "EndOfStream",
        .foreign_query_failed => "ForeignQueryFailed",
        .invalid_api_key_request => "InvalidApiKeyRequest",
        .invalid_api_server_config => "InvalidApiServerConfig",
        .invalid_ard_agents_request => "InvalidArdAgentsRequest",
        .invalid_ard_search_request => "InvalidArdSearchRequest",
        .invalid_backup_id => "InvalidBackupId",
        .invalid_backup_list_limit => "InvalidBackupListLimit",
        .invalid_character => "InvalidCharacter",
        .invalid_create_user_request => "InvalidCreateUserRequest",
        .invalid_detail => "InvalidDetail",
        .invalid_duration => "InvalidDuration",
        .invalid_enrichment_request => "InvalidEnrichmentRequest",
        .invalid_eval_request => "InvalidEvalRequest",
        .invalid_identifier => "InvalidIdentifier",
        .invalid_index_request => "InvalidIndexRequest",
        .invalid_job_id => "InvalidJobId",
        .invalid_json_object => "InvalidJsonObject",
        .invalid_linear_merge_request => "InvalidLinearMergeRequest",
        .invalid_metadata => "InvalidMetadata",
        .invalid_password => "InvalidPassword",
        .invalid_password_update_request => "InvalidPasswordUpdateRequest",
        .invalid_path_parameter => "InvalidPathParameter",
        .invalid_permission_type => "InvalidPermissionType",
        .invalid_query_builder_request => "InvalidQueryBuilderRequest",
        .invalid_read_consistency => "InvalidReadConsistency",
        .invalid_resource_type => "InvalidResourceType",
        .invalid_restore_job_list_cursor => "InvalidRestoreJobListCursor",
        .invalid_restore_job_list_limit => "InvalidRestoreJobListLimit",
        .invalid_restore_job_list_phase => "InvalidRestoreJobListPhase",
        .invalid_restore_job_list_scope => "InvalidRestoreJobListScope",
        .invalid_retrieval_agent_request => "InvalidRetrievalAgentRequest",
        .invalid_role => "InvalidRole",
        .invalid_secret_key => "InvalidSecretKey",
        .invalid_transaction_commit_request => "InvalidTransactionCommitRequest",
        .invalid_transaction_session_record => "InvalidTransactionSessionRecord",
        .maintenance_busy => "MaintenanceBusy",
        .maintenance_history_full => "MaintenanceHistoryFull",
        .maintenance_job_id_exhausted => "MaintenanceJobIdExhausted",
        .member_table_outside_scope => "MemberTableOutsideScope",
        .missing_field => "MissingField",
        .missing_location => "MissingLocation",
        .missing_resource => "MissingResource",
        .missing_resource_type => "MissingResourceType",
        .missing_role => "MissingRole",
        .no_tables => "NoTables",
        .path_already_exists => "PathAlreadyExists",
        .privilege_escalation => "PrivilegeEscalation",
        .probe_unavailable => "ProbeUnavailable",
        .role_not_found => "RoleNotFound",
        .row_filter_not_found => "RowFilterNotFound",
        .savepoint_limit_exceeded => "SavepointLimitExceeded",
        .session_lease_lost => "SessionLeaseLost",
        .session_limit_exceeded => "SessionLimitExceeded",
        .session_record_too_large => "SessionRecordTooLarge",
        .stale_index_repair_control => "StaleIndexRepairControl",
        .syntax_error => "SyntaxError",
        .too_many_runtime_statuses => "TooManyRuntimeStatuses",
        .transaction_commit_request_mismatch => "TransactionCommitRequestMismatch",
        .transaction_commit_sealed => "TransactionCommitSealed",
        .tree_root_set_too_large => "TreeRootSetTooLarge",
        .unrequested_capability_grant => "UnrequestedCapabilityGrant",
        .unsupported_aggregate => "UnsupportedAggregate",
        .unsupported_backup_location => "UnsupportedBackupLocation",
        .unsupported_manifest_api_version => "UnsupportedManifestApiVersion",
        .unsupported_object_kind_for_v1 => "UnsupportedObjectKindForV1",
        .unsupported_retrieval_agent_request => "UnsupportedRetrievalAgentRequest",
        .unsupported_source_kind => "UnsupportedSourceKind",
        .update_path_not_found => "UpdatePathNotFound",
        .user_exists => "UserExists",
        .queue_full => "QueueFull",
        .resource_limit_exceeded => "ResourceLimitExceeded",
        .body_too_large => "BodyTooLarge",
        .body_capacity_exceeded => "BodyCapacityExceeded",
        .body_read_failed => "BodyReadFailed",
        .inference_provider_failure => "InferenceProviderFailure",
        .kernel_jit_required_dynamic_load => "KernelJitRequiredDynamicLoad",
        .unexpected_token => "UnexpectedToken",
        .enrichment_wait_canceled => "EnrichmentWaitCanceled",
        .enrichment_wait_timeout => "EnrichmentWaitTimeout",
        .enrichment_worker_failed => "EnrichmentWorkerFailed",
        .ha_sync_commit_would_block => "HASyncCommitWouldBlock",
        .ha_sync_commit_wait_limit_exceeded => "HASyncCommitWaitLimitExceeded",
        .ha_sync_commit_wait_missing_context => "HASyncCommitWaitMissingContext",
        .ha_sync_commit_wait_standby_not_in_policy => "HASyncCommitWaitStandbyNotInPolicy",
        .deadline_exceeded => "DeadlineExceeded",
        .pre_decision_deadline_exceeded => "PreDecisionDeadlineExceeded",
        .graph_distinct_budget_exceeded => "GraphDistinctBudgetExceeded",
        .graph_anchor_filter_requires_index => "GraphAnchorFilterRequiresIndex",
        .graph_match_operation_limit_exceeded => "GraphMatchOperationLimitExceeded",
        .graph_cross_range_mode_unsupported => "GraphQueryModeUnsupported",
        .graph_work_budget_exceeded => "GraphWorkBudgetExceeded",
        .graph_min_weight_domain_violation => "GraphMinWeightDomainViolation",
        .graph_max_weight_domain_violation => "GraphMaxWeightDomainViolation",
        .graph_path_weight_overflow => "GraphPathWeightOverflow",
    };
}

test "stable status preserves public boundary semantics" {
    try std.testing.expect(Status.ok.isOk());
    try std.testing.expectEqual(error.TableNotFound, errorFromStatus(statusFromError(error.TableNotFound)));
    try std.testing.expectEqual(error.TableVisibilityTimeout, errorFromStatus(statusFromError(error.TableVisibilityTimeout)));
    try std.testing.expectEqual(error.ExtensionOwnedObject, errorFromStatus(statusFromError(error.ExtensionOwnedObject)));
    try std.testing.expectEqual(error.ResourceRequestTooLarge, errorFromStatus(statusFromError(error.ResourceRequestTooLarge)));
    try std.testing.expectEqual(error.ResourceTemporarilyUnavailable, errorFromStatus(statusFromError(error.ResourceTemporarilyUnavailable)));
    try std.testing.expectEqual(error.QueueFull, errorFromStatus(statusFromError(error.QueueFull)));
    try std.testing.expectEqual(error.ResourceLimitExceeded, errorFromStatus(statusFromError(error.ResourceLimitExceeded)));
    try std.testing.expectEqual(error.GraphQueryModeUnsupported, errorFromStatus(statusFromError(error.GraphQueryModeUnsupported)));
    try std.testing.expectEqual(error.InferenceProviderFailure, errorFromStatus(statusFromError(error.InferenceProviderFailure)));
    try std.testing.expectEqual(error.KernelJitRequiredDynamicLoad, errorFromStatus(statusFromError(error.KernelJitRequiredDynamicLoad)));
    try std.testing.expectEqual(error.UnexpectedToken, errorFromStatus(statusFromError(error.UnexpectedToken)));
    try std.testing.expectEqual(error.EnrichmentWaitCanceled, errorFromStatus(statusFromError(error.EnrichmentWaitCanceled)));
    try std.testing.expectEqual(error.EnrichmentWaitTimeout, errorFromStatus(statusFromError(error.EnrichmentWaitTimeout)));
    try std.testing.expectEqual(error.EnrichmentWorkerFailed, errorFromStatus(statusFromError(error.EnrichmentWorkerFailed)));
    try std.testing.expectEqual(error.DeadlineExceeded, errorFromStatus(statusFromError(error.DeadlineExceeded)));
    try std.testing.expectEqual(error.PreDecisionDeadlineExceeded, errorFromStatus(statusFromError(error.PreDecisionDeadlineExceeded)));
    try std.testing.expectEqual(error.UnsupportedPlatform, errorFromStatus(statusFromError(error.UnsupportedPlatform)));
    try std.testing.expectEqual(error.UnsupportedTransformOperation, errorFromStatus(statusFromError(error.UnsupportedTransformOperation)));
    try std.testing.expectEqual(error.HAReadRequiresPrimary, errorFromStatus(statusFromError(error.HAReadRequiresPrimary)));
    try std.testing.expectEqual(error.PersistentDescriptorAdmissionExhausted, errorFromStatus(statusFromError(error.PersistentDescriptorAdmissionExhausted)));
    try std.testing.expectEqual(error.CommitVisibilityNotSatisfied, errorFromStatus(statusFromError(error.CommitVisibilityNotSatisfied)));
    try std.testing.expectEqual(error.AbortDecisionNotDurable, errorFromStatus(statusFromError(error.AbortDecisionNotDurable)));
    try std.testing.expectEqual(error.LeaderUnavailable, errorFromStatus(statusFromError(error.LeaderUnavailable)));
    try std.testing.expectEqual(error.HASyncCommitWouldBlock, errorFromStatus(statusFromError(error.HASyncCommitWouldBlock)));
    try std.testing.expectEqual(error.HASyncCommitWaitLimitExceeded, errorFromStatus(statusFromError(error.HASyncCommitWaitLimitExceeded)));
    try std.testing.expectEqual(error.HASyncCommitWaitMissingContext, errorFromStatus(statusFromError(error.HASyncCommitWaitMissingContext)));
    try std.testing.expectEqual(error.HASyncCommitWaitStandbyNotInPolicy, errorFromStatus(statusFromError(error.HASyncCommitWaitStandbyNotInPolicy)));
    try std.testing.expectEqual(error.RuntimeBoundaryFailure, errorFromStatus(statusFromError(error.UnitPrivateError)));
}

test "stable status replaces private provider errors with a named fallback" {
    try std.testing.expectEqual(
        error.InferenceProviderFailure,
        errorFromStatus(statusFromErrorWithFallback(error.UnitPrivateInferenceError, error.InferenceProviderFailure)),
    );
    try std.testing.expectEqual(
        error.ResourceTemporarilyUnavailable,
        errorFromStatus(statusFromErrorWithFallback(error.ResourceTemporarilyUnavailable, error.InferenceProviderFailure)),
    );
}

test "stable detail detection distinguishes private errors" {
    try std.testing.expect(errorHasStableDetail(error.UnexpectedToken));
    try std.testing.expect(!errorHasStableDetail(error.UnitPrivateInferenceError));
}

test "every classified boundary outcome retains its identity" {
    const classified = comptime blk: {
        const details = std.meta.tags(Detail)[1..];
        var errors: [details.len]anyerror = undefined;
        for (details, 0..) |detail, index| {
            errors[index] = @field(anyerror, detailErrorName(detail));
        }
        break :blk errors;
    };
    for (classified) |err| {
        try std.testing.expectEqual(err, errorFromStatus(statusFromError(err)));
    }
}

test "stable status has a C layout" {
    try std.testing.expectEqual(@sizeOf(c_int) * 2, @sizeOf(Status));
    try std.testing.expectEqual(@as(usize, 0), @offsetOf(Status, "code"));
    try std.testing.expectEqual(@sizeOf(c_int), @offsetOf(Status, "detail"));
}

test "unknown wire values fail closed" {
    try std.testing.expectEqual(error.RuntimeBoundaryFailure, errorFromStatus(.{ .code = 999, .detail = 999 }));
    try std.testing.expectEqual(error.RuntimeBoundaryFailure, errorFromStatus(.{ .code = @intFromEnum(Code.internal), .detail = 999 }));
    try std.testing.expectEqual(error.RuntimeBoundaryFailure, errorFromStatus(.{
        .code = @intFromEnum(Code.invalid_argument),
        .detail = @intFromEnum(Detail.table_not_found),
    }));
}
