#!/usr/bin/env python3
"""Capture exact released tensor schemas on Torch's allocation-free meta device."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import oracle
from oracle import FIXTURES, prepare_runtime, write_json

VARIANTS = ("base", "small", "multi")
INVENTORY = "models/tensor_inventory.json"


def consolidate(inventories):
    base = inventories["base"]
    result = {"format_version": 2, "models": list(VARIANTS), "dtype": "torch.float32",
              "provenance": base["provenance"], "source": base["source"], "tensors": {}}
    for variant in VARIANTS:
        item = inventories[variant]
        if (item["model"] != variant or item["provenance"] != base["provenance"] or
                item["source"] != base["source"] or item["tensors"].keys() != base["tensors"].keys()):
            raise oracle.ContractError("inventory variants do not share a schema")
    for name, spec in base["tensors"].items():
        shapes = {"base": spec["shape"]}
        for variant in VARIANTS:
            item = inventories[variant]["tensors"][name]
            if item["dtype"] != result["dtype"]:
                raise oracle.ContractError("inventory dtype differs")
            if item["shape"] != spec["shape"]:
                shapes[variant] = item["shape"]
        result["tensors"][name] = shapes
    return result


def expand_inventory(data, variant):
    """Resolve only explicitly captured shapes; never derive gold from native code."""
    if (variant not in VARIANTS or data.get("format_version") != 2 or
            data.get("models") != list(VARIANTS) or data.get("dtype") != "torch.float32" or
            data.get("source") != "meta_constructed_schema" or
            data["provenance"]["commit"] != oracle.UPSTREAM_COMMIT or len(data["tensors"]) != 334):
        raise oracle.ContractError("published inventory identity differs")
    tensors = {}
    for name, shapes in data["tensors"].items():
        if not isinstance(shapes, dict) or "base" not in shapes or not shapes.keys() <= set(VARIANTS):
            raise oracle.ContractError("invalid inventory variant shapes")
        for shape in shapes.values():
            if not isinstance(shape, list) or not 1 <= len(shape) <= 8 or any(type(n) is not int or not 0 < n < 2**31 for n in shape):
                raise oracle.ContractError("invalid inventory shape")
        tensors[name] = {"dtype": data["dtype"], "shape": shapes.get(variant, shapes["base"])}
    return {"format_version": 1, "model": variant, "provenance": data["provenance"],
            "source": data["source"], "tensors": tensors}


def load_inventory(variant):
    manifest = oracle.read_json(FIXTURES / "reference_manifest.json")
    oracle.verify_file(Path(__file__), manifest["generators"][Path(__file__).name])
    path = FIXTURES / INVENTORY
    pin = oracle.verify_file(path, manifest["files"][INVENTORY])
    return expand_inventory(oracle.read_json(path), variant), pin


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--small-model", type=Path, help="optional published checkpoint header cross-check")
    parser.add_argument("--output-dir", type=Path, default=FIXTURES)
    parser.add_argument("--zig-output", type=Path, default=Path(__file__).resolve().parents[2] / "src/models/gliner_boundary_tensor_inventory.zig")
    args = parser.parse_args()
    provenance, torch = prepare_runtime(args.source)
    from transformers import DebertaV2Config, DebertaV2Model
    from gliner2.configuration import BoundaryHeadSettings
    from gliner2.models.boundary.model import BoundaryHead
    from gliner2.models.boundary.records import RecordHead
    from gliner2.models.boundary.relations import SparseRelationScorer
    from gliner2.layers import create_mlp
    output = ["// Generated by scripts/gliner25/capture_inventory.py; do not edit.",
              "// Shape-only modules constructed from immutable published configs on Torch meta.",
              "pub const Spec = struct { name: []const u8, shape: []const i64 };", ""]
    inventories = {}
    for variant in VARIANTS:
        config = json.loads((FIXTURES / "models" / variant / "config.json").read_text())
        encoder = json.loads((FIXTURES / "models" / variant / "encoder_config.json").read_text())
        settings = BoundaryHeadSettings(**config["boundary_head"])
        h = encoder["hidden_size"]
        with torch.device("meta"):
            modules = {
                "encoder": DebertaV2Model(DebertaV2Config.from_dict(encoder)),
                "classifier": create_mlp(h, [h * 2], 1, dropout=settings.dropout,
                                         activation="relu", add_layer_norm=False),
                "boundary_head": BoundaryHead(h, settings, query_dim=h, build_candidate_states=settings.enable_records),
                "record_decoder": RecordHead(h, settings.record_dim, settings.record_instance_queries),
                "relation_scorer": SparseRelationScorer(h, dropout=settings.dropout,
                    relation_query_dim=2*h if settings.directional_relation_states else h,
                    use_biaffine_content=settings.relation_biaffine_content),
            }
        tensors = {f"{prefix}.{name}": dict(shape=list(tensor.shape), dtype=str(tensor.dtype))
                   for prefix, module in modules.items() for name, tensor in module.state_dict().items()}
        if variant == "small" and args.small_model:
            from oracle import verify_model_dir
            verify_model_dir("small", args.small_model)
            with (args.small_model / "model.safetensors").open("rb") as source:
                count = int.from_bytes(source.read(8), "little")
                if count > 4 * 1024 * 1024:
                    raise RuntimeError("unexpected checkpoint header size")
                actual = json.loads(source.read(count))
            actual.pop("__metadata__", None)
            if tensors.keys() != actual.keys():
                raise RuntimeError(f"checkpoint tensor names differ: missing={tensors.keys() - actual.keys()}, extra={actual.keys() - tensors.keys()}")
            for name, spec in tensors.items():
                if spec["shape"] != actual[name]["shape"] or actual[name]["dtype"] != "F32":
                    raise RuntimeError(f"checkpoint tensor shape or dtype differs: {name}")
        inventories[variant] = {
            "format_version": 1, "provenance": provenance, "model": variant,
            "source": "meta_constructed_schema", "tensors": tensors,
        }
        output.append(f"pub const {variant} = [_]Spec{{")
        for name, spec in sorted(tensors.items()):
            shape = ', '.join(map(str, spec["shape"]))
            if len(spec["shape"]) > 1:
                shape = ' ' + shape + ' '
            output.append('    .{ .name = ' + json.dumps(name) + ', .shape = &.{' + shape + '} },')
        output.extend(["};", ""])
        print(f"{variant}: {len(tensors)} exact tensor shapes")
    inventory_path = args.output_dir / INVENTORY
    inventory_path.parent.mkdir(parents=True, exist_ok=True)
    write_json(inventory_path, consolidate(inventories))
    args.zig_output.write_text("\n".join(output))


if __name__ == "__main__":
    main()
