//go:build go1.22

// Package indexes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package indexes

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/go/pkg/antfly/lib/chunking"
	externalRef1 "github.com/antflydb/antfly/go/pkg/antfly/lib/embeddings"
	externalRef2 "github.com/antflydb/antfly/go/pkg/generating"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AlgebraicIndexStatsIndexType.
const (
	AlgebraicIndexStatsIndexTypeAlgebraic AlgebraicIndexStatsIndexType = "algebraic"
)

// Defines values for AlgebraicIndexStatsPlannerLastDecision.
const (
	AlgebraicIndexStatsPlannerLastDecisionFallback AlgebraicIndexStatsPlannerLastDecision = "fallback"
	AlgebraicIndexStatsPlannerLastDecisionSelected AlgebraicIndexStatsPlannerLastDecision = "selected"
)

// Defines values for AntflyType.
const (
	AntflyTypeBlob            AntflyType = "blob"
	AntflyTypeBoolean         AntflyType = "boolean"
	AntflyTypeDatetime        AntflyType = "datetime"
	AntflyTypeEmbedding       AntflyType = "embedding"
	AntflyTypeGeopoint        AntflyType = "geopoint"
	AntflyTypeGeoshape        AntflyType = "geoshape"
	AntflyTypeHtml            AntflyType = "html"
	AntflyTypeKeyword         AntflyType = "keyword"
	AntflyTypeLink            AntflyType = "link"
	AntflyTypeNumeric         AntflyType = "numeric"
	AntflyTypeSearchAsYouType AntflyType = "search_as_you_type"
	AntflyTypeText            AntflyType = "text"
)

// Defines values for DistanceMetric.
const (
	DistanceMetricCosine       DistanceMetric = "cosine"
	DistanceMetricInnerProduct DistanceMetric = "inner_product"
	DistanceMetricL2Squared    DistanceMetric = "l2_squared"
)

// Defines values for EdgeDirection.
const (
	EdgeDirectionBoth EdgeDirection = "both"
	EdgeDirectionIn   EdgeDirection = "in"
	EdgeDirectionOut  EdgeDirection = "out"
)

// Defines values for EdgeTypeConfigTopology.
const (
	EdgeTypeConfigTopologyGraph EdgeTypeConfigTopology = "graph"
	EdgeTypeConfigTopologyTree  EdgeTypeConfigTopology = "tree"
)

// Defines values for EmbeddingsIndexStatsIndexType.
const (
	EmbeddingsIndexStatsIndexTypeEmbeddings EmbeddingsIndexStatsIndexType = "embeddings"
)

// Defines values for EnrichmentKind.
const (
	EnrichmentKindAsset     EnrichmentKind = "asset"
	EnrichmentKindChunk     EnrichmentKind = "chunk"
	EnrichmentKindEmbedding EnrichmentKind = "embedding"
)

// Defines values for FullTextIndexStatsIndexType.
const (
	FullTextIndexStatsIndexTypeFullText FullTextIndexStatsIndexType = "full_text"
)

// Defines values for GraphIndexStatsIndexType.
const (
	GraphIndexStatsIndexTypeGraph GraphIndexStatsIndexType = "graph"
)

// Defines values for GraphQueryType.
const (
	GraphQueryTypeKShortestPaths GraphQueryType = "k_shortest_paths"
	GraphQueryTypeNeighbors      GraphQueryType = "neighbors"
	GraphQueryTypePattern        GraphQueryType = "pattern"
	GraphQueryTypeShortestPath   GraphQueryType = "shortest_path"
	GraphQueryTypeTraverse       GraphQueryType = "traverse"
)

// Defines values for IndexType.
const (
	IndexTypeAlgebraic  IndexType = "algebraic"
	IndexTypeEmbeddings IndexType = "embeddings"
	IndexTypeFullText   IndexType = "full_text"
	IndexTypeGraph      IndexType = "graph"
)

// Defines values for MergeStrategy.
const (
	MergeStrategyFailover MergeStrategy = "failover"
	MergeStrategyRrf      MergeStrategy = "rrf"
	MergeStrategyRsf      MergeStrategy = "rsf"
)

// Defines values for PathFindWeightMode.
const (
	PathFindWeightModeMaxWeight PathFindWeightMode = "max_weight"
	PathFindWeightModeMinHops   PathFindWeightMode = "min_hops"
	PathFindWeightModeMinWeight PathFindWeightMode = "min_weight"
)

// Defines values for PathWeightMode.
const (
	PathWeightModeMaxWeight PathWeightMode = "max_weight"
	PathWeightModeMinHops   PathWeightMode = "min_hops"
	PathWeightModeMinWeight PathWeightMode = "min_weight"
)

// AlgebraicIndexConfig Schema-derived algebraic sidecar configuration. Public requests may opt into schema derivation, while materializations remain engine-owned.
type AlgebraicIndexConfig struct {
	// DeriveFromSchema When true, derive the algebraic capability sidecar from the table schema. Internal fields and materialization definitions are not public API.
	DeriveFromSchema bool `json:"derive_from_schema,omitempty"`
}

// AlgebraicIndexStats Compact public statistics for an algebraic sidecar index. Detailed runtime, adaptive, and materialization records remain internal diagnostics.
type AlgebraicIndexStats struct {
	ActiveProgressLifecycle         string `json:"active_progress_lifecycle,omitempty"`
	ActiveProgressRowsProcessed     uint64 `json:"active_progress_rows_processed,omitempty"`
	ActiveProgressTargetRows        uint64 `json:"active_progress_target_rows,omitempty"`
	AdaptiveBackfillingCount        uint64 `json:"adaptive_backfilling_count,omitempty"`
	AdaptiveCleanupRecommendedCount uint64 `json:"adaptive_cleanup_recommended_count,omitempty"`
	AdaptiveProgressCount           uint64 `json:"adaptive_progress_count,omitempty"`
	AdaptiveReadyCount              uint64 `json:"adaptive_ready_count,omitempty"`
	AdaptiveStaleCount              uint64 `json:"adaptive_stale_count,omitempty"`

	// BackfillItemsProcessed Number of documents processed during current backfill
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Backfill progress as a ratio from 0.0 to 1.0
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// CapabilityLifecycleStatus Schema-derived algebraic capability lifecycle, for example current, stale, or rebuild_required.
	CapabilityLifecycleStatus string `json:"capability_lifecycle_status,omitempty"`

	// CheckpointReplayTailSequenceCount Number of derived-log sequences after the durable checkpoint that still need replay.
	CheckpointReplayTailSequenceCount uint64 `json:"checkpoint_replay_tail_sequence_count,omitempty"`

	// DiskUsage Size of the index in bytes
	DiskUsage uint64 `json:"disk_usage,omitempty"`

	// Error Error message if stats could not be retrieved
	Error   string `json:"error,omitempty"`
	Healthy bool   `json:"healthy,omitempty"`

	// IndexType Discriminator for the index stats variant.
	IndexType            AlgebraicIndexStatsIndexType           `json:"index_type"`
	LastErrorReason      string                                 `json:"last_error_reason,omitempty"`
	ParseErrorCount      uint64                                 `json:"parse_error_count,omitempty"`
	PlannerFallbackCount uint64                                 `json:"planner_fallback_count,omitempty"`
	PlannerLastDecision  AlgebraicIndexStatsPlannerLastDecision `json:"planner_last_decision,omitempty"`

	// PlannerLastEstimatedResultBuckets Latest algebraic planner result-bucket estimate for the last selected or fallback decision.
	PlannerLastEstimatedResultBuckets uint64 `json:"planner_last_estimated_result_buckets,omitempty"`

	// PlannerLastEstimatedScanRows Latest algebraic planner scan-row estimate for the last selected or fallback decision.
	PlannerLastEstimatedScanRows   uint64 `json:"planner_last_estimated_scan_rows,omitempty"`
	PlannerLastFallbackReason      string `json:"planner_last_fallback_reason,omitempty"`
	PlannerLifecycleBlockingReason string `json:"planner_lifecycle_blocking_reason,omitempty"`
	PlannerLifecycleReady          bool   `json:"planner_lifecycle_ready,omitempty"`
	PlannerSelected                uint64 `json:"planner_selected,omitempty"`

	// ProjectionCheckpointAppliedSequence Highest derived-log sequence covered by the durable projection checkpoint.
	ProjectionCheckpointAppliedSequence uint64 `json:"projection_checkpoint_applied_sequence,omitempty"`

	// ProjectionCheckpointConfigHash Projection configuration identity associated with the durable checkpoint.
	ProjectionCheckpointConfigHash uint64 `json:"projection_checkpoint_config_hash,omitempty"`

	// ProjectionCheckpointGeneration Projection generation associated with the durable checkpoint.
	ProjectionCheckpointGeneration uint64 `json:"projection_checkpoint_generation,omitempty"`

	// ProjectionCheckpointStatus Durable projection checkpoint status: clean, rebuilding, degraded, or repair_required.
	ProjectionCheckpointStatus string `json:"projection_checkpoint_status,omitempty"`

	// Rebuilding Whether the sidecar is currently rebuilding
	Rebuilding bool `json:"rebuilding,omitempty"`

	// RecommendationCount Number of currently recommended algebraic shapes.
	RecommendationCount uint64 `json:"recommendation_count,omitempty"`

	// RepairScanIssueCount Repair issues found by explicit repair-scan accounting for this projection.
	RepairScanIssueCount uint64 `json:"repair_scan_issue_count,omitempty"`
	SchemaVersion        uint64 `json:"schema_version,omitempty"`

	// TotalIndexed Number of documents reflected in the algebraic sidecar
	TotalIndexed uint64 `json:"total_indexed,omitempty"`
}

// AlgebraicIndexStatsIndexType Discriminator for the index stats variant.
type AlgebraicIndexStatsIndexType string

// AlgebraicIndexStatsPlannerLastDecision defines model for AlgebraicIndexStats.PlannerLastDecision.
type AlgebraicIndexStatsPlannerLastDecision string

// AntflyType defines model for AntflyType.
type AntflyType string

// DistanceMetric Distance metric for the vector index (dense only). Use "cosine" for models trained with cosine similarity (e.g. CLIP, OpenAI). Use "inner_product" for models trained with dot product similarity. Use "l2_squared" (default) for models trained with Euclidean distance.
type DistanceMetric string

// Edge A typed, weighted connection between documents
type Edge struct {
	// CreatedAt When the edge was created
	CreatedAt time.Time `json:"created_at,omitempty"`

	// Metadata Optional edge metadata
	Metadata map[string]interface{} `json:"metadata,omitempty"`

	// Source Base64-encoded source document key
	Source []byte `json:"source"`

	// Target Base64-encoded target document key
	Target []byte `json:"target"`

	// Type Edge type (e.g., "cites", "similar_to", "authored_by")
	Type string `json:"type"`

	// UpdatedAt When the edge was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`

	// Weight Edge weight/confidence (0.0 to 1.0)
	Weight float64 `json:"weight"`
}

// EdgeDirection Direction of edges to query:
// - out: Outgoing edges from the node
// - in: Incoming edges to the node
// - both: Both outgoing and incoming edges
type EdgeDirection string

// EdgeTypeConfig Configuration for a specific edge type
type EdgeTypeConfig struct {
	// AllowSelfLoops Whether to allow edges from a node to itself
	AllowSelfLoops bool `json:"allow_self_loops,omitempty"`

	// Field Document field containing target node key(s) for automatic edge creation.
	// Supports string (single target) or array of strings (multiple targets).
	// When omitted, edges must be provided explicitly via _edges.
	Field string `json:"field,omitempty"`

	// MaxWeight Maximum allowed edge weight
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum allowed edge weight
	MinWeight float64 `json:"min_weight,omitempty"`

	// Name Edge type name (e.g., 'cites', 'similar_to')
	Name string `json:"name"`

	// RequiredMetadata Required metadata fields for this edge type
	RequiredMetadata *[]string `json:"required_metadata,omitempty"`

	// Topology Topology constraint for this edge type:
	// - tree: Single parent per node, no cycles
	// - graph: No constraints (default)
	Topology EdgeTypeConfigTopology `json:"topology,omitempty"`
}

// EdgeTypeConfigTopology Topology constraint for this edge type:
// - tree: Single parent per node, no cycles
// - graph: No constraints (default)
type EdgeTypeConfigTopology string

// EmbeddingsIndexConfig Unified configuration for embeddings indexes. When sparse is true, creates a sparse vector index (SPLADE inverted index). When sparse is false (default), creates a dense vector index (HNSW). For dense indexes, dimension can be omitted if an embedder is configured — it will be auto-detected.
type EmbeddingsIndexConfig struct {
	// ChunkSize Number of documents per posting list chunk (sparse only)
	ChunkSize int `json:"chunk_size,omitempty"`

	// Chunker A unified configuration for a chunking provider.
	Chunker *externalRef0.ChunkerConfig `json:"chunker,omitempty"`

	// Dimension Vector dimension for dense indexes. Required for external dense indexes. Can be omitted for managed dense indexes when an embedder is configured (auto-detected via probe). Ignored for sparse indexes.
	Dimension int `json:"dimension,omitempty"`

	// DistanceMetric Distance metric for the vector index (dense only). Use "cosine" for models trained with cosine similarity (e.g. CLIP, OpenAI). Use "inner_product" for models trained with dot product similarity. Use "l2_squared" (default) for models trained with Euclidean distance.
	DistanceMetric DistanceMetric `json:"distance_metric,omitempty"`

	// Embedder A unified configuration for an embedding provider.
	//
	// Embedders can be configured with templates to customize how documents are
	// converted to text before embedding. Templates use Handlebars syntax and
	// support various built-in helpers.
	//
	// **Template System:**
	// - **Syntax**: Handlebars templating (https://handlebarsjs.com/guide/)
	// - **Caching**: Templates are automatically cached with configurable TTL (default: 5 minutes)
	// - **Context**: Templates receive the full document as context
	//
	// **Built-in Helpers:**
	//
	// 1. **scrubHtml** - Remove script/style tags and extract clean text from HTML
	//    ```handlebars
	//    {{scrubHtml html_content}}
	//    ```
	//    - Removes `<script>` and `<style>` tags
	//    - Adds newlines after block elements (p, div, h1-h6, li, etc.)
	//    - Returns plain text with preserved readability
	//
	// 2. **eq** - Equality comparison for conditionals
	//    ```handlebars
	//    {{#if (eq status "active")}}Active user{{/if}}
	//    {{#if (eq @key "special")}}Special field{{/if}}
	//    ```
	//
	// 3. **media** - GenKit dotprompt media directive for multimodal content
	//    ```handlebars
	//    {{media url=imageDataURI}}
	//    {{media url=this.image_url}}
	//    {{media url="https://example.com/image.jpg"}}
	//    {{media url="s3://endpoint/bucket/image.png"}}
	//    {{media url="file:///path/to/image.jpg"}}
	//    ```
	//
	//    **Supported URL Schemes:**
	//    - `data:` - Base64 encoded data URIs (e.g., `data:image/jpeg;base64,...`)
	//    - `http://` / `https://` - Web URLs with automatic content type detection
	//    - `file://` - Local filesystem paths
	//    - `s3://` - S3-compatible storage (format: `s3://endpoint/bucket/key`)
	//
	//    **Automatic Content Processing:**
	//    - **Images**: Downloaded, resized (if needed), converted to data URIs
	//    - **PDFs**: Text extracted or first page rendered as image
	//    - **HTML**: Readable text extracted using Mozilla Readability
	//
	//    **Security Controls:**
	//    Downloads are protected by content security settings (see Configuration Reference):
	//    - Allowed host whitelist
	//    - Private IP blocking (prevents SSRF attacks)
	//    - Download size limits (default: 100MB)
	//    - Download timeouts (default: 30s)
	//    - Image dimension limits (default: 2048px, auto-resized)
	//
	//    See: https://antfly.io/docs/configuration#security--cors
	//
	// 4. **encodeToon** - Encode data in TOON format (Token-Oriented Object Notation)
	//    ```handlebars
	//    {{encodeToon this.fields}}
	//    {{encodeToon this.fields lengthMarker=false indent=4}}
	//    {{encodeToon this.fields delimiter="\t"}}
	//    ```
	//
	//    **What is TOON?**
	//    TOON is a compact, human-readable format designed for passing structured data to LLMs.
	//    It provides **30-60% token reduction** compared to JSON while maintaining high LLM
	//    comprehension accuracy.
	//
	//    **Key Features:**
	//    - Compact syntax using `:` for key-value pairs
	//    - Array length markers: `tags[#3]: ai,search,ml`
	//    - Tabular format for uniform data structures
	//    - Optimized for LLM parsing and understanding
	//    - Maintains human readability
	//
	//    **Benefits:**
	//    - **Lower API costs** - Reduced token usage means lower LLM API costs
	//    - **Faster responses** - Less tokens to process
	//    - **More context** - Fit more documents within token limits
	//
	//    **Options:**
	//    - `lengthMarker` (bool): Add # prefix to array counts like `[#3]` (default: true)
	//    - `indent` (int): Indentation spacing for nested objects (default: 2)
	//    - `delimiter` (string): Field separator for tabular arrays (default: none, use `"\t"` for tabs)
	//
	//    **Example output:**
	//    ```
	//    title: Introduction to Vector Search
	//    author: Jane Doe
	//    tags[#3]: ai,search,ml
	//    metadata:
	//      edition: 2
	//      pages: 450
	//    ```
	//
	//    **Default in RAG:** TOON is the default format for document rendering in RAG queries.
	//
	//    **References:**
	//    - TOON Specification: https://github.com/toon-format/toon
	//    - Go Implementation: https://github.com/alpkeskin/gotoon
	//
	// **Template Examples:**
	//
	// Document with metadata:
	// ```handlebars
	// Title: {{metadata.title}}
	// Date: {{metadata.date}}
	// Tags: {{#each metadata.tags}}{{this}}, {{/each}}
	//
	// {{content}}
	// ```
	//
	// HTML content extraction:
	// ```handlebars
	// Product: {{name}}
	// Description: {{scrubHtml description_html}}
	// Price: ${{price}}
	// ```
	//
	// Multimodal with image:
	// ```handlebars
	// Product: {{title}}
	// {{media url=image}}
	// Description: {{description}}
	// ```
	//
	// Conditional formatting:
	// ```handlebars
	// {{title}}
	// {{#if author}}By: {{author}}{{/if}}
	// {{#if (eq category "premium")}}⭐ Premium Content{{/if}}
	// {{body}}
	// ```
	//
	// **Environment Variables:**
	// - `GEMINI_API_KEY` - API key for Google AI
	// - `OPENAI_API_KEY` - API key for OpenAI
	// - `OPENAI_BASE_URL` - Base URL for OpenAI-compatible APIs
	// - `OLLAMA_HOST` - Ollama server URL (e.g., http://localhost:11434)
	//
	// **Importing Pre-computed Embeddings:**
	//
	// You can import existing embeddings (from OpenAI, Cohere, or any provider), but only
	// for indexes configured with `external: true`. External indexes accept vectors written
	// directly through the document `_embeddings` field and do not generate prompts from
	// `field` or `template`.
	//
	// **Steps:**
	// 1. Create an embeddings index with `external: true`
	// 2. For dense indexes, set the index `dimension`
	// 3. Write documents with `_embeddings: { "<indexName>": [...<embedding>...] }`
	//
	// **Example:**
	// ```json
	// {
	//   "title": "My Document",
	//   "content": "Document text...",
	//   "_embeddings": {
	//     "my_vector_index": [0.1, 0.2, 0.3, ...]
	//   }
	// }
	// ```
	//
	// **Delete Behavior:**
	// - Use `"_embeddings": { "<indexName>": null }` to delete a stored external vector
	// - Omitting `_embeddings[<indexName>]` leaves the existing vector unchanged
	//
	// **Use Cases:**
	// - Migrating from another vector database with existing embeddings
	// - Using embeddings generated by external systems
	// - Importing pre-computed OpenAI, Cohere, or other provider embeddings
	// - Batch processing embeddings offline before ingestion
	Embedder *externalRef1.EmbedderConfig `json:"embedder,omitempty"`

	// EmbeddingName Generated embedding artifact name consumed by this vector index. Use with a matching embedding enrichment for artifact-backed managed embeddings.
	EmbeddingName string `json:"embedding_name,omitempty"`

	// External When true, embeddings are supplied externally via _embeddings and the index does not derive prompts from a field or template.
	External bool `json:"external,omitempty"`

	// Field Field to extract embeddings from (managed indexes only; not allowed when external=true)
	Field string `json:"field,omitempty"`

	// MemOnly Whether to use in-memory only storage (dense only)
	MemOnly bool `json:"mem_only,omitempty"`

	// MinWeight Minimum weight threshold for sparse vector entries (sparse only)
	MinWeight float32 `json:"min_weight,omitempty"`

	// SourceArtifactName Artifact stream consumed by the embedding enrichment backing this vector index. This is descriptive public configuration; the matching enrichment defines the materialized source.
	SourceArtifactName string `json:"source_artifact_name,omitempty"`

	// Sparse When true, creates a sparse (SPLADE) inverted index. When false (default), creates a dense (HNSW) vector index.
	Sparse bool `json:"sparse,omitempty"`

	// Summarizer A unified configuration for a generative AI provider.
	Summarizer *externalRef2.GeneratorConfig `json:"summarizer,omitempty"`

	// Template Handlebars template for generating prompts (managed indexes only; not allowed when external=true). See https://handlebarsjs.com/guide/ for more information.
	Template string `json:"template,omitempty"`

	// TopK Default number of results to return from search (sparse only)
	TopK int `json:"top_k,omitempty"`
}

// EmbeddingsIndexStats Statistics for an embeddings index (dense or sparse)
type EmbeddingsIndexStats struct {
	// BackfillItemsProcessed Total items processed during backfill
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Backfill progress as a ratio from 0.0 to 1.0
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// CheckpointReplayTailSequenceCount Number of derived-log sequences after the durable checkpoint that still need replay.
	CheckpointReplayTailSequenceCount uint64 `json:"checkpoint_replay_tail_sequence_count,omitempty"`

	// DiskUsage Size of the index in bytes
	DiskUsage uint64 `json:"disk_usage,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// IndexType Discriminator for the index stats variant.
	IndexType EmbeddingsIndexStatsIndexType `json:"index_type"`

	// ProjectionCheckpointAppliedSequence Highest derived-log sequence covered by the durable projection checkpoint.
	ProjectionCheckpointAppliedSequence uint64 `json:"projection_checkpoint_applied_sequence,omitempty"`

	// ProjectionCheckpointConfigHash Projection configuration identity associated with the durable checkpoint.
	ProjectionCheckpointConfigHash uint64 `json:"projection_checkpoint_config_hash,omitempty"`

	// ProjectionCheckpointGeneration Projection generation associated with the durable checkpoint.
	ProjectionCheckpointGeneration uint64 `json:"projection_checkpoint_generation,omitempty"`

	// ProjectionCheckpointStatus Durable projection checkpoint status: clean, rebuilding, degraded, or repair_required.
	ProjectionCheckpointStatus string `json:"projection_checkpoint_status,omitempty"`

	// Rebuilding Whether the index enricher is currently backfilling
	Rebuilding bool `json:"rebuilding,omitempty"`

	// RepairScanIssueCount Repair issues found by explicit repair-scan accounting for this projection.
	RepairScanIssueCount uint64 `json:"repair_scan_issue_count,omitempty"`

	// TotalIndexed Number of vectors/documents in the index
	TotalIndexed uint64 `json:"total_indexed,omitempty"`

	// TotalNodes Total number of nodes in the index (dense only)
	TotalNodes uint64 `json:"total_nodes,omitempty"`

	// TotalTerms Number of unique terms in the inverted index (sparse only)
	TotalTerms uint64 `json:"total_terms,omitempty"`

	// WalBacklog Number of documents pending enrichment in the WAL
	WalBacklog uint64 `json:"wal_backlog,omitempty"`
}

// EmbeddingsIndexStatsIndexType Discriminator for the index stats variant.
type EmbeddingsIndexStatsIndexType string

// EnrichmentConfig Inline managed enrichment definition. Enrichments materialize generated artifacts before indexing and may target source rows or previously generated artifact streams.
type EnrichmentConfig struct {
	// ChunkOverlap Chunk overlap for chunk enrichments.
	ChunkOverlap int `json:"chunk_overlap,omitempty"`

	// ChunkSize Chunk size for chunk enrichments.
	ChunkSize int `json:"chunk_size,omitempty"`

	// ChunkerJson Serialized chunker configuration for chunk enrichments.
	ChunkerJson string `json:"chunker_json,omitempty"`

	// ContentType Produced asset content type for asset enrichments.
	ContentType string `json:"content_type,omitempty"`

	// ExpectedDims Expected embedding dimension for embedding enrichments.
	ExpectedDims int `json:"expected_dims,omitempty"`

	// Field Source field to read from the source document or source artifact payload.
	Field string `json:"field,omitempty"`

	// FullTextIndex When true on a chunk or asset enrichment, route generated text into the table's default full-text index.
	FullTextIndex bool `json:"full_text_index,omitempty"`

	// Kind Managed generated artifact kind.
	Kind EnrichmentKind `json:"kind"`

	// Name Stable generated artifact name.
	Name string `json:"name"`

	// ProducerJson Serialized asset producer configuration.
	ProducerJson string `json:"producer_json,omitempty"`

	// SourceArtifactName Existing artifact stream this enrichment consumes. Chunk enrichments may consume asset artifacts; embedding enrichments may consume chunk artifacts.
	SourceArtifactName string `json:"source_artifact_name,omitempty"`

	// Template Optional template for generated text input.
	Template string `json:"template,omitempty"`
}

// EnrichmentKind Managed generated artifact kind.
type EnrichmentKind string

// FullTextIndexConfig defines model for FullTextIndexConfig.
type FullTextIndexConfig struct {
	// MemOnly Whether to use memory-only storage
	MemOnly bool `json:"mem_only,omitempty"`
}

// FullTextIndexStats defines model for FullTextIndexStats.
type FullTextIndexStats struct {
	// BackfillItemsProcessed Number of documents indexed during current rebuild
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Progress of ongoing rebuild as fraction [0.0, 1.0]
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// CheckpointReplayTailSequenceCount Number of derived-log sequences after the durable checkpoint that still need replay.
	CheckpointReplayTailSequenceCount uint64 `json:"checkpoint_replay_tail_sequence_count,omitempty"`

	// DiskUsage Size of the index in bytes
	DiskUsage uint64 `json:"disk_usage,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// IndexType Discriminator for the index stats variant.
	IndexType FullTextIndexStatsIndexType `json:"index_type"`

	// ProjectionCheckpointAppliedSequence Highest derived-log sequence covered by the durable projection checkpoint.
	ProjectionCheckpointAppliedSequence uint64 `json:"projection_checkpoint_applied_sequence,omitempty"`

	// ProjectionCheckpointConfigHash Projection configuration identity associated with the durable checkpoint.
	ProjectionCheckpointConfigHash uint64 `json:"projection_checkpoint_config_hash,omitempty"`

	// ProjectionCheckpointGeneration Projection generation associated with the durable checkpoint.
	ProjectionCheckpointGeneration uint64 `json:"projection_checkpoint_generation,omitempty"`

	// ProjectionCheckpointStatus Durable projection checkpoint status: clean, rebuilding, degraded, or repair_required.
	ProjectionCheckpointStatus string `json:"projection_checkpoint_status,omitempty"`

	// Rebuilding Whether the index is currently rebuilding
	Rebuilding bool `json:"rebuilding,omitempty"`

	// RepairScanIssueCount Repair issues found by explicit repair-scan accounting for this projection.
	RepairScanIssueCount uint64 `json:"repair_scan_issue_count,omitempty"`

	// TotalIndexed Number of documents in the index
	TotalIndexed uint64 `json:"total_indexed,omitempty"`
}

// FullTextIndexStatsIndexType Discriminator for the index stats variant.
type FullTextIndexStatsIndexType string

// GraphIndexConfig Configuration for graph index type
type GraphIndexConfig struct {
	// EdgeTypes List of edge types with their configurations
	EdgeTypes *[]EdgeTypeConfig `json:"edge_types,omitempty"`

	// MaxEdgesPerDocument Maximum number of edges per document (0 = unlimited)
	MaxEdgesPerDocument int `json:"max_edges_per_document,omitempty"`

	// Summarizer A unified configuration for a generative AI provider.
	Summarizer *externalRef2.GeneratorConfig `json:"summarizer,omitempty"`

	// Template Handlebars template for generating summarizer input text.
	// Uses document fields as template variables.
	// Same pattern as EmbeddingsConfig template.
	Template string `json:"template,omitempty"`
}

// GraphIndexStats Statistics for graph index
type GraphIndexStats struct {
	// AlgebraicGraph Algebraic graph execution health for bounded semiring traversal.
	AlgebraicGraph struct {
		Traversal *struct {
			Attempted   *uint64 `json:"attempted,omitempty"`
			Fallback    *uint64 `json:"fallback,omitempty"`
			Proven      *uint64 `json:"proven,omitempty"`
			Rejected    *uint64 `json:"rejected,omitempty"`
			ResultNodes *uint64 `json:"result_nodes,omitempty"`
		} `json:"traversal,omitempty"`
	} `json:"algebraic_graph,omitempty"`

	// BackfillItemsProcessed Number of edges indexed during current rebuild
	BackfillItemsProcessed uint64 `json:"backfill_items_processed,omitempty"`

	// BackfillProgress Rebuild progress as a ratio from 0.0 to 1.0
	BackfillProgress float64 `json:"backfill_progress,omitempty"`

	// CheckpointReplayTailSequenceCount Number of derived-log sequences after the durable checkpoint that still need replay.
	CheckpointReplayTailSequenceCount uint64 `json:"checkpoint_replay_tail_sequence_count,omitempty"`

	// EdgeTypes Count of edges per edge type
	EdgeTypes *map[string]uint64 `json:"edge_types,omitempty"`

	// Error Error message if stats could not be retrieved
	Error string `json:"error,omitempty"`

	// IndexType Discriminator for the index stats variant.
	IndexType GraphIndexStatsIndexType `json:"index_type"`

	// ProjectionCheckpointAppliedSequence Highest derived-log sequence covered by the durable projection checkpoint.
	ProjectionCheckpointAppliedSequence uint64 `json:"projection_checkpoint_applied_sequence,omitempty"`

	// ProjectionCheckpointConfigHash Projection configuration identity associated with the durable checkpoint.
	ProjectionCheckpointConfigHash uint64 `json:"projection_checkpoint_config_hash,omitempty"`

	// ProjectionCheckpointGeneration Projection generation associated with the durable checkpoint.
	ProjectionCheckpointGeneration uint64 `json:"projection_checkpoint_generation,omitempty"`

	// ProjectionCheckpointStatus Durable projection checkpoint status: clean, rebuilding, degraded, or repair_required.
	ProjectionCheckpointStatus string `json:"projection_checkpoint_status,omitempty"`

	// Rebuilding Whether the index is currently rebuilding
	Rebuilding bool `json:"rebuilding,omitempty"`

	// RepairScanIssueCount Repair issues found by explicit repair-scan accounting for this projection.
	RepairScanIssueCount uint64 `json:"repair_scan_issue_count,omitempty"`

	// TotalEdges Total number of edges in the graph
	TotalEdges uint64 `json:"total_edges,omitempty"`
}

// GraphIndexStatsIndexType Discriminator for the index stats variant.
type GraphIndexStatsIndexType string

// GraphNodeSelector Defines how to select start/target nodes for graph queries
type GraphNodeSelector struct {
	// Keys Explicit list of node keys
	Keys []string `json:"keys,omitempty"`

	// Limit Maximum number of nodes to select from the referenced results
	Limit int `json:"limit,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`

	// ResultRef Reference to search results to use as nodes:
	// - "$full_text_results" - use full-text search results
	// - "$embeddings_results.index_name" - use vector search results from specific index
	ResultRef string `json:"result_ref,omitempty"`
}

// GraphQuery Declarative graph query to execute after full-text/vector searches
type GraphQuery struct {
	// Fields Which fields to return from documents
	Fields []string `json:"fields,omitempty"`

	// IncludeDocuments Fetch full documents for graph results
	IncludeDocuments bool `json:"include_documents,omitempty"`

	// IncludeEdges Include edge details for each node
	IncludeEdges bool `json:"include_edges,omitempty"`

	// IndexName Graph index name (must be graph type)
	IndexName string `json:"index_name"`

	// Params Parameters for graph traversal and pathfinding
	Params GraphQueryParams `json:"params,omitempty"`

	// Pattern Pattern steps for pattern query type
	Pattern []PatternStep `json:"pattern,omitempty"`

	// ReturnAliases Which aliases to return from pattern query (empty = all)
	ReturnAliases []string `json:"return_aliases,omitempty"`

	// StartNodes Defines how to select start/target nodes for graph queries
	StartNodes GraphNodeSelector `json:"start_nodes,omitempty"`

	// TargetNodes Defines how to select start/target nodes for graph queries
	TargetNodes GraphNodeSelector `json:"target_nodes,omitempty"`

	// Type Type of graph query to execute
	Type GraphQueryType `json:"type"`
}

// GraphQueryParams Parameters for graph traversal and pathfinding
type GraphQueryParams struct {
	// Algorithm Graph algorithm to run (e.g., 'pagerank', 'betweenness')
	Algorithm string `json:"algorithm,omitempty"`

	// AlgorithmParams Parameters for the graph algorithm
	AlgorithmParams map[string]interface{} `json:"algorithm_params,omitempty"`

	// DeduplicateNodes Remove duplicate nodes (traversal)
	DeduplicateNodes bool `json:"deduplicate_nodes,omitempty"`

	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter by edge types
	EdgeTypes []string `json:"edge_types,omitempty"`

	// IncludePaths Include path information (traversal)
	IncludePaths bool `json:"include_paths,omitempty"`

	// K Number of paths to find (k-shortest-paths)
	K int `json:"k,omitempty"`

	// MaxDepth Maximum traversal depth
	MaxDepth int `json:"max_depth,omitempty"`

	// MaxResults Maximum number of results (traversal)
	MaxResults int `json:"max_results,omitempty"`

	// MaxWeight Maximum edge weight
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum edge weight
	MinWeight float64 `json:"min_weight,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`

	// WeightMode Path weighting algorithm for pathfinding:
	// - min_hops: Minimize number of edges
	// - min_weight: Minimize sum of edge weights
	// - max_weight: Maximize product of edge weights
	WeightMode PathWeightMode `json:"weight_mode,omitempty"`
}

// GraphQueryResult Results of a graph query
type GraphQueryResult struct {
	// Matches Pattern matches (for pattern queries)
	Matches []PatternMatch `json:"matches,omitempty"`

	// Nodes Result nodes
	Nodes []GraphResultNode `json:"nodes,omitempty"`

	// Paths Result paths (for pathfinding queries)
	Paths []Path `json:"paths,omitempty"`

	// Took Query execution time
	Took time.Duration `json:"took,omitempty"`

	// Total Total number of results
	Total int `json:"total"`

	// Type Type of graph query to execute
	Type GraphQueryType `json:"type"`
}

// GraphQueryType Type of graph query to execute
type GraphQueryType string

// GraphResultNode A node in graph query results
type GraphResultNode struct {
	// Depth Distance from start node
	Depth int `json:"depth,omitempty"`

	// Distance Weighted distance
	Distance float64 `json:"distance,omitempty"`

	// Document Full document (if include_documents=true)
	Document map[string]interface{} `json:"document,omitempty"`

	// Edges Connected edges (when include_edges=true)
	Edges []Edge `json:"edges,omitempty"`

	// Evidence Parsed evidence envelope for provenance labels and edge metadata
	Evidence map[string]interface{} `json:"evidence,omitempty"`

	// Key Document key
	Key string `json:"key"`

	// Path Keys in path from start to this node
	Path []string `json:"path,omitempty"`

	// PathEdges Edges in path from start to this node
	PathEdges []PathEdge `json:"path_edges,omitempty"`

	// Provenance Algebraic provenance labels folded into this result, when requested by an algebraic graph executor
	Provenance []string `json:"provenance,omitempty"`
}

// IndexConfig Configuration for an index
type IndexConfig struct {
	// Description Optional description of the index and its purpose
	Description *string `json:"description,omitempty"`

	// Enrichments Inline managed enrichment definitions required by this index. Enrichments are table-level generated artifacts such as chunks, asset-derived document units, or embeddings over an artifact stream.
	Enrichments []EnrichmentConfig `json:"enrichments,omitempty"`

	// Name Name of the index
	Name string `json:"name"`

	// Type The type of the index.
	Type IndexType `json:"type"`

	// Version Version of the index implementation. Defaults to 0.
	Version int `json:"version,omitempty"`
	union   json.RawMessage
}

// IndexStats Statistics for an index
type IndexStats struct {
	union json.RawMessage
}

// IndexType The type of the index.
type IndexType string

// MergeConfig Configuration for result fusion when combining multiple search indexes.
type MergeConfig struct {
	// RankConstant RRF k constant (1/(k+rank)). Defaults to 60.0.
	RankConstant float64 `json:"rank_constant,omitempty"`

	// Strategy Merge strategy for combining results from the semantic_search and full_text_search.
	// rrf: Reciprocal Rank Fusion - combines scores using reciprocal rank formula
	// rsf: Relative Score Fusion - normalizes scores by min/max within a window and combines weighted scores
	// failover: Use full_text_search if embedding generation fails
	Strategy *MergeStrategy `json:"strategy,omitempty"`

	// Weights Named weights keyed by index name. `full_text` for the full-text search index;
	// embedding index names for vector indexes.
	// Unspecified indexes default to 1.0. Applied in both RRF and RSF.
	Weights *map[string]float64 `json:"weights,omitempty"`

	// WindowSize RSF normalization window size. Defaults to `limit`.
	WindowSize int `json:"window_size,omitempty"`
}

// MergeStrategy Merge strategy for combining results from the semantic_search and full_text_search.
// rrf: Reciprocal Rank Fusion - combines scores using reciprocal rank formula
// rsf: Relative Score Fusion - normalizes scores by min/max within a window and combines weighted scores
// failover: Use full_text_search if embedding generation fails
type MergeStrategy string

// NodeFilter Filter nodes during graph traversal using existing query primitives
type NodeFilter struct {
	// FilterPrefix Filter by key prefix
	FilterPrefix string `json:"filter_prefix,omitempty"`

	// FilterQuery Antfly query to filter nodes (same syntax as search filter_query)
	FilterQuery map[string]interface{} `json:"filter_query,omitempty"`
}

// Path defines model for Path.
type Path struct {
	Edges  []PathEdge `json:"edges,omitempty"`
	Length int        `json:"length,omitempty"`

	// Nodes Ordered list of node keys (base64-encoded)
	Nodes       []string `json:"nodes,omitempty"`
	TotalWeight float64  `json:"total_weight,omitempty"`
}

// PathEdge defines model for PathEdge.
type PathEdge struct {
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Source   string                 `json:"source,omitempty"`
	Target   string                 `json:"target,omitempty"`
	Type     string                 `json:"type,omitempty"`
	Weight   float64                `json:"weight,omitempty"`
}

// PathFindRequest defines model for PathFindRequest.
type PathFindRequest struct {
	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter by specific edge types
	EdgeTypes []string `json:"edge_types,omitempty"`
	K         int      `json:"k,omitempty"`
	MaxDepth  int      `json:"max_depth,omitempty"`
	MaxWeight float64  `json:"max_weight,omitempty"`
	MinWeight float64  `json:"min_weight,omitempty"`

	// Source Source node key (base64-encoded)
	Source string `json:"source"`

	// Target Target node key (base64-encoded)
	Target string `json:"target"`

	// WeightMode Algorithm for path finding:
	// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
	// - max_weight: Path with maximum product of edge weights (strongest connection chain)
	// - min_weight: Path with minimum sum of edge weights (lowest cost route)
	WeightMode PathFindWeightMode `json:"weight_mode,omitempty"`
}

// PathFindResult defines model for PathFindResult.
type PathFindResult struct {
	Paths        []Path  `json:"paths,omitempty"`
	PathsFound   int     `json:"paths_found,omitempty"`
	SearchTimeMs float64 `json:"search_time_ms,omitempty"`
	Source       string  `json:"source,omitempty"`
	Target       string  `json:"target,omitempty"`

	// WeightMode Algorithm for path finding:
	// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
	// - max_weight: Path with maximum product of edge weights (strongest connection chain)
	// - min_weight: Path with minimum sum of edge weights (lowest cost route)
	WeightMode PathFindWeightMode `json:"weight_mode,omitempty"`
}

// PathFindWeightMode Algorithm for path finding:
// - min_hops: Shortest path by hop count (breadth-first search, ignores weights)
// - max_weight: Path with maximum product of edge weights (strongest connection chain)
// - min_weight: Path with minimum sum of edge weights (lowest cost route)
type PathFindWeightMode string

// PathWeightMode Path weighting algorithm for pathfinding:
// - min_hops: Minimize number of edges
// - min_weight: Minimize sum of edge weights
// - max_weight: Maximize product of edge weights
type PathWeightMode string

// PatternEdgeStep Edge constraints in a pattern step
type PatternEdgeStep struct {
	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// MaxHops Maximum number of hops (>1 = variable-length path)
	MaxHops int `json:"max_hops,omitempty"`

	// MaxWeight Maximum edge weight filter
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinHops Minimum number of hops (1 = direct edge)
	MinHops int `json:"min_hops,omitempty"`

	// MinWeight Minimum edge weight filter
	MinWeight float64 `json:"min_weight,omitempty"`

	// Types Edge types to traverse (empty = any)
	Types []string `json:"types,omitempty"`
}

// PatternMatch A single match from a pattern query
type PatternMatch struct {
	// Bindings Map of alias to matched node
	Bindings map[string]GraphResultNode `json:"bindings,omitempty"`

	// Path Edges traversed in this match
	Path []PathEdge `json:"path,omitempty"`
}

// PatternStep A step in a graph pattern query
type PatternStep struct {
	// Alias Name for this node (reuse alias for cycle detection)
	Alias string `json:"alias,omitempty"`

	// Edge Edge constraints in a pattern step
	Edge PatternEdgeStep `json:"edge,omitempty"`

	// NodeFilter Filter nodes during graph traversal using existing query primitives
	NodeFilter NodeFilter `json:"node_filter,omitempty"`
}

// Pruner Configuration for pruning search results based on score quality.
// Helps filter out low-relevance results in RAG pipelines by detecting
// score gaps or deviations from top results.
type Pruner struct {
	// MaxScoreGapPercent Stop returning results when the gap between consecutive scores
	// exceeds this percentage of the total score range (max - min).
	// Detects "elbows" in score distributions regardless of score scale.
	// For example, 30.0 stops when a gap spans 30% of the score range.
	MaxScoreGapPercent float64 `json:"max_score_gap_percent,omitempty"`

	// MinAbsoluteScore Hard minimum score threshold. Results with scores below this value
	// are excluded regardless of other pruning settings.
	MinAbsoluteScore float64 `json:"min_absolute_score,omitempty"`

	// MinScoreRatio Keep only results with score >= max_score * min_score_ratio.
	// For example, 0.5 keeps results scoring at least half of the top result.
	// Applied after fusion scoring.
	MinScoreRatio float64 `json:"min_score_ratio,omitempty"`

	// RequireMultiIndex Only keep results that appear in multiple indexes (both full-text
	// and vector search). Useful for increasing precision by requiring
	// agreement between different retrieval methods.
	RequireMultiIndex bool `json:"require_multi_index,omitempty"`

	// StdDevThreshold Keep results within N standard deviations below the mean score.
	// For example, 1.0 keeps results with score >= mean - 1*stddev.
	// Useful for statistical outlier detection in result sets.
	StdDevThreshold float64 `json:"std_dev_threshold,omitempty"`
}

// SortDirection Sort direction for a single field. true = descending, false = ascending.
type SortDirection = bool

// SortField A single sort field with direction.
type SortField struct {
	// Desc Sort direction. true = descending, false = ascending.
	Desc *bool `json:"desc,omitempty"`

	// Field The field name to sort by.
	Field string `json:"field"`
}

// TraversalResult A single result from graph traversal
type TraversalResult struct {
	// Depth Distance from start node (0 = start node)
	Depth int `json:"depth"`

	// Document Document data (if loaded)
	Document map[string]interface{} `json:"document,omitempty"`

	// Key Base64-encoded document key
	Key []byte `json:"key"`

	// Path Sequence of keys from start to this node (if include_paths=true)
	Path [][]byte `json:"path,omitempty"`

	// PathEdges Sequence of edges from start to this node (if include_paths=true)
	PathEdges []Edge `json:"path_edges,omitempty"`

	// TotalWeight Product of edge weights along the path
	TotalWeight float64 `json:"total_weight,omitempty"`
}

// TraversalRules Rules for graph traversal
type TraversalRules struct {
	// DeduplicateNodes Visit each node only once
	DeduplicateNodes bool `json:"deduplicate_nodes,omitempty"`

	// Direction Direction of edges to query:
	// - out: Outgoing edges from the node
	// - in: Incoming edges to the node
	// - both: Both outgoing and incoming edges
	Direction EdgeDirection `json:"direction,omitempty"`

	// EdgeTypes Filter edges by type (empty = all types)
	EdgeTypes []string `json:"edge_types,omitempty"`

	// IncludePaths Include path information in results
	IncludePaths bool `json:"include_paths,omitempty"`

	// MaxDepth Maximum traversal depth (0 = unlimited)
	MaxDepth int `json:"max_depth,omitempty"`

	// MaxResults Maximum results to return (0 = unlimited)
	MaxResults int `json:"max_results,omitempty"`

	// MaxWeight Maximum edge weight filter
	MaxWeight float64 `json:"max_weight,omitempty"`

	// MinWeight Minimum edge weight filter
	MinWeight float64 `json:"min_weight,omitempty"`
}

// AsFullTextIndexConfig returns the union data inside the IndexConfig as a FullTextIndexConfig
func (t IndexConfig) AsFullTextIndexConfig() (FullTextIndexConfig, error) {
	var body FullTextIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFullTextIndexConfig overwrites any union data inside the IndexConfig as the provided FullTextIndexConfig
func (t *IndexConfig) FromFullTextIndexConfig(v FullTextIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFullTextIndexConfig performs a merge with any union data inside the IndexConfig, using the provided FullTextIndexConfig
func (t *IndexConfig) MergeFullTextIndexConfig(v FullTextIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbeddingsIndexConfig returns the union data inside the IndexConfig as a EmbeddingsIndexConfig
func (t IndexConfig) AsEmbeddingsIndexConfig() (EmbeddingsIndexConfig, error) {
	var body EmbeddingsIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsIndexConfig overwrites any union data inside the IndexConfig as the provided EmbeddingsIndexConfig
func (t *IndexConfig) FromEmbeddingsIndexConfig(v EmbeddingsIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsIndexConfig performs a merge with any union data inside the IndexConfig, using the provided EmbeddingsIndexConfig
func (t *IndexConfig) MergeEmbeddingsIndexConfig(v EmbeddingsIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGraphIndexConfig returns the union data inside the IndexConfig as a GraphIndexConfig
func (t IndexConfig) AsGraphIndexConfig() (GraphIndexConfig, error) {
	var body GraphIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGraphIndexConfig overwrites any union data inside the IndexConfig as the provided GraphIndexConfig
func (t *IndexConfig) FromGraphIndexConfig(v GraphIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGraphIndexConfig performs a merge with any union data inside the IndexConfig, using the provided GraphIndexConfig
func (t *IndexConfig) MergeGraphIndexConfig(v GraphIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAlgebraicIndexConfig returns the union data inside the IndexConfig as a AlgebraicIndexConfig
func (t IndexConfig) AsAlgebraicIndexConfig() (AlgebraicIndexConfig, error) {
	var body AlgebraicIndexConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlgebraicIndexConfig overwrites any union data inside the IndexConfig as the provided AlgebraicIndexConfig
func (t *IndexConfig) FromAlgebraicIndexConfig(v AlgebraicIndexConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlgebraicIndexConfig performs a merge with any union data inside the IndexConfig, using the provided AlgebraicIndexConfig
func (t *IndexConfig) MergeAlgebraicIndexConfig(v AlgebraicIndexConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IndexConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Description != nil {
		object["description"], err = json.Marshal(t.Description)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'description': %w", err)
		}
	}

	if t.Enrichments != nil {
		object["enrichments"], err = json.Marshal(t.Enrichments)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'enrichments': %w", err)
		}
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["type"], err = json.Marshal(t.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	object["version"], err = json.Marshal(t.Version)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'version': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *IndexConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["description"]; found {
		err = json.Unmarshal(raw, &t.Description)
		if err != nil {
			return fmt.Errorf("error reading 'description': %w", err)
		}
	}

	if raw, found := object["enrichments"]; found {
		err = json.Unmarshal(raw, &t.Enrichments)
		if err != nil {
			return fmt.Errorf("error reading 'enrichments': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &t.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &t.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
	}

	return err
}

// AsFullTextIndexStats returns the union data inside the IndexStats as a FullTextIndexStats
func (t IndexStats) AsFullTextIndexStats() (FullTextIndexStats, error) {
	var body FullTextIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFullTextIndexStats overwrites any union data inside the IndexStats as the provided FullTextIndexStats
func (t *IndexStats) FromFullTextIndexStats(v FullTextIndexStats) error {
	v.IndexType = "full_text"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFullTextIndexStats performs a merge with any union data inside the IndexStats, using the provided FullTextIndexStats
func (t *IndexStats) MergeFullTextIndexStats(v FullTextIndexStats) error {
	v.IndexType = "full_text"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEmbeddingsIndexStats returns the union data inside the IndexStats as a EmbeddingsIndexStats
func (t IndexStats) AsEmbeddingsIndexStats() (EmbeddingsIndexStats, error) {
	var body EmbeddingsIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEmbeddingsIndexStats overwrites any union data inside the IndexStats as the provided EmbeddingsIndexStats
func (t *IndexStats) FromEmbeddingsIndexStats(v EmbeddingsIndexStats) error {
	v.IndexType = "embeddings"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEmbeddingsIndexStats performs a merge with any union data inside the IndexStats, using the provided EmbeddingsIndexStats
func (t *IndexStats) MergeEmbeddingsIndexStats(v EmbeddingsIndexStats) error {
	v.IndexType = "embeddings"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsGraphIndexStats returns the union data inside the IndexStats as a GraphIndexStats
func (t IndexStats) AsGraphIndexStats() (GraphIndexStats, error) {
	var body GraphIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGraphIndexStats overwrites any union data inside the IndexStats as the provided GraphIndexStats
func (t *IndexStats) FromGraphIndexStats(v GraphIndexStats) error {
	v.IndexType = "graph"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGraphIndexStats performs a merge with any union data inside the IndexStats, using the provided GraphIndexStats
func (t *IndexStats) MergeGraphIndexStats(v GraphIndexStats) error {
	v.IndexType = "graph"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAlgebraicIndexStats returns the union data inside the IndexStats as a AlgebraicIndexStats
func (t IndexStats) AsAlgebraicIndexStats() (AlgebraicIndexStats, error) {
	var body AlgebraicIndexStats
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlgebraicIndexStats overwrites any union data inside the IndexStats as the provided AlgebraicIndexStats
func (t *IndexStats) FromAlgebraicIndexStats(v AlgebraicIndexStats) error {
	v.IndexType = "algebraic"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlgebraicIndexStats performs a merge with any union data inside the IndexStats, using the provided AlgebraicIndexStats
func (t *IndexStats) MergeAlgebraicIndexStats(v AlgebraicIndexStats) error {
	v.IndexType = "algebraic"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IndexStats) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"index_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t IndexStats) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "algebraic":
		return t.AsAlgebraicIndexStats()
	case "embeddings":
		return t.AsEmbeddingsIndexStats()
	case "full_text":
		return t.AsFullTextIndexStats()
	case "graph":
		return t.AsGraphIndexStats()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t IndexStats) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *IndexStats) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x923IjN5Lor+BwdqOlXpKiutseLycce2S12tZMX3Ra8ngnhg4KrAJJWFVAGUBJohWK",
	"2E84D/sb56f2S04gE0BdeZFItXtn+8VWs3BJAHlHZuKuE8k0k4IJozvDu46O5iyl8OdRMmMTRXl0KmJ2",
	"eyzFlM/s7zHTkeKZ4VJ0hp1z6NCLmeLXLCbUdyKaxyyiikTQMVfUduiTs3yS8Igo9mvOtNEkpQsiM0O4",
	"MJLg7AQGg/ZdcjPnCSMpNUxxmvDf4GdNFEspF4SJGResJ28Ei/udbidTMmPKcKYRUgvUeKpkOsahm/D/",
	"NGeCGJWzLk7LiJmz0jIimtEJT7hZhBXZ8aCVoZOEOaD75FQYpgRNyJSzJNaEirgON4nZlAuOS6CKESEN",
	"yXBHjs5O7QrMImOdYWciZcKo6HQ7t72Z7Nlfe/qKZz0JgNOkl0luJ+wMLfD396GnnPzCItO579YO8NxQ",
	"o5vrP5ZpRqMAhTbUcG14pMlUKkJFy4lyO1yfvGaG8oTFROXC8JR1CY1pZvi1/atl7YpFUsXh6LjfrpjT",
	"mZAwZ/MIaWQHHGdKzhTTepzwKYsWUcLsR7dibRQXs423qtsYVMkbbf8VMa1ZbEeeSpVS0xl2ci7M16+K",
	"c7EDzZjaYjJD1YwZmHPXM7ntH09odDXlScLFbBzJXJinmiiyOJpnY3u0acpEzOKnnTDs4pPOohiNF087",
	"hTY0YU8yhT/8MTcsraF1lfTf5+mEKSKnJJZRnloRQEJzEueWqkiUK8WEIX7YTvdJgPUH24TyO9eE+CaE",
	"akIJyBNkxYP+gBhJDvuDMnCxzCcJK4ATsNoHwFZw/oLr2HMzuX6AGCzJjzBKF3gru6VpljC/w10CONEl",
	"UhHFJjlP4rGVklyhaHsss4vmLLqCH8eKZQldjC3bHmsrgEVUwsGlyIFr6iVyRnwvTejUMAVSMM4VyMFi",
	"ImLm1BBt7KkJZiUETNzfLe7EXF+Nc01nrOU4+G/Mwm7hA3FFuCCThWF6tzAwpaRqTn9ifyYp0xY6wqcg",
	"VjWJZJ7EIPMnjChmFGfXLN7ibOeMJma+KMnCh+oN3Q5szxi719fxmtt/pVxQIxUgbbGhuKRrqjgVxh4t",
	"E3naGf69E3C/8/PjV5ZQbcawu5YbawvN4+V9RpVmbrSnYLlZQoVgajylSWI52pNOAjsTs4hrjrvi912z",
	"hEUG8MkDss0JVOZj2nCrz1mWpPPEjCd5dMXa9Mm31DBtSgzQjUOwYw87Ej9gQCo7DfFLsDzQr4H4te6Y",
	"fSxZn46oCMrZhkuzfXpK3nxuqwr4uAMS8uMGSThJZHRlNcynGBw0sK3Ymh8zUMWOqVFJa2ZxKcYlAUuz",
	"LOEWiZyYbOLQD3w2t0jUJlRJJK+ZYjGZLCqCtZirJGN3jTet60HbfTynet5cylkJrLKNT3jMhLEKD9Va",
	"RtySFbnhZr5EW/gkK5kxwRC8lQspmn1OwC9TOl+vQhCCvYYEjLSu1ym5mHVJzGaKxix2ymZGudqJrlnM",
	"0epoMXOnMgZPgvbab7IoAfh4N4gFwZmiFHdxnXZbnj8YsWWnx5xmTO/4mN2Wg6zhWudLtfCP0JBAG02m",
	"MhfAHdhtlvCIG3d2PTsQoREMYo02FD9clzBjxytAp9f4mimvhuxwcCMNTcagZm5qtyo2dUKWi5oHzyHb",
	"LtcPR4jkYjWvkgr9c5sfTphpsrhwGnahrlEVzcdUjxcyx87dzhVb3EgFJgG7NZ1uZ25Sa3KLPGWKR51u",
	"J6aGGZ7axgVxJFxcdbqdGZMAJ/4JmGv18nTCYkdWk0ROmkrhfddq+oaKiL2zVkmEez6leWJ3K3kx1r/m",
	"VIFq2TAQoBtJoV/Qe65ZZC0GtBT2YiY0I1Iki/0++VEzMupEUnPBRh3okcqYJZoYRbnw7BYbEM1TnlBl",
	"pcke68/65Pjt6VmXfMiYODoNo3EQ9ZmScR6ZFYPG0hDXqjSyH6VY56hjgYb17y8d7CSPEh4zKkjsdqFs",
	"BVU2rQJfp+tWv412fhK3mb1HxHaNu+SG8dncUkMkhXCiYcLMDWOiIJqGszVSDHRgapb5yeeMsHjGyA3V",
	"xLWu+FyoYT2HnY9dWcoMjakBVz2NY47NzkqAgre+Bt4HNxyCF8aoU+MDGJzMVZsC9x3V7OtXPSYiaQUF",
	"Ngt7Sq7Yorwhk4XZZi/QV7wWCGz2ZEC0ugYsAgK2IV12LU1zw/SoY/90xDU2Ev9NczOXisXjyWLU2d8C",
	"mDyLH4CiYH65LrvGUySxJRuDHw9AL45Bt98rvJT7O3RT1iSRw9qAOW7YAO3PjycIu67XXCEzqQoImZsW",
	"yeCaWjltD0Tb1f+aM7UYjkSPyNwMyYfczKRVWLBBuFgTMma2ERdDcioimRZtjKy0mEgzH5LvpJnbEXEw",
	"KqwWUO41EiXOjNByARLUzLflwlauL7scPa7YRXChRnTGIj7lEWKpO57apVeSyBtruU7HiZSZrux2G/cL",
	"urUk0Le8nxT2yn7ixg65jXINN5stdohnPPDdyhxDubC77zgTQHDFFnsaxSnNjUyp8ZsAksTqqCNxnmeZ",
	"VEYTPAuyp7mYJcwNtG/tFaoUXViswiaa7KV5YngWWun9/kgAM5ApN8bKQ9yPNNfges2UvOaWcXo9OlmQ",
	"a07JGJr1AVseLb7o7bjMGtypHdaP7B295Wme4nlZUAq2sdNbjJSLNngGDXi4+CTwCJqulCb2uxcpz0Ci",
	"POuSZ4U8edaUHiUeOC5rD3VTCpsE5cDf0wdjqUyQcHnW9GkV1+yAhfBvmclEzhZVljhTNJs3mOKFa2tJ",
	"RIMyaVqmB/5oFGNDco7Yn1G4g8uYAlLqEiEJOMq0bQpzDcl7WRpWFwpshfnZYa15AOA9mvPVpA6caZvl",
	"c+JND70yhuRHwaccldUauwy2i0Zbguk+AcrW4NMnXLvYDVRGNfBX+FK1QM7P3h69PiFcXDOFRmLMbvcb",
	"Y01polmxc+Vh0YapjvrD+/Of9vvkjVTus4OxS2KeMqHBIUOt5u05EeFTQoVbFkMHiFs0i8l//cd/Em7I",
	"DU8S28dyyV7MDNi1zdCIaJ6Lq7Hmv7Eqpxm8eNXd5KaXKZJJDf6ChGtDYDyy53YDrLUO8A/LFzrDr19t",
	"YdHD2Axuyv5JsWln2PnDQRF4dOCijg6gGRez8TG2dwgDl31uQ5vY81c8k2LLp/Xz6JNA/Hjx6iNPqo2O",
	"q0cFdh8VdMbiaktyY7Fm+THuVQ4OJEum5ITt98npTEgPhkc7N315rw+3uxYFY3ScBlN+1ZbXDP977y9Y",
	"f1gFbY5PXJfivMLHcTvD/x4drVbQ+JaEKsOnNDIoAywvy1PvDee6QntosoMZTklKTTQHXS8MxYTi0Rx1",
	"ElAZcOTehEZXVgS4Yy2WsI3X0+NThQyBlXSXB5uVOBtVjOgcrw4CcgaVpNROxKX711gyDXfJLmwtUzLN",
	"TFD6UBWzsoWlWUIN6z+B4vcGJjHSQq3syZWgBTj2/E570rFs5U8Atlc0gJj8qr+18+1v5T1Ix3aOFf5n",
	"SXIgu17KUqkWABLRRio6YxVf1TYb9lC1C9sSM1dMz2VS4RAO8ZkwijPd4NBBN5smkpotVDM0HseeWJZQ",
	"7pGnUm0Uo2mNTlk7EVq6A3ugScgX9ieuSZjF4jIGI1b0gT/B6AWtF4NDUKU1DeflQNHgnNmGtHGrH0TY",
	"DU3EKR/7Ne3DKR9rVQ7UMqqbtg1m6jxNqeK/rWfw1lLVY5kxQTM+1nNqFWx/QyZmY8fDZYnte2bTcvFJ",
	"RZywCVU6cCTA8WK8wMEexzT65JwxMjcm08ODg3mY7hfdj2R6MMt5zA6cM1dZ+ke6cVcjLhjLAsqSRHbJ",
	"3d0f+JTssV/JeyuNRp0/y7kYdfbv7+0f1MypuLtjiWb393d3ton9/wGf3t//L/I3mQNTv7s7mrH7e7Jg",
	"dtky2epuzchsfFXT9BpOF/xERND3MOoC3CaKmVwJ5Mt4+bBc2Tvc5mpknRmwJBL5vBF6XNf+A3f2rHG/",
	"oRRvHv14IQ1NCDRrRj3+D4x2/BIm+A8bJrjzEL+CMLeKMPsSQ/MlhuZLDM0jY2iQRFENZrVQmlICyHax",
	"NP/dw1Q2jiRB9VofFP4xF0cCfZ8CKCFjppepJYUCB80qwNRt1J1DZphK9arNygX/NWcE2hWglY2b5Ubq",
	"9kDe0AQynBI52zCnhYm6PeqA/uno7e8XFnQSwFnmFz8VCRes8FbVTF6OGZXFOLps/no+zOLg/tJkwqZo",
	"/MTs1l+VpnTh7+lcNIOSN9pytUyxay5znSxaBnP2v17mmLZyOKFZy6Uo+JndZ+AB6Hkulld1hg629TuX",
	"fORNOOy3TwEEU+NfdJvkPC/8Fa5hyz1IK3CPzgiSwjBhliiEZxClZA9aa2aIa4yXc2CXwc87AoXdZuAk",
	"H8e8jeWcuM8lp1LVzd/mbNrdwS3xep4jlUy981MxGhexC/WIIGus4k+BcjK6SCTdSkuY5oll1LcGhdsD",
	"PFTE6mUOoVqOs0uUzE2Ze9hZMD075Dw/08TNRiwgPddkW9fUFRfxOqdUwe3+YlsvvVE+x+TsFr5l2/fb",
	"LpExPm8TQsVN8+1rKe7buBs38sCe3HK8tquxYneNXEgJ55rVfXJc5x/A9d13t5wgJf7UTlaVLog/octW",
	"jq2lPsMQ1NfmMSwwM8vN4+dvu8p2mLhaaP/FIWs9rANldQve2THLRjRsYafbgd2vxOm2Bei+yZPkgt2a",
	"2kV6VfJufPuBVx+98tXHbmsPVMANDr/H+uratDqn1NfzlJ359Mkdd2feXyenRAoMRHOwEKrJVFE0Lv8+",
	"6A+65LA/+PmL++6L++73cd8F5eGL9+6L9+6L9+738949Sf7b/xif3dP76h7m0Ple0Wy+MtCxGQ8OgZgO",
	"G1pjwVk8YzBlW0I618aH10NvHQiV16wSXY5pXWlfVUPaWwJeU3qLgdLjjKmxP4Q2VRgjnAtfJkZhZ0wV",
	"1vHegHxLcpHwlBsW72+VkvjZBjYUkKG1AoZLfyR+1EwXW+HLhpXGAdk9SSAm/ZymjGTUGKYsaybFpTpC",
	"WQR6YcBvCGi4uzPcJOz+fiTu7pw75/5+G4NpBeZvdrdfwvqW5AeXuDnGIOVmAFLI7MRh2C2LciAoLIcC",
	"M0wsP2Mx0SzlYB8YRa+Z0jRp+ivDp6aJYrc7zTYtH3BfqryxYftMyWsmNm2t2C+bFzOA9lCsI1w1rO/T",
	"PN37x6cMPcbAQx7xmRl3H50h9yUoY1cWVUWqtad5bobidQGbC1MVNeWsjgbj+kez7LbM6/hi1X2x6r5Y",
	"dV+suiez6oAtrw968EoAbKpPpfs9rbr3MmbnUEmqTVy8dgHoc3ljtQAsOWXxVJmDUgZsWff9NWeKs2YJ",
	"hiu2aL8HxeNLnMXnE2r15qmKD6i9Z42xTew5XFSx4nAHqtiUKcv6Yx+AvA3q2GnGU56Y9ZadPac32LJQ",
	"f6F9k1AciAg/hEOXgqVzzaySByuEfMxR55+KO1fXcNQhPWhZXIJWR3IdS5lS7kMfkU7QlIVBXIR/DRYM",
	"1/Y549Bti/zkLZR5oIP/kzO1aCOAKKFWvlyzEn4vMDPIWmfM6Zxhow4qq20hBLSG29gtj+beVq5FtZcr",
	"m+ycKriIkjxm42KSZjoUMxa2PElKvqmC5huk8JhinQjEEj56ip9R542hPjcCwGg0B2TebnKPsy35fCU/",
	"FqZw+2R7XLsdfpu8rowqut55VeDoGbaHnuAyaVGPnC9FG5bhLnnvikPeWib4qondWOeGZVugGOLymCac",
	"arYU993nOvJXgd9jaWYW5FtCk2T/KcgBpFvhWVh7KhUJGkrbbDOAs5o2wweovlWX/P6EC7z+eRf88Szg",
	"ah3hFE2ZYarMFILzCWLxMmrmUy6cuthwjEnFzTxdRn2hAaBGLkIZhYzOmKLi6lmXPHNVoATT+tk2BBkm",
	"GxekuXm5ptpWBDWvWMMWpZtiFudWX6KGLYuy/chSeW3tHtfOqTJ74TS2Sv6My2Vy1jnbi5o6Db9IPdnW",
	"6jWgzQd//1MKOouLK2SM/VzOotvV5l2t8mcBTBa9LZGQvauenktlmDY9+LLV/UFKb8cxy8x8uepbECs2",
	"3HI2rxBsoGp7dbB1kx83+7ICVn7yT1WRpi0d+smqzzzWlEBYxqlVodbrAvOfoPk723o3OvdHOP82RoZ4",
	"IaeEllXvhvSAxGmml6tBrgHZq2tCnOn9B+pB7+xYW7CgpVxbQ3YrfN0QIthC7PgejuPRQC3hhw4o5Ex+",
	"87wQf8wGbrNxRsoW/gkYVLonc5XvAlmt96d0hh3bqf/a+UIf6vhZ7/LZgZ9gdxohwrwTZfCi1blvf7Wr",
	"bjeWK/WagN3bn4TlKROp7B55sQdCutPtXI0rv4A57eyeLS4D6rTTUm8UHFFcVBZSHGX9Oa5W4RpqyKKr",
	"w9oVNVP18UVwWmwoXxk1NNmlfClHQ2yuDb8pewzIHp+ShrOhXhjlwRi5xGNwjPVhXcE3TfagskLFzRCm",
	"3jh+ZAsGxq6xXuaDzQltl+A6EyauWSJdwgpesQOGJXTCEiyks6s6sVdssaIgIlZifbzTo41e/sIW4BsH",
	"BbxEM5CgwbWnnZ3bBXa+ZY6nE++w3xSodTJwSzQqznxV/EgTM6YyiSGH0cONvKyLBUfco4V4k1l5Gq8c",
	"iSLV7ne/JqYsWm0hnR4Yo0ZFCNWRgn2YdoZ/X32AbbkK9901fKO1VOC6Xo2Qu3UdWh+1vP+5KapKW7I0",
	"LaX0czUMHSrQGk2yXGVSs7Zko1JizeMSPzXxGBEqpLm6QuWEUKpcylYvYdcsaU0K1Xk0J1RjTo/uYjpQ",
	"eMosyKVccKPhZrVUl0VeM3wlspqKVCmp8/dqrcKvDl+E1Dpf5h4zv0JKDPqYgzQdI2Tj68POshypoi2A",
	"aZtaVKjlF/7x62+WTV2ukt86/RiyrjeDoYDXotZmcrOeDbyF9dTqoYcyRmUsbcPKTVRooBzUnrud0gMQ",
	"y4uc/RUb1VI1LHLY9bqHYV3tIvDuDPo7u911CV1Lr3cfVpHIb1xcDs5B8zrLXHhA8f7ZRjwI5+6Wa6ps",
	"xiJ9xyKbYxN27Hu54Mp1bBWb3wf+uHiPqF66NL9/lFjwAz9IKmzWqQn9Q2SC67MUV5YYdHNXv7iM4+05",
	"N5Wj7oZKwSuezbvvdt4xNXtAmXFUW8g0B7oD5SWS6QSLcody2e6quVSBtCoFFRVXY6gpTFtjTT6+IVfE",
	"fyd7hwd7V/9i++zvV8n560F/0N+pnaWNFWJYdHnV0cK2nfvGwY+3WdThEigbQYeWJGLnrdRW5UeRXFyG",
	"9sllOP7LcOHRCBqADn8aiSL7thgCOVC5CCAEhf8oXGhAqVqez8zGeNQ+OXKVRbmAavnEHptVUD6ev6mF",
	"it+Vecmg/7LbgcjxogZpZ3jYFv59w0Usb5aUWfh4/oYIu6XhIWhsDpUXqnhyCZEnl/2nq0RXxYdKxW6l",
	"po163dCceGTDSgyBjCoRGpD5z1IqDI/G7jztJhcxI/hjfySUmg7JRxbxTMmIJuQjFVfkDVJqz43PNNGR",
	"VEyTXONcobklMAtJmid0JJSGwRKMvTi3fYqx/LYXo00WJOXiIKW3EPzHBaH+OCy0YfLwfgz2G4kp5YnV",
	"9YZQeLe+KsKnpZzxUrCh7VZ9fQG3WekpPFOJg7ZyvJL/fdlVGF7auRjx+nUqbhzzufLomsqs0LZb1RZw",
	"YsccZ4pN+e2q27crZseBVlvUb8DZfvXxNJv7OvA1qcJnOC3vxZ62Wp5eCENvrUrvjqc82+OdSFtcZJw5",
	"T0Yztwn++FRugYSJGQKyVTBai6r4QcUQ4twI0CN7k8pjPU8SjIHBlcWl2g5fl9nmxP0jVfUiBZs98LT9",
	"y03bP7u07ZtJ2z8u9Jkc5Rsu4o/o/mqe6FPHOzSfzHmSwIer+ostKd6Ed4aHg8GOqvPXggxKlXzDZF/t",
	"cq7dI1L9An+HSv2SJ9dcvSXPUts46q4fWLuovlu0yykfGElgCa8WTbDqwa+fd0HmPtSgSuXh/vtTXGTD",
	"ZGPIX9hKXLtXNg1P2TjVT4Wvv5+g2R6btkWX0nAVe8pyibnMdMOoOgphij5YgrhoCQi09/2G5NxdaWOb",
	"yYLMZUYgZYXsTRSjsZn3plxpb0B3CYfnVbz5ovdhvMAFh8TCjFlPjtuG10B9Fr234ve0UVLM7OylJzSj",
	"OeVi30PZMqoLX9J52hwxkTc4nDZYY22/ZBaVdqvEtiu8douL/FpIUlsM0NwBCnXFGifUfkAQrcV/Y/XM",
	"nfoGhXYt+1I/Iog+s22XnEzFmCzvWrFRlS3cbtcMU8IqLRDY3f5qWfnNLbCns1JceTMG4tGqkl3TvP4Y",
	"4NJn5YoTsX3I3igfDF6yQ/JtqCnQQ2MIjne/8yQqx9q4QmeY7jy8cIN9cpRa3ye7Q3hGAOfuNuZhQY9P",
	"sTFL1OyToniIkd5/wkoJBGKx/yQX2lsIniLGsCUkyb0YCfGM/jWkSnJE89EI5G4rvcIPjDGso34GEZoJ",
	"p7DLGGsZ18KcHrwT7fEhGIvhD9I9iM41TvrJYjC2P+B2nnsEfBU5Lbr8Vp8t7PmS29CQ9Qp6/p5ikPUH",
	"hwSu3kWUQBoVMuFtlH7mPCEbxM4GcfP4cOVt9l7los3j2rxiylQObvBavqI1lGIiBXqOya85TbhZ9Efi",
	"B5Zk2nsrZW5IIm96iiXsGgJwfH8uyMej70nGM5aAK3qy8EcgZiOBo85oBgWqY3bNsbyR88LLzA+EVxv1",
	"GOjbMQwwntFsnDEVtRYuOsdhTK4qfv4b/7z0jGbhMXUr/SGs9poFXzm7jRiLtUuoxlnoLFwNgrPObY+i",
	"YsbIXkpvCahM+/2ReA2r1WTUYclE3uhRx24Kto+5Rb1J7gNAZlTFias6iS10RBPWH4k38NAhXOx0yctB",
	"f0C0sRIO3y6ENeiMCk1eDv7ZQ1aCqXYz9HKwaxFNJ1omuWF4IG1llVRc6NMAWHgcrU982Dto3f5ugyXy",
	"xr0wRpOcjQRVjLBbCGWMa5slIWe/wGFj4BXA6qoH/cHhrteN+Ad01BbaxzJ8j041FkhQhfuWBCwmz0lt",
	"xPq5D/pfkSvGMh3Gs41BxTckYVQbMqfJtMBMTz79kfDXhj5xF+6UXPfGPn21y21y/o0x3FNvWt/6g901",
	"u9Yii3tODaFZxqiyBBRuvf096R7choZb2JGgIq4mYe/DM5PTPAGGx0WkGNX4UhmLOGzIZOHCsIA70Zli",
	"DB+8c/wh5lPIMze+XgxNSMrMXMbVd6Yf8Y6biccxux4HqliCTmVM4oK8J9pQEVvqKnFPTzuMpIw6ZlNH",
	"psP+oIZMbchpu/fI4XNt4phdY5Ezv4Pax9PQxEqAhDNViFd7Ri5sQTNTJ8XDXaJY283wuVSm9rx91Qep",
	"DAnGm3/KHTVNCCjrY3H1byEoEB+c6LrH/b4l1P/UUh7dzf2mvdZ8UGe1BQBLzsO2B1j6nbbgxfUEU13R",
	"NuAvKZN/Mfc18iEh3Ehcw2TRUny95tXEEdtCcC78/e6yhKiwYT4ExuoFtbvhbTMTsGph8e+tUvEelzIQ",
	"IszhJfM9PiWJpFXP9G5C2b+rOL6LaFCMbA8UOVkYtvNI93NfQEpO8S51SWB5JWUCPMfNnIXVkD5NVHwZ",
	"fkyv2GIBT5h0Ub8+bnsQpOkipYmEF10xFbizU/ZcD3bvOhLd4nqj4Bx50ppcaH9uS8xv4Rat+eWO2bZR",
	"61+55qYowoEqnsTko88zyxzRdYJVMCrVJNBXtP+JMs9XSbClmehBk9iq1kr7Ve3L7ma54busbNvIFQ/X",
	"xoNl0DTffd0xPC2PWy91Rn8Cj+9D3tp+UnC28L1A1gAXszGGeB3ja1BF0C9Nkg2irFuLG4ehYVBMYMHA",
	"6Jq3LOPjXCXtytyPH996S/FU+OpZR2enhIkYS/P5giNzY7LhwUEiI5rMpTbDbwbfDJ7t98kxZE1pSSbM",
	"avnwxP3R+4s3b/82Pn3/5uTjyfvjk7Gdh4lrrqQAVcPfWFTfaW6do1ImTvE2OZ/KmFWf6u9M+S2U8Wwu",
	"2e8bgV6uMFifnHBwHzyDjs/QtoF8BmLkFRM9dIL5zpAzQ90QoAuDGgD/1gfu0S99cGc/3R9UV+lBW60v",
	"45qa+vLP3bVuPHuaLqSQh0MNy86UvOYxU/2RGIlGM64JJRETRrl3kX64uDgjmqlrHjG0v90AuhgSL0qt",
	"Md4z1gCMKDzo3h8Ju+GlTUppBvzrw/v3/+5+R5En1cLFRO9pnvKEwrM2c3lDPiQJTSm5kepK7wPMz58f",
	"+4nfwX4Pnz8fiR6BfR2Sczw1+FcPnoILcFrZZw8z3DjnPDE9LrpEOJj8CcCF8JFYOKcSAH/Dk4S46tEW",
	"Oqudrzz2Ym0ObNwWB+7bwyF5B2/2wH4x3MUXvZSL3DBycfEWWr0YkjOmNNfwZNsZm0wSBhaCRUjb4hxs",
	"o2kCvK/QY8Izc1L4UstY7BQCjjHsS9djxQOvWEqKVk5gKpSLakLSC0jtscuqCoBbFtEh+Pyu494HHMMZ",
	"uP6aZVRhxk3H7lIIeym1Gtzfl1npCia6WdLKSqZ8/3OThba8zLa5Wdekz9r7ahYz5dSl6llF57uEXbP+",
	"SMD7bpliGlLI2TUTGJSdmcV+17cHrLSs10jl678Oo6kZEp1Pp9wlLrra237wZ5q4U3SeDjcZnWh4L859",
	"yzUjw6gyElVO1c0tOywlMBQJMBUn2MMvwAICbXiI7vjOfD/wo0nFApqu0zmPpTBKJuBHB2rHh9DACkdv",
	"P1AfvAvoHtbqE9gudKbsueGLM7GbVGRlcuHe5oINhM0rZVvatnh2blDAIUzr8MOJeEmPrR74KkubsOs/",
	"NwXMEckFpqM0H7GkLXKlylK2ZRAbcoOzEtqskPl+di/2y4EnMoKn2xCotvSFUs1P5ByYylZmRY8SzUWa",
	"xVrZjL8908SLLvLubZDOdgJg2GVswZyJQuBa8jwtCfHWHI8lAp3sOUT+l0AVwnih/IZRkyvmpfFbAMTO",
	"61SntolQDnryKInBgGlW2gVRWJq1Lgmx8/by0K7kBLG30C7IZMZgFT0meteH/a/I3h+//obEPNX7XWtA",
	"96wd8vZd7+3XvesXZO/lN6/wox0PRwGqRX9ekV106RQH5vAoaA6XherQf4iEftEpJHId5lbau+/u1Fp4",
	"cmvgxcOsgfoCChwsKaV7XitddhrFYexXIWzZ4scp9RXe8h2LlYyuHslcfjonboBlfAWeqPFtI8WACmiC",
	"kZDD1oPRXXLDJqFafpegDVrqrbvk5PicGKqviJLQw4qtk+MXhAvncoff+8toLJJzplgfgO5dv+oSmtLf",
	"pOgbbqjo4c9WUPSuXwwHOMhrGUFXiyl6eHAQy0j36Y3uu66RTA8muBkHCTVMm4NcMzXLecwO8LR7Os8y",
	"qQyL+3OTJu2yqwZalZLcBB170jM8mlz3GNWmd9ikrwk10byUVrnMz2KxFdoWr1kXx+nZlUVaK98huNLM",
	"lcxn8+rLqeVXNfwryy2ZTrnJclN7h7mJRbhj7jUR3LYqow4D6DUg6LYSLj5GR9ahgfgGJ8cyJo5Oe1Yf",
	"pIbD+wZVMoAi0u2zwztNS17mOIYTDmt2TzotMtYNpTRc2Lm/Len6HyBGqUuihGrNp07UgH8gSnJtmKpe",
	"sm3EpzwcyKVOX/vy5d4ZU0PIZ13ybBW1PKvxrSY+N4DzuNwGneUb+D2wHQ+wV0U8oIES6iAUJNIyuf0r",
	"Gwt2M4Z4oY1ewvZP4UJfItgNwVijIGyLZ7r8k/kBs9vvQI3KRdT6PlgNW3xDMmFzes2l6u9GEOA0j5MD",
	"DsRlquXZKeTAWOl8aUX+FVtcuptdqcjl8YcfTj6ejI/OTsd/OfnbZbuwXsbIEa2YmCVcz3vXL/uDYCJ1",
	"yeHgxSuvOGFDUDMTLmY5TaD1Ct7uENfy9fAeAcrrKuMuk3qnRrglFakJaZW143TtSlLrzepFsfNui9s1",
	"our+LtWFGoRRZ2He29lcYu3W0lUUQLnvi1ogRQDLdUKkbGeWbaPm+GXm1+l2qtwPfvC8r9WUavHYth5G",
	"c3tFqeZNA8krLt0Kv2kdvXnJVSF5D9nJ+9cNUH7Ad0Hm8FIg7qQmiRQzeDaGYlRhSm+dwxED88tb+v7D",
	"+5NOt3N+cfTxotOFOX7eCddo8ouH+sdKg30v5Syps6B1xVdK/f/KlGG3j++P3t8t+oO+sF3/jzI3TD1+",
	"jHZ9/gEDtMqBB/RvdVa0+TmBFacybivuiu+BuCsADD4HYnOKoCZCCnRquvcoyR5P6QwMgTzmskssV5Vd",
	"cvb6jd7vjoT3Z5pwRcC1eGYIFy1eDmxglQ5t1IIsmAHxAw6zS6Nydtn1fhWjGDW6NCzVpFgYWCXgM9VM",
	"xGTCBVULD/JI1GFmJurvY1wHK5xH1qJhNIbwiVsDz8CLGb4ASi5KDZ9pFLVcu9f3FNOZFBoUV3CfRRHL",
	"sPOchY37r//4T9zhaUJn5JdcW7UlSbz3ZySENIWqw3Er3ksDj/s5r6zT1WmiGI0X/t2lsIFOP7ssNibg",
	"y2V3JC5nLOWC98KPvRe9TLFrzm4uu+QySnjWe+7/ihKaXe5X1QFwAl1eXv6ipRiJu5EgZBQk66gzJKPO",
	"NbCGUaeLHwFg/KJlynrT3OSK9QoAe66Fbx8+2E4WBUbiHuZsVeY2dSu3MNLCs7wrp6lYppf5KTWJqLAK",
	"g+8cXnZzD8KC6Rfl2kiw/ebypvQ8DVVsJCIpYIfBbd2u9ZKLMJo1Lkqv3vpqIyIeCW/pWcVE5iWanLMk",
	"Y8ob9H4scr7QhqXOC/j8+TkM9fz5kDRf1QWXolfw5uHzLxo0PDTT93EYd3dmxymgtvyI5kamFNx4iXMh",
	"xu0+xKCFDslXBG/ZtB/dUt6tqY6uWMT4NQuFnYpAOaqRVm8Nrv07vyU/4JbA4kfisE+eP9eRyic/mDR5",
	"/pz0iHukAjHlQJtFwoihM+fjR16Cr+DhmYH18sPFu7cW6cnl5WWxS/DL3V0Yn8xNmozDY8C+A/zfT6zJ",
	"JUT1RggARvhewuT+gwXJ/24hc/2P4lhbqwqNKgwgnyTgH8CSf5rsZV0S8+sumR/25l93ScId/wwgmFwJ",
	"TbKEcrc8OCe44VLXEM9PYzrhCTdwY/rC7h/7FTbuxGWdEDD9FdeFO9dfxOmle/QHPiV77Ff3zCAZdSzH",
	"vmajzv79/RH8aQlA3d0d8KnbuaLT/7aG0qgDBSsss9m/vz/Hv9FgKveC/R6JlxbwlMWcAuzfM/EXbkgs",
	"TaZkmhkCn3yg7jWKgpKICtJoyXKwe66Sb0FavaaG/vjxNABefLZCpA9txrlKWhqMOp76nKYMhAc9+r9k",
	"s1GntY9+aTs4l+/BJI+umHGdMrGs05QnbHhwcJBRMz8wsmUSt3mEWK7hvXLgcz63zNndLAAqXcbU0OEl",
	"6RGMZSUhlpUaSn78eKqDhIOWMNnBLxmb/QmrPnT7/f6lR8xL52m+JAf4t4Z/9MhPbGLnd1HxgdMEQQ2G",
	"VIh296O5ldoB8BLE/qCBK+KTAr4h7KNtdv6y7NFyd4zw8EBKzdA1rG+4Ndn3w4YdBeCOHXBn+DSzDziA",
	"KZ8/PwX9xjK61/JG4IVE1+olYP3t8alTIva7pCJBwsaGkawehwzz1njWxcB9gAn8mV2DYgKLKFFN4BBC",
	"d8vUbPePQPOWDVbHQX/fO/kbTxLqWgXOgDjColxZluAvcP06/cpQQGRKGiyHPgmKHtG+r08TInuaWYOy",
	"LKvDe4L7Q88Fk0TesJjMpTbkZs4NS7g27uOZ4tdWAJ6eIWcE6Wa1JuCO5+cf3xBqDI2utEc8Dyj6eCGM",
	"T5ek1OFg8O67RlvDUybzSsOXgzAknG/Jd9oY9MXg1TfZbRewuefO3aPROWPD4HDBG6I+l+B6OaioMX/w",
	"+9frRVLBtdkrYNZAhhdSCmTa8E93ky7IxYcP7wkiNdm7gKiqD4ozYc/mA5iy5L3E2rH7S5lfMQXoyH30",
	"+AaW0/7Z2d/vqLpi6lu8tuciZsJ8+2pd15hhfKX6dtQZjUwru/rJGkVcwwr/zWEhrBbDqSxtR6ZL5nlK",
	"RU95jHdbETPNZ8Lp7RkFkrW6fR4ZUPxg+4wkb9++s8oWIaR8f/v8+ctB7+vBPztHg2JxDtwIblSsqET6",
	"/fP5h/cWYyGLmgtDseDhnM/mdmAY1rZXbO4wh0ZRrmi06IdV/oUtSOWWFzDuGFfndUak28shFsW8Yose",
	"ZO6RjHIVlAml6MKdCUnhUPSQXFp14+9/ePnzkFDedfU/0sRrMBd0kidU+V2zo1sVW6oUdyjsmJ/lQ3Bq",
	"2bZv374jGVUAndV3csuYIG8K0rygxzu3MxpPqq6PwCZ8xwSbcqPLTPWtvGEKPH6R1EY7TS/OI9j7K7i9",
	"oDNMxNIkgdYWntAjjPSGaqtZOTuR4VBvmdY4Dqj97s390Oed1eojr8GSHnnDDUkhtTSYBC5TzDmjgCeE",
	"FbnQ0ZJ0LVPLJdmzZtT+0KqA5A+uTKKFA0LBMZROk4RfMXJpT++yxGwg48GPigR3Sfa4MPtDcgr/RE6r",
	"Mxr5N4sFluNH31aFc4WRAkleQlEXLmb7QwLZViTEk6En3OEMgFoeS0jBumD1XDqqvvQddCFUvW8bb6T8",
	"BnmlGgqp2nUYzKaAZ3gk+SvGQ50D/kJDmpu5VEPyZyoYeS1RBrYjO3zy1fRQ6hDCUMMdkhfuByta9ZC8",
	"+mrQ4ESu9qrLuR4+fx74EDwK7r6WaCgYNSiqsUQt5Gu7d44K+g/ysIQrMLpzL6Pzt5AgM27m+QRUSiOl",
	"6OGs8Lfr/b0kp5Wa4a2daZJdMX3FxcFMYueKwelOyVtdIY0Kg1iKvaxJkws8PqulYpM+HKjl7q+pqX6J",
	"qYEPF3Sm7Yc/QN5H0ZHO9P393Z0VG/f3XXJ3d2Ab2B4jcXdXssncUVnlJ+gi3oUkRRNIl6hj54RYBAtc",
	"4WcYVuy/kgNibG1B2/hM8YgNyT/d3WX2rxII7wp7AzYKtLOVAITtaVggLWCVgClNelxYaw4HDZYgqs1a",
	"mcwaYkhC9/ffLezg/l/B9CqstYgaNpNqAe4mlvI8BYvtv/7f/yVn+G+vIJc6T2S8KEH5/PlJ6ULmrz4G",
	"wrk0Lr8/eXf6/rS4HOv5ux6gJ/SYk6NTaPvh7OT90dK26J0uN/zu6BzCY7xpA+ZP0bRsJhydnWrs+vbt",
	"0buj8Q8fzi9sNxcwDSa1gv7OFGrE0xwevnr5ah9XfJpae8tS/5liME1uuXBRrN1R199kDr4pDu2LWryl",
	"iLM9cFogwF13R4Px8mIR3F37XTLJDURDjsS0KIDd8HhdslvDlKAJSpPLPjlxP4Qu6EV1gaia3ChuDBMj",
	"gQZ2svChEcgCPXu4LGpga3/3aRWDWBIhTYjfJGiz40XySFxCw0u4JfXOuEvnAjs3LMN9OuyTY8Vs77Kv",
	"z73m0b4ucHe8gQIYQoeM9i5cGRYvLFwGzf4S3Aw/KW7qcr6ysiG5I6MO+nZgiPc0df6dUWdI/t7v9/Fj",
	"6IIf+/3+z+T+cr1TFwgV/bbvFsQz3+Cm9b4MaBBYM7jK+/3QqgSwbXmHcm7USRdjPFUMvAaIB/3DLhn0",
	"X9j/vOwSC6htfu/dv+76mCXMMPKdu5F3tPsjCvz6dKt2SORJQu4vwQbGMamPtfYn6DDPTvAh5cDSKmfw",
	"99bBf74kCaPX7k42EJILp85FNKdixmJcjgX8mOrAhN7xmUL/KVZDEpin4DqHoEhAhxYaxb2o0W0RsTxZ",
	"FGtDxwX0KHhEVuYRLZTuS3G4+5LqxN9BWFMW3BOVt2emU3gmx/mqOZTrwxvllrgsCHAp7ihe9nRKk6R6",
	"hw9ZUxx896t8+2vCBVfEDeNVSafrLjQ63Y4EDmz/wLnxD6gPqDrdUsCYiy/oPiz2uPVOdsOwkCCdyN73",
	"APf+Y0NE6lLwQSEijeulweCwFCTycvDHF0UAbTMWhPL+DBbSj9n1gRuMZhw9FZWnOGqhsxC10VnIXNn2",
	"PZeHXETG2ZmL+JA2MKvY5Q7/YREi/hBWRYhUt3fzCJFalJ/PcIVlNSEp/EQuoqJABsdK9v749TddcvjV",
	"y6+BsOFkFItkmlpzId5vD7WzOoZZGj/m1n+cyDwmvmk5ZMzlnx0+2++Tj/5FLIvCGE5ALLfxeQ2odMEx",
	"2B3tb5gfuORoV8ebbBJosmTgBkyZktbAHfN4g01yjcnpa7K3ZOHd4u2wyk7tt+7IJiHeJTQtskH97GA8",
	"Fw+T8CkoTeHlkv3+2kDtx8S2tIaDbMj6nF68hN29redNYD00fk0jl7fjJBMki9pdAsaYq6TMFCuqOBPX",
	"llaXMkEhUx6VQjUrSQXp7YQ6LOolVM0Y2SuHztEk6dmTT9JatkGTWaI0AkMa3Qz/Fn1bfhmtRa7WIatJ",
	"VC/eluQhgFnRZIkrwl3LNOaOqUxggTXU4XrWJc8aG1WPNG1ZzHJy8OxhyaK6qynGwb4+I6KEJ49JhPDA",
	"PAGBtcVLbUpg0Pex+kTdUl6iT5z7cKN2g7hOlUuJr111LAeqfvXya09tjcaOItfpKdY6tGfUR0UQaBBU",
	"FAht2ERT0Ve9fr9fCll9iMr7IKXEnd5KpaR6Ro9QSvSGuQdVYbsHouad84QULcNdB6gJQScZkhdffd0l",
	"Xx2+wHDjmvrSrrG0qAhLt3oNA8ONXK4hLB13M7YECnDGSzi1li0VR1uwpfIjXdjgmQYFCk6+eejeM7Uh",
	"v2qF8mn4VWt85gN4FvZfxrdKLcKdGw3BXXZPQ/SG5TCNbBmwz4uSgX5s3d+MJX788OPFycdHmlm4+Qdr",
	"eN1+d2lD4HPdkUBr66BNt+2SX2+YOLD/eVn68s1kiTYSLOE+dfaaNdxq0fzreKJUNba4cqVN7uhs8Ydz",
	"SIcJa7lk9dg+HafkUxIS2vANYRcFu78x21u3lSs3xgXyQlLglDMVVLeVo1o9bgWK1TW6dRDugK+0xq1v",
	"wFMqVluwwZpcYY8Jw1SmuGa9maIx2y9SM6FKqzOK/XXecZFoSfaOXh/vYyBpbuaYwoz1Hp2trMnp0TvI",
	"tiSXkHN5QHlQRXLN1OX2jpkuaQkd9iHfBxA9fQAB30tUo8jukPfiWL0IvWc9yg98evg169GGS+dgxkyv",
	"evKNKiYNf07hjuiUvAudTRw9wUbvpIveLMp67rcqT3GuvwY/KeXHjtvrIcIzHUaGxDkaYW0aiNeAeyKe",
	"sD45SsAdC9GCRpKj18d4Vy5F7/vjszJ/0b+bWwjq7LVs5J/I4YtveoevBt/UAh1Dq428SJ4/VU+wCnyF",
	"/EopigUlWs7d5mnqkmcst2fXu2HaHC4rbPX9hw/fvz0ZH7/98OPr8dsPx0cXpx/eV5WpyrBP6o5ayl+e",
	"zDG1xCm1wV6dffzw55Pji00l4cY8e3VptCPLhyr10Za8/K+LB+mMxOSPUDSkWY3X1ymJHet3z1DVBsZG",
	"xDeCOjA8SbhmkRSxDvWkS7OVQ1QGS6jCvcy7cu6f8P3XpVNDFSIokOVfiq2suBJaOBi0Q3L/4NNYfRBn",
	"TPVcYntLzkQ4DHKUuMBrDO8M7tAe+Y0peSBTbqzyA1FnmNjg6nJ5Z2XLq9iw/HWpIQ9Ftftqtay7tc/6",
	"OBQwsnT5zIoInXZ08LVzHg/5Bbs1dcBXVCAHpSeG0h+hVZFyVKuTR/YG/UHvsD+oOoSniaSm+Qr3w1Gq",
	"AftG9I1pamvJ29ccajw0Ek6sCMpzfVofkcBz7RN8LsOHX/qQPUIjJbWrpkcmMhcxhbgr8iHU2ZosGvXs",
	"rAnZihClimrN4sU+OA75LFY5zBJ3Z+3l4mgkRiPxzMWjKgrFc/X+gwAq5dRWCzgte5axvqeZL8S1Fe/x",
	"umQo9vY9/iC3rdlUKKlW/pY8Bp3PrqLO2no59Hbp6TSZVIHynkmttSxX6TAzfx7IPmqGnhC3KheGp+zg",
	"e5amtPey9+H9+39vRTOWZnakXLUWbHAl3hQVsUwF01Bor1TxCvjUi2V8Kjzk+qL0dtigwb+6HRec3/L2",
	"ycXFWQjr9TH88AhMSSRXUSCiSaLXPJwPlb6z8VXLRsusd0W03UrwaVFFU2aYWiJFZDbO2jhdlLBcLxlm",
	"+TYdrtym7ZS7KknPlcx49Hiqxv4PJOelLqJiQO8hegqCK7J5EZ02du1ECc1j1tNSCGZ6r3pf9V4MXnw1",
	"+NcX/9pqa0DSYyhB4wi2WOJyU2PlPE9CuYdrKfdwHeX+LmS0K+g3ETBV5AwCZnd++XXk6gohPJZYS5XN",
	"NifXTy7clpRuqhII9UfRX04qvevD4WD3pZn6X0jwM5RkGDv5SMpwZXB2JMNq9Yva0GWq8BWUxdguKDGL",
	"NmsePiCMkHUUOu0KXX4/MSrTlIq4p3pZkutNqxStEJf18Vp8ckxbvfAh++377Iw6v4jpLaHfGbdo4RMP",
	"rfG0dgrw9NYnWld0aN2o6LHe9agYdrXrUdv9BVvDCqEWTzEq3sDueuQlOtsONrfdctt24HZB2lbsatOK",
	"QBsT4+7rBK0U6eW4zZIkfDF49U3pYjMzvVf9w9b4sBpLH/T/eP8Q3rM6daId8t2mTwQtupxKEYrKQ05F",
	"WyrF41jfwxIslizfJ108WCmrpQy06Qi7i7n/XZyEtZvQF/2vetOE6vla9aq01WsvP8uj7ioiv/8ZeyP/",
	"2xlUj85M+IRujHZ142FZCJ+xA2NNMH6VruD7y/7L4R8Hk39Ur3wpqv8f1iW/Gd215Td8QrprVZ0flpyw",
	"Ix9JLVj+KXwkFu0tyT0M+3svnsBRsrnsDtrmliHyxUA7doXscFc/HxH/uXGJlnSDT8sl2k3hh6cE7JBb",
	"1ALH/8E5xoNdq5UoFXzsvR5KHp7oxA9FjeM014ZMQtXluDVYfAVHwWFaXiSB+lZy2oDExc/RJJnQ6IpY",
	"yxQi0zaFD/Bnw5eWv3C8rTnezpy3D+ZF7e7Ox6cR1E1d3caKdhVzvt7HsLOI7M8rSuLBHohiLU/ngPji",
	"fPgMb2ru4UmWqWyRHQLVoLPTEHhaeYIQ6N0CXmQG+mpW4f2D19/BnnADCHQK9Z8qrAKdppjV0Rn0B314",
	"b8yxo86w87I/6L+0/AHf3hd5ktz//wAAAP//GNG7Mh0iAQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../shared/generating.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "chunking.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "embeddings.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
