// Copyright 2026 Antfly, Inc.
//
// Licensed under the Elastic License 2.0 (ELv2); you may not use this file
// except in compliance with the Elastic License 2.0. You may obtain a copy of
// the Elastic License 2.0 at
//
//     https://www.antfly.io/licensing/ELv2-license
//
// Unless required by applicable law or agreed to in writing, software distributed
// under the Elastic License 2.0 is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// Elastic License 2.0 for the specific language governing permissions and
// limitations.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageSnapshotMetadata struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ID string                 `protobuf:"bytes,1,opt,name=ID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageSnapshotMetadata) Reset() {
	*x = StorageSnapshotMetadata{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageSnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageSnapshotMetadata) ProtoMessage() {}

func (x *StorageSnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StorageSnapshotMetadata) GetID() string {
	if x != nil {
		return x.xxx_hidden_ID
	}
	return ""
}

func (x *StorageSnapshotMetadata) SetID(v string) {
	x.xxx_hidden_ID = v
}

type StorageSnapshotMetadata_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ID string
}

func (b0 StorageSnapshotMetadata_builder) Build() *StorageSnapshotMetadata {
	m0 := &StorageSnapshotMetadata{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ID = b.ID
	return m0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x06common\x1a!google/protobuf/go_features.proto\"0\n" +
	"\x17StorageSnapshotMetadata\x12\x15\n" +
	"\x02ID\x18\x01 \x01(\tB\x05\xaa\x01\x02\b\x02R\x02IDB=Z3github.com/antflydb/antfly/go/pkg/antfly/src/common\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []any{
	(*StorageSnapshotMetadata)(nil), // 0: common.StorageSnapshotMetadata
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
