// Package middleware provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package middleware

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// CORSConfig defines model for CORSConfig.
type CORSConfig struct {
	// AllowCredentials Indicates whether credentials (cookies, auth headers) are allowed. Note: If true, allowed_origins cannot be ['*'].
	AllowCredentials bool `json:"allow_credentials,omitempty,omitzero"`

	// AllowedHeaders Headers that can be used in CORS requests. ['*'] allows any valid requested header; when credentials are enabled, the server reflects the validated requested header names because browsers treat '*' as a literal name in credentialed CORS.
	AllowedHeaders []string `json:"allowed_headers,omitempty,omitzero"`

	// AllowedMethods HTTP methods allowed for CORS requests
	AllowedMethods []string `json:"allowed_methods,omitempty,omitzero"`

	// AllowedOrigins List of allowed origins for CORS requests. Use ['*'] to allow all origins. Defaults to ['*'] if empty and enabled is true. Credentialed CORS rejects both '*' and the opaque 'null' origin.
	AllowedOrigins []string `json:"allowed_origins,omitempty,omitzero"`

	// Enabled Controls whether CORS is enabled
	Enabled bool `json:"enabled,omitempty,omitzero"`

	// ExposedHeaders Headers exposed to the client. Useful if your API returns custom headers that the frontend needs to read. ['*'] is rejected when credentials are enabled because browsers treat it as a literal header name.
	ExposedHeaders []string `json:"exposed_headers,omitempty,omitzero"`

	// MaxAge How long (in seconds) the results of a preflight request can be cached
	MaxAge int `json:"max_age,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5xVQW/bOBP9KwNe3Bay6g8BvoP2FLjBNkC3CRoXW6AIgrE4srhLcVhyFMdb5L8vSEmO",
	"7aS76F5ka0gO37z3ZvRd1dx5duQkquq7inVLHea/y6tPN0t2jdmkNx/YUxBDeQ2t5e1dHUiTE4M2BzU1",
	"2FtRVYM2UqE0xToYL4adqtSl06ZGoQjblqSlAAfH4VXN/KehWAD20kJLqCnE14CBIF9GuoSPLFTBZQMS",
	"eiqm+B0HszEuQo3OscCa4Ovszey2VIWSnSdVqTWzJXTqsVDTofGGI9xf1ZKdkJP5Kp0r1HkvLQfzF+Ya",
	"CvVl/om+9RSF9Px3I23aUtfkRRXqKqNQt6d1vx8uAmlREsSEr4+kwThIFEMYUsZygD2UFQHdDu7RGj1t",
	"ID3S8kti0B3Rl2gih2tLugBpCSKFewoQqLFUS8yxnA1TntOM4LCjCGuqsY8E68DbmDEHQoHZmxlgBARr",
	"hALavDvBf0JAOteSKKcH7Lylf2XztlBGqMsKjDJFCcZtkkpjAEPA3aFqHUnL+lS1Xy9WqlDXVzf553N6",
	"vrv4cLG6SLJcry6vPt6khfPV8v0L+qxW1zDmnSwFDYdjcY4L+/GF/6mq0cBDVYfYPpgowM0e1uT0Z/BK",
	"+BxH24PwsD89pxMlvBvoiml52GcaoM7LDtDpyTxgYm6uEpan2kKgP7KV1izt4Amns6/Y47eeYOZ6a2fj",
	"jSdOaEV8rN6+HUNlzZ0q9lH0vjxc+SkSR+RHlsjz4YTLZMbA9mn85KJMnEp/cVrQg+d4Oi1e6u5xY2I3",
	"UVJbQ06yKk1vE9U77gOcX19CIOlDmlZ9FO6mSTeMh3S0CblrNDgineUKhHoaDiaOOpD+xynwo142ctzK",
	"B/1/ItmX+YoF7XzJvZOfk6TDhzvc0JEkZ/9fLJ61Hm/BstvAK+MgUs1Ox9eZhEAxmzV5H3yaYmbTymT3",
	"aYzWWLdZuD3s4ZbOONP1naoWe2zGCW0oqMcnuLxOPKrHFDKu4efiDl+/PuSBBcOnMffeuZPG7mAYHUZr",
	"S1sMmUAxknCo3/ZROMqiCnVPIQ75F+Wi/F8ijD059EZV6qxclGeqUB6ljapKLfX4dwAAAP//iR65q6QH",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
