#!/usr/bin/env bash
# Copyright 2026 Antfly, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

env_flag_enabled() {
  case "${1:-}" in
    ""|0|false|FALSE|no|NO|off|OFF) return 1 ;;
    *) return 0 ;;
  esac
}

q4_0_f16_ffn_flag_value() {
  if [[ -n "${TERMITE_METAL_Q4_0_F16_FFN_EXPERIMENT+x}" ]]; then
    printf '%s\n' "$TERMITE_METAL_Q4_0_F16_FFN_EXPERIMENT"
  else
    printf '%s\n' "${TERMITE_METAL_ENABLE_Q4_0_F16_FFN:-0}"
  fi
}

q4_0_sumsq_flag_value() {
  if env_flag_enabled "${TERMITE_METAL_DISABLE_Q4_0_LINEAR_RMS_ADD_SUMSQ:-0}"; then
    printf '0\n'
  elif [[ -n "${TERMITE_METAL_ENABLE_Q4_0_LINEAR_RMS_ADD_SUMSQ+x}" ]]; then
    printf '%s\n' "$TERMITE_METAL_ENABLE_Q4_0_LINEAR_RMS_ADD_SUMSQ"
  else
    printf '%s\n' "${TERMITE_METAL_Q4_0_LINEAR_RMS_ADD_SUMSQ_EXPERIMENT:-0}"
  fi
}

q4_0_f16_project_flag_value() {
  if [[ -n "${TERMITE_METAL_Q4_0_LINEAR_RMS_ADD_F16_PROJECT_EXPERIMENT+x}" ]]; then
    printf '%s\n' "$TERMITE_METAL_Q4_0_LINEAR_RMS_ADD_F16_PROJECT_EXPERIMENT"
  else
    printf '%s\n' "${TERMITE_METAL_Q4_0_LINEAR_RMS_ADD_F16_PROJECT:-0}"
  fi
}

if env_flag_enabled "${ANTFLY_INFERENCE_GEMMA4_BENCH_LOCK:-1}"; then
  BENCH_LOCK_DIR="${ANTFLY_INFERENCE_GEMMA4_BENCH_LOCK_DIR:-/tmp/antfly-gemma4-e4b-metal-bench.lock}"
  cleanup_bench_lock() {
    rm -f "$BENCH_LOCK_DIR/pid"
    rmdir "$BENCH_LOCK_DIR" 2>/dev/null || true
  }
  if mkdir "$BENCH_LOCK_DIR" 2>/dev/null; then
    printf '%s\n' "$$" >"$BENCH_LOCK_DIR/pid"
    trap cleanup_bench_lock EXIT
    trap 'cleanup_bench_lock; exit 130' INT
    trap 'cleanup_bench_lock; exit 143' TERM HUP
  else
    echo "another Gemma4 E4B Metal bench is running; set ANTFLY_INFERENCE_GEMMA4_BENCH_LOCK=0 to override" >&2
    exit 75
  fi
fi

E4B_VARIANT="${ANTFLY_INFERENCE_GEMMA4_E4B_VARIANT:-standard}"
IS_QAT=0
OUT_SUFFIX="e4b"
case "$E4B_VARIANT" in
  standard|q4_k|q4_k_m)
    export ANTFLY_INFERENCE_GEMMA4_MODEL_NAME="${ANTFLY_INFERENCE_GEMMA4_MODEL_NAME:-ggml-org/gemma-4-E4B-it-GGUF}"
    ;;
  qat|qat-q4_0|q4_0)
    IS_QAT=1
    OUT_SUFFIX="e4b-qat-q4_0"
    export ANTFLY_INFERENCE_GEMMA4_MODEL_NAME="${ANTFLY_INFERENCE_GEMMA4_MODEL_NAME:-google/gemma-4-E4B-it-qat-q4_0-gguf}"
    ;;
  *)
    echo "unsupported Gemma4 E4B variant: $E4B_VARIANT" >&2
    echo "expected one of: standard, q4_k, q4_k_m, qat, qat-q4_0, q4_0" >&2
    exit 2
    ;;
esac

if [[ -n "${ANTFLY_INFERENCE_GEMMA4_E4B_DRAFT_MODEL:-}" && -z "${ANTFLY_INFERENCE_GEMMA4_DRAFT_MODEL:-}" ]]; then
  export ANTFLY_INFERENCE_GEMMA4_DRAFT_MODEL="$ANTFLY_INFERENCE_GEMMA4_E4B_DRAFT_MODEL"
fi
if [[ "$IS_QAT" == "1" ]]; then
  export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_DISPATCH="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_DISPATCH:-1}"
  export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PAIR_ACT_REDUCE="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PAIR_ACT_REDUCE:-0}"
  export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PLE_ACTIVATION_RHS_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PLE_ACTIVATION_RHS_REDUCE_OUT_F16:-1}"
  export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PLE_LINEAR_REDUCE_IN_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PLE_LINEAR_REDUCE_IN_F16:-1}"
  REQUIRE_ACTIVE_DECODE="${ANTFLY_INFERENCE_GEMMA4_REQUIRE_ACTIVE_DECODE:-0}"
  ACTIVE_MATERIALIZE="${ANTFLY_GEMMA4_MTP_ACTIVE_MATERIALIZE:-1}"
  ACTIVE_MATERIALIZE_ENABLED=0
  case "$ACTIVE_MATERIALIZE" in
    1|true|TRUE|yes|YES|on|ON) ACTIVE_MATERIALIZE_ENABLED=1 ;;
  esac
  if [[ "$REQUIRE_ACTIVE_DECODE" != "0" || "$ACTIVE_MATERIALIZE_ENABLED" == "1" ]]; then
    export ANTFLY_INFERENCE_GEMMA4_MIN_ACTIVE_DECODE_SUCCESS="${ANTFLY_INFERENCE_GEMMA4_MIN_ACTIVE_DECODE_SUCCESS:-1}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_ACTIVE_DECODE_FINAL_FUSED_ARGMAX="${ANTFLY_INFERENCE_GEMMA4_MIN_ACTIVE_DECODE_FINAL_FUSED_ARGMAX:-1}"
  else
    export ANTFLY_INFERENCE_GEMMA4_MIN_ACTIVE_DECODE_SUCCESS="${ANTFLY_INFERENCE_GEMMA4_MIN_ACTIVE_DECODE_SUCCESS:-0}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_ACTIVE_DECODE_FINAL_FUSED_ARGMAX="${ANTFLY_INFERENCE_GEMMA4_MIN_ACTIVE_DECODE_FINAL_FUSED_ARGMAX:-0}"
  fi
  if [[ -n "${ANTFLY_INFERENCE_GEMMA4_DRAFT_MODEL:-}" ]]; then
    export ANTFLY_INFERENCE_GEMMA4_MIN_PREFILL_FRAME_EXECUTE="${ANTFLY_INFERENCE_GEMMA4_MIN_PREFILL_FRAME_EXECUTE:-1}"
    export ANTFLY_INFERENCE_GEMMA4_REQUIRE_MTP_ENABLED="${ANTFLY_INFERENCE_GEMMA4_REQUIRE_MTP_ENABLED:-1}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_SPECULATIVE_ROUNDS="${ANTFLY_INFERENCE_GEMMA4_MIN_SPECULATIVE_ROUNDS:-1}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_SPECULATIVE_DRAFTED="${ANTFLY_INFERENCE_GEMMA4_MIN_SPECULATIVE_DRAFTED:-1}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_SPECULATIVE_MATCHED="${ANTFLY_INFERENCE_GEMMA4_MIN_SPECULATIVE_MATCHED:-1}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_MTP_ACCEPTANCE_PERMILLE="${ANTFLY_INFERENCE_GEMMA4_MIN_MTP_ACCEPTANCE_PERMILLE:-1}"
  fi
  if [[ -z "${ANTFLY_INFERENCE_GEMMA4_DRAFT_MODEL:-}" ]]; then
    QAT_MAX_TOKENS="${ANTFLY_INFERENCE_GEMMA4_BENCH_MAX_TOKENS:-128}"
    QAT_MIN_DECODE_TOK_S=20
    if [[ "$QAT_MAX_TOKENS" =~ ^[0-9]+$ && "$QAT_MAX_TOKENS" -ge 512 ]]; then
      QAT_MIN_DECODE_TOK_S=8
    fi
    export TERMITE_METAL_DISABLE_PLANNED_COMPUTE_BARRIERS="${TERMITE_METAL_DISABLE_PLANNED_COMPUTE_BARRIERS:-1}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_DECODE_TOK_S="${ANTFLY_INFERENCE_GEMMA4_MIN_DECODE_TOK_S:-$QAT_MIN_DECODE_TOK_S}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_HOT_DECODE_TOK_S="${ANTFLY_INFERENCE_GEMMA4_MIN_HOT_DECODE_TOK_S:-$QAT_MIN_DECODE_TOK_S}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PAIR_ACT_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PAIR_ACT_REDUCE_OUT_F16:-0}"
    Q4_0_F16_FFN="$(q4_0_f16_ffn_flag_value)"
    Q4_0_F16_FFN_DISABLED="${TERMITE_METAL_DISABLE_Q4_0_F16_FFN:-0}"
    if env_flag_enabled "$Q4_0_F16_FFN" && ! env_flag_enabled "$Q4_0_F16_FFN_DISABLED"; then
      if ! env_flag_enabled "${ANTFLY_INFERENCE_GEMMA4_ALLOW_UNSAFE_Q4_0_F16_FFN:-0}"; then
        echo "QAT Q4_0 F16 FFN is not production-safe; set ANTFLY_INFERENCE_GEMMA4_ALLOW_UNSAFE_Q4_0_F16_FFN=1 for experiments" >&2
        exit 2
      fi
      export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PAIR_ACT_RMS_SCALE_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PAIR_ACT_RMS_SCALE_REDUCE_OUT_F16:-1}"
      export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_ACTIVATION_RHS_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_ACTIVATION_RHS_REDUCE_OUT_F16:-1}"
    else
      export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PAIR_ACT_RMS_SCALE_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_PAIR_ACT_RMS_SCALE_REDUCE_OUT_F16:-0}"
      export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_ACTIVATION_RHS_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_ACTIVATION_RHS_REDUCE_OUT_F16:-0}"
    fi
    Q4_0_SUMSQ="$(q4_0_sumsq_flag_value)"
    if env_flag_enabled "$Q4_0_SUMSQ"; then
      export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_LINEAR_REDUCE_SUMSQ="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_LINEAR_REDUCE_SUMSQ:-1}"
      export ANTFLY_INFERENCE_GEMMA4_MIN_RMS_NORM_ADD_SUMSQ="${ANTFLY_INFERENCE_GEMMA4_MIN_RMS_NORM_ADD_SUMSQ:-1}"
      export ANTFLY_INFERENCE_GEMMA4_MAX_Q4_0_LINEAR_REDUCE_SUMSQ="${ANTFLY_INFERENCE_GEMMA4_MAX_Q4_0_LINEAR_REDUCE_SUMSQ:--1}"
      export ANTFLY_INFERENCE_GEMMA4_MAX_RMS_NORM_ADD_SUMSQ="${ANTFLY_INFERENCE_GEMMA4_MAX_RMS_NORM_ADD_SUMSQ:--1}"
    else
      export TERMITE_METAL_DISABLE_Q4_0_LINEAR_RMS_ADD_SUMSQ="${TERMITE_METAL_DISABLE_Q4_0_LINEAR_RMS_ADD_SUMSQ:-1}"
      export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_LINEAR_REDUCE_SUMSQ="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_LINEAR_REDUCE_SUMSQ:-0}"
      export ANTFLY_INFERENCE_GEMMA4_MIN_RMS_NORM_ADD_SUMSQ="${ANTFLY_INFERENCE_GEMMA4_MIN_RMS_NORM_ADD_SUMSQ:-0}"
      export ANTFLY_INFERENCE_GEMMA4_MAX_Q4_0_LINEAR_REDUCE_SUMSQ="${ANTFLY_INFERENCE_GEMMA4_MAX_Q4_0_LINEAR_REDUCE_SUMSQ:-0}"
      export ANTFLY_INFERENCE_GEMMA4_MAX_RMS_NORM_ADD_SUMSQ="${ANTFLY_INFERENCE_GEMMA4_MAX_RMS_NORM_ADD_SUMSQ:-0}"
    fi
    export ANTFLY_INFERENCE_GEMMA4_MAX_LAST_COMPUTE_ENCODERS="${ANTFLY_INFERENCE_GEMMA4_MAX_LAST_COMPUTE_ENCODERS:-1}"
    Q4_0_HALF_PROJECT="$(q4_0_f16_project_flag_value)"
    if env_flag_enabled "$Q4_0_HALF_PROJECT"; then
      export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_LINEAR_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_0_LINEAR_REDUCE_OUT_F16:-1}"
    fi
    export ANTFLY_INFERENCE_GEMMA4_MIN_PAGED_ATTENTION_1X="${ANTFLY_INFERENCE_GEMMA4_MIN_PAGED_ATTENTION_1X:-1}"
  fi
fi

export OUT_DIR="${OUT_DIR:-/tmp/antfly-inference-gemma4-${OUT_SUFFIX}-metal-$(date -u +%Y%m%d-%H%M%S)}"
export ANTFLY_INFERENCE_GEMMA4_REUSE_PROBE="${ANTFLY_INFERENCE_GEMMA4_REUSE_PROBE:-0}"

if [[ "${ANTFLY_INFERENCE_GEMMA4_E4B_REQUIRE_FULL_TOKENS:-0}" != "0" ]]; then
  export ANTFLY_INFERENCE_GEMMA4_BENCH_PROMPT="${ANTFLY_INFERENCE_GEMMA4_BENCH_PROMPT:-Write a numbered list from 1 to 300. Each item must be exactly: local inference benchmark continues.}"
  export ANTFLY_INFERENCE_GEMMA4_REQUIRE_MAX_TOKENS="${ANTFLY_INFERENCE_GEMMA4_REQUIRE_MAX_TOKENS:-1}"
  export ANTFLY_INFERENCE_GEMMA4_MIN_GENERATED_TOKENS="${ANTFLY_INFERENCE_GEMMA4_MIN_GENERATED_TOKENS:-${ANTFLY_INFERENCE_GEMMA4_BENCH_MAX_TOKENS:-128}}"
fi

macos_free_speculative_mb() {
  local stats page_size pages
  stats="$(vm_stat 2>/dev/null)" || return 1
  page_size="$(awk '/page size of/ { print $8; exit }' <<<"$stats")"
  pages="$(awk '
    /Pages free:/ { gsub(/\./, "", $3); free = $3 }
    /Pages speculative:/ { gsub(/\./, "", $3); speculative = $3 }
    END { print free + speculative }
  ' <<<"$stats")"
  if [[ -z "$page_size" || -z "$pages" ]]; then
    return 1
  fi
  echo $((pages * page_size / 1024 / 1024))
}

macos_pressure_available_mb() {
  local stats total_bytes free_pct
  stats="$(memory_pressure -Q 2>/dev/null)" || return 1
  total_bytes="$(awk '/The system has/ { print $4; exit }' <<<"$stats")"
  free_pct="$(awk '/System-wide memory free percentage:/ { gsub(/%/, "", $5); print $5; exit }' <<<"$stats")"
  if [[ -z "$total_bytes" || -z "$free_pct" ]]; then
    return 1
  fi
  echo $((total_bytes * free_pct / 100 / 1024 / 1024))
}

MIN_FREE_MB="${ANTFLY_INFERENCE_GEMMA4_E4B_MIN_FREE_MB:-1024}"
if [[ "$MIN_FREE_MB" != "0" ]]; then
  free_mb="$(macos_pressure_available_mb || macos_free_speculative_mb || true)"
  if [[ -n "$free_mb" && "$free_mb" -lt "$MIN_FREE_MB" ]]; then
    echo "Gemma4 E4B Metal bench refused: available memory ${free_mb} MiB below ${MIN_FREE_MB} MiB" >&2
    echo "set ANTFLY_INFERENCE_GEMMA4_E4B_MIN_FREE_MB=0 to force the run" >&2
    memory_pressure -Q >&2 2>/dev/null || true
    exit 2
  fi
fi

FAST_RESIDENCY="${ANTFLY_INFERENCE_GEMMA4_E4B_FAST_RESIDENCY:-1}"
if [[ "$FAST_RESIDENCY" != "0" ]]; then
  export TERMITE_METAL_DISABLE_GEMMA4_E4B_FAST_RESIDENCY="${TERMITE_METAL_DISABLE_GEMMA4_E4B_FAST_RESIDENCY:-0}"
  if [[ "$IS_QAT" == "0" ]]; then
    export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_PAIR_ACT_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_PAIR_ACT_REDUCE_OUT_F16:-0}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_Q6_REDUCE_IN_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q6_REDUCE_IN_F16:-0}"
  fi
  export ANTFLY_INFERENCE_GEMMA4_BENCH_SERVER_TOKENS="${ANTFLY_INFERENCE_GEMMA4_BENCH_SERVER_TOKENS:-16 64}"
  export ANTFLY_INFERENCE_GEMMA4_BENCH_SERVER_READY_POLLS="${ANTFLY_INFERENCE_GEMMA4_BENCH_SERVER_READY_POLLS:-3600}"
  export ANTFLY_INFERENCE_GEMMA4_MIN_SERVER_TOK_S="${ANTFLY_INFERENCE_GEMMA4_MIN_SERVER_TOK_S:-10}"
else
  export TERMITE_METAL_DISABLE_GEMMA4_E4B_FAST_RESIDENCY=1
  if [[ "$IS_QAT" == "0" ]]; then
    export TERMITE_METAL_Q8_RUNTIME_STAGING_MAX_MB="${ANTFLY_INFERENCE_GEMMA4_E4B_BASELINE_Q8_STAGING_MB:-32}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_Q4_PAIR_ACT_REDUCE_OUT_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q4_PAIR_ACT_REDUCE_OUT_F16:-1}"
    export ANTFLY_INFERENCE_GEMMA4_MIN_Q6_REDUCE_IN_F16="${ANTFLY_INFERENCE_GEMMA4_MIN_Q6_REDUCE_IN_F16:-1}"
  fi
fi

"$SCRIPT_DIR/bench_metal_gemma4_e2b.sh"
