#!/usr/bin/env python3
# Copyright 2026 Antfly, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate WGSL matmul shaders for the IQ-family GGUF quant formats.

Reads grid tables from src/gguf/quant_codec.zig and emits per-format shaders to
web/shaders/. Each shader inlines its grid as const arrays so it ships standalone.

Run from pkg/inference root: `python3 scripts/gen_iq_shaders.py`.
"""
from __future__ import annotations

import os
import re
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "gguf" / "quant_codec.zig"
SHADERS_DIR = ROOT / "web" / "shaders"


def parse_grid(name: str, text: str) -> list[int]:
    pat = re.compile(rf"^(?:pub )?const {re.escape(name)} = \[_\](u16|u32)\{{(.*?)^\}};", re.M | re.S)
    m = pat.search(text)
    if not m:
        raise SystemExit(f"grid {name!r} not found")
    body = m.group(2)
    body = re.sub(r"//.*", "", body)
    nums = re.findall(r"-?0[xX][0-9a-fA-F]+|-?\d+", body)
    return [int(n, 0) for n in nums]


# ---------- Common shader skeleton ----------

PROLOG = """// Tiled matrix multiplication with B transposed and {fmt} dequantization.
// C[M,N] = A[M,K] @ dequant(B_{fmt_lower})^T
//
// Auto-generated by scripts/gen_iq_shaders.py — do not edit by hand. Reflects the
// byte layout in src/gguf/quant_codec.zig.

struct Params {{
    M: u32,
    N: u32,
    K: u32,
    _pad: u32,
}};

@group(0) @binding(0) var<storage, read> A: array<f32>;
@group(0) @binding(1) var<storage, read> B_raw: array<u32>;
@group(0) @binding(2) var<storage, read_write> C: array<f32>;
@group(0) @binding(3) var<uniform> params: Params;

const TILE_M: u32 = 16;
const TILE_N: u32 = 16;
const TILE_K: u32 = 32;

var<workgroup> tile_a: array<f32, 512>;
var<workgroup> tile_b: array<f32, 512>;

fn read_byte(byte_offset: u32) -> u32 {{
    let word_idx = byte_offset / 4u;
    let byte_in_word = byte_offset % 4u;
    return (B_raw[word_idx] >> (byte_in_word * 8u)) & 0xFFu;
}}

fn read_u16(byte_offset: u32) -> u32 {{
    return read_byte(byte_offset) | (read_byte(byte_offset + 1u) << 8u);
}}

fn read_f16(byte_offset: u32) -> f32 {{
    let word_idx = byte_offset / 4u;
    let byte_off = byte_offset % 4u;
    let w0 = B_raw[word_idx];
    var bits: u32;
    if (byte_off == 0u) {{
        bits = w0 & 0xFFFFu;
    }} else if (byte_off == 2u) {{
        bits = (w0 >> 16u) & 0xFFFFu;
    }} else {{
        let w1 = B_raw[word_idx + 1u];
        bits = ((w0 >> (byte_off * 8u)) | (w1 << ((4u - byte_off) * 8u))) & 0xFFFFu;
    }}
    return unpack2x16float(bits).x;
}}

// Sign mask helper shared by all IQ2 variants. Returns 8 sign bits with the
// 8th bit set so that the parity of the byte is even.
fn iq2_sign_mask(idx: u32) -> u32 {{
    let low = idx & 0x7Fu;
    let parity = countOneBits(low) & 1u;
    return low | (parity << 7u);
}}
"""

EPILOG = """
@compute @workgroup_size(TILE_M, TILE_N)
fn matmul_transb_{fmt_lower}(
    @builtin(global_invocation_id) gid: vec3<u32>,
    @builtin(local_invocation_id) lid: vec3<u32>,
) {{
    let row = gid.y;
    let col = gid.x;
    let local_row = lid.y;
    let local_col = lid.x;
    let tid = local_row * TILE_N + local_col;

    let row_base = gid.y - local_row;
    let col_base = gid.x - local_col;
    let num_tiles = (params.K + TILE_K - 1u) / TILE_K;

    var sum: f32 = 0.0;

    for (var t: u32 = 0u; t < num_tiles; t++) {{
        let k_base = t * TILE_K;

        for (var stage: u32 = 0u; stage < 2u; stage++) {{
            let idx = tid + stage * 256u;
            let a_m = idx / TILE_K;
            let a_k = idx % TILE_K;
            let g_row = row_base + a_m;
            let g_k = k_base + a_k;
            if (g_row < params.M && g_k < params.K) {{
                tile_a[idx] = A[g_row * params.K + g_k];
            }} else {{
                tile_a[idx] = 0.0;
            }}
        }}

        for (var stage: u32 = 0u; stage < 2u; stage++) {{
            let idx = tid + stage * 256u;
            let b_k = idx / TILE_N;
            let b_n = idx % TILE_N;
            let g_col = col_base + b_n;
            let g_k = k_base + b_k;
            if (g_col < params.N && g_k < params.K) {{
                tile_b[idx] = dequant_{fmt_lower}(g_col, g_k);
            }} else {{
                tile_b[idx] = 0.0;
            }}
        }}

        workgroupBarrier();

        for (var i: u32 = 0u; i < TILE_K; i++) {{
            sum += tile_a[local_row * TILE_K + i] * tile_b[i * TILE_N + local_col];
        }}

        workgroupBarrier();
    }}

    if (row < params.M && col < params.N) {{
        C[row * params.N + col] = sum;
    }}
}}
"""


def fmt_array(name: str, values: list[int], width: int, per_line: int = 8) -> str:
    """Emit a `const NAME = array<u32, N>(...)` literal.

    width selects formatting:
      * 16: pack two u16 grid entries per u32 (low|high<<16).
      * 32: store one u32 entry per element.
    """
    if width == 16:
        packed = []
        for i in range(0, len(values), 2):
            lo = values[i] & 0xFFFF
            hi = values[i + 1] & 0xFFFF if i + 1 < len(values) else 0
            packed.append(lo | (hi << 16))
        out = packed
    elif width == 32:
        out = [v & 0xFFFFFFFF for v in values]
    else:
        raise ValueError(width)

    lines = []
    for i in range(0, len(out), per_line):
        chunk = ", ".join(f"0x{v:08x}u" for v in out[i:i + per_line])
        lines.append(f"    {chunk},")
    body = "\n".join(lines).rstrip(",")
    return f"const {name}: array<u32, {len(out)}> = array<u32, {len(out)}>(\n{body}\n);\n"


def grid_lookup_u16(grid_name: str) -> str:
    """Return helper that reads one u16 grid entry from a packed u32 array."""
    return textwrap.dedent(f"""
        fn {grid_name}_lookup(i: u32) -> u32 {{
            let word = {grid_name}[i >> 1u];
            return select((word >> 16u) & 0xFFFFu, word & 0xFFFFu, (i & 1u) == 0u);
        }}
        """)


def grid_lookup_u32(grid_name: str) -> str:
    return textwrap.dedent(f"""
        fn {grid_name}_lookup(i: u32) -> u32 {{
            return {grid_name}[i];
        }}
        """)


# ---------- Per-format dequant bodies ----------

IQ2_XXS_BODY = """
fn dequant_iq2_xxs(b_row: u32, k_abs: u32) -> f32 {{
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 66u;

    let d = read_f16(block_byte);
    let qs_off = block_byte + 2u;

    let ib32 = in_block / 32u;
    let elem32 = in_block % 32u;
    let lane = elem32 / 8u;
    let j = elem32 % 8u;

    let group_off = qs_off + ib32 * 8u;
    let packed_grids = read_byte(group_off + 0u)
        | (read_byte(group_off + 1u) << 8u)
        | (read_byte(group_off + 2u) << 16u)
        | (read_byte(group_off + 3u) << 24u);
    let packed_signs_scales = read_byte(group_off + 4u)
        | (read_byte(group_off + 5u) << 8u)
        | (read_byte(group_off + 6u) << 16u)
        | (read_byte(group_off + 7u) << 24u);

    let db = d * (0.5 + f32(packed_signs_scales >> 28u)) * 0.25;
    let grid_index = (packed_grids >> (8u * lane)) & 0xFFu;
    let sign_idx = (packed_signs_scales >> (7u * lane)) & 0x7Fu;
    let signs = iq2_sign_mask(sign_idx);
    let grid = iq2_xxs_grid_lookup(grid_index);
    let raw = 2 * i32((grid >> (2u * j)) & 0x3u) + 1;
    let sign = select(1.0, -1.0, ((signs >> j) & 1u) != 0u);
    return db * f32(raw) * sign;
}}
"""

IQ2_XS_BODY = """
fn dequant_iq2_xs(b_row: u32, k_abs: u32) -> f32 {{
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 74u;

    let d = read_f16(block_byte);
    let qs_off = block_byte + 2u;
    let scales_off = block_byte + 66u;

    let ib32 = in_block / 32u;
    let elem32 = in_block % 32u;
    let lane = elem32 / 8u;
    let j = elem32 % 8u;

    let scale_byte = read_byte(scales_off + ib32);
    let half = lane / 2u;
    let scale_nibble = select(scale_byte >> 4u, scale_byte & 0x0Fu, half == 0u);
    let dl = d * (0.5 + f32(scale_nibble)) * 0.25;

    let pair_off = qs_off + (4u * ib32 + lane) * 2u;
    let packed = read_u16(pair_off);
    let grid_index = packed & 0x01FFu;
    let signs = iq2_sign_mask(packed >> 9u);
    let grid = iq2_xs_grid_lookup(grid_index);
    let raw = 2 * i32((grid >> (2u * j)) & 0x3u) + 1;
    let sign = select(1.0, -1.0, ((signs >> j) & 1u) != 0u);
    return dl * f32(raw) * sign;
}}
"""

IQ2_S_BODY = """
fn dequant_iq2_s(b_row: u32, k_abs: u32) -> f32 {{
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 82u;

    let d = read_f16(block_byte);
    let qs_off = block_byte + 2u;
    let qh_off = block_byte + 66u;
    let scales_off = block_byte + 74u;

    let ib32 = in_block / 32u;
    let elem32 = in_block % 32u;
    let lane = elem32 / 8u;
    let j = elem32 % 8u;

    let scale_byte = read_byte(scales_off + ib32);
    let half = lane / 2u;
    let scale_nibble = select(scale_byte >> 4u, scale_byte & 0x0Fu, half == 0u);
    let dl = d * (0.5 + f32(scale_nibble)) * 0.25;

    let qh_byte = read_byte(qh_off + ib32);
    let high = (qh_byte >> (2u * lane)) & 0x03u;
    let low = read_byte(qs_off + ib32 * 4u + lane);
    let grid_index = low | (high << 8u);
    let signs = read_byte(qs_off + 32u + ib32 * 4u + lane);
    let grid = iq2_s_grid_lookup(grid_index);
    let raw = 2 * i32((grid >> (2u * j)) & 0x3u) + 1;
    let sign = select(1.0, -1.0, ((signs >> j) & 1u) != 0u);
    return dl * f32(raw) * sign;
}}
"""

IQ3_XXS_BODY = """
fn dequant_iq3_xxs(b_row: u32, k_abs: u32) -> f32 {{
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 98u;

    let d = read_f16(block_byte);
    let grid_indexes_off = block_byte + 2u;
    let scales_signs_off = block_byte + 2u + 64u;

    let ib32 = in_block / 32u;
    let elem32 = in_block % 32u;
    let lane = elem32 / 8u;
    let half = (elem32 % 8u) / 4u;     // 0 = grid1, 1 = grid2
    let j = elem32 % 4u;

    let packed = read_byte(scales_signs_off + 4u * ib32 + 0u)
        | (read_byte(scales_signs_off + 4u * ib32 + 1u) << 8u)
        | (read_byte(scales_signs_off + 4u * ib32 + 2u) << 16u)
        | (read_byte(scales_signs_off + 4u * ib32 + 3u) << 24u);
    let db = d * (0.5 + f32(packed >> 28u)) * 0.5;
    let signs = iq2_sign_mask((packed >> (7u * lane)) & 0x7Fu);

    let grid_index = read_byte(grid_indexes_off + ib32 * 8u + 2u * lane + half);
    let grid = iq3_xxs_grid_lookup(grid_index);
    let raw = (grid >> (8u * j)) & 0xFFu;
    let sign_bit = (j + half * 4u);
    let sign = select(1.0, -1.0, ((signs >> sign_bit) & 1u) != 0u);
    return db * f32(raw) * sign;
}}
"""

IQ3_S_BODY = """
fn dequant_iq3_s(b_row: u32, k_abs: u32) -> f32 {{
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 110u;

    let d = read_f16(block_byte);
    let qs_off = block_byte + 2u;
    let qh_off = block_byte + 66u;
    let signs_off = block_byte + 74u;
    let scales_off = block_byte + 106u;

    // Layout follows quant_codec.zig dequantizeIQ3S:
    //   pair = ib32 / 2  (0..3)        — picks scale nibble
    //   half = ib32 % 2  (0..1)        — picks low/high nibble
    //   q_base = ib32 * 16 (within qs)
    //   sign_base = ib32 * 4
    let pair = (in_block / 32u) / 2u;
    let half = (in_block / 32u) % 2u;
    let elem32 = in_block % 32u;
    let lane = elem32 / 8u;
    let grid_half = (elem32 % 8u) / 4u;  // 0 = grid1, 1 = grid2
    let j = elem32 % 4u;

    let scale_byte = read_byte(scales_off + pair);
    let scale_nibble = select(scale_byte >> 4u, scale_byte & 0x0Fu, half == 0u);
    let dl = d * f32(1u + 2u * scale_nibble);

    let q_base = pair * 16u + half * 8u;
    let qh_byte = read_byte(qh_off + pair * 2u + half);
    let q_idx = q_base + 2u * lane + grid_half;
    let high = (qh_byte >> (2u * lane + grid_half)) & 0x01u;
    let grid_index = read_byte(qs_off + q_idx) | (high << 8u);
    let grid = iq3_s_grid_lookup(grid_index);
    let sign_bits = read_byte(signs_off + (pair * 8u + half * 4u) + lane);
    let raw = (grid >> (8u * j)) & 0xFFu;
    let sign_bit = j + grid_half * 4u;
    let sign = select(1.0, -1.0, ((sign_bits >> sign_bit) & 1u) != 0u);
    return dl * f32(raw) * sign;
}}
"""

IQ1_S_BODY = """
fn dequant_iq1_s(b_row: u32, k_abs: u32) -> f32 {{
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 50u;

    let d = read_f16(block_byte);
    let qs_off = block_byte + 2u;
    let qh_off = block_byte + 34u;

    let ib = in_block / 32u;
    let elem = in_block % 32u;
    let lane = elem / 8u;
    let j = elem % 8u;

    let qh_word = read_u16(qh_off + 2u * ib);
    let dl = d * f32(2u * ((qh_word >> 12u) & 0x7u) + 1u);
    let delta = select(0.125, -0.125, (qh_word & 0x8000u) != 0u);

    let low = read_byte(qs_off + ib * 4u + lane);
    let high = (qh_word >> (3u * lane)) & 0x7u;
    let grid_index = low | (high << 8u);
    let grid = iq1_s_grid_lookup(grid_index);
    let trit = (grid >> (2u * j)) & 0x3u;
    let raw = i32(trit) - 1;
    return dl * (f32(raw) + delta);
}}
"""

IQ1_M_BODY = """
fn dequant_iq1_m(b_row: u32, k_abs: u32) -> f32 {{
    let blocks_per_row = params.K / 256u;
    let block_idx = k_abs / 256u;
    let in_block = k_abs % 256u;
    let block_byte = (b_row * blocks_per_row + block_idx) * 56u;

    let qs_off = block_byte;
    let qh_off = block_byte + 32u;
    let scales_off = block_byte + 48u;

    // Reconstruct per-block fp16 scale bits from 4 u16 nibble shards.
    let s0 = read_u16(scales_off + 0u);
    let s1 = read_u16(scales_off + 2u);
    let s2 = read_u16(scales_off + 4u);
    let s3 = read_u16(scales_off + 6u);
    let scale_bits = (s0 >> 12u) | ((s1 >> 8u) & 0x00F0u) | ((s2 >> 4u) & 0x0F00u) | (s3 & 0xF000u);
    let d = unpack2x16float(scale_bits & 0xFFFFu).x;

    let ib = in_block / 32u;
    let elem = in_block % 32u;
    let lane = elem / 8u;       // 0..3, picks indexes[lane]
    let j = elem % 8u;

    let sc_word = select(select(s3, s2, ib < 6u), select(s1, s0, ib < 2u), ib < 4u);
    let sc_pair = ib % 2u;
    let sc_shift = 6u * sc_pair;
    let dl_idx = lane / 2u;
    let dl = d * f32(2u * ((sc_word >> (sc_shift + 3u * dl_idx)) & 0x7u) + 1u);

    let q_base = ib * 4u;
    let h_base = ib * 2u;
    let qh_byte = read_byte(qh_off + h_base + (lane / 2u));
    let qs_byte = read_byte(qs_off + q_base + lane);
    let high_shift = select(8u, 4u, (lane % 2u) == 1u);
    let grid_index = qs_byte | ((qh_byte << high_shift) & 0x700u);

    let delta_bit = select(0x08u, 0x80u, (lane % 2u) == 1u);
    let delta = select(0.125, -0.125, (qh_byte & delta_bit) != 0u);

    let grid = iq1_s_grid_lookup(grid_index);
    let trit = (grid >> (2u * j)) & 0x3u;
    let raw = i32(trit) - 1;
    return dl * (f32(raw) + delta);
}}
"""


SHADER_SPECS = [
    {
        "fmt": "IQ2_XXS",
        "fmt_lower": "iq2_xxs",
        "grids": [("iq2_xxs_grid", "u16")],
        "body": IQ2_XXS_BODY,
    },
    {
        "fmt": "IQ2_XS",
        "fmt_lower": "iq2_xs",
        "grids": [("iq2_xs_grid", "u16")],
        "body": IQ2_XS_BODY,
    },
    {
        "fmt": "IQ2_S",
        "fmt_lower": "iq2_s",
        "grids": [("iq2_s_grid", "u16")],
        "body": IQ2_S_BODY,
    },
    {
        "fmt": "IQ3_XXS",
        "fmt_lower": "iq3_xxs",
        "grids": [("iq3_xxs_grid", "u32")],
        "body": IQ3_XXS_BODY,
    },
    {
        "fmt": "IQ3_S",
        "fmt_lower": "iq3_s",
        "grids": [("iq3_s_grid", "u32")],
        "body": IQ3_S_BODY,
    },
    {
        "fmt": "IQ1_S",
        "fmt_lower": "iq1_s",
        "grids": [("iq1_s_grid", "u16")],
        "body": IQ1_S_BODY,
    },
    {
        "fmt": "IQ1_M",
        "fmt_lower": "iq1_m",
        "grids": [("iq1_s_grid", "u16")],
        "body": IQ1_M_BODY,
    },
]


def main():
    text = SRC.read_text()
    grids = {
        "iq2_xxs_grid": parse_grid("iq2_xxs_grid", text),
        "iq2_xs_grid": parse_grid("iq2_xs_grid", text),
        "iq2_s_grid": parse_grid("iq2_s_grid", text),
        "iq3_xxs_grid": parse_grid("iq3_xxs_grid", text),
        "iq3_s_grid": parse_grid("iq3_s_grid", text),
        "iq1_s_grid": parse_grid("iq1_s_grid", text),
    }

    SHADERS_DIR.mkdir(parents=True, exist_ok=True)

    for spec in SHADER_SPECS:
        parts = [PROLOG.format(fmt=spec["fmt"], fmt_lower=spec["fmt_lower"])]
        for grid_name, grid_width in spec["grids"]:
            values = grids[grid_name]
            width = 16 if grid_width == "u16" else 32
            parts.append(fmt_array(grid_name, values, width=width))
            if grid_width == "u16":
                parts.append(grid_lookup_u16(grid_name))
            else:
                parts.append(grid_lookup_u32(grid_name))
        parts.append(spec["body"].format(fmt_lower=spec["fmt_lower"]))
        parts.append(EPILOG.format(fmt_lower=spec["fmt_lower"]))
        out_path = SHADERS_DIR / f"matmul_transb_{spec['fmt_lower']}.wgsl"
        out_path.write_text("".join(parts))
        print(f"wrote {out_path.relative_to(ROOT)} ({len(parts)} parts)")


if __name__ == "__main__":
    main()
