//go:build go1.22

// Package embeddings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package embeddings

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CohereEmbedderConfigInputType.
const (
	CohereEmbedderConfigInputTypeClassification CohereEmbedderConfigInputType = "classification"
	CohereEmbedderConfigInputTypeClustering     CohereEmbedderConfigInputType = "clustering"
	CohereEmbedderConfigInputTypeSearchDocument CohereEmbedderConfigInputType = "search_document"
	CohereEmbedderConfigInputTypeSearchQuery    CohereEmbedderConfigInputType = "search_query"
)

// Defines values for CohereEmbedderConfigTruncate.
const (
	CohereEmbedderConfigTruncateEND   CohereEmbedderConfigTruncate = "END"
	CohereEmbedderConfigTruncateNONE  CohereEmbedderConfigTruncate = "NONE"
	CohereEmbedderConfigTruncateSTART CohereEmbedderConfigTruncate = "START"
)

// Defines values for EmbedderProvider.
const (
	EmbedderProviderAntfly     EmbedderProvider = "antfly"
	EmbedderProviderBedrock    EmbedderProvider = "bedrock"
	EmbedderProviderCohere     EmbedderProvider = "cohere"
	EmbedderProviderGemini     EmbedderProvider = "gemini"
	EmbedderProviderMock       EmbedderProvider = "mock"
	EmbedderProviderOllama     EmbedderProvider = "ollama"
	EmbedderProviderOpenai     EmbedderProvider = "openai"
	EmbedderProviderOpenrouter EmbedderProvider = "openrouter"
	EmbedderProviderTermite    EmbedderProvider = "termite"
	EmbedderProviderVertex     EmbedderProvider = "vertex"
)

// AntflyEmbedderConfig Configuration for the built-in Antfly embedding provider.
//
// Uses an embedded INT8-quantized all-MiniLM-L6-v2 ONNX model bundled directly
// in the binary. No external service, API key, or model download required.
//
// **Model:** all-MiniLM-L6-v2 (384 dimensions, text-only)
//
// **Features:**
// - Zero configuration — works out of the box
// - No network access required
// - Pure Go inference via GoMLX
type AntflyEmbedderConfig = map[string]interface{}

// BedrockEmbedderConfig Configuration for the AWS Bedrock embedding provider.
//
// Uses the AWS credential chain: environment variables, web identity, shared credentials, ECS task roles, and EC2 instance roles.
//
// **Example Models:** cohere.embed-v4, amazon.titan-embed-text-v2:0
//
// **Docs:** https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html
type BedrockEmbedderConfig struct {
	// BatchSize The batch size for embedding requests to optimize throughput.
	BatchSize *int `json:"batch_size,omitempty"`

	// Dimension Output dimension for Bedrock embedding models that support configurable dimensions.
	Dimension *int `json:"dimension,omitempty"`

	// Dimensions Alias for output dimension when using OpenAI-compatible configuration fields.
	Dimensions *int `json:"dimensions,omitempty"`

	// InputType Cohere Bedrock input type, such as search_document, search_query, classification, or clustering.
	InputType *string `json:"input_type,omitempty"`

	// Model The Bedrock model ID to use (e.g., 'cohere.embed-v4', 'amazon.titan-embed-text-v2:0').
	Model string `json:"model"`

	// Region The AWS region for the Bedrock service (e.g., 'us-east-1').
	Region *string `json:"region,omitempty"`

	// StripNewLines Whether to strip new lines from the input text before embedding.
	StripNewLines *bool `json:"strip_new_lines,omitempty"`

	// Truncate Cohere Bedrock truncate behavior.
	Truncate *string `json:"truncate,omitempty"`
}

// CohereEmbedderConfig Configuration for the Cohere embedding provider.
//
// API key via `api_key` field or `COHERE_API_KEY` environment variable.
//
// **Example Models:** embed-english-v3.0 (default, 1024 dims), embed-multilingual-v3.0
//
// **Docs:** https://docs.cohere.com/reference/embed
type CohereEmbedderConfig struct {
	// ApiKey The Cohere API key. Can also be set via COHERE_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// InputType Specifies the type of input for optimized embeddings.
	InputType *CohereEmbedderConfigInputType `json:"input_type,omitempty"`

	// Model The name of the Cohere embedding model to use.
	Model string `json:"model"`

	// Truncate How to handle inputs longer than the max token length.
	Truncate *CohereEmbedderConfigTruncate `json:"truncate,omitempty"`
}

// CohereEmbedderConfigInputType Specifies the type of input for optimized embeddings.
type CohereEmbedderConfigInputType string

// CohereEmbedderConfigTruncate How to handle inputs longer than the max token length.
type CohereEmbedderConfigTruncate string

// EmbedderConfig defines model for EmbedderConfig.
type EmbedderConfig struct {
	// Multimodal Declare that this model supports non-text content (images, audio, video, PDFs),
	// even if the model isn't in Antfly's built-in model registry yet.
	//
	// When `true`, Antfly treats the model as multimodal and will send binary content
	// (images, audio, etc.) to the provider instead of extracting text. The provider's
	// API is still responsible for accepting the content — this flag just tells Antfly
	// not to strip it.
	//
	// Not needed for models already in the registry (e.g., `multimodalembedding`,
	// `gemini-embedding-2-preview`, `clip-*`, `clipclap`).
	//
	// **Example:**
	// ```json
	// {
	//   "provider": "vertex",
	//   "model": "some-future-multimodal-model",
	//   "multimodal": true
	// }
	// ```
	Multimodal *bool `json:"multimodal,omitempty"`

	// Provider The embedding provider to use.
	Provider EmbedderProvider `json:"provider"`
	union    json.RawMessage
}

// EmbedderProvider The embedding provider to use.
type EmbedderProvider string

// GoogleEmbedderConfig Configuration for the Google AI (Gemini) embedding provider.
//
// API key via `api_key` field or `GEMINI_API_KEY` environment variable.
//
// **Example Models:** gemini-embedding-001 (default, 3072 dims)
//
// **Docs:** https://ai.google.dev/gemini-api/docs/embeddings
type GoogleEmbedderConfig struct {
	// ApiKey The Google API key. Can also be set via GEMINI_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimension The dimension of the embedding vector (768, 1536, or 3072 recommended).
	Dimension *int `json:"dimension,omitempty"`

	// Location The Google Cloud location (e.g., 'us-central1'). Required for Vertex AI, optional for Gemini API.
	Location *string `json:"location,omitempty"`

	// Model The name of the embedding model to use.
	Model string `json:"model"`

	// ProjectId The Google Cloud project ID (optional for Gemini API, required for Vertex AI).
	ProjectId *string `json:"project_id,omitempty"`

	// Url The URL of the Google API endpoint (optional, uses default if not specified).
	Url *string `json:"url,omitempty"`
}

// OllamaEmbedderConfig Configuration for the Ollama embedding provider.
//
// Local embeddings for privacy and offline use. URL via `url` field or `OLLAMA_HOST` env var.
//
// **Example Models:** nomic-embed-text (768 dims), mxbai-embed-large (1024 dims), all-minilm (384 dims)
//
// **Docs:** https://ollama.com/search?c=embedding
type OllamaEmbedderConfig struct {
	// Model The name of the Ollama model to use (e.g., 'nomic-embed-text', 'mxbai-embed-large').
	Model string `json:"model"`

	// Url The URL of the Ollama API endpoint. Can also be set via OLLAMA_HOST environment variable.
	Url *string `json:"url,omitempty"`
}

// OpenAIEmbedderConfig Configuration for the OpenAI embedding provider.
//
// API key via `api_key` field or `OPENAI_API_KEY` environment variable.
// Supports OpenAI-compatible APIs via `url` field.
//
// **Example Models:** text-embedding-3-small (default, 1536 dims), text-embedding-3-large (3072 dims)
//
// **Docs:** https://platform.openai.com/docs/guides/embeddings
type OpenAIEmbedderConfig struct {
	// ApiKey The OpenAI API key. Can also be set via OPENAI_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimensions Output dimension for the embedding (uses MRL for dimension reduction). Recommended: 256, 512, 1024, 1536, or 3072.
	Dimensions *int `json:"dimensions,omitempty"`

	// Model The name of the OpenAI model to use.
	Model string `json:"model"`

	// Url The URL of the OpenAI API endpoint. Defaults to OpenAI's API. Can be set via OPENAI_BASE_URL environment variable.
	Url *string `json:"url,omitempty"`
}

// OpenRouterEmbedderConfig Configuration for the OpenRouter embedding provider.
//
// OpenRouter provides a unified API for multiple embedding models from different providers.
// API key via `api_key` field or `OPENROUTER_API_KEY` environment variable.
//
// **Example Models:** openai/text-embedding-3-small (default), openai/text-embedding-3-large,
// google/gemini-embedding-001, qwen/qwen3-embedding-8b
//
// **Docs:** https://openrouter.ai/docs/api/reference/embeddings
type OpenRouterEmbedderConfig struct {
	// ApiKey The OpenRouter API key. Can also be set via OPENROUTER_API_KEY environment variable.
	ApiKey *string `json:"api_key,omitempty"`

	// Dimensions Output dimension for the embedding (if supported by the model).
	Dimensions *int `json:"dimensions,omitempty"`

	// Model The OpenRouter model identifier (e.g., 'openai/text-embedding-3-small', 'google/gemini-embedding-001').
	Model string `json:"model"`
}

// TermiteEmbedderConfig Configuration for the Termite embedding provider.
//
// Termite is Antfly's built-in ML service for local embeddings using ONNX models.
// It provides embedding generation with multi-tier caching (memory + persistent).
//
// **Features:**
// - Local ONNX-based embedding generation
// - L1 memory cache with configurable TTL
// - L2 persistent Pebble database cache
// - Singleflight deduplication for concurrent identical requests
//
// **Example Models:** bge-base-en-v1.5 (768 dims), all-MiniLM-L6-v2 (384 dims)
//
// Models are loaded from the `models/embedders/{name}/` directory.
type TermiteEmbedderConfig struct {
	// ApiUrl The URL of the Termite API endpoint. Can also be set via ANTFLY_TERMITE_URL environment variable.
	ApiUrl *string `json:"api_url,omitempty"`

	// Model The embedding model name (maps to models/embedders/{name}/ directory).
	Model string `json:"model"`
}

// VertexEmbedderConfig Configuration for Google Cloud Vertex AI embedding models (enterprise-grade).
//
// Uses Application Default Credentials (ADC) for authentication. Requires IAM role `roles/aiplatform.user`.
//
// **Example Models:** gemini-embedding-001 (default, 3072 dims), multimodalembedding (images/audio/video)
//
// **Docs:** https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings
type VertexEmbedderConfig struct {
	// CredentialsPath Path to service account JSON key file. Alternative to ADC for non-GCP environments.
	CredentialsPath *string `json:"credentials_path,omitempty"`

	// Dimension The dimension of the embedding vector (768, 1536, or 3072 for gemini-embedding-001; 128-1408 for multimodalembedding).
	Dimension *int `json:"dimension,omitempty"`

	// Location Google Cloud region for Vertex AI API (e.g., 'us-central1', 'europe-west1'). Can also be set via GOOGLE_CLOUD_LOCATION. Defaults to 'us-central1'.
	Location *string `json:"location,omitempty"`

	// Model The name of the Vertex AI embedding model to use.
	Model string `json:"model"`

	// ProjectId Google Cloud project ID. Can also be set via GOOGLE_CLOUD_PROJECT environment variable.
	ProjectId *string `json:"project_id,omitempty"`
}

// AsGoogleEmbedderConfig returns the union data inside the EmbedderConfig as a GoogleEmbedderConfig
func (t EmbedderConfig) AsGoogleEmbedderConfig() (GoogleEmbedderConfig, error) {
	var body GoogleEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromGoogleEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided GoogleEmbedderConfig
func (t *EmbedderConfig) FromGoogleEmbedderConfig(v GoogleEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeGoogleEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided GoogleEmbedderConfig
func (t *EmbedderConfig) MergeGoogleEmbedderConfig(v GoogleEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsVertexEmbedderConfig returns the union data inside the EmbedderConfig as a VertexEmbedderConfig
func (t EmbedderConfig) AsVertexEmbedderConfig() (VertexEmbedderConfig, error) {
	var body VertexEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromVertexEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided VertexEmbedderConfig
func (t *EmbedderConfig) FromVertexEmbedderConfig(v VertexEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeVertexEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided VertexEmbedderConfig
func (t *EmbedderConfig) MergeVertexEmbedderConfig(v VertexEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOllamaEmbedderConfig returns the union data inside the EmbedderConfig as a OllamaEmbedderConfig
func (t EmbedderConfig) AsOllamaEmbedderConfig() (OllamaEmbedderConfig, error) {
	var body OllamaEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOllamaEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OllamaEmbedderConfig
func (t *EmbedderConfig) FromOllamaEmbedderConfig(v OllamaEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOllamaEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OllamaEmbedderConfig
func (t *EmbedderConfig) MergeOllamaEmbedderConfig(v OllamaEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenAIEmbedderConfig returns the union data inside the EmbedderConfig as a OpenAIEmbedderConfig
func (t EmbedderConfig) AsOpenAIEmbedderConfig() (OpenAIEmbedderConfig, error) {
	var body OpenAIEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenAIEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OpenAIEmbedderConfig
func (t *EmbedderConfig) FromOpenAIEmbedderConfig(v OpenAIEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenAIEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OpenAIEmbedderConfig
func (t *EmbedderConfig) MergeOpenAIEmbedderConfig(v OpenAIEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsOpenRouterEmbedderConfig returns the union data inside the EmbedderConfig as a OpenRouterEmbedderConfig
func (t EmbedderConfig) AsOpenRouterEmbedderConfig() (OpenRouterEmbedderConfig, error) {
	var body OpenRouterEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOpenRouterEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided OpenRouterEmbedderConfig
func (t *EmbedderConfig) FromOpenRouterEmbedderConfig(v OpenRouterEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOpenRouterEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided OpenRouterEmbedderConfig
func (t *EmbedderConfig) MergeOpenRouterEmbedderConfig(v OpenRouterEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsBedrockEmbedderConfig returns the union data inside the EmbedderConfig as a BedrockEmbedderConfig
func (t EmbedderConfig) AsBedrockEmbedderConfig() (BedrockEmbedderConfig, error) {
	var body BedrockEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromBedrockEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided BedrockEmbedderConfig
func (t *EmbedderConfig) FromBedrockEmbedderConfig(v BedrockEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeBedrockEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided BedrockEmbedderConfig
func (t *EmbedderConfig) MergeBedrockEmbedderConfig(v BedrockEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsCohereEmbedderConfig returns the union data inside the EmbedderConfig as a CohereEmbedderConfig
func (t EmbedderConfig) AsCohereEmbedderConfig() (CohereEmbedderConfig, error) {
	var body CohereEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCohereEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided CohereEmbedderConfig
func (t *EmbedderConfig) FromCohereEmbedderConfig(v CohereEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCohereEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided CohereEmbedderConfig
func (t *EmbedderConfig) MergeCohereEmbedderConfig(v CohereEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTermiteEmbedderConfig returns the union data inside the EmbedderConfig as a TermiteEmbedderConfig
func (t EmbedderConfig) AsTermiteEmbedderConfig() (TermiteEmbedderConfig, error) {
	var body TermiteEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTermiteEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided TermiteEmbedderConfig
func (t *EmbedderConfig) FromTermiteEmbedderConfig(v TermiteEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTermiteEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided TermiteEmbedderConfig
func (t *EmbedderConfig) MergeTermiteEmbedderConfig(v TermiteEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAntflyEmbedderConfig returns the union data inside the EmbedderConfig as a AntflyEmbedderConfig
func (t EmbedderConfig) AsAntflyEmbedderConfig() (AntflyEmbedderConfig, error) {
	var body AntflyEmbedderConfig
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAntflyEmbedderConfig overwrites any union data inside the EmbedderConfig as the provided AntflyEmbedderConfig
func (t *EmbedderConfig) FromAntflyEmbedderConfig(v AntflyEmbedderConfig) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAntflyEmbedderConfig performs a merge with any union data inside the EmbedderConfig, using the provided AntflyEmbedderConfig
func (t *EmbedderConfig) MergeAntflyEmbedderConfig(v AntflyEmbedderConfig) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t EmbedderConfig) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Multimodal != nil {
		object["multimodal"], err = json.Marshal(t.Multimodal)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'multimodal': %w", err)
		}
	}

	object["provider"], err = json.Marshal(t.Provider)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'provider': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *EmbedderConfig) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["multimodal"]; found {
		err = json.Unmarshal(raw, &t.Multimodal)
		if err != nil {
			return fmt.Errorf("error reading 'multimodal': %w", err)
		}
	}

	if raw, found := object["provider"]; found {
		err = json.Unmarshal(raw, &t.Provider)
		if err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
	}

	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8R863LbyPXnq5zCZMuSFiR18TgupqaysiR7lOhWkpxJdugSm8Ah2SOgG+5uSOKoVLWP",
	"sB/2Nfal8iRb53QDBElQkp1k/19mKKAvp8/ldy594Mco0XmhFSpno/5jZJMp5oJ/7is3zmZH+QjTFM2B",
	"VmM5oecp2sTIwkmton7kn5dG0N8w1gbcFGFUysx1pAK/CCCvItUECqPvZIqmO1AD9dmiBaHCa0zh+Oz6",
	"fedrKZSTv2MKIss6p1LJk9POybvO3S6cn539HXKdYgajUqUZppBKg4nLZgMlld9bKmFmXTjTgA8OjRIZ",
	"WDR3MsEY9i+O4RZnMWgT1kn1vcq0SMHg11IaTJmyra1Tetvf2lolYmPv/VtIZY7KSq1sDA4fXEerbLbp",
	"p35E4UqDtr+1NVAd+J9oNCQLfPrn//o/cK/NrQVdOtBjT7h+oOFnGhQ6egsiSdDamjJ6e1EahE8apBqj",
	"QZUg3EkBn/Tpyd+jOMIHkRcZkpgqRkf9SLAQoqc4crMCo36kR79h4ujBB0yNTm6/T8r7v1xBWOBZCVdj",
	"E4MpKidFBslUSNUHVHfSaJWjcnAnjBSjDG0M9zgCyUPdLAY7FQbTxmwbw9HBFThhb8FoniFUCkcHuyCV",
	"dYK4ws+DKI88V4BFSlKBRE/RYJeJ7ty9jUHk4netuk46oTr+MUv1bre/7Rc51AlPnTpX2H6vl+rEdsW9",
	"7Yapic57I8+MXiYcWtcrLZpJKVPssarZji2LQhuHaXfq8mxRXjwk6kdLpEVxU5JhgyiODE68aErbQWFd",
	"Z4fEWRhdoHES2YJHwiXTGyt/Ry/RsSgzF/V34iXpXpPy0VigsSzeuThJ+dA6C06DLpzMaYibGl1OpkXp",
	"ulGtVVI5nKAhOmrrWFWl89IVpZvbD2+3qkWeY+CmwkFg29yGRhk2DPAFEuwqDfuZFJY31svU3E9RQWmJ",
	"hPMC1f5xhwBSOEl7LhrxWGKWrtldqqJ0N/75qjGRhOsz81CgoTHYMpmCsGBRmGR6k+qkJNuIqwdfSzSz",
	"GJJMWCvHMmFCGMySrLQOjVSTBkHW0QOiJ2jXY4vkKzo8HB4fkqBLi7CB3Uk3hjdLCvkmhjfPWcubzW5T",
	"sVv0eYW4SpfbqCPc8O9r2KkIDqBeE1pbwjIJcxNp2Zx+FTcK728yqdAuWMpYZBaXreWXKbopGmITzwWF",
	"98BzYWx0ziQGmeKDgxGOtcG5ZjfEM9I6Q6EYmE2pEuFe1pZqIIxwKu6kNi3iZpZ6lxH1fw2y/9KC/n7t",
	"7wP/QNca3A9+lp3TUBTy5hZnQ28xpK3Dg/Ofjy6PbvYvjm/+evSPYasjWIveXpdQTTJpp527ve42bASZ",
	"xbCzvcve2W7GYWBeZk5mUk1KkfHoZwA9aCuBucHgYXu8zCJaN+07WrLWqDa3aJXSRTz3260id+BYu0kE",
	"zgcWd+FAKBCZ1TBCsOiY54v8bWdvmzUs41YwhJYjLtJ1VWAixzI4e5pPUY03A8bZ4DnSucIwcqIqc9LR",
	"1fWbiBfF0SLk8YMK8Bqq3Qp41RlahbHKXiVyrEKyFSX3IOkRchFkWldfIWvRzivKjs4OV0j5Wd/TPlNB",
	"Ya7npIVMqwlBz1T4WDcXD+D0LSrIUE3ctMnSs/OzoyiOrq73L6+jmPf48v1QsQoSIsvOx1H/18dIKwy/",
	"/mBwHPWjH3rzrKIXUoreJ60n2TLYPMXPT/obGocP3zjpPMtELr51Env775h0qUuH5hsntsfdL81qxeuX",
	"Jl2jyaX71lmt2d/TF5q2CFWMrrlORUt4cYhJJgz6KM5NpQ32EwI6C0orjhwosnIEThsyFxMO6MtU6hgI",
	"KHUMF4cf7WY8UHiHCqS3Tb+UtOqNgzrTfGPnuacfQMGDdWYGM3TsUX6hCG/oTInDuMpPnUHhbGNZYWF+",
	"MM4u7mVGeaRKQ4JZkTxQyzSjS7qbZLu0XAX2nJmgSAlZ8MEZkTjCEzp8F64bA99Y7z2lBetoT4O20Mpy",
	"AEpQSklh4SdPsWYcZZTM4XEmJvBbaSn8yDIbTjhQSrt5yCI9K860A4VImfe4SogtiMygSGcQ8umagSHO",
	"Gs4ZU+PiMB6o4QRzqWSnftjZ7RQG7yTeD2MYJpksOlvVryQTxXBz0cNzujwcDn+zWg3U40ABDGpnOYj6",
	"MIjuGA4GUexfMsH+jdU5dsYl5d2dOYGdMKIaX7+gSaQCA/XEe7YGZXNH/bytVFZyUY1fhtV6oS9PX5Zx",
	"fh9KRZ4zXc4uSNRqXXxVbWkhEYocfzUZSVPdFBzmBaehJPSktE5z4jbV91A5WQvC4EAlWjFbU1bZ1pAV",
	"ruvVKDP4mX3SSBgLdqaceCADGagqTaMAQ5cNQ5xiVqCpsvFqLbiaWYd5KJJsbV3xUltb/eb64Rh0/o0q",
	"UJvWr3+zHKn5HHvTL3MgkqlUE1pnTjWBkCidzoWTiciyGSQimVa8Wsgrr69P6miyDz9CLlXp0Fark7k9",
	"uMXVDSYo75CtZVxmWc1hgpHEz/Bn/1Cx5GfPEj78QO10YWvLJqYc/ezybGsLOnCJub5D8JrSs26WITgx",
	"sYxFAUAgIU31MuPU4+fr0xPSdBgOh3Mu8ZPHx3p9mLo8uwnA8fRUTeD/VxtbGA7K7e29xBPAv3HIm1cv",
	"iKTqOVEW5u+nqaWUyGdEYuzQwCjj5D5Dr3YbRQypvIthutOZvoshkwE0axJcaZSFIhMyHI/lVBiknA9T",
	"IIASI5lJNyP+7RL/8Csz7uhrKeg5cN5upA22lGiVSrIskdm1PPpBjmEDv4J1wpUWBhHB9B0Oos2np33+",
	"SQZgHh97chw4N5/0PyjhGUSWQmFCmM2npyv/2yc+zVnM74HaI8JzTKVg2j+h+qt0kGpXGJ0XDvhVKHHS",
	"5ozSc79Uu6A1x/HTS5P9xC7qUDjx+fK4Jnz+mjxHl8fclCZrGTCIKusLES8bHs/o/lZMBlHrHLtHE1Ra",
	"aKlcb1Qmt+jCpEKtmzSWGfZ7vV4h3LTndMsmgXkAhBpVSQ0+X57AFSFyKLyyKg1T4UR/CB34ICy+ewuo",
	"Ek3+jp7D58tjW7s1Hsmb9X4rcPKnEU+Iu93usFLMITGh3+sNoed/W/6jA7/giPa3Xk9rpKm9MydEKToS",
	"o1bVauGktMCJTlhNMrSMikCnr0xqyHykYVd7zXKUddqICcLGWJtcuH4YuMxwSr03a4bt18QdBOIujE7Q",
	"Wqkmc75tbR1zUENAdxgq5JjGFIxwFrchxyFy2IxhwYPUjK1XouDNA+aDq6ALuQwwlsY6KOgMBlWK5L2E",
	"BRZCPZ1AjaZfss0TDC6u44t1p/p3mWUijKqRwesIJqUhSKATG53V+lGdzDuIwmgSEKYwqqM7sNVci47c",
	"kIUNi5QYNn31ZVUq2OxXKJhl+h5TmGrr4H4qHWbSuvDywsg7coDHFx4Z2btRqMToeHV1+RGEcyK5tZXi",
	"VYT6Am0mc0kwWnupne3t0w8rY53MUZcLA/e26yVZvo3C58qiu9tv3xcPMWtzJ8i9UqMrxH5dOPHXC12p",
	"uYTSWwhjfqj41+kkmnBpoN4yWLMZXmutPGjzn153pILr8/Mz8EoNG9eU33bOjURFsjnnlBTOtOMNNteC",
	"33wLDoy7vlxbQ07765BHnwpzi+Ynrv+BVCkq99Pbl6amyDxE89MgGgxcK1z9QpmQtHzCPwct5NNKC8K7",
	"rMTFMC1zoTqm0vjAihStnKgQrBeCTZYC+jJxHPgx+5yGk5NTCrYA4NhVYaOFra297c677f8WCgYG05LR",
	"iK9DyFV6+/3L1fkZaWyGkAupnJCKtpnKyZQW5mVpvMFp0ByRJKURyaxbn/KvOIOFSzDWuAN/uipm9HY7",
	"7A/5OLc469yJrEQohDR1MGGMmAWZQM5CsX0YUrjx6w97X/ogZOwLRXGeVRHMtRiVmTAV12h1CrG1yT2H",
	"ao5Vu5zXxSkae3JyCoUwTB3FOyUBk3VCUSgcZpwGzlgvqeV4hJnwARWOpbNNUD3R92i4cpdo62yI9NIy",
	"Yd7f8tUDmWWOQlnIeDTRU8+oV/ooLEVWITlEv9QJWuvX4bC/8MBezzmlqD6pIljowEfpIKeH85SAHBgF",
	"Xb6oxJhQn+icc5amd21ayxA2KHfa7FMICD9QtDaWD0SHYCkmuqQNMnmLMCTpDRtgQ7lY7WW9wQ1hQyq3",
	"2Ydj/tMjrS1EQoIhQSm07EcYEBaQq16pNskhbPiS12YfPnIV2mIhjHDa+Ip20BkmtbmW0gpjznqGwaqH",
	"1QQ7d6pVjdpfJ1UMqoJqJ12GdA5ndDA6YsvfMKHtr1h/eaAo3VSbPvxFKIRD7X1gu7Lzqxyd4LCF/wJA",
	"H+H2YTc8INdq+/D2x+0VJDr0JyS4vdz/1N/aqnGI0phw/qYN1UmNd9UkBT8XvpZoZLht5bVrf9jQFV49",
	"lIl9EXfuQSbSTcsRh5ROa9Xxu/LvMPuThmPicF5pQutkkRW3aG+l6k20n7yQcAYpVVnXYXUgDtoavFzy",
	"JtdefBSl+iFdFiih+6Fwi29S4fjFtZhYevEDimS+dpdk+fT0+Ehu4+kphsfHHg2gGQP1+NjIyYKoKPip",
	"Y5GqbqTVKpEXXrVoTyVyT9y8ztBfyP8aBYgbygVp8IWRCfbhD4+PBf1qkHA6zzeYURydPUtAzZ6VDKSF",
	"rAYxjU0P5tla0EEKvlZ3XdiMEjFvQk9PH2a0ePVXnXrNs7VEOJxoM+MaE+ayzDlj++f//d9w4f+uAuTG",
	"5JFOZw0qt7aOGhcrf6saGEJJY/jp6PT47Hh+ydWp7mzYnnw9HPaPeez5xdHZ/tqxvjjdHPhh/+ro5vPl",
	"SZXacPozH9pME/YvKBinqScn+6f7Nz+fX13TNF8m52tUNDw/pEIhy8koJ6EAtr+z83bvbWhuOc4p3yLr",
	"vzDI25SEwkf1tU6wrn/okmtTkscDPkjLs+b3P7DBRQtPcBzuWvgyW6hZXe7ajGFUOtAqmw0UHZC8wwPa",
	"lYrXsOr28d5k2IWjqv2nmuJLp3DHwGvh3kjnUA1U1UNU9TV4CKzgYXgzp7m6w6TAINWgtIMJKjQELz5n",
	"97fAAzXkgUO+7ayKccNQArtyWHg+7XThwCDNbtb6rKe4/Vxc7vhIgIwqRKcPaGO++vN3zzR1WEf2Qy4z",
	"/GKkW/bzCyfrwyMMIl/b4SXORB7qO4OoD792u13/sp7iX3a73S/wNHy5ksuG6ou1pzOowLeuzVa1DB5Q",
	"QzPXx7vdelSDYBr56P3cIMpnN16qN0w7U7zd3Ylhu7tL/9mLgQil4U9VzTdcA2OGDuFDuE4PtvvZO/zl",
	"7Z7jkCqzDJ6GnAP7NQVn6JjO+9A8jbTBeS4Z0hZk8Gvr4l+GkKG4C3ertSH5taBUyVSoCab+OET4gbA1",
	"CJ3KifH1UzY2oTQ3L4TJ5JRGhB6sDi026nmxZLeVxnOiPO+x48IFz5hjRNHEiBZL99TUlySLG3/gnqSi",
	"Lk80adDjcSYVVrVqqSZow81wS1MVd6fMLyb2OjYXWbZ4F68LVEJy7X6loN96D79amm9eDIdbWH8pEsXh",
	"6iKKI82wSz/8hv6H4VvEKG60eIXmgDjK/d/OX+RFcdXQ13bv3XrL+sqWjtojwcYnJnvze9s7lj3fN7V3",
	"rNwjbW/vNBo89rb/uOsbPNr7OITsTvgg3RTvemExUUhfnZir0KKm1B0X0UyXhsZ36M+FVjbaed7b0Ubm",
	"okYF2X9bd0clhOe6OxbZ+/rujqW2vNB+4I+1Ssm8NhS6IebKEOBj44/v3sew8+PeOzZmlozBROc5pQjp",
	"ZntvHMUVbm3DVzj/QabLFKqhzR6vBJUzItt5s9mFy3DJxirsewWAEEYX89gRvC4TR19qjav6MdaI9vle",
	"kdc0iaxZeIWmwmhKam9k+gomhcFwfAgbaw4e1z3Ei5zabOVIada0ClKMGE7bUNOq3jzfnRNmWyeRcsyB",
	"kg09Ql4vfFQf9aPSyH+hha211+OVeBcC4DUY50vyDZfDVTcj70Qy4/ivckEkZWYNo2FpsiYSLsTcqO7I",
	"QNcin9K5TBoNlWxgVTNb/jASQXU6mTAThI1mr5vIsg6JO8vrBvV1COk9EGfMvp7w5+Sn+pztDnSZsiXX",
	"Wbk01pyoPX9YxcFnmlKbhhXE1LSqGg+W6XoTw5sVRi33g7YcZr0NVJiw5lDx82YSaG+aSTukN/RkLZ7P",
	"T7CWmH+XVbU1Q73Wqnju90YOy3nwmsjhquogak93l01xrcW1B4bNdtIf995VJrYyOJjhSxEJ5X4kmK6P",
	"+NjwOBjhxoXXxCT2ttPtdhuNpd8S0H5T+BGk92z4sSij7wg/7Cs/C1h0qxvsVE5DnWM+sr7J4ICgjj76",
	"sPvjuxh+3Nn1TcFLgUp7bNISDKxl9Quo5Rm5PhZYu+7rsIhD3UI2dOpFLJqLdo5FoQzM9wV+wBvLoRJL",
	"flXoVd3plSDVSuW/EaRamy+/Aaj8/HVg1RhRX6OJul+LGFk3ZBCsrHy9wil3KsdcDa+v4rgT6jU4eHn+",
	"+fro8juzKM/x3gsAtxmvHcjgFg+UT6Z6baFrDF/vUfXoP3uNN+9Ha+KOOs/tipCOUV621Gj/EhBqs4SF",
	"z550FRJDpv3tsBg04UVoXBTb/z94lGOoPzCD0Wzezbr5aqx7iZXPMiY05PJHemOJpg7Snl2VIrZnVGw5",
	"dnuJwu8Fk/Yu6VciSZi8Dkaq19K2dCmfntQfMtFy2XLWEb5Fqz98JfBoXuvP9wxlOf6KjW+0CJc6jiSR",
	"+KZI2Mgx12YG/x0KNFZah8pVXbhLX6369If27YyEbX640diIB+5AWJV7KttbKnngbmNXuMARf8ZXVSB5",
	"Mg27kmqS4TiTk6mDFNOyyMKFYdXHl5SG8dSrGpFZfaS4DgxHE+RTdFB17na6Py4kVms/8PXx3GnoijYI",
	"vgtq/pnX0Esk4BYa2/OXb71h6NnTZtZdhbI1WdL77fe7DVhbpnkRyapiYCuMvSaBr5Ty5dRk/+z648k/",
	"bq6PLk+Pr7/F+bed7nnf/+yHissFFo62NnJRcPCyThRzSSwhSQt/vxc8Wr9SeQV2LJRx6qLMahyxgcqh",
	"KYy02JkYkeLm/OPq/WJuH9Wd/sH8U2nY2D882PTd5KWbeoOhwXXxzMLx/il/Lw1D/mq6J2SdsZQWzfBf",
	"r9TG0PLRQPWxR4+/m+jxpx5rMqiEOFSVdSl98tX0jpC9CozusCNWary9CbrOoq+wg6U7gpUC77w+GTXK",
	"jdFrKr910S7KZ51JUnTCs0XbDVcBK6bb+ML9phBuuqpCF8JN+SuO4DFEwl01vmmLL4tlhl3Yz/hOhluG",
	"nYb9wwPfMKNV59PBRdN67X9ZnZgIamPkn2Bn931n5+32+6Vu53rUq8rKVUSzKMFF4hfMr/GR8dwSCRzb",
	"Ss8xvMGSZNe5R+u4FN1apz8//3RydHNwcv758Obk/GD/+vj8bDHnWlj2P1qfXosv/7FK9Zoq9St4dXF5",
	"/pejg+vXxs6vBOon/sB1rFv+QQDlk9+L46pKvRhxMG4Tw+bJ3GqsZ+efoR1+YCqlY17OeyOgulFcbCD2",
	"14Pe4KLt7naX/zEHDnULGfWjve52d48wRLipjfqqzLKn/xcAAP//xpeoOrpFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
