// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	externalRef0 "github.com/antflydb/antfly/lib/ai"
	externalRef1 "github.com/antflydb/antfly/lib/audio"
	externalRef2 "github.com/antflydb/antfly/lib/chunking"
	externalRef3 "github.com/antflydb/antfly/lib/embeddings"
	externalRef4 "github.com/antflydb/antfly/lib/middleware"
	externalRef5 "github.com/antflydb/antfly/lib/reranking"
	externalRef6 "github.com/antflydb/antfly/pkg/generating"
	externalRef7 "github.com/antflydb/antfly/pkg/libaf/logging"
	externalRef8 "github.com/antflydb/antfly/pkg/libaf/scraping"
	externalRef9 "github.com/antflydb/antfly/pkg/termite"
	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for StorageBackend.
const (
	StorageBackendLocal StorageBackend = "local"
	StorageBackendS3    StorageBackend = "s3"
)

// Config defines model for Config.
type Config struct {
	// Chains Named chain configurations for fallback/retry logic.
	//
	// Chains are ordered lists of generators with retry and fallback logic.
	// Each link references a generator by name from the `generators` map.
	// The first chain defined becomes the default when no chain name is specified.
	//
	// **Chain Conditions:**
	// - `on_error`: Try next generator on any error (default)
	// - `on_rate_limit`: Try next only on rate limit (429) errors
	// - `on_timeout`: Try next only on timeout errors
	// - `always`: Always try the next generator
	//
	// **Example:**
	// ```yaml
	// chains:
	//   default:
	//     - generator: gemini-flash  # Reference by name
	//       retry:
	//         max_attempts: 3
	//       condition: on_rate_limit
	//     - generator: ollama-local  # Reference by name
	//   with-inline:
	//     - generator: gemini-flash
	//     - generator_config:  # Inline config
	//         provider: anthropic
	//         model: claude-sonnet-4-5-20250929
	// ```
	//
	// Then in API calls: `chain: "default"` or `chain: "with-inline"`
	Chains map[string][]NamedChainLink `json:"chains,omitempty,omitzero"`

	// Chunkers Named chunker configurations for text chunking.
	//
	// Define named chunkers that can be referenced by indexes and API calls.
	// The first chunker defined becomes the default when no chunker name is specified.
	//
	// **Example:**
	// ```yaml
	// chunkers:
	//   fixed-500:
	//     provider: termite
	//     model: fixed
	//     target_tokens: 500
	//     overlap_tokens: 50
	//   semantic:
	//     provider: termite
	//     model: semantic-chunker
	//     api_url: "http://localhost:8080"
	// ```
	Chunkers map[string]externalRef2.ChunkerConfig `json:"chunkers,omitempty,omitzero"`
	Cors     externalRef4.CORSConfig               `json:"cors,omitempty,omitzero"`

	// DefaultShardsPerTable Default number of shards to create for a new table.
	DefaultShardsPerTable uint64 `json:"default_shards_per_table,omitempty,omitzero"`

	// DisableShardAlloc Disables automatic shard reallocation (splitting/merging).
	DisableShardAlloc bool `json:"disable_shard_alloc,omitempty,omitzero"`

	// Embedders Named embedder configurations for embedding operations.
	//
	// Define named embedders that can be referenced by indexes, templates, and API calls.
	// The first embedder defined becomes the default when no embedder name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add openai.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:openai.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Gemini: `GEMINI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//    - Cohere: `COHERE_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// embedders:
	//   openai-small:
	//     provider: openai
	//     model: text-embedding-3-small
	//   termite-local:
	//     provider: termite
	//     model: bge-base-en-v1.5
	//     api_url: "http://localhost:8082"
	// ```
	Embedders map[string]externalRef3.EmbedderConfig `json:"embedders,omitempty,omitzero"`

	// EnableAuth Enables authentication and authorization (RBAC) for the API.
	EnableAuth bool `json:"enable_auth,omitempty,omitzero"`

	// Generators Named generator configurations for AI operations.
	//
	// Define named generators that can be referenced by chains, templates, and API calls.
	// The first generator defined becomes the default when no generator name is specified.
	//
	// **API Key Configuration:**
	//
	// API keys can be provided via the encrypted keystore (recommended) or environment variables:
	//
	// 1. **Keystore** (recommended for production):
	//    ```bash
	//    antfly keystore create
	//    antfly keystore add gemini.api_key
	//    ```
	//    Then reference in config: `api_key: ${secret:gemini.api_key}`
	//
	// 2. **Environment variable** (simpler for development):
	//    Omit `api_key` from config and set the appropriate env var:
	//    - Gemini: `GEMINI_API_KEY`
	//    - OpenAI: `OPENAI_API_KEY`
	//    - Anthropic: `ANTHROPIC_API_KEY`
	//
	// See [Secrets Management](/docs/secrets) for complete documentation.
	//
	// **Example:**
	// ```yaml
	// generators:
	//   gemini-flash:
	//     provider: gemini
	//     model: gemini-2.5-flash
	//   ollama-local:
	//     provider: ollama
	//     model: llama3
	//   openai-gpt4:
	//     provider: openai
	//     model: gpt-4.1
	// ```
	Generators map[string]externalRef6.GeneratorConfig `json:"generators,omitempty,omitzero"`

	// HealthEnabled Enables the health/metrics server. Defaults to true.
	HealthEnabled bool `json:"health_enabled,omitempty,omitzero"`

	// HealthPort Port for the health/metrics server. Defaults to 4200.
	HealthPort int `json:"health_port,omitempty,omitzero"`

	// Log Logging configuration for Termite services
	Log externalRef7.Config `json:"log,omitempty,omitzero"`

	// MaxShardSizeBytes Maximum size of a shard in bytes. Used to determine when to split shards.
	MaxShardSizeBytes uint64 `json:"max_shard_size_bytes,omitempty,omitzero"`

	// MaxShardsPerTable Maximum number of shards that can be created for a single table.
	MaxShardsPerTable uint64       `json:"max_shards_per_table,omitempty,omitzero"`
	Metadata          MetadataInfo `json:"metadata,omitempty,omitzero"`

	// MinShardSizeBytes Minimum size of a shard in bytes before it becomes eligible for automatic merge consideration. If unset, defaults to one quarter of max_shard_size_bytes.
	MinShardSizeBytes uint64 `json:"min_shard_size_bytes,omitempty,omitzero"`

	// MinShardsPerTable Minimum number of shards to keep for a table. Automatic merges will not reduce a table below this count.
	MinShardsPerTable uint64 `json:"min_shards_per_table,omitempty,omitzero"`

	// RemoteContent Configuration for remote content fetching (remotePDF, remoteMedia, remoteText templates).
	// Consolidates S3 credentials and security settings separate from backup storage.
	//
	// **Credential Resolution Order:**
	// 1. Explicit `credentials="name"` parameter in template
	// 2. First credential where `buckets` glob pattern matches URL's bucket
	// 3. `default_s3` credential
	// 4. Legacy fallback: `storage.s3` credentials (backward compatibility)
	RemoteContent externalRef8.RemoteContentConfig `json:"remote_content,omitempty,omitzero"`

	// ReplicationFactor How many replicas of each shard should be maintained.
	ReplicationFactor uint64 `json:"replication_factor,omitempty,omitzero"`

	// Rerankers Named reranker configurations for search result reranking.
	//
	// Define named rerankers that can be referenced by indexes, search queries, and API calls.
	// The first reranker defined becomes the default when no reranker name is specified.
	//
	// **Example:**
	// ```yaml
	// rerankers:
	//   cohere-english:
	//     provider: cohere
	//     model: rerank-english-v3.0
	//   termite-local:
	//     provider: termite
	//     model: mxbai-rerank-base-v1
	//     url: "http://localhost:8080"
	// ```
	Rerankers map[string]externalRef5.RerankerConfig `json:"rerankers,omitempty,omitzero"`

	// ShardCooldownPeriod Cooldown period after shard operations (start/stop/split). Format: duration string like '1m', '30s'. Default: '1m' (one minute).
	ShardCooldownPeriod time.Duration `json:"shard_cooldown_period,omitempty,omitzero"`

	// SpeechToText Named speech-to-text provider configurations.
	//
	// Define named STT providers that can be referenced by templates and API calls.
	// The first provider defined becomes the default when no provider name is specified.
	//
	// **Example:**
	// ```yaml
	// speech_to_text:
	//   whisper-local:
	//     provider: termite
	//     api_url: "http://localhost:8080"
	//     model: openai/whisper-base
	//   openai-whisper:
	//     provider: openai
	//     model: whisper-1
	// ```
	//
	// Then in templates: `{{transcribeAudio url="..." provider="whisper-local"}}`
	SpeechToText map[string]externalRef1.STTConfig `json:"speech_to_text,omitempty,omitzero"`

	// SplitFinalizeGracePeriod Minimum continuous readiness duration required before finalizing a split. Format: duration string like '15s', '1m'. Default: '15s'.
	SplitFinalizeGracePeriod time.Duration `json:"split_finalize_grace_period,omitempty,omitzero"`

	// SplitTimeout Maximum duration for a shard split operation before triggering rollback. Format: duration string like '5m', '30s'. Default: '5m' (five minutes).
	SplitTimeout time.Duration `json:"split_timeout,omitempty,omitzero"`
	Storage      StorageConfig `json:"storage,omitempty,omitzero"`

	// SwarmMode Bypasses Raft consensus for shards, using direct writes instead. Useful for development and testing with a single node.
	SwarmMode bool                `json:"swarm_mode,omitempty,omitzero"`
	Termite   externalRef9.Config `json:"termite,omitempty,omitzero"`
	Tls       TLSInfo             `json:"tls,omitempty,omitzero"`

	// Version Internal version of antfly
	Version string `json:"version,omitempty,omitzero"`
}

// LocalStorageConfig defines model for LocalStorageConfig.
type LocalStorageConfig struct {
	// BaseDir Root directory for all antfly data storage. Defaults to 'antflydb'.
	BaseDir string `json:"base_dir,omitempty,omitzero"`
}

// MetadataInfo defines model for MetadataInfo.
type MetadataInfo struct {
	// OrchestrationUrls Mapping from Metadata Node ID (hex string) to its URL used by store nodes for enrolling into the cluster
	OrchestrationUrls map[string]string `json:"orchestration_urls,omitempty,omitzero"`
}

// NamedChainLink A link in a chain that can reference a generator by name OR provide an inline config.
//
// Use `generator` (string) to reference a named generator from the `generators` map.
// Use `generator_config` (object) to provide an inline generator configuration.
// Only one of `generator` or `generator_config` should be specified.
type NamedChainLink struct {
	// Condition Condition for trying the next generator in chain:
	// - always: Always try next regardless of outcome
	// - on_error: Try next on any error (default)
	// - on_timeout: Try next only on timeout errors
	// - on_rate_limit: Try next only on rate limit errors
	Condition externalRef6.ChainCondition `json:"condition,omitempty,omitzero"`

	// Generator Name of the generator from the generators map
	Generator string `json:"generator,omitempty,omitzero"`

	// GeneratorConfig A unified configuration for a generative AI provider.
	GeneratorConfig externalRef6.GeneratorConfig `json:"generator_config,omitempty,omitzero"`

	// Retry Retry configuration for generator calls
	Retry externalRef6.RetryConfig `json:"retry,omitempty,omitzero"`
}

// S3Info defines model for S3Info.
type S3Info struct {
	// AccessKeyId AWS access key ID. Supports keystore syntax for secret lookup. Falls back to AWS_ACCESS_KEY_ID environment variable if not set.
	AccessKeyId string `json:"access_key_id,omitempty,omitzero"`

	// Bucket S3 bucket name where SST files will be stored
	Bucket string `json:"bucket"`

	// Endpoint S3-compatible endpoint (e.g., 's3.amazonaws.com' or 'localhost:9000' for MinIO)
	Endpoint string `json:"endpoint"`

	// Prefix Optional path prefix within the bucket (e.g., 'antfly/production/')
	Prefix string `json:"prefix,omitempty,omitzero"`

	// SecretAccessKey AWS secret access key. Supports keystore syntax for secret lookup. Falls back to AWS_SECRET_ACCESS_KEY environment variable if not set.
	SecretAccessKey string `json:"secret_access_key,omitempty,omitzero"`

	// SessionToken Optional AWS session token for temporary credentials. Supports keystore syntax for secret lookup.
	SessionToken string `json:"session_token,omitempty,omitzero"`

	// UseSsl Enable SSL/TLS for S3 connections (default: true for AWS, false for local MinIO)
	UseSsl bool `json:"use_ssl,omitempty,omitzero"`
}

// StorageBackend Storage backend type
type StorageBackend string

// StorageConfig defines model for StorageConfig.
type StorageConfig struct {
	// Data Storage backend type
	Data  StorageBackend     `json:"data,omitempty,omitzero"`
	Local LocalStorageConfig `json:"local,omitempty,omitzero"`

	// Metadata Storage backend type
	Metadata StorageBackend `json:"metadata,omitempty,omitzero"`
	S3       S3Info         `json:"s3,omitempty,omitzero"`
}

// TLSInfo defines model for TLSInfo.
type TLSInfo struct {
	// Cert Path to TLS certificate file
	Cert string `json:"cert,omitempty,omitzero"`

	// Key Path to TLS key file
	Key string `json:"key,omitempty,omitzero"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y96XIcOZIw+Cqw6F4jqcmLl0qVY2UzFEWpOE2KXDLVqt5KWSYyApmJZgQQBSBIZsm4",
	"to+wP/Y19qXmSdbgOOLMi6Kma/tra7MuKgOHwwE/4e74GoQ8STkjTMmg/zWQ4ZwkGP485WxKZ/qvVPCU",
	"CEUJ/B7OMWXwF44iqihnOL4utaCKJPDHnwWZBv3gT918kq6dofsRJyQ61WNdUHYXPLUCtUhJ0A+wEHih",
	"/x0RGQqa6hmCfgDtEUyOQgAtE1h/k2jKBZriOJ7g8K4riBILFPMZDTtDNmQwhURYEMRFRASJUEylkohP",
	"0YwwIrDiQqIHqubI9MUs8sP5gc5wOEcxZXdIkCkRhIVEIpyPgCYLxHBC0FTwBKk5QeN89DFKcNoZssGc",
	"oCkVUtl1RGRKGYnQhIQ8IRK6RWSKs1ihhzlhiHHbEoamEsmUhHRKSQRre/UKVodOOTM7IfuvXg1ZG405",
	"GxEhuBj30UAsECOPqgArZwizBYIWaNfOuOc6CqzIKKYJVcXenMUL3VF/RfAV7R4d/LhnRpGus6IJ4Vlj",
	"T/up2AHHD3ghx310An8gjX6NhDK8ZqlnjzhJYwIrHI/HC5zEQ2YOY3/IkEMc/I1QO+/eRzOSUEbb0xjL",
	"OUJ/QjduC92umT7IHIC++xdCCX4cYaVIkirZR4fuQ+jw3UclfDVMzeMYJ7gd8xDHS6fWh69NWUwZWQd+",
	"7fPIEENfD34OQ1jyyFeRCn5PIyL6CDM1FzylYWGJPCJxH4UxziLSlpwxotpH7eP2Qe/guPfjwY+Abb0F",
	"A30iKUMn1+coxHEs+2gM+O+jYWCxPwzGiIvC74WlDYPxkAWtgJiN1AzC9gr6v2pGZJEa9IMSVoNW4Fcb",
	"9IMiNoJWAFumxyruVdA/fHpqfS31K+5E8PSlVQQNAFg6SWkki2+YUaMu6AfLcRe0Aod8zdkc9oOnpy85",
	"w+OTv5NQaY4XzjN2R8RK5rqKp8Z0MoIxKJuNeEoYTuno1Axq2flSvgqNmjir0rToRgW28w7YFpxe31Mz",
	"L6xQiBmakJxHRvqYUxaRR80uWZQfngo7NNNvxhBN22UscQmfMFACeU3pI4nax72eJbacPhQRCVWWHVjK",
	"gNbmF4XFjKiR4neEyT467vXM7/yeiBinhQ/6d0kSzBQNN5rFNW5bSM1HvX+ZiDUhzZVK+90uHN85l6r/",
	"pvemNwwsdZbJyi+weErhx6AVlIEN+se90iG1wAWtoLRa3a731AocnHBEDXRBvxm4oOXnrq4uaJzyqZEm",
	"uNjo3Cc0imLygAXJT/7VzW3x2MM5Gsk5FpEcpUSMFJ5U+NBhlTze2dPHsmRChFYaTH+kOAoF0cJQEwlG",
	"jDwgGK9T3IujVqAZSZIlQX/fr44yRWaAhcf2jLftrxll6vURgEqlHsmAOsJxzMMSlEpkpAao6SMRzhRP",
	"sKKhgRQJAgMARaNdmcZUKcpm3YSIGWWzPQ2vhWDCeUww0yCQZEKi6Bt5kRmEspn0e3Jmx13NjtzsTfzI",
	"D4o0KOZDnS15+NfzpRbSQiPGSv+5nEd5mDZhUr7xMi6l5/gLWaDT4gKBZw2Z/nZHFtJBbUklQvcUw2yE",
	"hWKRKhJBM8UFQbtCQ5MQFpFoT4tgwu6p4CwhTKF7LCgcjr4efr+DXr36i+346lWpK2A4FTzKQg3QnuFd",
	"4/F44nQPzNQ0XuQTGyJo/ISjCMG+047e+juycKPBf0Gf8DuCvF7fR2PbvI/+/FWSUBDVL4/zBArJgV7I",
	"WcM69aIk1RQoYEERuScxT3Ubu6Irrb+6acZGaTezwwmQRAGicaptH0E1mRN2rycw/dvoKiXs5LyPxlfX",
	"Zx9Pzkcn1+ejv5z9bWw/fwAFoo/GH84uzz/WPp84VaCPxicfBz/fXF2fn1YbnfI5EaSPxqdXP5/dnBU+",
	"D9ktIejXW8CNRJeY4RnRy/uy2414KLsGa3IPlq+pMyaKoIiHmW4Fh22VuPTUA6s1uG/LBMdxTZiZjyVZ",
	"pjWGtifT9qHpqZtYTm+UsI3k4mRG2hMsSZuw9v1+53gjuXiwRC4WF1IUjc0Al4WU6Qt2anER6+XgQUEO",
	"VlezhRwkDEQCztS8JAumOJY1YXDGvCyYEy14DffXR1v/xAX93cqDm7cnp+aU6PN+cn3eLA5yW/a58iC9",
	"m43sKEXt9IMbeLVAyG3XBolwcr5SFBSs/OWywBiSG4qCHJpNZEHe+n91YWCsqm8XBuVx/gDCYA23XyMr",
	"1gmD783tcwKB9RRt3xqPNh9LLNq2P+gc5y6KorFdFxnwsTQG/HJYEDazVB1tImtmqWofdfYb2X3JiC+w",
	"+yrAZS5svmpGVPIYFPobYCviAX6EXvkCSpMaQJuFShPDnxMcq/nI8P1orf7vWL4+qaZrNyFK0FAiScQ9",
	"ER1kbRmwXfQQzazezptyoUqTHh30etVJr7lQXnhsMKseo2wfwaAVs+ipFcR8tolAiekET0cxn81KHg8v",
	"ShL8aI0oSX8no8lCGUHlF/X6h/3emzevj6oLu8SP2mhDups2+rA1pihDMEgHfZIk0kuKCIhtRgy/VxyB",
	"iWXNxNJi93s/HP5wtP/m4AggM1bh0ev9H3pvfnxzcPAD4CI3F3tHb45/eL2x0ejXusy2PegtW2XduC3I",
	"ScPTI2vmSspmMWmwdPfLwG8ONlE4wgqv2+5L2+6cTTn0o2zJ1pZWaABauo9oQqZaOlHlRTiJ6YxOYmvX",
	"e2Nam8vgWpWadg1PRedTlDFJVMsJfTjlnBH0W4aFMjhtOoQl1B28fnN0eHx0/Pp5CHSIqO17EyKa/Bh3",
	"hKR2e82+opPysiV6oHGMGFdIkCgLiWuJJiTmD0jNqUQhz5gqH4lnrUeQGZVKLIxKXV3Hp5sLDbzmN8BZ",
	"kWue67BMTbFIUITlfMKxiMosSKvost/tun4do6h0KO/e7xehD9a1nHKRYKVhFzTnpFIJymZmIQlXZBRy",
	"pghTm7MzGQqcFvnZDQx0asbJmZsgaWw1+9EUh+C4XuXK+pk/oASzBbId4QqM4HBuaULOeRZrVRYlmDKF",
	"tWJb2s/DAts6fubeCvzNHm4zSBlBZtjVNoSbvMmEkASLcI4EkVpz9zPUjQm/gk38SnbU3zIi6GqLwsO2",
	"iUHhG2/lAveQg1oVgm+hTdgspg1qnvlc0rRMf9ejfX/Y6T3PpE8eJ5i27XBgDd/vmwbPcHWX11FUuBrg",
	"LStfpmujRe/GaAI1WOIuX+UJb1TwjEwIOY8j/sA086Y8qnO8U9sAmQYIT7VcMSSbm71oVyosVFcqnnZB",
	"A9nroPfAofoosmcdGeaEYnpH0M5+stNCO4c9ueM5ZB9+RbtagiWUZYrslThAsJ/UOF2Z1hVNSOednQ9W",
	"mRISzkeKjxR5VN9C9ziLKPc0fzsYrCZ3M3Fb8TbcYLk9q1B/ncJvBwPfeBWVe0/BCrL2k25C1r7xVmRd",
	"xi8Q4MOcypSITUhykwumAukae6XrJtAUUbDZ7M+bmG1uhP3a7bJHax+Nv35VAjO9tRNyondfc4ifhkGn",
	"0xkGfoKfhkFpxcPg6WmZ6882LNK4B2WZv680+Hb3Xg342sLlB2Q8mlKGY604zgQOyVI24RQ8rW5QlvFM",
	"IkFwRBmRMmcAgvyWUQEHEfReO7hmCtgYLmu5xrHUbGM/KXONY7lT4RTHcntWoddrw0QaVmitFQ+XtUiM",
	"8gJGl+eHbn1K0NmMAPiCm5CedQs8bmSLx5otTum944uywhiPt2eMigs8I+s4361plvM6+YBFMtInbL0f",
	"+O0ixVISiW7wVIHxQpjMrMoD+n8LZdqkQxEVJFToQVDN0SiTiuAIrNxpFlf9ZsDxFJFK94TIKW8YMh4t",
	"8Su4o76BHmybNhj0Kl4rKgYXt85GvCdCAiKqR+mcKSIYjpFtAaYhaPelTe11euCxqaj2TbR6oVlAea9q",
	"kXOa/EcRLavpgZk3mgTVzbvhXNl94da+wXHsHKvaFkb2DJUtnB03YoUiCxMllF0QNlPzovK+ankl67u2",
	"MC7COZHKnG3NGlfq9+vspirVp9oYMl5ZBwb6yCOCzt+h3Tl5tOS7p9dOlUTaRMykEdLG96wPpb08ZpoN",
	"6PEoUxzEcBhnUoHNUhAX+03M/bjX06fhYMm3g6AVHC75dhjUsdqE50pUZO3gnpgYRMoQtpGBXkHJnedN",
	"YYlXN05eIqzlbCFQDLSLT7IYsTjW6qRHanHkypXKynDH8pg2cGqMds1yYeg6TEtuejpDdmXiCMGPUwSV",
	"i6ZZcmu2qEYZ6VuMZs2jzp51fwV75eMvS1dl9d3Tu+u8Fw0oLFxUJThtIo2mKLSXuXTzYXTPGO5G93VD",
	"NZ3q20PHN3AcX00h2m5DX8hhjmlBIsIUxbGEiLwKb83CO9KgNNweIvPJkMGDNvnQ7e0ATWns/Fr6jGg+",
	"EZXYZbJoG47ZtmOD98OxzdeHJS562LBZqSBT+lgH6So1XBGlWM2RaQVSFKiZOHh3SWfWaTlu3s3v4bo7",
	"eyVAC18aZZXT+YL+rwFhUcop04uxq/pS268vTTtoBM1bHN4RVr6MCIxeXOXbtgeamC4IhmwFhGWJBsR1",
	"kocagnwx7vcaNtfI1k1cyJVFwDWDVelXdWsQ7Vv4reuTysO1fQy9NNKSU2/qcflENJz/a33GFEeDi1uk",
	"W9ApDSFojcakdIq6+jR2Fe/qVp2UJE2bcEcWq6e4I4sVQ9+RRfPITQutm/zmGjU3/BtcJQWJAfLedAGb",
	"fvezscL2vOHYKdyvw3V64Q6YkjgCyVK5sm28Srf2+SXYtq9eFa1b/fttlqZcKBJZy0PqNkl62EIP+L6F",
	"HsgkaSE+m7XQNMYh2k3wIzo4vny7Z7q/4yH0cP5obR5rHapjY6JCnphr4FlGIyK7ZcdHWa+pG71PVYlo",
	"cdDEtwCXFmEd9B7HsQT61rtfxlMzmpqOFCjFja5+PZH+qhW6JbO9Pbk9G2l9b9l063RNi48iOyv6A8oA",
	"2QNkLx4U11pm57mHuXSMc7HIGdlAQK6nDS0htxvhr0Qo8vgtIwyM2VYY4ktdUOfOj2d4/K5d56pc86N+",
	"0eKrcmXEQPsr65PGnGIlb1/HhFrE2hDWgtg75PR2gs3rhsi/ta12GSJJIK5WdqpE74DOk3OAbsc+MAS5",
	"g7Xrz55JxrmHLdENP3CurevTmGcRuvUEPiCPCu2anUMn56aXtZ51NxBdyO4L3MjTkHhO2EKf8f3BX0l4",
	"0EI/Z2/PbgZ7KxyNDR7ETbyHqzyH4/G4zJ6+k2dt9VmqMZ7BnJTORYHUnfpivYPgYlDkMcjdG18auMwG",
	"pLKBLHPbWBRmDVtYPs6fJJEobjwG4AQqO8kps5Ze7RCDbAMxVMG8omzRatreFprikEw4v+s+4PuDexIe",
	"2G1fKhM/n/y1HLvWQpfXhy30/uLktIUuj066JyenZaF4S4hfWCng6SUPVqOMbJRZDhQtuxrE1snHwfuL",
	"v40GZzeX54MXk1wlALzD3MkpsHucMdGweTt7EMdAklQtWvqcS3cz8WzZVhUlGxzuVQzO02GB0+WH+yT1",
	"1+DODYYKtiLaPXlnI1zL0bD2iL8nWGWCmMOkBMEJZbOWJgwM97EUu2DZViEaJM1YqDL4uVlJC/VCOjNY",
	"FWhoZUoDha18RPMAXzPHqDCHC/mKMZtleEZGIbh/A8Lan24N39O7MaKRMVxnYdq2v9UPb5gjZ6Q18+Ua",
	"veMUOITgDvRft1cfvYrfqM2tXsRGIWzNWG72KVfwUVTjHGqa03lcR6Q7euqAPjv6D9k+u93Za1yiy6Up",
	"T5fJdkiYEjiu642ls+26d7Yg6hsS8hkDD5Mlagcx3JSpUczZTMOtSEzSOWcL/Y+ERDTE8SiioWGJSxZU",
	"PDxfV4FuG6Lzd1W+9uHq6sPF2ej04urTu9H1zdV/nZ0ONjcBMklGhM0xCytxjo13Gp8kQa61wYZx7U6I",
	"UkTos5oJHC7QbsilkijhgjTmOC1jZbUEyhNwwJTTKJ/hympOzDTOIBnU1dY6j9Q6qRHlBiSflVkW+YM5",
	"lTnPFBmTeUNznRAviv4me4kAXnLdLyRStoZMt+CZsleGcEPIEHm0FycVZaKDzpWRHSbU2uZYSvo7GTLI",
	"IKS/W2ka5dDA1RHjKMThHBK67omYE+zuu/VOQ2jZw5wwqzzfZIzppua6qQ0wRySN+UKfM4l24XoMzgVo",
	"w3/jGYo421GIEZ8WRtmsC0D4mXEouJTmosB1e8BMIQhywrHW7rPUxlY/UrXIIXSYsHdmTcAmWayogdXe",
	"NkjriXTzm7A6ieDMOgAA4quPH39p4zAkMREQh+mxZ85+CdqUCEml0hQHzbp5spyeSa+t4g/Aj+Zg1hNB",
	"/X2Yi9toShyVJMUuZ1qjpDlt9GkZaa0gqs0N4dqodkeqic/PGKmJ9JuM2mkWxxB/MYLYr+W3X01ir07o",
	"ejinkEfkEUhjanZUIsrQ25jcaxX985wwlAoi9YbvknvCELWa3F7LtS+7uA3N9cOp6iOZTaf0EQxbE7IW",
	"+cF3JLLnwrjC3GR4oufyY2eSoH5YGgkKbbB4Ya7g9Gru4QIzJz1p7mHKzLdwWd6WdzRtc+slb4O/Wp9I",
	"jbun1lYOhGUHLvcjmHt44olgnfQ55UwJHgP9qjkRBhPmNlazXUuAEBrub2cBdTBcXm3D41AjzF6qmA1I",
	"SMJtGRJAZI44aGv20Q4K5wlNuJr74Vi0pEddBm6K9C2cLScoW+5uaRBYze5Jl6venJe+gh89g/ms9gPU",
	"IG5wBiQ8vCt4AFqOdS5zBWzGsF5exaixreVm7By8ru6usmjVuhskr4I2GtTaqDzFDOFYcmA+RIGHfQsD",
	"uByI3WSyP8O56w7Wio0ueXfRGQUq34GOO8ZnYjQcOGMVjaaF4JgXDG+43DWSuuuKUHS/6k9P3fIqHWir",
	"L/DMmhov7TZRH91OLtEcnSojNa0ac4b+TiL082Bw7a1BiDiw/WRFmTOajqKaMRrVxsZDFlCS4BTiVLRm",
	"Y3/Po1x0CwkJezTGQGxz/oCuILsKPXBxJ/d86SM7sXdNaVUIsNhHt1UtNIdzsjBbZxIW0O4ko7FqU9bS",
	"mijA5PANCuQJWyAOZ8BcIGtpasvMaOhijqOVm5yvzYJt0GLBvdjvo0vD70FBM1g8aJsgMzQYXECrgz66",
	"zlW7azLRdrKWOcah1ka3oA5PYzqbKxSRKMt9IiYnkIWZELozjYwLJIZlElA3t/aVVbTGb2bb26mRDWUl",
	"jKJWKS6xgdvJ3LebA+CsqlxnrntStQlkJonQ+cfBm/ZvGWYKaATHcfuSMnpx2b543b4/KJ7vScaimETe",
	"/Boyd9dPGRaLDvrIc9PK0lnL3bQBU7F0wh8YnDh3RKs3jzUgdg/fHKGIJoRJLQRaJjlf6xV7Nf+XPkj/",
	"BxG8Irr/+//6fwzlIW0OWpEw4Y+6+UeOGFH6qza8iZQeMv31OhMEfeC5WxlkwAd+efFL+cjVzY5l1nnD",
	"3r8lkeDh3fM2/+TzLbIDrNx43a7gODMkXxRdXKDzk0skeExkOV674Ds3KQcdmCjPTDhqIZzg3znrKKow",
	"M5UIQP9v3x/0e80OxoiHsoMfZMd2DXnSnZiFdI1XqJtJIuBOuGt4U1s6p3tnrpK4WfVaAmKZqu1EgcnW",
	"AvRmsk2wVE03yhOswjkkv5WE8X6TGIa2Jl2vXOzFcStIsEsVTXQTNRc8m83TrOirLqSRLnOSz4nfdENY",
	"5++sxPdqzRI87LTQzqrN2qnEBS9HZ0O+2KwxWHVgj6n57k+uW4C/1bOA+42ogpLvUMPk+q90xMjDKKaM",
	"bGAIfbb2D9g5gqZQAAn65gFtlKWZMgXEbDy2388lHrlNVJ2ljMDUS3keHzB9l7GAdUEilQItq4JE6kyh",
	"cjYOOz1vJbbQfu8A+Lfca9mGoGLFlM0yHNssrKX8wZ4+zRt8EKfxCZWJHzZq5A4FZK2N3G1a4W6sDumy",
	"jKoNQ0oGOeZ9WEmT2VDG7+ae5eK6imZAfYmV4DUbMmoSdeD6n0/tcdYnxjGgoqldtAjr49tffsuIWASt",
	"IIyxlCYWy9xVWr+ghvvLZqZM42bU0csKMae1Q16NZMmZRePoNbCUyFiIVQW7Zx/fBU3Jp1qZx1oRMpiU",
	"KOZsplnIHBttKMGPVjePIa6yiNKPVx/PglZwOzi5GQQtmOPLc42lpRykzjue45BsGNjco9SKnz1rLHMJ",
	"+jJjGcPqhcaCYJaXG+uGZ4qIlxmvWUd85mCNcuaZY1mT+2UGa7SCmvzVIEMSHuEG5egdCWMsrJkP1y+G",
	"S1jlUSLGmXFO28x2tEsTPIP85iyivIW0OOAtdP3uvdxrDZnzS+c5+1SyHYW8xbUjcxusktS/IArkJjg7",
	"x0pkZNxydpoSBCtZGBZLlC8MHKFgrUvCImtoOZCHrAozUWEHMhJKgV/uTodPtXkmcAgZT3rxHTQoNNyR",
	"RkegEkml5xREppzJvI5EGJLUdJ4TjzhtWQGGpzGeob9nUitLcSztCoeMcZUrWNSg4iM3d1nWu25vQHEs",
	"CI4WyNqVHoFWKxzniPHnZtwasrGthZMXPztop4LcU/IwbqFxGNO0/cr9FcY4He81J6P+XXI2ZF+HDKGh",
	"VwmGQR8NbYjUMGiZjwCw+SJ5QtrTTNuf7RzAtm3h2vsPupM+AkP25GLH6iEB21wPrJAAz4o0XOn8ZsuU",
	"yzNfqtJVXHFRhva2Js80VhyFmVQcjJ85f/AhT+DoH7KQM8A2XD80691o4EfT5s7PIJAnWEgkF0xhuMQZ",
	"MkvsoF3xrECfcxKnRDgL142FbhdSkcT6EF69uoWhXr3qF8e3y9Dr33Va6tx//rsENdXYq3tmGOsr0+Pk",
	"UGve5ENEcBxbz5nFlUe8przB4MKr0n107FM37eiaCh9VeXRBQkLvCRDRNItjj2HNXULTw6z9rUPJzwYl",
	"tl4bFFSTocgmP6skfvUKtdENSfg9QeakdKVaQAGdmb2rMXwFhfoAmz0D++nnweWFq5CWYwl++frVj4+0",
	"Ie9KjDw9lUqquYklGg+zXu8wNADA32QMk7sPGiT3u4bMFSaLIqntOmPWmcIDkxhcJTGx9+1pC0X0voXm",
	"++356xaKqeWlHgSVCSZRGkOyml4e7BPcWop7qKiBIzyhsb1Uhzpu5DdA3NlvGda/w707FlTm7kx3uSqX",
	"4uhPdIp2yW9IKqwyiYaB5t73ZBjsPT2dwJ+aAMTXr106tZjLO/2ntvaGAQT3asaz9/R0a/42Vl+xl01g",
	"P9SAJySiGGD/QNhfqEIRV6ngSaoQfLIeQD05MO9cXHnJtGQ5pnsm4p9Acr3DCn+6OfeA55+1QOlAm1Em",
	"4oYGQ1/Zxqr7QHjQo/P3dDYMGvvIQ93BXv50TfKQ7ZSyZZ2mNCb9btcngNQnschDCBVjQj/dXKBbzait",
	"XxKO0jjCCvfHqI3eYkleHyHCQq7FIFy+fro5l17aQUuYrPv3lMz+fQIdWp1OZ+wO5tg6t8eoa/6W8I82",
	"+kwmen77JEQejOaENliDEVEkNNF/ZjS70jzoGvLLgCtCnpcjqTHgUTe7PWzDsVagJLggnN2pTU4fNyL8",
	"jizGex5heZkmWxwIXZvwHXfBAFO+enUOuo5mdO+sA5lELa2jgAm7S6dWodhroZIE8Yj1I2mdzjDMR+VY",
	"FwEfiC14odcgCDMPbWCJYBN8d83UdPcboHnNBsvjmFz0S/47jWNsW3nOYM4ICTOhWYK7iHfrdCszAiIV",
	"XG+Qre1pkSNdXxeqj3YlIeWqm/kDDXuuuONJHPMHEqE5lwo9zKkiMZXKfrwW9F4LwPNrwxlBumkNCrjj",
	"7e3Ne4SVwuGddAfPAWqcnPDCgSxIqf1eDzJ/ym1tUYRiw8OeHxL2N/fy1wc96B29SR9NAGvb7rs7RreE",
	"9L3XKC9xBRlFJTXmTw5/7XYID3gM2REwayDDAefMMG34p42IYGhwdfURmUONdgdwZ3olKGF6b67AHkcf",
	"uYlP3FvK/PIpQF/uAA+WnuU0f7ZOhEss7oj4yYRfUBYRpn46Wtc1IoBDKC4yHKpGdvVZG0hUwgr/w55C",
	"WK25PtW0HaoWmmcJZm3hTrxFRUQknTFXYxUDyWo9PwsVKH6APsXRxcWlVrYQQueFS9dXrw577de9/816",
	"SyB6TGMQrhi0qDT0C/G6D3Ma5yW99DRzOpvrgWFY3V6QuT05Lnqy41f5F7JApTsiW5oaVud0RkO34/4Y",
	"lnNHFu17HGcEpZgKr0wIgRd2T1ACmyL7aKzVjV//dPiljzBtGS9ZK4mdBjPAkyzGwmFNj65VbA713aAA",
	"gsWY9KVWnWdOt724uEQpFtJEL0Yo04xJKsy0Kmx7XFrMSLNTVX0EkPCWMDKlShaZ6gV/IMLU/eFSSavp",
	"RVkIuNfbkklNlgnBTKIYWmt4fA8/0nsstWZlbUZihrogUppxpE2U14zd97mEcrtOg0Vt9J4qiHUtmAQu",
	"xtN41IAn+BXZoJCCdC1SyxjtapNqr69VQPQnl6SsOILXmczVuTQFU8Z698YFZqNNNC9lDcGN0S5laq+P",
	"zuGftupKikOo7MAFYgSCpoyDrsS5/EieJPPiBH30Hlzw/vrYuPPtmQFQi2MxzghkOKCxpeqx6yBzoeoc",
	"9DxTaaYcgpxSraiKiV6H8lnXGi1/NTFut3B+Tf1jqLPdR/+FGUHvuJGBzYcdPrl8Yvf6EHEvDB3YH7Ro",
	"lX10ZB4XKXEiF9VOGbo5+dB/9crzoWKdqQINeaPGiGpTD0P3dbXqcvr38rBwVmB06yM3HuxcgsyommcT",
	"UCkV56xtZoW/XbFkjs41hn2qTmNnHKd3RN5R1p1x07lkcNpdclbXO7cgE4WS47IiTQZm+7SWapp0YEM1",
	"d3+HVflLhBV8GOCZ1B/+BLUS8454Jp+evn7VYuPpqYW+fu3qBrrHkH39WrDJ7FZp5cfrIs6dxFkdyGtz",
	"tPScEEOigcv9DP2S/VdwQIy0LagbXwsakj7689evqf6rAMJlbm8AokA7WwmAR0/NAmkAqwBMYdLT3Fqz",
	"Z1ArX/VZS5NpQ8yQ0NPT24Ue3P3Lm165tRZiRWZcLMD1RBKaJWCx/ff/+3+ja/NvpyAXOk94tChAWS4e",
	"/ldfJN3mbFYKe2t5Zu8EC9lLJ+fQtpoyXm5r3OTFhi6L2Zk2YP7kTYtmwsn1uXk57eri4uTyZPTz1e0A",
	"EklNgJSpuQz9rSlUC+HZ3z86PLKxH+eJtrc09V8LAtNkmgufebeYpa6/8Qx8UxTaI/JITemnQpzpLjgt",
	"DMAte9FkouHYwru79lpokpkH4YZML9C9DFX1eI1dMIyRJuMOOnPRMf4xKfCo2uBiCYWrFGFD5jMcbGyA",
	"YYGOPYwLPj93gasVg4hDdVsXh4uMzW6usodsDA1NpRnnjBu7FElFUoOn/Q46NS8CFX190kDcvC5wd7yH",
	"4lrMaqe2cKiyF+i669hr9mNwM3wWxWxHa6gWV9ZHX9EwML4dGOIjTqx/Zxj00a+dTsd89F3Mx06n8wU9",
	"jdc7eIFQjQ/3coEc8/UuW+fLgAaeNYPbvNPxrQoA65ZfjZwbBsliZHbVBNMDxL3Ofgv1Ogf6/w5bSAOq",
	"mz85V7C9AydQ+P4tmeN7yoWl3U9G4FenW4UhlsUxehqb+t4wJnbx8z5My8CoJ7hKzJNKpT34tXHwL2MU",
	"E3xvL5Y9IdkQ+YyFc8xmJMqzS06x9Ezoks5M5R3jIcTMxCXazi4c0ByHBho1uKjQbR55PlkUQtDAcQE9",
	"ch6RFnlEA6UbaPzdSXnitxDXk3r3RBEGPp1C6SdXi5vNiKyn8D7nsZb1N72ro7/rHvuG8G/7YEAhF9w+",
	"BtDK08T1HwLuM4NWIXrKBky0tg4h3/SKecPoFy+/0K55ymLvuZEwVTm5VSRM7TKq19svxMIc9n44MLEw",
	"zSEvmLqE24jcd+1gOKXGl5GjrB7uCsEpwYJnQrdv63+2As91g76euVV9P6IE5rI3JLYIhHGbsCoQpoze",
	"zQNhCmsplgiHZdUhyT1JNnAkPwyW2ez+8PpNC+0fH74G0oedKSbuN4fjlVNnl6y/nCZbDGtzCbY7ex10",
	"4wqZ6iPs08JbyGWwGLUMtqHyqtHKoJolW7s6rGaTeJolA2+VjFtDUp6Qi3aXLLyVl3wtYao5FXiTZJDC",
	"Mc1zQdzs5QICiE5BrfIV+PbWVzb41hCexoiWDdmg1aKXsD7j1y/ILfM8Er3Hoc3WsnIMEkc0xoBJZiIu",
	"1ZMqKu72GaGlDJHxhIaFEFOgOxcOaIqTm48xFjOCdovRgjiO2/oUxIkPAl/GOI28MmUKwCnxH+FPfp3N",
	"UrgKWeNrOEuLooMRUmePK8J1i/Rmt6lIbJ5NVOGCRPgqoqqRsQ2LWU4ajlUsWVRrNfVY2IvU08zpC+fk",
	"OSlSDpjvTGxNIV+bEpupffRMPWPDsmy3Lmip2ZSuUuhSQmxWOotxuseHrx3l1Rpb6lynv6wr7LZeg5F3",
	"7U6nU4jY3e5lwy2UlWoxuMYj/MyScHm6SkMROvDKFjQUd5zyc7QLIujS+lDylv6WBNQHr6v00cHx6xY6",
	"3j8w0dYVtWZtYoHjB0tRvYaZGUQu1xyWjrsZiwLFOKWFM7WWReVbm7OoYoFp02BHgmIFO1/f9LWV+erv",
	"7NSg/P68qzHEdAv+Zfov42GFFv7mDvsQMY1fHwOiuU1FjbR5FBGdggM+L4MkO5uxx5urT4Ozm2eaYrZQ",
	"1Bq+t9da2hB4XmvIjEXWbdJ/W+i3B8K6+v8OC1/eTJZoKd6G7mBr02njrpLYsI4/clFhkStXWueU1orf",
	"nlvak7CWY5a37X+Oa9Ip8vlhkCTr4mr3NmaB61C5EjE2NBgy7KaUiGrNsuZRtX634ohVNb11EL4wj2mO",
	"7t6Qwbhs7CXcpZCsXQ+jvrwolfmLq6aLubDPM1Q1TykGGORzunrfnC3L8Ea7tmLFvxXqz+x1GtNLjQ0F",
	"NW1M5nzTRCYx2tXBKORFV4M7TW50sepNJTXadP72BOlmHll9zblknS3NxDXa36UN2xYEmXisQiV9m0nu",
	"H+F2qeTjPJe8s03K9jNeoG69YKWI71wJ4uAbiiU2OG9MuURXo2DZVuQ7UWEwDfh9YZ7SmP6zbYVF7weq",
	"ax27hCkiUkElac8EjshL1Fp0/jrpk6TRGFKlu5h6syeTRIy/3TncQg3JDi5JpQv5Hl1IUdnbsHSj8eu3",
	"Me06HnVP2rjmVu7OiGqXJUuttkLNp5y7RCslBNc7m5dWfCyRtL2U+G5VINFJDJdGENOsODp5d2oiejhr",
	"fzi9LhK1/Ie5pjVATYj8d7R/8Ka9f9R7UwnH9q028mRvXQSykMqdU6LmmU3e7hbaIZneu/YDkWp/WWmd",
	"Ug3Gi6vTk8H51cfKy0DFYb+rS3wpf/luzvGllSrX4mrLepVb8e+ERlFMHrAoPGZ1dXO77BULHMf8YVQg",
	"zfV5+OcsghcdChXJigw55PzOvD2aqTmaE6yl2J5JojFxzR30kSvSR+dTW03M/j7igs4og6wkxpVG3687",
	"r3a+NFdidZ3sDCW4fw1s9E17YB4BOYFQHltWN2gFv7RvjKpFovZnqua6CYR3BK3gCqAIarlWP5uJSg80",
	"Qsk5ypBGsdfeiidtDSRfWgFVJAHo67nO5geIKiyuOCFqzqPqij+cDYJWcH11C//5pP//3dnF2eBML+la",
	"k+at/nAyOP25YW2DwTWy47rtAGaxYmHLJ3zWquzm1+nsgkooAuPAcqekBh48HmeODASO6vbwgJntUWZN",
	"pp2rXmgyo8zL9xDGaF+rL6y3IYclaBV8SWmn+GUrHGz65H6tFiCsn0oHeSOhkMeUyyqhNB1s2xD5Z8oo",
	"0bq0fZGPTtGCZ8adIGyOlUkNdETuEnihBpk+9BFkeUjzoheOKvj8pT3gCsftUy3jt8NXgh9H9iXDXH6/",
	"7vWaagDEHHQxhiQJOYvknk1XlXAQ4IX2VDg7zR4lnxcJeX6lF6lfl16d79VF9bI6QvVHpI0RXXlK+pkl",
	"pPzo25WQgiK0bZOSILqJbCdYhNybke1KWakhq9aVQt+prNRGgO2+bsd4QQQyP5c7/f+z2lT9lJh4p+ed",
	"Elt+Y8nh+K41Zhoewy46ce3nby4tY8ZpvjHe4j3uP0j1mLzM3SglYhTxcPmjtCxLJkQUyvSmpBBmb3xw",
	"bJb/AoHP5TpIq32rzejbqN5LfuCWq+DNw9dZP09HDeE7H/3qEw6v2cfkHjNViFEFoaPFFDw2UQoKaXkB",
	"hgv51jasVYZcENmEpa308Dohm4v45xGyvcRvIOTgBUMa9Gx+imeH6zQFHLzs3Vodt3Ws5mV0KoWzNXur",
	"r8Gk9QCCFPcp8uY+zJ+P9fjZphbE8lUUi0W76O8Gta1W6ICYQ8+iIicwCf5rIF9acqK+A9vUJdpQ59mk",
	"+MyG9PS8oawT+UXGapTXzxvK+DSqQ21dA7uZaxQEpqUJF0Vf8AVGhM1CzLv/O9yYOkjavc7rt/33+68b",
	"Y7CeNijyDY6FtdS8OlS6vqyGUGn/poAPEMsjnn0stPVYLgt93vS8bHnL9oLMvCpvrVOvpA8XbhueH4rZ",
	"eNvyvZl7IxlsF2eeewdvLKJOrs+3vWXgQpvIMQ2pKrm8UqzmVg++FgRWKqnyJod9ZOgdlSG/J2KBztiM",
	"MsBhH41n4Px3tpKz5FHkWhNobC8HcEqhaM1Yj/tBaIXH3W703fVGtSeOEsogHTaMs4hINK62sPg2CJTw",
	"z7HWJhMqpUmS96YZaOWSJNp+DNuWG1iV8T9NEdiill9tOcVStXu9ow2vQUqXH22cpm1t9mqDEC5CLNw2",
	"s+zk8lvGMtZdOzQOlmZ7YvW6/wBXJOZ6pPGhpJPr64tz46Efnd6cvTv7ODg/ubjdwjSpGwhr8dHAs9ea",
	"BWsH/eO9JrXERKkbaoKEXET/UNNkyYPqJ0zNBU9pWH2ofdOi1q4/yulMc9uCvyHYysrOB3SG9jJ72dVr",
	"X4/+vLaBz7r0xetMIYSNbeMwxllE2pIzRlT7qH3cPugdHPd+PPix8dhDXS9f99nK0nyJy6lh5Tz1g0iS",
	"VK8rE6Rx44zvWGAW8YQRCS/7FKJtdnudXnu/0yvnTExjju1T9Mbnud/o/zRoduRw17CrPG3fIalXBjoP",
	"Fjghyig9dZzrQdImsz+MSSYbhnkp6DfRgsqH8zvoQUuo1NYUfS6NFgrPb06l30piL1UmvUwX2O1AZzmF",
	"tO/3+72XL3ve+Rfl1Yd5LszfShGnc0zzcg+V2FA2IkJwETTcopn2ZovFwlVJZeTRZ+RDrQAU6vH7WtvG",
	"8QNeyD46gf/qXqa5IDMsoljvKZ8inqmQJxD/56bvo4FryxkUJ4CfczXZNrYFt0rN44XuY7+YftI217Q1",
	"gvo0DT1AtsFH36loE8MStE2cYygHwPwjH77RLF62HWBRP5M/Wd/xCykQFTd9E9FO4baPhYuRBj9WDSNd",
	"mw8GRqhq5Du9FNH+43QYniSYRW3RTuNMburaX6GrVMdr0NSJJCwk2+Db9XkxHvkvHekbof9Wnt3AHrat",
	"eb9sZLD2quOv870uGcy4jF5oMOOrfqHBrBPupUCD3KoXHMxkV7zQgEtU3meOttTMfeZ4zfKuqf79phdD",
	"62jm5auErxS4lYd7nZw66B29KQQMp6p91NlvzPGsMNxe54enDTjDasd/M8AvWyfFGxjFe4JasRRbRmUL",
	"DamZRW3nzF6yfldIZWtVqVIGZP0T9N9SR+N7uHE2Vnls2O9B57g9jbGcr1V6CqheG0xcHPWlqmx8N2Pz",
	"YK0ScPBPZ2w+u9rI9/fsNOsH2wWH/IF9OmsCT8rkBN8PO4f9H3qTP/Dxt9ZyPSxjMLj2xpi33fP4U1Nn",
	"MY+RCXEcg0/fT7e/jFL+Gcnt+0YLbaXzbldG5IX8FJWyFt/DT6FPu6a07Q59++A7OCs2l9Rep/zGYhb5",
	"QC/sjnhBrP5xBPofjTk0FAb5H2EOzTbs9nU6XpBJVKo5/JMziq29mqXHNCH1vlbfwb+tbz7kT5klmYRs",
	"M7s/UWMFhxWMxAxTh8M8QAAxymVIjBIwxXEMEQja/oSXsjaFD87P5uky/2J038boXsxvuikLuiFKLJYx",
	"HfjY4MnJL65ApQzqj2KHd3w6HdnyP9S5V6zIrSU/X/p25mHsR+OrojhGdqiVyDhu1GjzXaCM6rFGHqxy",
	"QuN+r57OdW66uOlRRGIMGUgJjWNq9euSJt3rNbIN/DjCSh9GVZ70sLVBDI/Gvu9d3P3eOh1ez7tkuYe9",
	"hvW62detd5MUtO18yVuGsm4n5r5foGnrH2va5hQIHSpihLFHkTFtEHY/kCTB7cP21cePv/yzmrjFHfyn",
	"tXG/VddsvmR6fm2Vqr9SNtHgSxXiWO8ofrEyFX+s6L+t3cj5Wr6fF/lfHuQ/7CV4TCd4ahI7S7eRWUT5",
	"qf7Vvo3VUEbPfHDxwSHUNdDdkButnjPC74mIcTqKLL/wqkZpYNMIuUZVrQJNiHoghBVnK75s1VtSpuaB",
	"sog/rJ77M7RZPjXYRvSRRG0zWmXFpRcJe71mSJ6224rVu3BNRNtXBqixYr8T6CS2j7WaMmu+QHob/U4E",
	"7/KEKkUiBC/VmceQoS8Rrny5rO8mrH2TW+OND1kpz3iL/OIi5yzmGi+hS/KovgHsAXlUVajVXBA5503p",
	"myAgI7BXfav8sXJb+S8/QCs5wIZm26aAb0TT5nX7tSS9TNp9bJByto8n5FCLuDAD3cDsaAcekpb+pUb3",
	"uh/CkDhmWqEJz1iE4Yk2dMXihal5M1lYEoU3Re0xls1HwT+W1+Cp8e/oGeEEeybT2D5v466Qh0M2HLId",
	"+3SlwDOB07nc2wqggvTDYkbUUmQO4HNdc9BnHsbdnt/EfDYrx40063kXpl0Dk3HatMsTqx2RmNwbNWUz",
	"gqtCdAHd9WaphYn3eN44t9B9S3RcONhzFYuyKa+pVQ4990RMuKRqgcyq84iPiEyyWdBy3R+wgCgWCHL9",
	"UtS2bIPGsI1VK6sU4BYJZTheCqh50dG9gwio7aAd123HFgKNuTDFWDiTPCYttPN3ye1pLzzQqpXvFtqJ",
	"+WyaqJ3cVdcm0ykNKWFKq+Y/Fd5BhdcJeGpHorFl1g5ZBfD1hIHW3vXYQSvQ3coIKzRegTR5mJ/xck2x",
	"ilSDdLvRHVk06rInn29dvRVtbZy/6yBfV/+OLOBhLPcSLKyNhIIoFHN+l6XV5K6Tz7ejk9PTs9vb0V/O",
	"/jY6f9eY2eVfDiGqrJebN3pMeuAdWbRp1IQC56NoYHGlV7fzB0wsa5OHHZzg3znDD5DauYO40Jvs6o3+",
	"2Ov1zAZeUnZ+tVdOlqt0Nhb2BbyrWrSxczgNpkY5/puRbxGa78G3bsDt2enN2aCwD8/YBDNJYS+CxgVC",
	"0qrh7suEL46RWSW0dRchmqBIknKBxaKY4LvV2pvAhlnaBqKmxGtJRlLGa6t/2UTi29uL7uDiFua+PdRc",
	"g5mX4WXlSVxocfL5toXMU9R5XWZ/lKrVwlbzbRkKnFbkmCJMuSfSVxYZJNFIH+gme8C9cF6s8qbbahNa",
	"ds+vjUkQU3bnC0dJSJ2E0m1QPxDay2KVQbRLHuHBxtQ/mC71+YJH00f2xxFNpSv3tlepT1au8xZGrFP+",
	"Zf/Hg06vc9DZf169O3ijf0Nk6Lb2SWTi7CN4/R/K1sG7/ejTzUUNKTBHufTi+0JnbYHgieRxplV6aGvZ",
	"UveTJEJ2I6xwd890MrPoLpMsvCOqa59otj2SRdv+nqWwQd0qPotjakZV67AdHmv7uJZ+3uoevlqgeePa",
	"v6UvMJsRiXb3D37o9PT/um9aaL9X+PuHg87+a/gXPNzxo/7nG/Pv1y20//rHzsHxkf33XmMlPnd4XarN",
	"yLnwyzcBNW+SdbDa90vpPY0yXKihxlPrmJEFH2ypaN1GNxMeOq1BjyYLRao3Mkdvjn94vfyaAjRvPvWA",
	"GZUGqqRThsyABagK462op1coJmJ+fX3kAIb6yqPmar4mQrkZTuiHHmik5t05gbp/lKGUPkIxalO1GT3Q",
	"OEYTcA5q5awkd23480qMZpKIEZ6RJpVAE0L7ZAZVuaB0ImwteNUL/K1UR9fUzXn3trvf6e0UxSS65Qmx",
	"z/B68v1M72hKIor3kCDgCPSn/oGquT5MGOVQlIVWcarG6IptJIReVK4JLrN7YOm5xK3W8yaR15saPCTa",
	"uG++U/JPG7vX5OdUFqfBaRpTohG8ydVSoX4mjtz70tclUOqlpuvL9MUyObIlOVboF3Y/h8Gfvxo1ow9a",
	"xNMwKHq98p2QVhJvbsBtKNO33fcbknBF7FibX2sI6ObZxpQo++CD+XD97n3LtrnUx9v9Y0AelS+CJfc6",
	"8AS45DGNoE6x1pIK9VpAZtrlaRpS8ECF9VIQU/RL665ZCk/w4pmrcpgfZHRDQGxquK9ERIR7j/nMFYgZ",
	"F2b8aRhoVWYYjAtuaMo8xOZRZipksa4MeoB8u7ERknKMZjGfaCmtiGAowSqcE6lPN7zCodvAU81jywJH",
	"8nBcGG3IjjrogsxwuPBxJ300dusrN5ZoV39/wEJzcGO70JiqxV7DbVI+X32DXS2d0gaYm5GHOWGIcQt6",
	"dV1ljpQKmmDRqO7PlUpXUeQziaCRbdXo+SNOSIQqzEuu416FnBqohsVw3MYpLbOyoFT60rVzNYdzTlQu",
	"J90P3hIsiEAVdhE8NdKv2bIXRt3t4aaIq5DlCvrvVMupmvNQdyTkfFJbxHdk8RQUbfMmg7nBIi6PYv58",
	"AqHOlMikMpWal05t9Vk3vSVgrQJrpaBtP7dfaVLKJjEN26/A1/J8MN2MDtSyIFiq3DkNbMnp+KPIkoYT",
	"VcoZ3RC4ZtdUPVXP71fthrXAgM1xtcwL7NSadgEFV4nsoM+a1WFQRBzbxm6cVq0blZp58LYkMQkVqVbN",
	"rh2hRAtCc4I2N57+J/e2lo5YlgZQ2chflZXFQUVW83siBI1KJZDKJ8hm6DU42puePfDK9lrT8bOtt67m",
	"BEVYzidcy0Y551kM/3mo1rW2yfCyM2RFPd67ZaTCLMIxZ6QrH7BIoH8H3RKlmxl/DdXikGF4nT8iacwX",
	"phaUVQr/kk2IYEQrOMYC5GLPKg1J/taTHcFX5Y4XJiSk4UGFZaFZDWFZ/uGMrr9UszcTa19P6m2gamvt",
	"g7BIW/fcHdPCUwecsUdtGMY4aAUzXn/O4K3pj1x/xIWzssw+6T3SQJcPX0Qg2sUV44J3D98DqH00tjCN",
	"oTS2/Uff9BhbtNv+UWHDx5qWx6Xn05SgUOfP/JcyC5w+6fCOKBTQB2UQ32Mag8/PzvdvZoYhC3kyoczo",
	"zVB1XzoLwj+iZ3VWiwr56hXajUiqscIZlI+PkMIzuQfVTcYzPkZNBc13TbGQHJQWOr3+BIVGWkjG/IFI",
	"U8FkrDdFjwHV4m9MoJvW2+0rTG092U9D2LvW1c1gGLTQFEvl+z/GWHeH6unol4uThr6PMW79cnGiuw6u",
	"P3VPP7076Z5ef3KvKgFu5KtXZkWAeNRGJ5qZRkRpK3hCSlgtlWAZh1kEEHz86/m78xOkR0cfrj+Zb1yQ",
	"JIbh0jQm6JQLcnmBdhMcXt1abLhrSI0AM6JKM7MkiMwZXH+Cl2Kh0S8XJ3ZW0+Y9FyHxqC0VVfcr+tVg",
	"Ty8fcGH+mPFh8EUPMRALd05svTiNgvxQKuMlLg7V12v24/VVmpl/mG/uX36Ga6i7rpECLuXYe/hPLZr8",
	"sICuSm+DKwDMok8rM7F/gq8s5zx4htA1bFCZxgBmfzR/GQ6wufCz2uXo+wnBVnBHSDrCMb2vXBke1x/D",
	"9Y9UKI50N8e9rQtNSwHzLiGearsxxlKZB8hN6lzhdkkbvoVn/vT2JxheFowXKHM+OTMMqB0+BIdPEWU4",
	"VPSeKi0gPkngA1HBNgcuOAyOk2GAdo9RQlmmbW29xftz/ds+mvNMwA89/W+CZxpcw2n3KoLQDRTj3xe+",
	"DYrpncsI9LLQjAZFuY1pHS9ckdTSDENmmDB2pfZKbx3C9SsWKkuB0TJyT4RHSaXWgdmkhtDG2fPvxfOT",
	"AbE3/vHHkX9bp3hMeuvj0IvvR3pu7b18zt0/ZCfeuiv6AI1v87eMZCRCWQoPD+LHEfwAJkJnyCz+eyA2",
	"MwbFoEiUM80K1o6W+ZUNjkfFJJl1y1Rc4bhCBzYoRW+vIDMqlVggPaHWh9xjie5dCf3nkPlwbNnyASEt",
	"RFTY2bNKuRaWpkwWlUgQeO2lZX4lWKq2ICFhKl60NdseMhr5rCJwEmG2yGGhEmlOq8wDOgm+I0hwnvhz",
	"vCkeD5fh0XCBUTLZDIeWaexShi7f7hVL/FuE+gBhiwoqc1zgNBXcogNQgRwqjJgrEFiBiNauFA30LBSe",
	"pMHRPZUaQjNpG+FQZXrXAe4hyySeabGVgjzjzCJeH05jFiR44e9rqWYKjyHRyNdTQBCEXhq866L17Jmk",
	"EUG182gv0xi8PEmZvbIQPK6e7t6Pr5dtTE412xJx8S4KRjFusSUsonBI812zVKy/TbM4biFGHvJx9a7R",
	"e4KOe4fo1gZzf2K5BgTSGBKK2icgFoxraflemskKOwoRWGQ61crF/Rr4h1mvd0hQr4LbZVk6eoNGUgms",
	"yMzZbUt8VS6kBSRC0Aq0WAlaAcSukaixQEs9xLNsGtiJi1YnusSpLNRRl/apLCpqvXJJzLgygeZUogSn",
	"QIVgRlrfqJ/HBClyhnLdAfS+82nhF4PC/CkdK0j3+qgoSdGuuRhkKCLaDG1ZKrWyX/OxvdrQP4Gk7Zel",
	"qh0pF5+tkuwE1dv6Nwxe5ljmSxqaDRkGRQyYRQGbqQvnXSxRigXcfqeC2Dlc+7LYbiFyT5g5cg0YSilj",
	"Rf0JYAUGBNJRooQ+6hWa9WqOAii0fMHmBkicEJTyGj/4Grw9OTnvTmbEvOTtX9/t+zOYUKHm3XDO2d2i",
	"nWiSV7Zt6dWj/aBvjmuTV8wAM4qoWHK75V8FBr6FKcura8ts4r5C8KazP8G75GrAy+LT/8bM+JpP+lR4",
	"h1ir8Ge1p3tzY6fUzYlb6HXqXARrOnnZDb1uym8arOoW8hmjv+cd4d+gt67t+iCoch1vyW8Ht+Q35H6t",
	"9i5rsP9nt2O9TV3Xzj3/dE9TIvby4t5EtUxpTv9qG4Sq5gHJtGBgV5XR2jyNEXicx3UJtN9aGifcqD6m",
	"NCUxZcTEuhovAjrD4dx/AYqVQ4ZRyNOF8wpByxaSHM3pbE5EMcI94YI4XWSSKfsqo/51yApA5G84mrdB",
	"/YKQT1cFqCyTdkoCZUZBMKoJn9YFfFXWNEkay2iWPz1ZYfm2fYlvNRpjgzmRpMEaoQl4bRWJF4Z9+fBe",
	"PZxsIXzPKdAZOIJ88kGMFWGhFy4WIuuGBN8yUnNuXYf+nBeIOL9QbmZfw0CD3STTcwYLjJiz9u9E8LIB",
	"B3NW9dlfl3FKV4StG8Y0bd9TZZ4xT/UyDg+2M+ktgkallEVnc9efLfN2BjXvPT1gqvxjOQbVisPVZ0wU",
	"admLer1Cq6Xp9rrzSlP5sCeNC2Q/Mf8Fs5hxlzHZQgUT4MYpSUaNNSWJqfTZlbkmd4Q+YEUe8ALZwKAq",
	"xzjsNfIIeVh95/fbLk4qKVDOfVxPgnp6sgHZawIAzNQmatG8ahlp04pOMq153pFF28Q2mwgJLbDtA9yS",
	"YBHOkX3ORK+dqkIoCypPcwvTmKqAJm4o6HV6nX2NI7tQjcROr3MYtAIbpseyOH76/wIAAP//ieSMmbwK",
	"AQA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/ai/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef1.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/audio/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef2.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/chunking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef3.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/embeddings/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef4.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/middleware/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef5.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../lib/reranking/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef6.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/generating/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef7.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/logging/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef8.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/libaf/scraping/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	for rawPath, rawFunc := range externalRef9.PathToRawSpec(path.Join(path.Dir(pathToFile), "../../pkg/termite/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
