/**
 * Named-link ids each model's chapters actually reference via L("…"), keyed
 * by content directory. The model page ships hover snippets only for these
 * (plus the curated spec's own source links) instead of the full corpus.
 *
 * Guarded by scripts/link-ids.test.ts, which greps content/<dir>/*.tsx and
 * fails the build when this map drifts from the chapters. A missing id only
 * degrades the hover peek (CodeLink falls back to a plain permalink pill).
 */
export const MODEL_LINK_IDS: Record<string, readonly string[]> = {
  gemma4: [
    "compiler-schedules",
    "config-global-head-dim",
    "config-layer-uses-sliding",
    "config-ple-hidden",
    "config-shared-kv",
    "config-sliding-pattern",
    "executor-pipelined-decode",
    "gemma-lm-head-repack",
    "gemma-mtp-ledger",
    "gemma-sampling-fallback",
    "gpt-compute-ple",
    "gpt-qk-head-norm",
    "kernel-gumbel",
    "kernel-head-rms-rope",
    "kv-manager",
    "kv-pool-config",
    "kv-prompt-cache",
    "kv-turboquant-polar4",
    "moe-mapped-route",
    "mtp-draft-request",
    "mtp-kv-donor",
    "perf-plan-comparison",
    "planner-a4b-forkjoin",
    "planner-encoder-scope",
    "planner-frame-descriptor",
    "renderer",
    "runtime-submit-frame",
    "server-chat",
    "session-factory",
    "tokenizer-sentencepiece",
  ],
  gliner2: [
    "gliner-deberta-graph",
    "gliner-fused-attn-bwd-kernel",
    "gliner-fused-attn-gate",
    "gliner-fused-attn-kernel",
    "gliner-gru-combine-kernel",
    "gliner-pipeline",
    "gliner-rel-bucket",
    "gliner-score-spans",
    "gliner-serving-head",
    "gliner-span-marker",
    "gliner-word-embeddings-kernel",
  ],
  gliner25: [
    "gliner25-adamw-renorm",
    "gliner25-boundary-encoder",
    "gliner25-decode-query",
    "gliner25-detect-arch",
    "gliner25-device-kinds",
    "gliner25-engine-device",
    "gliner25-engine-native",
    "gliner25-enum-prefix",
    "gliner25-executor-preflight",
    "gliner25-extraction-parse",
    "gliner25-head-forward",
    "gliner25-hungarian-match",
    "gliner25-longdoc-merge",
    "gliner25-longdoc-plan",
    "gliner25-manifest-gate",
    "gliner25-markers",
    "gliner25-mega-kernel",
    "gliner25-normalizer",
    "gliner25-offset-units",
    "gliner25-overlap-policy",
    "gliner25-peft-inject",
    "gliner25-peft-kinds",
    "gliner25-precision-policy",
    "gliner25-prompt-build",
    "gliner25-proposer-marginals",
    "gliner25-qualification-empty",
    "gliner25-resident-constants",
    "gliner25-rotary-endpoints",
    "gliner25-runtime-withheld",
    "gliner25-shared-pool-film",
    "gliner25-stop-gradient",
    "gliner25-task-classify",
    "gliner25-task-records",
    "gliner25-task-relations",
    "gliner25-train-entry",
    "gliner25-word-ranges",
  ],
  "qwen3-embedding": [
    "embed-baseline",
    "embed-eos",
    "embed-pipeline",
    "embed-pooling-strategy",
    "kernel-q8-mm-sg",
    "kernel-sg-q16-f16kv-gqa2",
    "qwen3-embed-catalog",
    "qwen3-embed-graph",
    "tokenizer-hf",
  ],
  "qwen3-vl": [
    "model-compatibility-doc",
    "qwen3vl-deepstack-tap",
    "qwen3vl-family-gate",
    "qwen3vl-merger",
    "qwen3vl-mrope-kernel",
    "qwen3vl-patchify",
    "qwen3vl-plan",
    "qwen3vl-pos-interp",
    "qwen3vl-projector",
    "qwen3vl-reranker-score",
    "qwen3vl-splice",
    "qwen3vl-support-doc",
  ],
};

/** Content directory for a model slug (gemma4 variants share one). */
export function contentDirFor(slug: string): string {
  return slug.startsWith("gemma4") ? "gemma4" : slug;
}
